### ISSUE TITLE
cannot export Mnist network

### ISSUE THREAD

**Issue by lanpa** [onnx/onnx#105]
The network is from https://github.com/pytorch/examples/blob/master/mnist/main.py

```
Traceback (most recent call last):
  File "onnx_graph.py", line 77, in <module>
    torch.onnx.export(model, dummy_input, "test.proto", verbose=True)
  File "/Users/dexter/anaconda3/lib/python3.6/site-packages/torch/onnx.py", line 72, in export
    _export(model, args, f, export_params, verbose, training)
  File "/Users/dexter/anaconda3/lib/python3.6/site-packages/torch/onnx.py", line 96, in _export
    torch._C._jit_pass_onnx(trace)
  File "/Users/dexter/anaconda3/lib/python3.6/site-packages/torch/onnx.py", line 121, in run_symbolic
    return symbolic_fn(*args)
  File "/Users/dexter/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/thnn/pooling.py", line 105, in symbolic
    .is_("strides", _pair(stride)))
TypeError: is_(): incompatible function arguments. The following argument types are supported:
    1. (self: torch._C.Node, arg0: str, arg1: List[int]) -> torch._C.Node

Invoked with: %13 : UNKNOWN_TYPE = MaxPool[kernel_shape=[2, 2], pads=[0, 0], dilations=[1, 1]](%12), uses = [];
, 'strides', (None, None) (occurred when translating MaxPool2d)
```
ps. alexnet, vgg, resnet, densenet from torchvision works fine. And my pytorch and onnx are built from source on Oct 9.

**Comment by jerryzh168** [comment]
@houseroad

**Comment by houseroad** [comment]
Thanks, @jerryzh168, it's on my list now :-)

**Comment by lanpa** [comment]
btw, does onnx has metadata such as network's hierarchy ?
(like features, classifier in the following)
```
  (features): Sequential (
    (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
    (1): ReLU (inplace)
    (2): MaxPool2d (size=(3, 3), stride=(2, 2), dilation=(1, 1))
    (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (4): ReLU (inplace)
    (5): MaxPool2d (size=(3, 3), stride=(2, 2), dilation=(1, 1))
    (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU (inplace)
    (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): ReLU (inplace)
    (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU (inplace)
    (12): MaxPool2d (size=(3, 3), stride=(2, 2), dilation=(1, 1))
  )
  (classifier): Sequential (
    (0): Dropout (p = 0.5)
    (1): Linear (9216 -> 4096)
    (2): ReLU (inplace)
    (3): Dropout (p = 0.5)
    (4): Linear (4096 -> 4096)
    (5): ReLU (inplace)
    (6): Linear (4096 -> 1000)
  )
```

**Comment by bddppq** [comment]
No we don't. Is it just for better structuring the operators in a model?

**Comment by lanpa** [comment]
Hi, I am working on visualizing onnx graph on tensorboard. (https://github.com/lanpa/tensorboard-pytorch/commit/f0cda9715e7daaf83e1c00e61d3835e74cdf3cd4) 

If metadata is available, I can group the nodes without much pain lol.

**Comment by ezyang** [comment]
@lanpa You'll be interested in this PR https://github.com/pytorch/pytorch/pull/3016

It doesn't export to ONNX yet but we plan on doing so.

**Comment by houseroad** [comment]
With PR https://github.com/pytorch/pytorch/pull/3100, you should be able to export and run MNIST model. I also run the exported model on Caffe2 backend, and it works well.

**Comment by fmassa** [comment]
@lanpa Nice! FYI I have a working version of a ONNX -> TF converter that would make visualizing the graphs straightforward. I'm planing to release it soon in `onnx/onnx-converters`.
