### ISSUE TITLE
Symbol not found: __ZN6google8protobuf18GoogleOnceInitImplEPlPNS0_7ClosureE

### ISSUE THREAD

**Issue by dendisuhubdy** [onnx/onnx#1300]
```
>>> import torch.onnx
>>> # Load the ONNX model
... model = onnx.load("alexnet.onnx")
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'onnx' is not defined
>>>
>>> # Check that the IR is well formed
... onnx.checker.check_model(model)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'onnx' is not defined
>>>
>>> # Print a human readable representation of the graph
... print(onnx.helper.printable_graph(model.graph))
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'onnx' is not defined
>>> import onnx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/grokmachine/.pyenv/versions/3.7.0/lib/python3.7/site-packages/onnx/__init__.py", line 10, in <module>
    import onnx.helper  # noqa
  File "/Users/grokmachine/.pyenv/versions/3.7.0/lib/python3.7/site-packages/onnx/helper.py", line 13, in <module>
    import onnx.defs as defs
  File "/Users/grokmachine/.pyenv/versions/3.7.0/lib/python3.7/site-packages/onnx/defs/__init__.py", line 8, in <module>
    import onnx.onnx_cpp2py_export.defs as C
ImportError: dlopen(/Users/grokmachine/.pyenv/versions/3.7.0/lib/python3.7/site-packages/onnx/onnx_cpp2py_export.cpython-37m-darwin.so, 2): Symbol not found: __ZN6google8protobuf18GoogleOnceInitImplEPlPNS0_7ClosureE
  Referenced from: /Users/grokmachine/.pyenv/versions/3.7.0/lib/python3.7/site-packages/onnx/onnx_cpp2py_export.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/grokmachine/.pyenv/versions/3.7.0/lib/python3.7/site-packages/onnx/onnx_cpp2py_export.cpython-37m-darwin.so
```

**Comment by houseroad** [comment]
How do you install the onnx?

**Comment by dendisuhubdy** [comment]
I tried both compiling it from source and trying installing from pip. I'm on Mac OS X 10.13

**Comment by houseroad** [comment]
Sure, @dendisuhubdy how did you install protobuf?

**Comment by dendisuhubdy** [comment]
`brew install protobuf`

**Comment by dendisuhubdy** [comment]
Nevermind, this was my mistake not doing a `git submodule update --init`
