### ISSUE TITLE
Problem installing onnx from source

### ISSUE THREAD

**Issue by elboyran** [onnx/onnx#1302]
After installing onnx from binaries and encountering problems (missing functions) when running the Python API notebooks and after an advice to install from source, I have attempted several times to do so. Unfortunately, the installation check does not work. 
Windows host, VBox 5.2.18 virtual machine Ubuntu 18.04. 

Below is exactly what I did (following the installation instructions) in my last attempt:
```
elena@elena-VirtualBox:~$ cd eStep/XAI/Software/
elena@elena-VirtualBox:~/eStep/XAI/Software$ conda update -n base -c defaults conda
elena@elena-VirtualBox:~/eStep/XAI/Software$ conda create --name onnx_elena
elena@elena-VirtualBox:~/eStep/XAI/Software$ source activate onnx_elena
(onnx_elena) elena@elena-VirtualBox:~/eStep/XAI/Software$ conda config --add channels conda-forge
(onnx_elena) elena@elena-VirtualBox:~/eStep/XAI/Software$ conda install -c conda-forge protobuf numpy
(onnx_elena) elena@elena-VirtualBox:~/eStep/XAI/Software$ git clone https://github.com/onnx/onnx.git
(onnx_elena) elena@elena-VirtualBox:~/eStep/XAI/Software$ cd onnx
(onnx_elena) elena@elena-VirtualBox:~/eStep/XAI/Software/onnx$ git submodule update --init --recursive
(onnx_elena) elena@elena-VirtualBox:~/eStep/XAI/Software/onnx$ python setup.py install
(onnx_elena) elena@elena-VirtualBox:~/eStep/XAI/Software/onnx$ cd onnx
(onnx_elena) elena@elena-VirtualBox:~/eStep/XAI/Software/onnx/onnx$ python -c "import onnx"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/elena/anaconda3/envs/onnx_elena/lib/python3.6/site-packages/onnx-1.2.2-py3.6-linux-x86_64.egg/onnx/__init__.py", line 11, in <module>
    import onnx.helper  # noqa
  File "/home/elena/anaconda3/envs/onnx_elena/lib/python3.6/site-packages/onnx-1.2.2-py3.6-linux-x86_64.egg/onnx/helper.py", line 13, in <module>
    import onnx.defs as defs
  File "/home/elena/anaconda3/envs/onnx_elena/lib/python3.6/site-packages/onnx-1.2.2-py3.6-linux-x86_64.egg/onnx/defs/__init__.py", line 7, in <module>
    import onnx.onnx_cpp2py_export.defs as C
ImportError: /home/elena/anaconda3/envs/onnx_elena/lib/python3.6/site-packages/onnx-1.2.2-py3.6-linux-x86_64.egg/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev
```

Please, advice!

**Comment by elboyran** [comment]
Following the advice from issue #745 to use conda instead of conda-forge did not help either:
```
(onnx_elena) elena@elena-VirtualBox:~/eStep/XAI/Software$ pip uninstall onnx
(onnx_elena) elena@elena-VirtualBox:~/eStep/XAI/Software$ conda install protobuf numpy
(onnx_elena) elena@elena-VirtualBox:~/eStep/XAI/Software$ cd onnx
(onnx_elena) elena@elena-VirtualBox:~/eStep/XAI/Software/onnx$ python setup.py install
(onnx_elena) elena@elena-VirtualBox:~/eStep/XAI/Software/onnx$ cd onnx
(onnx_elena) elena@elena-VirtualBox:~/eStep/XAI/Software/onnx/onnx$ python -c "import onnx"
(onnx_elena) elena@elena-VirtualBox:~/eStep/XAI/Software/onnx/onnx$ python -c "import onnx"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/elena/anaconda3/envs/onnx_elena/lib/python3.6/site-packages/onnx-1.2.2-py3.6-linux-x86_64.egg/onnx/__init__.py", line 11, in <module>
    import onnx.helper  # noqa
  File "/home/elena/anaconda3/envs/onnx_elena/lib/python3.6/site-packages/onnx-1.2.2-py3.6-linux-x86_64.egg/onnx/helper.py", line 13, in <module>
    import onnx.defs as defs
  File "/home/elena/anaconda3/envs/onnx_elena/lib/python3.6/site-packages/onnx-1.2.2-py3.6-linux-x86_64.egg/onnx/defs/__init__.py", line 7, in <module>
    import onnx.onnx_cpp2py_export.defs as C
ImportError: /home/elena/anaconda3/envs/onnx_elena/lib/python3.6/site-packages/onnx-1.2.2-py3.6-linux-x86_64.egg/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev
```

**Comment by elboyran** [comment]
Using pip seems to work.

```
*********************************************
elena@elena-VirtualBox:~/eStep/XAI/Software$ conda create --name onnx_ely
elena@elena-VirtualBox:~/eStep/XAI/Software$ source activate onnx_ely
(onnx_ely) elena@elena-VirtualBox:~/eStep/XAI/Software$ conda install protobuf numpy
(onnx_ely) elena@elena-VirtualBox:~/eStep/XAI/Software$ pip install onnx
(onnx_ely) elena@elena-VirtualBox:~/eStep/XAI/Software$ python -c "import onnx"
```

But installing from source still doesn't and should be fixed. Installing from binaries installs old onnx.

**Comment by houseroad** [comment]
Since you are not using `python setup.py develop`, you probably should not enter the `onnx` folder to execute the command. Try to execute python -c "import onnx" in other folder?

**Comment by ArmenAg** [comment]
I'm having this same issue building from source.

**Comment by clovett** [comment]
Me too...
```
ImportError: /root/miniconda3/envs/py36/lib/python3.6/site-packages/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev
```

**Comment by maxwillzq** [comment]
I have same problem after change to other folder 

the error message is same 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/qzhang/Documents/OpenSource/onnx/onnx/__init__.py", line 14, in <module>
    import onnx.helper  # noqa
  File "/Users/qzhang/Documents/OpenSource/onnx/onnx/helper.py", line 13, in <module>
    import onnx.defs as defs
  File "/Users/qzhang/Documents/OpenSource/onnx/onnx/defs/__init__.py", line 7, in <module>
    import onnx.onnx_cpp2py_export.defs as C
ModuleNotFoundError: No module named 'onnx.onnx_cpp2py_export.defs'
```

Any suggestion ? I exactly follow the contribution guide page 
https://github.com/onnx/onnx/blob/master/docs/CONTRIBUTING.md

**Comment by maxwillzq** [comment]
when I use "python setup.py develop", it works now.
We should improve our document on this

**Comment by houseroad** [comment]
seems it's path related issue. Try to uninstall onnx package first, then use `pip install .` to install the package. You have to change your folder to run the python cmd. Otherwise, python runtime may get confused.

**Comment by yuslepukhin** [comment]
Please, follow the  updated build instructions for Windows.
