### ISSUE TITLE
pip install onnx does not work on windows 10

### ISSUE THREAD

**Issue by RanACohen** [onnx/onnx#1446]
```
C:\Users\rancohen>pip install onnx==1.3.0
Collecting onnx==1.3.0
  Using cached https://files.pythonhosted.org/packages/cd/eb/9761255a96e988710aafdfde3d5698fd785845b981aba1f495150ffbf4b3/onnx-1.3.0-cp36-cp36m-win_amd64.whl
Requirement already satisfied: typing>=3.6.4 in c:\users\rancohen\appdata\local\programs\python\python36\lib\site-packages (from onnx==1.3.0) (3.6.6)
Requirement already satisfied: typing-extensions>=3.6.2.1 in c:\users\rancohen\appdata\local\programs\python\python36\lib\site-packages (from onnx==1.3.0) (3.6.5)
Requirement already satisfied: six in c:\users\rancohen\appdata\local\programs\python\python36\lib\site-packages (from onnx==1.3.0) (1.10.0)
Requirement already satisfied: protobuf in c:\users\rancohen\appdata\local\programs\python\python36\lib\site-packages (from onnx==1.3.0) (3.6.1)
Requirement already satisfied: numpy in c:\users\rancohen\appdata\local\programs\python\python36\lib\site-packages (from onnx==1.3.0) (1.12.1)
Requirement already satisfied: setuptools in c:\users\rancohen\appdata\local\programs\python\python36\lib\site-packages (from protobuf->onnx==1.3.0) (28.8.0)
Installing collected packages: onnx
  Found existing installation: onnx 1.2.2
    Uninstalling onnx-1.2.2:
      Successfully uninstalled onnx-1.2.2
Successfully installed onnx-1.3.0

C:\Users\rancohen>python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rancohen\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx\__init__.py", line 6, in <module>
    from .onnx_pb import *  # noqa
  File "C:\Users\rancohen\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx\onnx_pb.py", line 8, in <module>
    from .onnx_ml_pb2 import *  # noqa
  File "C:\Users\rancohen\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx\onnx_ml_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\rancohen\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.

```

**Comment by raymondxyang** [comment]
What's the python protobuf package version? 1.3.0 seems work with 3.6.1

**Comment by RanACohen** [comment]
protobuf is 3.6.1:
`Requirement already satisfied: protobuf in c:\users\rancohen\appdata\local\programs\python\python36\lib\site-packages (from onnx==1.3.0) (3.6.1)`

Still does not work on a clean machine

**Comment by mx-iao** [comment]
Can you try installing in an Anaconda environment with the following commands:
`conda install -c conda-forge protobuf numpy`
Then:
`pip install onnx`
Works for me on Windows 10

**Comment by prasanthpul** [comment]
Please try @mx-iao suggestion. There are many people successfully installing and using ONNX package on Windows 10. Feel free to re-open the issue if you still have a problem.

**Comment by srohit0** [comment]
I've the same issue.
