### ISSUE TITLE
onnx export to tf error

### ISSUE THREAD

**Issue by uhvardhan** [onnx/onnx#1483]
I am trying to export a onnx model to tf. Here is the code:

`import onnx
from onnx_tf.backend import prepare

# Load the ONNX file
model = onnx.load('model.onnx')

# Import the onnx model to Tensorflow
tf_rep = prepare(model)

# Input nodes to the model
print('inputs:', tf_rep.inputs)

# Output nodes from the model
print('outputs:', tf_rep.outputs)

# All nodes in the model
print('tensor_dict:')
print(tf_rep.tensor_dict)`

I am following the steps in the tutorial.[Tutorial](https://github.com/onnx/tutorials/blob/master/tutorials/PytorchTensorflowMnist.ipynb)

I get the following error: 
`Traceback (most recent call last):
  File "/tmp/pycharm_project_896/utils/onnx2tf.py", line 8, in <module>
    tf_rep = prepare(model)
  File "/home/harsh/git_clone/onnx-tensorflow/onnx_tf/backend.py", line 74, in prepare
    super(TensorflowBackend, cls).prepare(model, device, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/onnx/backend/base.py", line 65, in prepare
    onnx.checker.check_model(model)
  File "/usr/local/lib/python2.7/dist-packages/onnx/checker.py", line 82, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: model with IR version < 3 cannot have opset_import specified`

Can anyone explain where I am going wrong?

Thanks

**Comment by fumihwh** [comment]
@uhvardhan Could you share your pb file?
Seems your pb file has some problem.

**Comment by uhvardhan** [comment]
It's a pth file. I first tried to convert pth files to onnx model and then to tf model. 
[ResNet-2018-09-18T21:50:42.pth.zip](https://github.com/onnx/onnx/files/2461094/ResNet-2018-09-18T21.50.42.pth.zip)

**Comment by houseroad** [comment]
@uhvardhan could you move this issue to onnx-tf repository?
