### ISSUE TITLE
ONNX not able to installed from Alpine Linux

### ISSUE THREAD

**Issue by little-eyes** [onnx/onnx#1534]
I try to build a container image from Alpine Linux and install onnx, but it seems to get into errors below. Can anyone help?

Dockerfile
```shell
FROM python:3.6-alpine3.8

RUN apk update && \
	apk add --no-cache \
    # bash \
    libstdc++ \
    libgomp \
    build-base \
    cmake \
    gfortran \
    libpng && \
    ln -s locale.h /usr/include/xlocale.h && \
    apk add --no-cache --virtual .build-deps \
    lapack-dev \
    musl-dev \
    python3-dev \
    jpeg-dev \
    freetype-dev \
    libffi-dev \
    openssl-dev \
    gcc \
    g++ && \
    pip install --no-cache-dir \
    onnxmltools==1.2.2.129
```

The error is the following:

  Running setup.py install for onnx: started
    Running setup.py install for onnx: finished with status 'error'
    Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-qvye8hkx/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-tka9qavc/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running create_version
    running cmake_build
    -- Build type not set - defaulting to Release
    -- The C compiler identification is GNU 6.4.0
    -- The CXX compiler identification is GNU 6.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at CMakeLists.txt:216 (message):
      Protobuf compiler not found
    Call Stack (most recent call first):
      CMakeLists.txt:247 (relative_protobuf_generate_cpp)

    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-qvye8hkx/onnx/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qvye8hkx/onnx/setup.py", line 328, in <module>
        'backend-test-tools = onnx.backend.test.cmd_tools:main',
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-qvye8hkx/onnx/setup.py", line 203, in run
        self.run_command('cmake_build')
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-qvye8hkx/onnx/setup.py", line 190, in run
        subprocess.check_call(cmake_args)
      File "/usr/local/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/local/include/python3.6m', '-DPYTHON_EXECUTABLE=/usr/local/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-36m-x86_64-linux-gnu.so', '/tmp/pip-install-qvye8hkx/onnx']' returned non-zero exit status 1.

    ----------------------------------------
Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-qvye8hkx/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-tka9qavc/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-qvye8hkx/onnx/

Related package versions:

(1/33) Installing binutils (2.30-r5)
(2/33) Installing libmagic (5.32-r0)
(3/33) Installing file (5.32-r0)
(4/33) Installing gmp (6.1.2-r1)
(5/33) Installing isl (0.18-r0)
(6/33) Installing libgomp (6.4.0-r9)
(7/33) Installing libatomic (6.4.0-r9)
(8/33) Installing pkgconf (1.5.3-r0)
(9/33) Installing libgcc (6.4.0-r9)
(10/33) Installing mpfr3 (3.1.5-r1)
(11/33) Installing mpc1 (1.0.3-r1)
(12/33) Installing libstdc++ (6.4.0-r9)
(13/33) Installing gcc (6.4.0-r9)
(14/33) Installing musl-dev (1.1.19-r10)
(15/33) Installing libc-dev (0.7.1-r0)
(16/33) Installing g++ (6.4.0-r9)
(17/33) Installing make (4.2.1-r2)
(18/33) Installing fortify-headers (0.9-r0)
(19/33) Installing build-base (0.5-r1)
(20/33) Installing libattr (2.4.47-r7)
(21/33) Installing libacl (2.2.52-r5)
(22/33) Installing lz4-libs (1.8.2-r0)
(23/33) Installing libarchive (3.3.2-r3)
(24/33) Installing nghttp2-libs (1.32.0-r0)
(25/33) Installing libssh2 (1.8.0-r3)
(26/33) Installing libcurl (7.61.1-r0)
(27/33) Installing rhash-libs (1.3.6-r1)
(28/33) Installing libuv (1.20.2-r0)
(29/33) Installing cmake (3.11.1-r2)
(30/33) Installing libquadmath (6.4.0-r9)
(31/33) Installing libgfortran (6.4.0-r9)
(32/33) Installing gfortran (6.4.0-r9)
(33/33) Installing libpng (1.6.34-r1)
Executing busybox-1.28.4-r1.trigger
OK: 229 MiB in 66 packages
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/16) Installing lapack (3.8.0-r0)
(2/16) Installing lapack-dev (3.8.0-r0)
(3/16) Installing python3 (3.6.6-r0)
(4/16) Installing python3-dev (3.6.6-r0)
(5/16) Installing libjpeg-turbo (1.5.3-r3)
(6/16) Installing libjpeg-turbo-dev (1.5.3-r3)
(7/16) Installing jpeg-dev (8-r6)
(8/16) Installing freetype (2.9.1-r1)
(9/16) Installing zlib-dev (1.2.11-r1)
(10/16) Installing libpng-dev (1.6.34-r1)
(11/16) Installing freetype-dev (2.9.1-r1)
(12/16) Installing libffi-dev (3.2.1-r4)
(13/16) Installing libcrypto1.0 (1.0.2p-r0)
(14/16) Installing libssl1.0 (1.0.2p-r0)
(15/16) Installing openssl-dev (1.0.2p-r0)

**Comment by little-eyes** [comment]
> `Protobuf compiler not found`
> 
> protoc cannot be found in your path.

Thank you @houseroad, missed it. This solved the problem.
