### ISSUE TITLE
error incompatible with your Protocol Buffer headers. Please update. fatal error: google/protobuf/generated_message_table_driven.h: No such file or directory

### ISSUE THREAD

**Issue by karlTUM** [onnx/onnx#1559]
Hi,
I would like to install onnx from source. I followed the installation as:
```
git clone https://github.com/onnx/onnx.git
cd onnx
git submodule update --init --recursive
python setup.py install
```
But it got errors:
```
running install
running bdist_egg
running egg_info
writing onnx.egg-info/PKG-INFO
writing dependency_links to onnx.egg-info/dependency_links.txt
writing entry points to onnx.egg-info/entry_points.txt
writing requirements to onnx.egg-info/requires.txt
writing top-level names to onnx.egg-info/top_level.txt
reading manifest file 'onnx.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'onnx.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running create_version
running cmake_build
CMake Warning at /usr/share/cmake-3.10/Modules/FindProtobuf.cmake:455 (message):
  Protobuf compiler version 3.3.0 doesn't match library version 3.0.0
Call Stack (most recent call first):
  CMakeLists.txt:103 (find_package)


CMake Warning at CMakeLists.txt:352 (find_package):
  By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pybind11",
  but CMake did not find one.

  Could not find a package configuration file provided by "pybind11"
  (requested version 2.2) with any of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.


-- 
-- ******** Summary ********
--   CMake version         : 3.10.2
--   CMake command         : /usr/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 7.3.0
--   CXX flags             : 
--   Build type            : Release
--   Compile definitions   : 
--   CMAKE_PREFIX_PATH     : 
--   CMAKE_INSTALL_PREFIX  : /usr/local
--   CMAKE_MODULE_PATH     : 
-- 
--   ONNX version          : 1.3.0
--   ONNX NAMESPACE        : onnx
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
-- 
--   Protobuf compiler     : /usr/local/bin/protoc
--   Protobuf includes     : /usr/include
--   Protobuf libraries    : /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread
--   BUILD_ONNX_PYTHON     : ON
--     Python version      : 
--     Python executable   : /home/karl/anaconda3/envs/py36/bin/python
--     Python includes     : /home/karl/anaconda3/envs/py36/include/python3.6m
-- Configuring done
-- Generating done
-- Build files have been written to: /home/karl/Documents/work_code/py/mxnet_face/onnx/.setuptools-cmake-build
[  3%] Built target onnxifi_dummy
[  7%] Built target gen_onnx_proto
[ 11%] Built target onnxifi_loader
[ 13%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx.pb.cc.o
[ 15%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-operators.pb.cc.o
[ 19%] Built target onnxifi_wrapper
In file included from /home/karl/Documents/work_code/py/mxnet_face/onnx/.setuptools-cmake-build/onnx/onnx.pb.cc:5:0:
/home/karl/Documents/work_code/py/mxnet_face/onnx/.setuptools-cmake-build/onnx/onnx.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^~~~~
/home/karl/Documents/work_code/py/mxnet_face/onnx/.setuptools-cmake-build/onnx/onnx.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^~~~~
/home/karl/Documents/work_code/py/mxnet_face/onnx/.setuptools-cmake-build/onnx/onnx.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^~~~~
In file included from /home/karl/Documents/work_code/py/mxnet_face/onnx/.setuptools-cmake-build/onnx/onnx.pb.cc:5:0:
/home/karl/Documents/work_code/py/mxnet_face/onnx/.setuptools-cmake-build/onnx/onnx.pb.h:25:10: fatal error: google/protobuf/generated_message_table_driven.h: No such file or directory
 #include <google/protobuf/generated_message_table_driven.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/karl/Documents/work_code/py/mxnet_face/onnx/.setuptools-cmake-build/onnx/onnx-operators.pb.cc:5:0:
/home/karl/Documents/work_code/py/mxnet_face/onnx/.setuptools-cmake-build/onnx/onnx-operators.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^~~~~
/home/karl/Documents/work_code/py/mxnet_face/onnx/.setuptools-cmake-build/onnx/onnx-operators.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^~~~~
/home/karl/Documents/work_code/py/mxnet_face/onnx/.setuptools-cmake-build/onnx/onnx-operators.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^~~~~
CMakeFiles/onnx_proto.dir/build.make:84: recipe for target 'CMakeFiles/onnx_proto.dir/onnx/onnx.pb.cc.o' failed
make[2]: *** [CMakeFiles/onnx_proto.dir/onnx/onnx.pb.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/karl/Documents/work_code/py/mxnet_face/onnx/.setuptools-cmake-build/onnx/onnx-operators.pb.cc:5:0:
/home/karl/Documents/work_code/py/mxnet_face/onnx/.setuptools-cmake-build/onnx/onnx-operators.pb.h:25:10: fatal error: google/protobuf/generated_message_table_driven.h: No such file or directory
 #include <google/protobuf/generated_message_table_driven.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/onnx_proto.dir/build.make:108: recipe for target 'CMakeFiles/onnx_proto.dir/onnx/onnx-operators.pb.cc.o' failed
make[2]: *** [CMakeFiles/onnx_proto.dir/onnx/onnx-operators.pb.cc.o] Error 1
CMakeFiles/Makefile2:242: recipe for target 'CMakeFiles/onnx_proto.dir/all' failed
make[1]: *** [CMakeFiles/onnx_proto.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 328, in <module>
    'backend-test-tools = onnx.backend.test.cmd_tools:main',
  File "/home/karl/anaconda3/envs/py36/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/home/karl/anaconda3/envs/py36/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/karl/anaconda3/envs/py36/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/karl/anaconda3/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/karl/anaconda3/envs/py36/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/karl/anaconda3/envs/py36/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/karl/anaconda3/envs/py36/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/karl/anaconda3/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/karl/anaconda3/envs/py36/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/karl/anaconda3/envs/py36/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/home/karl/anaconda3/envs/py36/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/karl/anaconda3/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/karl/anaconda3/envs/py36/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/karl/anaconda3/envs/py36/lib/python3.6/distutils/command/install_lib.py", line 105, in build
    self.run_command('build_py')
  File "/home/karl/anaconda3/envs/py36/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/karl/anaconda3/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 203, in run
    self.run_command('cmake_build')
  File "/home/karl/anaconda3/envs/py36/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/karl/anaconda3/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 197, in run
    subprocess.check_call(build_args)
  File "/home/karl/anaconda3/envs/py36/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '.', '--', '-j', '8']' returned non-zero exit status 2.


```
Does anyone know how to solve this problem?

Thank you.

**Comment by snnn** [comment]
```
--   Protobuf compiler     : /usr/local/bin/protoc
--   Protobuf includes     : /usr/include
```

They don't match.

**Comment by karlTUM** [comment]
I reinstall Anaconda3.6 and it works.
