### ISSUE TITLE
onnx.onnx_cpp2py_export.checker.ValidationError: Field 'name' of graph is required to be non-empty.

### ISSUE THREAD

**Issue by lilichu** [onnx/onnx#1593]
hi! I just execute the code of [tutorials:](https://github.com/onnx/tutorials/blob/master/tutorials/Caffe2OnnxExport.ipynb)
```
import onnx
import caffe2.python.onnx.frontend
from caffe2.proto import caffe2_pb2

# We need to provide type and shape of the model inputs, 
# see above Note section for explanation
data_type = onnx.TensorProto.FLOAT
data_shape = (1, 3, 224, 224)
value_info = {
    'data': (data_type, data_shape)
}

predict_net = caffe2_pb2.NetDef()
with open('predict_net.pb', 'rb') as f:
    predict_net.ParseFromString(f.read())

init_net = caffe2_pb2.NetDef()
with open('init_net.pb', 'rb') as f:
    init_net.ParseFromString(f.read())

onnx_model = caffe2.python.onnx.frontend.caffe2_net_to_onnx_model(
    predict_net,
    init_net,
    value_info,
)

onnx.checker.check_model(onnx_model)
```
then I encounter the issue:
```
Traceback (most recent call last):
  File "caffe2_onnx.py", line 41, in <module>
    value_info,
  File "/home/user/pytorch/build/caffe2/python/onnx/frontend.py", line 332, in caffe2_net_to_onnx_model
    model = make_model(cls.caffe2_net_to_onnx_graph(*args, **kwargs),
  File "/home/user/pytorch/build/caffe2/python/onnx/frontend.py", line 268, in caffe2_net_to_onnx_graph
    checker.check_graph(graph_def)
  File "/usr/local/lib/python2.7/dist-packages/onnx/checker.py", line 51, in checker
    proto.SerializeToString(), ctx)
onnx.onnx_cpp2py_export.checker.ValidationError: Field 'name' of graph is required to be non-empty.
```
could anyone help me? thanks!

**Comment by linkerzhang** [comment]
as the error message shown, an onnx graph needs a name.  @houseroad may have idea on fixing the issue since this piece of code is exporting caffe2 net to onnx model.

**Comment by lilichu** [comment]
hi! @houseroad  could you please help me?thanks! I just run the code of [tutorials](https://github.com/onnx/tutorials/blob/master/tutorials/Caffe2OnnxExport.ipynb)

**Comment by lilichu** [comment]
I add the code such as:
```
# if predict_net.name == "":
#     predict_net.name = "ModelNameHere"
```
It is OK .
