### ISSUE TITLE
onnx.onnx_cpp2py_export.checker.ValidationError: No Schema registered for Shape

### ISSUE THREAD

**Issue by lilichu** [onnx/onnx#1621]
anaconda3
python3.6
pytorch： 0.4.1
onnx: 1.0.1

hi! I install onnx: `conda install -c conda-forge onnx`. then I run the tutorial[https://pytorch.org/docs/master/onnx.html](url)(alexnet.onnx), when I run 
```
import onnx

# Load the ONNX model
model = onnx.load("alexnet.onnx")

# Check that the IR is well formed
onnx.checker.check_model(model)

# Print a human readable representation of the graph
onnx.helper.printable_graph(model.graph)
```
 I encounter the issue:
```
Traceback (most recent call last):
  File "example.py", line 7, in <module>
    onnx.checker.check_model(model)
  File "/home/user/anaconda3/envs/python36/lib/python3.6/site-packages/onnx/checker.py", line 32, in checker
    proto.SerializeToString(), ir_version)
onnx.onnx_cpp2py_export.checker.ValidationError: No Schema registered for Shape

==> Context: Bad node spec: input: "29" output: "30" op_type: "Shape"
```

**Comment by lilichu** [comment]
`pip install onnx` is OK.
