### ISSUE TITLE
Got error with upsampling operation

### ISSUE THREAD

**Issue by ht-alchera** [onnx/onnx#1655]
my implementation is below..
```
import onnx
from onnx import helper
from onnx import TensorProto

import numpy as np

data = np.array([[[
    [1, 2],
    [3, 4],
]]], dtype=np.float32)

scales = np.array([1.0, 1.0, 2.0, 3.0], dtype=np.float32)

inputs = list()
input_tensor = helper.make_tensor_value_info(
    'x', TensorProto.FLOAT, data.shape)
scale_tensor = helper.make_tensor_value_info(
    'scales', TensorProto.FLOAT, (4,))
inputs.append(input_tensor)
inputs.append(scale_tensor)

initializers = list()
initializers.append(helper.make_tensor('scales', TensorProto.FLOAT, scales.shape, scales))

graph = helper.make_graph(
            nodes=[helper.make_node("Upsample", ['x', 'scales'], ['y'])],
            name='UPSAMPLE-TEST',
            inputs=inputs,
            outputs=[],
            initializer=initializers)

model_def = helper.make_model(graph)
onnx.checker.check_model(model_def)
```

and I got the output

```
onnx.onnx_cpp2py_export.checker.ValidationError: Input size 2 not in range [min=1, max=1].

==> Context: Bad node spec: input: "x" input: "scales" output: "y" op_type: "Upsample"
```

I can't understand error message..any hint?
Thanks!

my onnx version is 1.3.0 with python 2.7.15.

**Comment by ht-alchera** [comment]
This code is work..

```
data = np.array([[[
    [1, 2],
    [3, 4],
]]], dtype=np.float32)

scales = np.array([1.0, 1.0, 2.0, 3.0], dtype=np.float32)

inputs = list()
input_tensor = helper.make_tensor_value_info(
    'x', TensorProto.FLOAT, data.shape)
# scale_tensor = helper.make_tensor_value_info(
#     'scales', TensorProto.FLOAT, (4,))
inputs.append(input_tensor)
# inputs.append(scale_tensor)

# initializers = list()
# initializers.append(helper.make_tensor('scales', TensorProto.FLOAT, scales.shape, scales))

graph = helper.make_graph(
            nodes=[helper.make_node(
                "Upsample",
                inputs=['x'],
                scales=[1.0, 1.0, 2.0, 3.0],
                outputs=['y'])],
            name='UPSAMPLE-TEST',
            inputs=inputs,
            outputs=[])

model_def = helper.make_model(graph)
onnx.checker.check_model(model_def)

onnx.save(model_def, 'upsample.onnx')
```

but, I ran 'convert-onnx-to-caffe2' command to convert to caffe2 model after save onnx file.
I got this message..

```
ONNX FATAL: [enforce fail at backend.cc:1239] . Expects 2 input in upsample after onnx version 9
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x59 (0x7fb7674b3c29 in /home/anaconda3/envs/py2715/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #1: caffe2::onnx::Caffe2Backend::CreateUpsample(caffe2::onnx::OnnxNode*, caffe2::onnx::ConversionContext const&) + 0xf79 (0x7fb796708c79 in /home/anaconda3/envs/py2715/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #2: caffe2::onnx::Caffe2Backend::OnnxNodeToCaffe2Ops(onnx_torch::ModelProto const&, onnx_torch::ModelProto const&, caffe2::onnx::ConversionContext const&, caffe2::onnx::OnnxNode*) + 0x115 (0x7fb7967079e5 in /home/anaconda3/envs/py2715/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #3: caffe2::onnx::Caffe2Backend::ConvertNode(std::string const&, caffe2::onnx::ConversionContext const&) + 0x118 (0x7fb796708e58 in /home/anaconda3/envs/py2715/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #4: <unknown function> + 0x59bf3 (0x7fb79798bbf3 in /home/anaconda3/envs/py2715/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state_gpu.so)
frame #5: <unknown function> + 0x8bab8 (0x7fb7979bdab8 in /home/anaconda3/envs/py2715/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state_gpu.so)
<omitting python frames>
frame #40: __libc_start_main + 0xf0 (0x7fb7a652e830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #41: <unknown function> + 0x107f (0x562dcf1c307f in /home/anaconda3/envs/py2715/bin/python)
```

well..what's going on in onnx & caffe2?

I thought it comes from mismatch version. but I used onnx 1.3.0(is it operator-9? right?).
however my implementation is work when i implement like upsample-7. and not work for convert to caffe2..
:(

**Comment by achigeor** [comment]
I have the same issue https://github.com/onnx/onnx/issues/1638

**Comment by ht-alchera** [comment]
@achigeor oh, I guess it is some versioning problem in onnx..:(

**Comment by lyuwenyu** [comment]
I have the same problem

pytorch `1.0.0.dev20181130`
python `3.6`
onnx `1.3.0`

**Comment by YueshangGu** [comment]
same question, I want to convert my caffe2 model(with ResizeNearest operator) to onnx. But I get this error.
```
onnx.onnx_cpp2py_export.checker.ValidationError: Input size 2 not in range [min=1, max=1].

==> Context: Bad node spec: input: "fpn_inner_res5_1_sum" input: "OC2_DUMMY_0" output: "fpn_inner_res4_1_sum_topdown" op_type: "Upsample" attribute { name: "mode" s: "nearest" type: STRING }
```

**Comment by xxradon** [comment]
@ht-alchera @achigeor @lyuwenyu @YueshangGu    EveryOne,I think I got a way to handle this bug,change the code https://github.com/onnx/onnx/blob/f612532843bd8e24efeab2815e45b436479cc9ab/onnx/defs/tensor/defs.cc#L1179

`if (!hasNInputShapes(ctx, 1))`
to 
`if (!hasNInputShapes(ctx, 2))`.
And rebuild the onnx and install ,then you will find "onnx.onnx_cpp2py_export.checker.ValidationError: Input size 2 not in range [min=1, max=1]." error can be fixed.
Tips,before you install the onnx,you should use pip uninstall onnx.

**Comment by ht-alchera** [comment]
@xxradon oh, I'm going to try!

**Comment by ht-alchera** [comment]
@xxradon it works for me :) thanks!

**Comment by lyuwenyu** [comment]
@xxradon  Very nice, THX.

**Comment by YueshangGu** [comment]
@xxradon I have a problem when I build onnx from source. I can build success but when I import onnx I get    this error.
```
>>> import onnx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kai/anaconda2/lib/python2.7/site-packages/onnx-1.3.0-py2.7-linux-x86_64.egg/onnx/__init__.py", line 11, in <module>
    import onnx.helper  # noqa
  File "/home/kai/anaconda2/lib/python2.7/site-packages/onnx-1.3.0-py2.7-linux-x86_64.egg/onnx/helper.py", line 13, in <module>
    import onnx.defs as defs
  File "/home/kai/anaconda2/lib/python2.7/site-packages/onnx-1.3.0-py2.7-linux-x86_64.egg/onnx/defs/__init__.py", line 7, in <module>
    import onnx.onnx_cpp2py_export.defs as C
ImportError: /home/kai/anaconda2/lib/python2.7/site-packages/onnx-1.3.0-py2.7-linux-x86_64.egg/onnx/onnx_cpp2py_export.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev
```
and the protobuf info
```
libprotobuf               3.5.2                hd28b015_1    conda-forge
protobuf                  3.5.2            py27hd28b015_0    conda-forge
```
I find an issue #745  about it but I don't get the solution. Can you help me?

**Comment by xxradon** [comment]
@YueshangGu Actually,this error came up with protobuf version mismatching,there are two protobuf in your system,one is in your system by apt-get install ,the other is in anaconda by conda install ,so if you build install onnx,you should point out which protobuf you use.

**Comment by YueshangGu** [comment]
@xxradon I remove the protobuf installed by apt-get install, and in camke output it should use the protobuf in anaconda, but I still get the error above.

cmake output
```
running install
running bdist_egg
running egg_info
writing requirements to onnx.egg-info/requires.txt
writing onnx.egg-info/PKG-INFO
writing top-level names to onnx.egg-info/top_level.txt
writing dependency_links to onnx.egg-info/dependency_links.txt
writing entry points to onnx.egg-info/entry_points.txt
reading manifest file 'onnx.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'onnx.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running create_version
running cmake_build
-- Found Protobuf: /home/kai/anaconda2/lib/libprotobuf.so (found version "3.5.1")
--
-- ******** Summary ********
--   CMake version         : 3.13.1
--   CMake command         : /usr/local/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   CXX flags             :  -Wnon-virtual-dtor
--   Build type            : Release
--   Compile definitions   :
--   CMAKE_PREFIX_PATH     :
--   CMAKE_INSTALL_PREFIX  : /usr/local
--   CMAKE_MODULE_PATH     : /home/kai/anaconda2/share/cmake/pybind11
--
--   ONNX version          : 1.3.0
--   ONNX NAMESPACE        : onnx
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
--
--   Protobuf compiler     : /home/kai/anaconda2/bin/protoc
--   Protobuf includes     : /home/kai/anaconda2/include
--   Protobuf libraries    : /home/kai/anaconda2/lib/libprotobuf.so
--   BUILD_ONNX_PYTHON     : ON
--     Python version      :
--     Python executable   : /home/kai/anaconda2/bin/python
--     Python includes     : /home/kai/anaconda2/include/python2.7
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/d/onnx/.setuptools-cmake-build
```
more info
```
kai@4CV80654G5:/mnt/d$ which protoc
/home/kai/anaconda2/bin/protoc
kai@4CV80654G5:/mnt/d$ whereis protoc
protoc: /home/kai/anaconda2/bin/protoc
kai@4CV80654G5:/mnt/d$ conda list | grep proto
libprotobuf               3.5.2                hd28b015_1    conda-forge
protobuf                  3.5.2            py27hd28b015_0    conda-forge
```

**Comment by glenn-jocher** [comment]
I have the same error with PyTorch 1.0 and ONNX 1.3.0. I think the original issue is: https://github.com/pytorch/pytorch/issues/10446

**Comment by xxradon** [comment]
@YueshangGu The error came from libprotobuf.so，not protoc,you should check using ldd command which libprotobuf.so you used by onnx make.
And @achigeor ,unsample error actually because of onnx's code,not pytorch's,so you should follow this https://github.com/onnx/onnx/issues/1655#issuecomment-446800091.

**Comment by allenling** [comment]
meet this error with ubuntu16.04+python3.5.2+pytorch1.3+onnx1.6...

could we resolve this without build onnx from source code?

i wanna move my model to trt6...
