### ISSUE TITLE
Cannot create operator of type 'BatchPermutation' on the device 'CUDA'

### ISSUE THREAD

**Issue by zhangxiang1993** [onnx/onnx#1666]
Hi 

When I am trying to convert caffe2 to ONNX. I got this error. 
The model is trained in Detectron, and converted to caffe2 .pb format.

# System information
*Operating system: Ubuntu 16.04
*CUDA version: 9.0
*cuDNN version: 7.1.4
*NVIDIA driver version: NVIDIA-SMI 390.87
*GPU models (for all devices if they are not all the same): GTX 1070
*python --version output: 2.7

```
[E operator.cc:143] Cannot find operator schema for BatchPermutation. Will skip schema checking.
WARNING:caffe2.python.workspace:Original python traceback for operator `190` in network `generalized_rcnn` in exception above (most recent call last):
Traceback (most recent call last):
  File "/home/**/PycharmProjects/caffe2/detectrontest/convert_caffe2_to_onnx.py", line 24, in <module>
    value_info,
  File "/home/**/anaconda2/lib/python2.7/site-packages/caffe2/python/onnx/frontend.py", line 350, in caffe2_net_to_onnx_model
    model = make_model(cls.caffe2_net_to_onnx_graph(*args, **kwargs),
  File "/home/**/anaconda2/lib/python2.7/site-packages/caffe2/python/onnx/frontend.py", line 232, in caffe2_net_to_onnx_graph
    inputs)
  File "/home/**/anaconda2/lib/python2.7/site-packages/caffe2/python/onnx/helper.py", line 62, in c2_native_run_net
    ws.RunNetOnce(predict_net)
  File "/home/**/anaconda2/lib/python2.7/site-packages/caffe2/python/onnx/workspace.py", line 63, in f
    return getattr(workspace, attr)(*args, **kwargs)
  File "/home/**/anaconda2/lib/python2.7/site-packages/caffe2/python/workspace.py", line 218, in RunNetOnce
    StringifyProto(net),
  File "/home/**/anaconda2/lib/python2.7/site-packages/caffe2/python/workspace.py", line 197, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at operator.cc:213] op. Cannot create operator of type 'BatchPermutation' on the device 'CUDA'. Verify that implementation for the corresponding device exist. It might also happen if the binary is not linked with the operator implementation code. If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing. Operator def: input: "roi_feat_shuffled" input: "rois_idx_restore_int32_gpu_0" output: "roi_feat" name: "" type: "BatchPermutation" device_option { device_type: 1 device_id: 0 }
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*) + 0x76 (0x7f60abeafd66 in /home/**/anaconda2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #1: caffe2::CreateOperator(caffe2::OperatorDef const&, caffe2::Workspace*, int) + 0xdf6 (0x7f60be096b46 in /home/**/anaconda2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #2: caffe2::SimpleNet::SimpleNet(std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*) + 0x425 (0x7f60be0b78a5 in /home/**/anaconda2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #3: <unknown function> + 0x11db77e (0x7f60be0b977e in /home/**/anaconda2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #4: <unknown function> + 0x11c5093 (0x7f60be0a3093 in /home/**/anaconda2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #5: caffe2::CreateNet(std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*) + 0xb49 (0x7f60be110369 in /home/**/anaconda2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #6: caffe2::CreateNet(caffe2::NetDef const&, caffe2::Workspace*) + 0x9d (0x7f60be1106bd in /home/**/anaconda2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #7: caffe2::Workspace::RunNetOnce(caffe2::NetDef const&) + 0x32 (0x7f60be0f89b2 in /home/**/anaconda2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #8: <unknown function> + 0x59108 (0x7f60bf403108 in /home/**/anaconda2/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state_gpu.so)
frame #9: <unknown function> + 0x592b4 (0x7f60bf4032b4 in /home/**/anaconda2/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state_gpu.so)
frame #10: <unknown function> + 0x95070 (0x7f60bf43f070 in /home/**/anaconda2/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state_gpu.so)
<omitting python frames>
frame #34: __libc_start_main + 0xf0 (0x7f60c44dd830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #35: <unknown function> + 0x107f (0x561479cc407f in /home/**/anaconda2/bin/python)

```

**Comment by fuzzyBatman** [comment]
You need to import Detectron ops. Assuming you are using the python tools for conversion add the following to your script ([ref](https://github.com/facebookresearch/Detectron/blob/e5bb3a8ff0b9caf59c76037726f49465d6b9678b/detectron/utils/c2.py#L42))

```
from caffe2.python import dyndep
import detectron.utils.env as envu

def import_detectron_ops():
    """Import Detectron ops."""
    detectron_ops_lib = envu.get_detectron_ops_lib()
    dyndep.InitOpsLibrary(detectron_ops_lib)

import_detectron_ops()
```

**Comment by prasanthpul** [comment]
Hope @fuzzyBatman's suggestion helped. If not, please open an issue in the caffe2 (pytorch) github so the experts can help you out.
