### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by ghltshubh** [onnx/onnx#1731]
```
$ python -c "import onnx"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "tensorflow-1.12-p3/anaconda3/lib/python3.6/site-packages/onnx-1.3.0-py3.6-linux-ppc64le.egg/onnx/__init__.py", line 11, in <module>
    import onnx.helper  # noqa
  File "tensorflow-1.12-p3/anaconda3/lib/python3.6/site-packages/onnx-1.3.0-py3.6-linux-ppc64le.egg/onnx/helper.py", line 13, in <module>
    import onnx.defs as defs
  File "tensorflow-1.12-p3/anaconda3/lib/python3.6/site-packages/onnx-1.3.0-py3.6-linux-ppc64le.egg/onnx/defs/__init__.py", line 7, in <module>
    import onnx.onnx_cpp2py_export.defs as C
ImportError: tensorflow-1.12-p3/anaconda3/lib/python3.6/site-packages/onnx-1.3.0-py3.6-linux-ppc64le.egg/onnx/onnx_cpp2py_export.cpython-36m-powerpc64le-linux-gnu.so: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringE
```

**Comment by houseroad** [comment]
you may have installed two protobuf in your system, one from os, one from conda. Please make sure you only install one, and use the only one to compile onnx.

**Comment by ghltshubh** [comment]
No I tried without installing anaconda protobuf as well.

**Comment by prasanthpul** [comment]
Please reopen if still an issue
