### ISSUE TITLE
onnx python install fails because of this warning: warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory

### ISSUE THREAD

**Issue by jeffsaremi** [onnx/onnx#1760]
Doing a pip install onnx
I get this:

```
Building wheels for collected packages: onnx
  Running setup.py bdist_wheel for onnx ... error
  Complete output from command C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\jesaremi\\AppData\\Local\\Temp\\pip-install-dsb5ydex\\onnx\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\jesaremi\AppData\Local\Temp\pip-wheel-ehfkgoqf --python-tag cp37:
  fatal: not a git repository (or any of the parent directories): .git
  running bdist_wheel
  running build
  running build_py
  running create_version
  running cmake_build
  -- Building for: Visual Studio 15 2017
  -- Build type not set - defaulting to Release
  -- The C compiler identification is MSVC 19.16.27026.1
  -- The CXX compiler identification is MSVC 19.16.27026.1
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Error at CMakeLists.txt:216 (message):
    Protobuf compiler not found
  Call Stack (most recent call first):
    CMakeLists.txt:247 (relative_protobuf_generate_cpp)


  -- Configuring incomplete, errors occurred!
  See also "C:/Users/jesaremi/AppData/Local/Temp/pip-install-dsb5ydex/onnx/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\jesaremi\AppData\Local\Temp\pip-install-dsb5ydex\onnx\setup.py", line 328, in <module>
      'backend-test-tools = onnx.backend.test.cmd_tools:main',
    File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\lib\site-packages\setuptools\__init__.py", line 143, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\jesaremi\AppData\Local\Temp\pip-install-dsb5ydex\onnx\setup.py", line 203, in run
      self.run_command('cmake_build')
    File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\jesaremi\AppData\Local\Temp\pip-install-dsb5ydex\onnx\setup.py", line 190, in run
      subprocess.check_call(cmake_args)
    File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\lib\subprocess.py", line 341, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['D:\\Program Files\\CMake\\bin\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Users\\jesaremi\\AppData\\Local\\Continuum\\anaconda3\\include', '-DPYTHON_EXECUTABLE=C:\\Users\\jesaremi\\AppData\\Local\\Continuum\\anaconda3\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp37-win_amd64.pyd', '-DPY_VERSION=3.7', '-DONNX_USE_MSVC_STATIC_RUNTIME=ON', '-DCMAKE_GENERATOR_PLATFORM=x64', 'C:\\Users\\jesaremi\\AppData\\Local\\Temp\\pip-install-dsb5ydex\\onnx']' returned non-zero exit status 1.
```

If go and examine the Cmake log file I see this;

```
    1 Warning(s)

    0 Error(s)

```
And the only warning seems to be this:

```
"C:\Users\jesaremi\AppData\Local\Temp\pip-install-dsb5ydex\onnx\.setuptools-cmake-build\CMakeFiles\CMakeTmp\cmTC_7c68a.vcxproj" (default target) (1) ->

(PrepareForBuild target) -> 

  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(399,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\jesaremi\AppData\Local\Temp\pip-install-dsb5ydex\onnx\.setuptools-cmake-build\CMakeFiles\CMakeTmp\cmTC_7c68a.vcxproj]
```

Is this my setup or there is something that could be done on your end?

**Comment by jeffsaremi** [comment]
python was set to 3.7. changed it to 3.6 and now its ok.
