### ISSUE TITLE
GNMT

### ISSUE THREAD

**Issue by kaitingwang** [onnx/onnx#1778]
Hi, I'm trying to export GNMT (https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Translation/GNMT)  to onnx using nvcr.io/nvidia/pytorch:19.01-py3.  I ran into various issues but I think this one is definitely an onnx problem (missing op?):

```
/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py:501: UserWarning: ONNX export failed on ATen operator frobenius_norm because torch.onnx.symbolic.frobenius_norm does not exist
  .format(op_name, op_name))
Traceback (most recent call last):
  File "train.py", line 460, in <module>
    passed = main()
  File "/opt/conda/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "train.py", line 414, in main
    train_loss, train_perf = trainer.optimize(train_loader)
  File "/workspace/examples/gnmt/seq2seq/train/trainer.py", line 268, in optimize
    self.preallocate(data_loader, training=True)
  File "/workspace/examples/gnmt/seq2seq/train/trainer.py", line 255, in preallocate
    self.iterate(src, tgt, update=False, training=training)
  File "/workspace/examples/gnmt/seq2seq/train/trainer.py", line 126, in iterate
    torch.onnx.export(self.model,list_inputs, "/tmp/gnmt.onnx")
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/__init__.py", line 27, in export
    return utils.export(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 104, in export
    operator_export_type=operator_export_type)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 287, in _export
    proto, export_map = graph._export_onnx(params, _onnx_opset_version, defer_weight_export, operator_export_type)
RuntimeError: ONNX export failed: Couldn't export operator aten::frobenius_norm
```

**Comment by prasanthpul** [comment]
@ebarsoum seems like an issue with the PyTorch exporter?

**Comment by neginraoof** [comment]
This is the PR for frobenius_norm ONNX export: https://github.com/pytorch/pytorch/pull/23536
You can find the ONNX model here: https://drive.google.com/drive/folders/1cWYUg1V1FFgFo8dF-W0hR2tyezCzY_UV?usp=sharing

**Comment by conjam** [comment]
@neginraoof thanks for sharing this negin, do you have the script to generate this lying around? Would love to use this, just want to verify how this was generated

**Comment by haowang5128** [comment]
> This is the PR for frobenius_norm ONNX export: https://github.com/pytorch/pytorch/pull/23536
> 
> You can find the ONNX model here: https://drive.google.com/drive/folders/1cWYUg1V1FFgFo8dF-W0hR2tyezCzY_UV?usp=sharing

Is the model still available?
