### ISSUE TITLE
Clip Operator run_node error using python2.7

### ISSUE THREAD

**Issue by colinback** [onnx/onnx#1870]
Run following python script on Ubuntu:
```python
import onnx
import numpy as np
from onnx_tf.backend import run_node
from onnx import helper

node = onnx.helper.make_node('Clip', inputs=['x'], outputs=['y'], min=-1.0, max=1.0)
shape = [10, 10]
x = np.ones(shape).astype(np.float32).reshape(shape)
y = run_node(node, [x])["y"]
```

error trace:
```shell
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    y = run_node(node, [x])["y"]
  File "/usr/local/lib/python2.7/dist-packages/onnx_tf/backend.py", line 174, in run_node
    ops = cls._onnx_node_to_tensorflow_op(node, input_dict)
  File "/usr/local/lib/python2.7/dist-packages/onnx_tf/backend.py", line 225, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "/usr/local/lib/python2.7/dist-packages/onnx_tf/handlers/handler.py", line 60, in handle
    return ver_handle(node, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/onnx_tf/handlers/backend/clip.py", line 30, in version_6
    return cls._common(node, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/onnx_tf/handlers/backend/clip.py", line 21, in _common
    node, inputs=[x, clip_value_min, clip_value_max])
  File "/usr/local/lib/python2.7/dist-packages/onnx_tf/handlers/backend_handler.py", line 111, in make_tensor_from_onnx_node
    return cls._run_tf_func(tf_func, inputs, attrs)
  File "/usr/local/lib/python2.7/dist-packages/onnx_tf/handlers/backend_handler.py", line 174, in _run_tf_func
    params = tf_func.__closure__[1].cell_contents.args
AttributeError: 'function' object has no attribute 'args'
```

**Comment by colinback** [comment]
Close. Sorry I should open it in onnx-tf.
