### ISSUE TITLE
Support int32 type shape for reshape operator

### ISSUE THREAD

**Issue by hexiaoting** [onnx/onnx#1932]
when convert tensorflow resetnet_v2_50 model to ONNX, then convert to caffe2, It failed:
`Traceback (most recent call last):
  File "/root/pytorch-env3-tf1.12/lib/python3.6/site-packages/ipdb/__main__.py", line 168, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/usr/lib/python3.6/bdb.py", line 434, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/root/pytorch-env3-tf1.12/bin/convert-onnx-to-caffe2", line 11, in <module>
    sys.exit(onnx_to_caffe2())
  File "/root/pytorch-env3-tf1.12/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/pytorch-env3-tf1.12/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/pytorch-env3-tf1.12/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/pytorch-env3-tf1.12/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/root/pytorch-env3-tf1.12/lib/python3.6/site-packages/caffe2/python/onnx/bin/conversion.py", line 87, in onnx_to_caffe2
    init_net, predict_net = c2.onnx_graph_to_caffe2_net(onnx_model_proto)
  File "/root/pytorch-env3-tf1.12/lib/python3.6/site-packages/caffe2/python/onnx/backend.py", line 914, in onnx_graph_to_caffe2_net
    return cls._onnx_model_to_caffe2_net(model, device=device, opset_version=opset_version, include_initializers=True)
  File "/root/pytorch-env3-tf1.12/lib/python3.6/site-packages/caffe2/python/onnx/backend.py", line 872, in _onnx_model_to_caffe2_net
    onnx_model = onnx.utils.polish_model(onnx_model)
  File "/root/pytorch-env3-tf1.12/lib/python3.6/site-packages/onnx/utils.py", line 20, in polish_model
    model = onnx.shape_inference.infer_shapes(model)
  File "/root/pytorch-env3-tf1.12/lib/python3.6/site-packages/onnx/shape_inference.py", line 35, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str)
RuntimeError: Inferred shape and existing shape differ in rank: (0) vs (2)`

The reason is the this reshape operator  converted to ONNX model  with input(1) is :
`  input {
    name: "resnet_v2_50/predictions/Reshape/shape"
    type {
      tensor_type {
        elem_type: 6
        shape {
          dim {
            dim_value: 2
          }
        }
      }
    }
  }`
type is int32 not int64. 
But when infer_shape in onnx code(onnx/defs/tensor/defs.cc:126) it only check raw_data and int64_data without int32_data.

**Comment by hexiaoting** [comment]
If this is a bug, I can make a pull request for this issue
