### ISSUE TITLE
Python version mismatched between CMake and mypy plugin

### ISSUE THREAD

**Issue by xkszltl** [onnx/onnx#1952]
https://github.com/onnx/onnx/blob/414dbc731506e21c70b4600352a161c528233a57/tools/protoc-gen-mypy.py#L1

On CentOS 7 where python->python2.7 and python3->python3.6, this `#!/usr/bin/env python` causes a mismatch with CMake's `PYTHON_EXECUTABLE` (3.6).

If protobuf versions are not the same under their pip, surprise!
```
Traceback (most recent call last):
    File "/tmp/pip-req-build-ooljh0no/tools/protoc-gen-mypy.py", line 367, in <module>
      main()
    File "/tmp/pip-req-build-ooljh0no/tools/protoc-gen-mypy.py", line 354, in main
      generate_mypy_stubs(Descriptors(request), response)
    File "/tmp/pip-req-build-ooljh0no/tools/protoc-gen-mypy.py", line 296, in generate_mypy_stubs
      pkg_writer.write_messages(fd.message_type, "")
    File "/tmp/pip-req-build-ooljh0no/tools/protoc-gen-mypy.py", line 178, in write_messages
      if msg.options.map_entry:
  AttributeError: 'MessageOptions' object has no attribute 'map_entry'
  --mypy_out: protoc-gen-mypy: Plugin failed with status code 1.
```

**Comment by snnn** [comment]
#1314
