### ISSUE TITLE
i want transfer tacotron2 model to onnx but  there is an error ㅠ

### ISSUE THREAD

**Issue by wojung** [onnx/onnx#1956]
i want to transfer pre-trained tacotron2 model to onnx 

#### first load model
```
    hparams = create_hparams()
    hparams.sampling_rate = 22050
    checkpoint_path = "tacotron2_statedict.pt"
    model = load_model(hparams)
    model.load_state_dict(torch.load(checkpoint_path)['state_dict'])
    _ = model.eval()
```

#### and i set input like this 
```
    text_inputs = torch.randn(64, 163, device='cuda')
    text_legths = torch.randn(64, device='cuda')
    mels = torch.randn(64, 80, 851, device='cuda')
    max_len = 163
    output_lengths = torch.randn(64, device='cuda')

    dummy_input = (text_inputs, text_legths, mels, max_len, output_lengths)
```

#### and try to transfer model to onnx
```
    dummy_input = (text_inputs, text_legths, mels, max_len, output_lengths)
```

#### but there is an error
```
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "inference.py", line 49, in <module>
    torch.onnx.export(model, dummy_input, "tacotron.onnx", verbose=True )
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/onnx/__init__.py", line 27, in export
    return utils.export(*args, **kwargs)
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/onnx/utils.py", line 104, in export
    operator_export_type=operator_export_type)
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/onnx/utils.py", line 281, in _export
    example_outputs, propagate)
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/onnx/utils.py", line 224, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/onnx/utils.py", line 192, in _trace_and_get_graph_from_model
    trace, torch_out = torch.jit.get_trace_graph(model, args, _force_outplace=True)
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/jit/__init__.py", line 197, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace)(*args, **kwargs)
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/jit/__init__.py", line 243, in forward
    in_vars, in_desc = _flatten(args)
RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got int
```

I think max_len is the problem, how do I change it  ㅜㅜ

**Comment by prasanthpul** [comment]
Can you file this in the PyTorch github repo? It seems specific to PyTorch export

**Comment by MuruganR96** [comment]
@prasanthpul  sir. i also having same problem. i try to export pytorch tacotron pretrained model to onnx model. it is throwing memory allocation issue.
```
Traceback (most recent call last):
  File "export_model.py", line 48, in <module>
    torch.onnx.export(model, y, "tts.onnx")
  File "/home/admin1/speech_recognition/text2speech/new_one/env/lib/python3.6/site-packages/torch/onnx/__init__.py", line 27, in export
    return utils.export(*args, **kwargs)
  File "/home/admin1/speech_recognition/text2speech/new_one/env/lib/python3.6/site-packages/torch/onnx/utils.py", line 104, in export
    operator_export_type=operator_export_type)
  File "/home/admin1/speech_recognition/text2speech/new_one/env/lib/python3.6/site-packages/torch/onnx/utils.py", line 281, in _export
    example_outputs, propagate)
  File "/home/admin1/speech_recognition/text2speech/new_one/env/lib/python3.6/site-packages/torch/onnx/utils.py", line 224, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/home/admin1/speech_recognition/text2speech/new_one/env/lib/python3.6/site-packages/torch/onnx/utils.py", line 192, in _trace_and_get_graph_from_model
    trace, torch_out = torch.jit.get_trace_graph(model, args, _force_outplace=True)
  File "/home/admin1/speech_recognition/text2speech/new_one/env/lib/python3.6/site-packages/torch/jit/__init__.py", line 197, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace)(*args, **kwargs)
  File "/home/admin1/speech_recognition/text2speech/new_one/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/admin1/speech_recognition/text2speech/new_one/env/lib/python3.6/site-packages/torch/jit/__init__.py", line 252, in forward
    out = self.inner(*trace_inputs)
  File "/home/admin1/speech_recognition/text2speech/new_one/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/admin1/speech_recognition/text2speech/new_one/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/admin1/speech_recognition/text2speech/new_one/TTS/models/tacotron.py", line 35, in forward
    inputs = self.embedding(characters)
  File "/home/admin1/speech_recognition/text2speech/new_one/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/admin1/speech_recognition/text2speech/new_one/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/admin1/speech_recognition/text2speech/new_one/env/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 118, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/admin1/speech_recognition/text2speech/new_one/env/lib/python3.6/site-packages/torch/nn/functional.py", line 1454, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: $ Torch: not enough memory: you tried to allocate 2442GB. Buy new RAM! at /pytorch/aten/src/TH/THGeneral.cpp:201
```
this one i tried with CPU memory.

when i am doing the same with GPU.(4 GPUs x 24 GB ). still showing same memory allocation issue.

please give me some suggestions sir. i have no idea about this.

Thank you so much.:)

**Comment by prasanthpul** [comment]
@MuruganR96 please file the issue in the PyTorch repo (https://github.com/pytorch/pytorch) so the right experts can take a look. Based on the error message, this is an issue with PyTorch

**Comment by MuruganR96** [comment]
@prasanthpul  thank you sir.
