### ISSUE TITLE
Pip install failed 

### ISSUE THREAD

**Issue by michaelulin** [onnx/onnx#197]
When installing onnx with pip, I receive the error below. I also receive a similar error when cloning the repository and trying the install using python setup.py install.

Pip install:
```
Running setup.py install for onnx ... error
    Complete output from command /usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-z7pGsD/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-IRFRUK-record/install-record.txt --single-version-externally-managed --compile:
    fatal: Not a git repository (or any of the parent directories): .git
    running install
    running build
    running build_py
    running create_version
    running build_proto
    compiling /tmp/pip-build-z7pGsD/onnx/onnx/onnx.proto
    onnx.proto:308:7: Expected "required", "optional", or "repeated".
    onnx.proto:308:19: Missing field number.
    onnx.proto:330:3: Expected "required", "optional", or "repeated".
    onnx.proto:330:15: Missing field number.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-z7pGsD/onnx/setup.py", line 274, in <module>
        url='https://github.com/onnx/onnx',
      File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python2.7/distutils/command/install.py", line 604, in run
        self.run_command('build')
      File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-z7pGsD/onnx/setup.py", line 152, in run
        self.run_command('build_proto')
      File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-z7pGsD/onnx/setup.py", line 136, in run
        proto_file
      File "/usr/lib64/python2.7/subprocess.py", line 541, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '[u'/usr/bin/protoc', u'--proto_path', u'/tmp/pip-build-z7pGsD/onnx/onnx', u'--python_out', u'/tmp/pip-build-z7pGsD/onnx/onnx', u'--cpp_out', u'/tmp/pip-build-z7pGsD/onnx/onnx', u'/tmp/pip-build-z7pGsD/onnx/onnx/onnx.proto']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-z7pGsD/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-IRFRUK-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-z7pGsD/onnx/

```

Install from source:
```

compiling /home/ec2-user/onnx/onnx/onnx.proto
onnx.proto:364:7: Expected "required", "optional", or "repeated".
onnx.proto:364:19: Missing field number.
onnx.proto:387:3: Expected "required", "optional", or "repeated".
onnx.proto:387:15: Missing field number.
Traceback (most recent call last):
  File "setup.py", line 302, in <module>
    'check-node = onnx.bin.checker:check_node',
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib64/python2.7/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_py')
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 172, in run
    self.run_command('build_proto')
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 156, in run
    proto_file
  File "/usr/lib64/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'/usr/bin/protoc', u'--proto_path', u'/home/ec2-user/onnx/onnx', u'--python_out', u'/home/ec2-user/onnx/onnx', u'--cpp_out', u'/home/ec2-user/onnx/onnx', u'/home/ec2-user/onnx/onnx/onnx.proto']' returned non-zero exit status 1
```

**Comment by bddppq** [comment]
What the version of `protoc` in your environment? onnx requires >= 2.6.1

**Comment by michaelulin** [comment]
That worked. I had 2.5. Updated it to 3.4 and everything worked fine. Thanks!
