### ISSUE TITLE
elem type differs when converting ONNX 10 to ONNX 8

### ISSUE THREAD

**Issue by hossein-pdftron** [onnx/onnx#1986]
Running the following simple snippet in Python 3.6.7 results in RuntimeError
```
import onnx.version_converter
import onnx.utils
import onnx
import torch
import torch.nn as nn

class TestNet(nn.Module):
    def __init__(self):
        super(TestNet, self).__init__()
        self.conv = nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3, padding=1)

    def forward(self, x):
        x = self.conv(x)
        x = x.view(x.shape[0], 4, 4, x.shape[-2], x.shape[-1])
        return x

print("torch " + torch.__version__)
print("onnx " + onnx.__version__)
dummy_input = torch.randn(1, 3, 224, 224, device='cuda')
model = TestNet().cuda()
model_path = "model.onnx"
torch.onnx.export(model, dummy_input, model_path)
model = onnx.load(model_path)
# model = onnx.utils.polish_model(model)  # no issue
model = onnx.version_converter.convert_version(model, 8)
model = onnx.utils.polish_model(model)
```

Output:
```
torch 1.0.1.post2
onnx 1.5.0
(op_type:Constant, name:): Inferred elem type differs from existing elem type: (INT64) vs (FLOAT)
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    model = onnx.utils.polish_model(model)
  File "/home/pdftron/.local/lib/python3.6/site-packages/onnx/utils.py", line 20, in polish_model
    model = onnx.shape_inference.infer_shapes(model)
  File "/home/pdftron/.local/lib/python3.6/site-packages/onnx/shape_inference.py", line 35, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str)
RuntimeError: Inferred elem type differs from existing elem type: (INT64) vs (FLOAT)
```

**Comment by spandantiwari** [comment]
We are looking into it. 
cc: @KsenijaS

**Comment by NessAupera** [comment]
I get a similar error with
onnx.__version__
'1.5.0'
torch.__version__
'1.1.0'
```(op_type:Constant, name:): Inferred elem type differs from existing elem type: (INT64) vs (FLOAT)
Traceback (most recent call last):
  File "carn-onnx-layers.py", line 34, in <module>
    model = onnx.utils.polish_model(model)
  File "/home/ness/.local/lib/python3.5/site-packages/onnx/utils.py", line 20, in polish_model
    model = onnx.shape_inference.infer_shapes(model)
  File "/home/ness/.local/lib/python3.5/site-packages/onnx/shape_inference.py", line 35, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str)
RuntimeError: Inferred elem type differs from existing elem type: (INT64) vs (FLOAT)
```

**Comment by KsenijaS** [comment]
fix for the issue in a PR:
https://github.com/onnx/onnx/pull/2101
