### ISSUE TITLE
Error converting Detectron -> Caffe2 -> ONNX

### ISSUE THREAD

**Issue by fuzzyBatman** [onnx/onnx#2061]
Python version: 3.7
OS: Fedora 30

Script:

```
import onnx

import caffe2.python.onnx.frontend
from caffe2.proto import caffe2_pb2

from caffe2.python import dyndep
import detectron.utils.env as envu

def import_detectron_ops():
    """Import Detectron ops."""
    detectron_ops_lib = envu.get_detectron_ops_lib()
    dyndep.InitOpsLibrary(detectron_ops_lib)

import_detectron_ops()

# We need to provide type and shape of the model inputs, 
# see above Note section for explanation
data_type = onnx.TensorProto.FLOAT
data_shape = (1, 3, 512, 512)
value_info = {
    'data': (data_type, data_shape)
}

predict_net = caffe2_pb2.NetDef()
with open('models/pb_frcnn/model.pb', 'rb') as f:
    predict_net.ParseFromString(f.read())

init_net = caffe2_pb2.NetDef()
with open('models/pb_frcnn/model_init.pb', 'rb') as f:
    init_net.ParseFromString(f.read())

onnx_model = caffe2.python.onnx.frontend.caffe2_net_to_onnx_model(
    predict_net,
    init_net,
    value_info,
)
```

Result:

```
RuntimeError: [enforce fail at generate_proposals_op.cc:241] im_info_tensor.sizes() == (vector<int64_t>{num_images, 3}). [0] vs 1 3
```

```
Found Detectron ops lib: /home/fuzzybatman/.local/lib/python3.7/site-packages/torch/lib/libcaffe2_detectron_ops_gpu.so
WARNING:caffe2.python.workspace:Original python traceback for operator `139` in network `detectron` in exception above (most recent call last):
Traceback (most recent call last):
  File "det2onnx.py", line 35, in <module>
    value_info,
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/caffe2/python/onnx/frontend.py", line 350, in caffe2_net_to_onnx_model
    model = make_model(cls.caffe2_net_to_onnx_graph(*args, **kwargs),
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/caffe2/python/onnx/frontend.py", line 232, in caffe2_net_to_onnx_graph
    inputs)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/caffe2/python/onnx/helper.py", line 62, in c2_native_run_net
    ws.RunNetOnce(predict_net)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/caffe2/python/onnx/workspace.py", line 63, in f
    return getattr(workspace, attr)(*args, **kwargs)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/caffe2/python/workspace.py", line 218, in RunNetOnce
    StringifyProto(net),
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/caffe2/python/workspace.py", line 197, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at generate_proposals_op.cc:241] im_info_tensor.sizes() == (vector<int64_t>{num_images, 3}). [0] vs 1 3
Error from operator: 
input: "rpn_cls_probs_fpn2" input: "rpn_bbox_pred_fpn2" input: "im_info" input: "anchor2" output: "rpn_rois_fpn2" output: "rpn_roi_probs_fpn2" name: "" type: "GenerateProposals" arg { name: "spatial_scale" f: 0.25 } arg { name: "pre_nms_topN" i: 12000 } arg { name: "post_nms_topN" i: 2000 } arg { name: "nms_thresh" f: 0.8 } arg { name: "min_size" f: 0 } arg { name: "correct_transform_coords" i: 1 } device_option { } engine: ""frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fcca12ac021 in /home/fuzzybatman/.local/lib/python3.7/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #1: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x49 (0x7fcca12abdc9 in /home/fuzzybatman/.local/lib/python3.7/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #2: <unknown function> + 0x1a5e0a3 (0x7fcc86d7a0a3 in /home/fuzzybatman/.local/lib/python3.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #3: <unknown function> + 0x1608fe5 (0x7fcc86924fe5 in /home/fuzzybatman/.local/lib/python3.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #4: caffe2::SimpleNet::Run() + 0x1b2 (0x7fcc86a22bc2 in /home/fuzzybatman/.local/lib/python3.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #5: caffe2::Workspace::RunNetOnce(caffe2::NetDef const&) + 0x25a (0x7fcc86a5c59a in /home/fuzzybatman/.local/lib/python3.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #6: <unknown function> + 0x57d78 (0x7fcca154fd78 in /home/fuzzybatman/.local/lib/python3.7/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-37m-x86_64-linux-gnu.so)
frame #7: <unknown function> + 0x8cf2e (0x7fcca1584f2e in /home/fuzzybatman/.local/lib/python3.7/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-37m-x86_64-linux-gnu.so)
<omitting python frames>
frame #41: __libc_start_main + 0xf3 (0x7fccb3185f33 in /lib64/libc.so.6)
```

**Comment by araufdogan** [comment]
@fuzzyBatman I got the same error, did you find any solution?

**Comment by fuzzyBatman** [comment]
Sorry I haven't worked on this for two years
