### ISSUE TITLE
Problem with loading converted onnx model

### ISSUE THREAD

**Issue by antonfr** [onnx/onnx#2094]
Hi, 
I have converted to onnx ssdlite_mobilenet_v2_coco model from tensorflow detection model zoo (could be found [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md)). To convert, I used the following script:
`
$ python3 -m tf2onnx.convert --input frozen_inference_graph.pb --inputs image_tensor:0 --outputs num_detections:0,detection_classes:0,detection_boxes:0,detection_scores:0 --output ssd_mobilenet.onnx --fold_const --opset 10
` 
Here is the output of this script:
`
//anaconda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2019-06-07 12:57:24,367 - INFO - Using tensorflow=1.13.1, onnx=1.5.0, tf2onnx=1.5.1/0c735a
2019-06-07 12:57:24,367 - INFO - Using opset <onnx, 10>
2019-06-07 12:57:26,867 - WARNING - Cannot infer shape for Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/zeros: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/zeros:0
2019-06-07 12:57:53,960 - INFO - 
2019-06-07 12:57:54,552 - INFO - Optimizing ONNX model
2019-06-07 12:58:35,835 - INFO - After optimization: Add -76 (370->294), Cast -1 (1265->1264), Const -48 (2154->2106), Gather +6 (554->560), Identity -162 (165->3), Mul -21 (301->280), Reshape -33 (327->294), Shape -1 (111->110), Transpose -187 (385->198), Unsqueeze -7 (429->422)
`
Now I'm trying to load the model using ML.NET. I'm using the following code:
`        public struct ImageSettings
        {
            public const int ImageWidth = 300;
            public const int ImageHeight = 300;
            public const bool ChannelLast = true;
        }

        public struct SSDSettings
        {
            public const string SSDInput = "image_tensor:0";
            public const string SSDDetectionsOutput = "num_detections:0";
            public const string SSDClassesOutput = "detection_classes:0";
            public const string SSDBoxesOutput = "detection_boxes:0";
            public const string SSDScoresOutput = "detection_scores:0";
        }

        public PredictionEngine<ImageData, ImagePredictions> LoadModel(string modelLocation,
                                                                       string imagesLocation,
                                                                       string tagsLocation)
        {
            IDataView data = mLContext.Data.LoadFromTextFile<ImageData>(path: tagsLocation,
                                                                        hasHeader: false);
            var pipeline = mLContext.Transforms.LoadImages(outputColumnName: "image_tensor:0",
                                                           imageFolder: imagesLocation,
                                                           inputColumnName: nameof(ImageData.ImagePath))
                   .Append(mLContext.Transforms.ResizeImages(outputColumnName: "image_tensor:0",
                                                             imageWidth: ImageSettings.ImageWidth,
                                                             imageHeight: ImageSettings.ImageHeight,
                                                             inputColumnName: "image_tensor:0"))
                   .Append(mLContext.Transforms.ExtractPixels(outputColumnName: "image_tensor:0",
                                                              interleavePixelColors: ImageSettings.ChannelLast))
                   .Append(mLContext.Transforms.ApplyOnnxModel(modelFile: modelLocation,
                                                               outputColumnNames: new[] { SSDSettings.SSDDetectionsOutput,
                                                                                          SSDSettings.SSDClassesOutput,
                                                                                          SSDSettings.SSDBoxesOutput,
                                                                                          SSDSettings.SSDScoresOutput },
                                                               inputColumnNames: new[] { SSDSettings.SSDInput }));

            var model = pipeline.Fit(data);

            var predictionEngine = mLContext.Model.CreatePredictionEngine<ImageData, ImagePredictions>(model);
            return predictionEngine;
        }`

I got the following error:
`Error initializing model :Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:InvalidGraph] Load model from /my/path/to/file/ssd_mobilenet.onnx failed:Node:Preprocessor/map/strided_slice Node (Preprocessor/map/strided_slice) has input size 4 not in range [min=1, max=1].
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath, SessionOptions options) in C:\agent\_work\6\s\csharp\src\Microsoft.ML.OnnxRuntime\InferenceSession.cs:line 83
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath) in C:\agent\_work\6\s\csharp\src\Microsoft.ML.OnnxRuntime\InferenceSession.cs:line 31
   at Microsoft.ML.Transforms.Onnx.OnnxModel..ctor(String modelFile, Nullable 1 gpuDeviceId, Boolean fallbackToCpu)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, Options options, Byte[] modelBytes)`

How could I fix this error?
MacOS 10.13.6
Tensorflow 1.13.1
Onnx 1.5.0
ML.NET 1.0
Visual Studio 2019 8.0.5

**Comment by prasanthpul** [comment]
Based on the error, this should be filed in https://github.com/microsoft/onnxruntime
@linkerzhang

**Comment by antonfr** [comment]
Thanks for your reply. I haven't added OnnxRuntime NuGet package, though I have been able to run TinyYolo and AlexNet without it. But now I have another problem:
`2019-06-12 14:32:53.802528 [W:onnxruntime:InferenceSession, session_state_initializer.cc:502 SaveInputOutputNamesToNodeMapping] Graph input with name i__19 is not associated with a node. 
2019-06-12 14:32:53.802581 [W:onnxruntime:InferenceSession, session_state_initializer.cc:502 SaveInputOutputNamesToNodeMapping] Graph input with name cond__21 is not associated with a node. 
2019-06-12 14:32:54.004760 [W:onnxruntime:InferenceSession, session_state_initializer.cc:502 SaveInputOutputNamesToNodeMapping] Graph input with name i__42 is not associated with a node. 
2019-06-12 14:32:54.004790 [W:onnxruntime:InferenceSession, session_state_initializer.cc:502 SaveInputOutputNamesToNodeMapping] Graph input with name cond__44 is not associated with a node. 
2019-06-12 14:32:54.005072 [W:onnxruntime:InferenceSession, session_state_initializer.cc:502 SaveInputOutputNamesToNodeMapping] Graph input with name i is not associated with a node. 
Onnx type not supported`

Seems that model wasn't converted properly. I have posted output of model conversion above.
