### ISSUE TITLE
Reshape cannot be converted from torch h5 to onyx

### ISSUE THREAD

**Issue by ElvishElvis** [onnx/onnx#2241]
In my pytorch model, I have this line in my model.
 cls32 = torch.reshape(cls32, (1, 2, 16, 8))

and when I try to convert it to onnx format by using

torch.onnx.export(net, (x), model_onnx_path, verbose=False,
                      input_names=model_input_names)

it shows 
   
/home/versa/anaconda3/envs/ConverterToCoreML/lib/python3.6/site-packages/torch/onnx/utils.py:501: UserWarning: ONNX export failed on ATen operator reshape because torch.onnx.symbolic.reshape does not exist
  .format(op_name, op_name))
Traceback (most recent call last):
  File "/home/versa/wuzongrui/PytorchConverterServer/MainConverter.py", line 22, in <module>
    input_names=model_input_names)
  File "/home/versa/anaconda3/envs/ConverterToCoreML/lib/python3.6/site-packages/torch/onnx/__init__.py", line 27, in export
    return utils.export(*args, **kwargs)
  File "/home/versa/anaconda3/envs/ConverterToCoreML/lib/python3.6/site-packages/torch/onnx/utils.py", line 104, in export
    operator_export_type=operator_export_type)
  File "/home/versa/anaconda3/envs/ConverterToCoreML/lib/python3.6/site-packages/torch/onnx/utils.py", line 287, in _export
    proto, export_map = graph._export_onnx(params, _onnx_opset_version, defer_weight_export, operator_export_type)
RuntimeError: ONNX export failed: Couldn't export operator aten::reshape

All other function works fine, and when I remove this line, it work perfectly.

Do I need to write this function to support reshape? and how do I do so?

Thanks!

torch version 1.1.0

**Comment by prasanthpul** [comment]
Have you tried using PyTorch 1.2?

In any case this is an issue with PyTorch rather than ONNX. Please open this in the PyTorch Github. FYI for @spandantiwari so he can look into it in the meantime
