### ISSUE TITLE
PythonAPIOverview.md: the exampe from "Creating an ONNX Model Using Helper Functions" fails

### ISSUE THREAD

**Issue by yurivict** [onnx/onnx#2423]
https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md

```
Traceback (most recent call last):
  File "create-onnx-model.py", line 38, in <module>
    onnx.checker.check_model(model_def)
  File "/usr/local/lib/python3.6/site-packages/onnx/checker.py", line 91, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Node () has input size 1 not in range [min=2, max=3].

==> Context: Bad node spec: input: "X" output: "Y" op_type: "Pad" attribute { name: "mode" s: "constant" type: STRING } attribute { name: "pads" ints: 0 ints: 1 ints: 0 ints: 1 type: INTS } attribute { name: "value" f: 1.5 type: FLOAT }
```

**Comment by skottmckay** [comment]
The Pad operator changed to take the pads and constant value as dynamic inputs. The following should work:

```
import onnx
from onnx import helper
from onnx import AttributeProto, TensorProto, GraphProto


# The protobuf definition can be found here:
# https://github.com/onnx/onnx/blob/master/onnx/onnx.proto


# Create inputs (ValueInfoProto)
X = helper.make_tensor_value_info('X', TensorProto.FLOAT, [1, 2])

# Create initializer with static pads and constant value
pads = helper.make_tensor('pads', TensorProto.INT64, [4], [0, 1, 0, 1])
value = helper.make_tensor('pad_value', TensorProto.FLOAT, [1], [1.5])

# Create one output (ValueInfoProto)
Y = helper.make_tensor_value_info('Y', TensorProto.FLOAT, [1, 4])

# Create a node (NodeProto)
node_def = helper.make_node(
    'Pad', # node name
    ['X', 'pads', 'pad_value'], # inputs
    ['Y'], # outputs
    mode='constant' # attributes
)

# Create the graph (GraphProto)
graph_def = helper.make_graph(
    [node_def], # nodes
    'test-model', # graph name
    [X], # graph inputs
    [Y], # graph outputs
    [pads, value]  # initializers
)

# Create the model (ModelProto)
model_def = helper.make_model(graph_def, producer_name='onnx-example')

print('The model is:\n{}'.format(model_def))
onnx.checker.check_model(model_def)
print('The model is checked!')
```

**Comment by yurivict** [comment]
Could you please also fix this script in the file that is exposed on the website?
