### ISSUE TITLE
Build broken: Unknown generator option: dllexport_decl

### ISSUE THREAD

**Issue by lutzroeder** [onnx/onnx#2481]
@orionr @linkerzhang @zrphercule

Run on macOS Catalina 10.15.1 with protobuf 3.11.0:
```
git clone https://github.com/onnx/onnx.git && cd onnx
git submodule update --init --recursive
python3 setup.py install
```
Log:
```
~/onnx: python3 setup.py install
running install
running bdist_egg
running egg_info
creating onnx.egg-info
writing onnx.egg-info/PKG-INFO
writing dependency_links to onnx.egg-info/dependency_links.txt
writing entry points to onnx.egg-info/entry_points.txt
writing requirements to onnx.egg-info/requires.txt
writing top-level names to onnx.egg-info/top_level.txt
writing manifest file 'onnx.egg-info/SOURCES.txt'
reading manifest file 'onnx.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'onnx.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.15-x86_64/egg
running install_lib
running build_py
running create_version
running cmake_build
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Protobuf: /usr/local/lib/libprotobuf.dylib (found version "3.11.0") 
Generated: /Users/x/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
Generated: /Users/x/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
CMake Warning at CMakeLists.txt:406 (find_package):
  By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pybind11",
  but CMake did not find one.

  Could not find a package configuration file provided by "pybind11"
  (requested version 2.2) with any of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.


-- 
-- ******** Summary ********
--   CMake version         : 3.15.5
--   CMake command         : /usr/local/Cellar/cmake/3.15.5/bin/cmake
--   System                : Darwin
--   C++ compiler          : /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
--   C++ compiler version  : 11.0.0.11000033
--   CXX flags             :  -Wnon-virtual-dtor
--   Build type            : Release
--   Compile definitions   : 
--   CMAKE_PREFIX_PATH     : 
--   CMAKE_INSTALL_PREFIX  : /usr/local
--   CMAKE_MODULE_PATH     : 
-- 
--   ONNX version          : 1.6.0
--   ONNX NAMESPACE        : onnx
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
--   ONNXIFI_ENABLE_EXT    : OFF
-- 
--   Protobuf compiler     : /usr/local/bin/protoc
--   Protobuf includes     : /usr/local/include
--   Protobuf libraries    : /usr/local/lib/libprotobuf.dylib
--   BUILD_ONNX_PYTHON     : ON
--     Python version      : 
--     Python executable   : /usr/local/opt/python/bin/python3.7
--     Python includes     : /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/include/python3.7m
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/x/onnx/.setuptools-cmake-build
Scanning dependencies of target gen_onnx_proto
Scanning dependencies of target onnxifi_loader
Scanning dependencies of target onnxifi_dummy
[  1%] Running gen_proto.py on onnx/onnx.in.proto
[  4%] Building C object CMakeFiles/onnxifi_loader.dir/onnx/onnxifi_loader.c.o
[  4%] Building C object CMakeFiles/onnxifi_dummy.dir/onnx/onnxifi_dummy.c.o
/Users/x/onnx/onnx/onnxifi_dummy.c:173:21: warning: incompatible function pointer types assigning to 'onnxExtensionFunctionPointer'
      (aka 'int (*)(void)') from 'onnxStatus (*)(onnxBackendID, const char *, onnxExtensionFunctionPointer *)' (aka
      'int (*)(void *, const char *, int (**)(void))') [-Wincompatible-function-pointer-types]
          *function = &onnxGetExtensionFunctionAddress;
                    ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/x/onnx/onnx/onnxifi_dummy.c:176:21: warning: incompatible function pointer types assigning to 'onnxExtensionFunctionPointer'
      (aka 'int (*)(void)') from 'onnxStatus (*)(onnxGraph, uint32_t, const onnxTensorDescriptorV1 *, uint32_t, const onnxTensorDescriptorV1 *,
      onnxMemoryFenceV1 *)' (aka 'int (*)(void *, unsigned int, const struct onnxTensorDescriptorV1 *, unsigned int, const struct onnxTensorDescriptorV1 *,
      struct onnxMemoryFenceV1 *)') [-Wincompatible-function-pointer-types]
          *function = &onnxSetIOAndRunGraph;
                    ^ ~~~~~~~~~~~~~~~~~~~~~
Processing /Users/x/onnx/onnx/onnx.in.proto
Writing /Users/x/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
Writing /Users/x/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto3
generating /Users/x/onnx/.setuptools-cmake-build/onnx/onnx_pb.py
2 warnings generated.
[  6%] Linking C static library libonnxifi_loader.a
[  9%] Linking C shared library libonnxifi_dummy.dylib
[  9%] Running C++ protocol buffer compiler on /Users/x/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
[  9%] Built target onnxifi_loader
--python_out: onnx/onnx-ml.proto: Unknown generator option: dllexport_decl
make[2]: *** [onnx/onnx-ml.pb.cc] Error 1
make[1]: *** [CMakeFiles/gen_onnx_proto.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target onnxifi_wrapper
[  9%] Built target onnxifi_dummy
[ 11%] Building C object CMakeFiles/onnxifi_wrapper.dir/onnx/onnxifi_wrapper.c.o
[ 13%] Linking C shared module libonnxifi.dylib
[ 13%] Built target onnxifi_wrapper
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 336, in <module>
    'backend-test-tools = onnx.backend.test.cmd_tools:main',
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/install_lib.py", line 105, in build
    self.run_command('build_py')
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 213, in run
    self.run_command('cmake_build')
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 207, in run
    subprocess.check_call(build_args)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '.', '--', '-j', '16']' returned non-zero exit status 2.
```

**Comment by xkszltl** [comment]
Having the same issue and trying to compose a PR

**Comment by bryteise** [comment]
Yes seems to be an issue with protobuf 3.11, works with protobuf 3.10.

**Comment by snnn** [comment]
Having the same issue

**Comment by victornoel** [comment]
@linkerzhang can we reopen this? The commit has been reverted and I can't build the latest master with protobuf 3.11

**Comment by tgpfeiffer** [comment]
Installing a version that has this PR https://github.com/onnx/onnx/pull/2482 included (rather than the latest version 1.6.0 on pypi) fixes the problem for me.

**Comment by orionr** [comment]
cc @malfet as an FYI

**Comment by creynia-mythic** [comment]
Still a problem...
