### ISSUE TITLE
PyTorch - ONNX Export Error with Opset 11 caused by F.Interpolate/nn.Upsampling...2d

### ISSUE THREAD

**Issue by glenn-jocher** [onnx/onnx#2487]
## 🐛 Bug

PyTorch model export to ONNX fails when using PyTorch 1.3.1 or nightly and ONNX 1.5.0. Failure is caused by all upsample operations: 

- `nn.UpsamplingBilinear2d(scale_factor=2)`
- `nn.UpsamplingNearest2d(scale_factor=2)`
- `F.interpolate(x, scale_factor=2)`

Error message:
```bash
torch version 1.4.0.dev20191127
onnx version 1.5.0
torch.Size([1, 3, 256, 256]) torch.Size([1, 3, 512, 512])
Traceback (most recent call last):
  File "/Users/glennjocher/PycharmProjects/iD/upsample_error_reproduce.py", line 28, in <module>
    onnx.checker.check_model(oml)
  File "/Users/glennjocher/opt/anaconda3/envs/pytorch_nightly/lib/python3.7/site-packages/onnx/checker.py", line 86, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Node (Resize_23) has input size 4 not in range [min=2, max=2].

==> Context: Bad node spec: input: "input" input: "20" input: "20" input: "23" output: "24" name: "Resize_23" op_type: "Resize" attribute { name: "coordinate_transformation_mode" s: "asymmetric" type: STRING } attribute { name: "cubic_coeff_a" f: -0.75 type: FLOAT } attribute { name: "mode" s: "nearest" type: STRING } attribute { name: "nearest_mode" s: "floor" type: STRING }
```

## To Reproduce

```python
# conda install pytorch torchvision -c pytorch-nightly
# conda install -c conda-forge onnx
import torch
import torch.nn as nn
import torch.nn.functional as F
import onnx


class TestModel(nn.Module):
    def __init__(self):
        super(TestModel, self).__init__()

    def forward(self, x):
        # m = nn.UpsamplingBilinear2d(scale_factor=2)  # fails
        # m = nn.UpsamplingNearest2d(scale_factor=2)  # fails
        x = F.interpolate(x, scale_factor=2)  # fails
        return x


print('torch version %s' % torch.__version__)
print('onnx version %s' % onnx.__version__)
img = torch.randn(1, 3, 256, 256)
tml = TestModel()
print(img.shape, tml(img).shape)
torch.onnx.export(tml, img, 'model.onnx', verbose=False, opset_version=11)

oml = onnx.load('model.onnx')  # onnx model
onnx.checker.check_model(oml)
```

## Expected behavior

Successful export and ONNX verification.

## Environment

```bash
Collecting environment information...
PyTorch version: 1.4.0.dev20191127
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.1
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.17.4
[pip] torch==1.4.0.dev20191127
[pip] torchvision==0.5.0a0+91a78e1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      233  
[conda] mkl-service               2.3.0            py37hfbe908c_0  
[conda] mkl_fft                   1.0.15           py37h5e564d8_0  
[conda] mkl_random                1.1.0            py37ha771720_0  
[conda] pytorch                   1.4.0.dev20191127         py3.7_0    pytorch-nightly
[conda] torchvision               0.5.0.dev20191127        py37_cpu    pytorch-nightly
```

**Comment by linkerzhang** [comment]
@spandantiwari

**Comment by spandantiwari** [comment]
@glenn-jocher - you have a similar issue open in PyTorch https://github.com/pytorch/pytorch/issues/30681. Let's track it in one place. 
 
@linkerzhang - we can close this one and will track the PyTorch issue.

**Comment by glenn-jocher** [comment]
@spandantiwari ok got it. I wasn't sure where the problem was originating, whether it was on the PyTorch side or the ONNX side.
