### ISSUE TITLE
ONNX 1.6 Conda Import Error

### ISSUE THREAD

**Issue by glenn-jocher** [onnx/onnx#2493]
ONNX 1.6 Conda import error: image not found

# Error Message
```python
>>> import onnx

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/glennjocher/opt/anaconda3/envs/pn2/lib/python3.7/site-packages/onnx/__init__.py", line 8, in <module>
    from .onnx_cpp2py_export import ONNX_ML
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: dlopen(/Users/glennjocher/opt/anaconda3/envs/pn2/lib/python3.7/site-packages/onnx/onnx_cpp2py_export.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libprotobuf.20.dylib
  Referenced from: /Users/glennjocher/opt/anaconda3/envs/pn2/lib/python3.7/site-packages/onnx/onnx_cpp2py_export.cpython-37m-darwin.so
  Reason: image not found
```

# To Reproduce

In a new Python 3.7 Anaconda environment:
```bash
conda install -yc conda-forge onnx
```

python:
```python
>>> import onnx
```

**Comment by csteegz** [comment]
I was able to resolve this by manually installing protobuf==3.9.1 with 
```
pip install protobuf==3.9.1
``` 
prior to installing onnx 1.6 (although this was on ubuntu, not Mac). 

I think that onnx might have compatibility issues with protobuf 3.11 and needs to limit it.

**Comment by matthewygf** [comment]
Solve it by installing onnx through pip
