### ISSUE TITLE
tf saved model failed to convert for tf.math.unsorted_segment_sum 

### ISSUE THREAD

**Issue by chenghuige** [onnx/onnx#2593]
python -m tf2onnx.convert  --saved-model ./model --output ./onnx --fold_const --verbose --continue_on_error
Applying fold_old_batch_norms
2020-02-08 07:17:16,352 - INFO - tf2onnx.tfonnx: Using tensorflow=1.14.0, onnx=1.6.0, tf2onnx=1.5.4/ee756a
2020-02-08 07:17:16,352 - INFO - tf2onnx.tfonnx: Using opset <onnx, 8>
2020-02-08 07:17:53,366 - ERROR - tf2onnx.tfonnx: pass1 convert failed for name: "deep/UnsortedSegmentSum"
op: "UnsortedSegmentSum"
input: "deep/mul_2"
input: "deep/add_2"
input: "deep/mul_4"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "Tindices"
  value {
    type: DT_INT64
  }
}
attr {
  key: "Tnumsegments"
  value {
    type: DT_INT32
  }
}
, ex=Value "<dtype: 'int32'>" is not valid attribute data type.
Traceback (most recent call last):
  File "/home/gezi/env/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/gezi/env/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gezi/env/anaconda3/lib/python3.6/site-packages/tf2onnx/convert.py", line 161, in <module>
    main()
  File "/home/gezi/env/anaconda3/lib/python3.6/site-packages/tf2onnx/convert.py", line 145, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/home/gezi/env/anaconda3/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 495, in process_tf_graph
    onnx_nodes, op_cnt, attr_cnt, output_shapes, dtypes = tensorflow_to_onnx(tf_graph, shape_override)
  File "/home/gezi/env/anaconda3/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 122, in tensorflow_to_onnx
    return tflist_to_onnx(graph.get_operations(), shape_override)
  File "/home/gezi/env/anaconda3/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 109, in tflist_to_onnx
    onnx_node = helper.make_node(node.type, input_names, output_names, name=node.name, **attr)
  File "/home/gezi/env/anaconda3/lib/python3.6/site-packages/onnx/helper.py", line 56, in make_node
    for key, value in sorted(kwargs.items()))
  File "/home/gezi/env/anaconda3/lib/python3.6/site-packages/onnx/helper.py", line 56, in <genexpr>
    for key, value in sorted(kwargs.items()))
  File "/home/gezi/env/anaconda3/lib/python3.6/site-packages/onnx/helper.py", line 273, in make_attribute
    'Value "{}" is not valid attribute data type.'.format(value))
ValueError: Value "<dtype: 'int32'>" is not valid attribute data type.

**Comment by TMVector** [comment]
Hi @chenghuige, I think you should raise this issue with https://github.com/onnx/tensorflow-onnx 🙂

**Comment by chenghuige** [comment]
@TMVector Ok, thanks, open here[https://github.com/onnx/tensorflow-onnx/issues/798] colse this
