### ISSUE TITLE
Error when building onnx in Ubuntu

### ISSUE THREAD

**Issue by DuZzzs** [onnx/onnx#2658]
environment：
```
Ubuntu 16.04.5 LTS
python 3.7
GPU：GTX 2060
```
command:
```
conda install -c conda-forge protobuf numpy
conda install pybind11 -c conda-forge

git clone https://github.com/onnx/onnx.git
cd onnx
git submodule update --init --recursive
python setup.py install
```
commits : c2fefcbfa052dd3b602ec825456184d275e91876
Error:
```
[  8%] Built target onnxifi_loader
[  8%] Built target onnxifi_dummy
[  8%] Running C++ protocol buffer compiler on /home/dzws/tensorrt/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
/usr/bin/env: "python\r": No such file or directory
--mypy_out: protoc-gen-mypy: Plugin failed with status code 127.
CMakeFiles/gen_onnx_proto.dir/build.make:61: recipe for target 'onnx/onnx-ml.pb.cc' failed
make[2]: *** [onnx/onnx-ml.pb.cc] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/gen_onnx_proto.dir/all' failed
make[1]: *** [CMakeFiles/gen_onnx_proto.dir/all] Error 2
make[1]: *** Waiting for unfinished tasks....
[ 11%] Built target onnxifi_wrapper
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 336, in <module>
    'backend-test-tools = onnx.backend.test.cmd_tools:main',
  File "/home/miniconda3/envs/mxnet_tensorrt/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/miniconda3/envs/mxnet_tensorrt/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/miniconda3/envs/mxnet_tensorrt/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/miniconda3/envs/mxnet_tensorrt/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/miniconda3/envs/mxnet_tensorrt/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/miniconda3/envs/mxnet_tensorrt/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/miniconda3/envs/mxnet_tensorrt/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/miniconda3/envs/mxnet_tensorrt/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/miniconda3/envs/mxnet_tensorrt/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/miniconda3/envs/mxnet_tensorrt/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/home/miniconda3/envs/mxnet_tensorrt/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/miniconda3/envs/mxnet_tensorrt/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/miniconda3/envs/mxnet_tensorrt/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/miniconda3/envs/mxnet_tensorrt/lib/python3.7/distutils/command/install_lib.py", line 105, in build
    self.run_command('build_py')
  File "/home/miniconda3/envs/mxnet_tensorrt/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/miniconda3/envs/mxnet_tensorrt/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 213, in run
    self.run_command('cmake_build')
  File "/home/miniconda3/envs/mxnet_tensorrt/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/miniconda3/envs/mxnet_tensorrt/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 207, in run
    subprocess.check_call(build_args)
  File "/home/miniconda3/envs/mxnet_tensorrt/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/visi/miniconda3/envs/mxnet_tensorrt/bin/cmake', '--build', '.', '--', '-j', '4']' returned non-zero exit status 2.
```
Also tried:
```
git clone -b rel-1.7.0 https://github.com/onnx/onnx.git
```
Anyone helps？ Thanks.

**Comment by askhade** [comment]
similar to #1314

**Comment by jcwchen** [comment]
It should be solved by https://github.com/onnx/onnx/pull/2961. Please reopen it if you still encounter this issue. Thank you!
