### ISSUE TITLE
onnx support for __range_length

### ISSUE THREAD

**Issue by yangshao** [onnx/onnx#2671]
Hi, i'm trying to export an pytorch model using range, and i get following errors:
/job/.local/lib/python3.7/site-packages/torch/onnx/utils.py:617: UserWarning: ONNX export failed on ATen operator __range_length because torch.onnx.symbolic_opset11.__range_length does not exist
  .format(op_name, opset_version, op_name))
Traceback (most recent call last):
  File "test_onnx/export_model.py", line 108, in <module>
    'output' : [0,1]}
  File "/job/.local/lib/python3.7/site-packages/torch/onnx/__init__.py", line 143, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/job/.local/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/job/.local/lib/python3.7/site-packages/torch/onnx/utils.py", line 382, in _export
    fixed_batch_size=fixed_batch_size)
  File "/job/.local/lib/python3.7/site-packages/torch/onnx/utils.py", line 262, in _model_to_graph
    fixed_batch_size=fixed_batch_size)
  File "/job/.local/lib/python3.7/site-packages/torch/onnx/utils.py", line 132, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/job/.local/lib/python3.7/site-packages/torch/onnx/__init__.py", line 174, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/job/.local/lib/python3.7/site-packages/torch/onnx/utils.py", line 618, in _run_symbolic_function
    op_fn = sym_registry.get_registered_op(op_name, '', opset_version)
  File "/job/.local/lib/python3.7/site-packages/torch/onnx/symbolic_registry.py", line 91, in get_registered_op
    return _registry[(domain, version)][opname]
KeyError: '__range_length'

which opset should i use?

**Comment by oms291** [comment]
Traceback (most recent call last):
  File "/home/smart3/coma/convert_to_onnx.py", line 171, in <module>
    input_names=input_names, output_names=output_names, opset_version=10)
  File "/home/smart3/anaconda3/envs/eneface/lib/python3.6/site-packages/torch/onnx/__init__.py", line 28, in _export
    result = utils._export(*args, **kwargs)
  File "/home/smart3/anaconda3/envs/eneface/lib/python3.6/site-packages/torch/onnx/utils.py", line 530, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/smart3/anaconda3/envs/eneface/lib/python3.6/site-packages/torch/onnx/utils.py", line 384, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/home/smart3/anaconda3/envs/eneface/lib/python3.6/site-packages/torch/onnx/utils.py", line 188, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/smart3/anaconda3/envs/eneface/lib/python3.6/site-packages/torch/onnx/__init__.py", line 241, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/smart3/anaconda3/envs/eneface/lib/python3.6/site-packages/torch/onnx/utils.py", line 787, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "/home/smart3/anaconda3/envs/eneface/lib/python3.6/site-packages/torch/onnx/utils.py", line 745, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/home/smart3/anaconda3/envs/eneface/lib/python3.6/site-packages/torch/onnx/symbolic_registry.py", line 109, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator __range_length to ONNX opset version 10 is not supported. Please open a bug to request ONNX export support for the missing operator.

i have the same problem

**Comment by BowenBao** [comment]
FYI: should be supported by this #48019

**Comment by fteufel** [comment]
Any news on this? I got the same error with opset version 11. 

Using pytorch, I have the following setup 
```
seq_length, batch_size = mask.shape
for i in range(1, seq_length):
    #do stuff
for idx in range(batch_size):
    #do stuff
```
The whole thing is inside of a `@torch.jit.script` function. Judging from the docs, https://pytorch.org/docs/stable/onnx.html#tracing-vs-scripting `for i in range()` loops should be fine with ONNX.



```
