### ISSUE TITLE
PyTorch to ONNX issue

### ISSUE THREAD

**Issue by Louyu666** [onnx/onnx#2731]
When I execute the following code come across an problem:
```
import torch
import torchvision

dummy_input = torch.randn(10, 3, 224, 224, device='cpu')
model = torchvision.models.alexnet(pretrained=True)
input_names = [ "actual_input_1" ] + [ "learned_%d" % i for i in range(16) ]
output_names = [ "output1" ]

torch.onnx.export(model, dummy_input, "alexnet.onnx", verbose=True, input_names=input_names, output_names=output_names)
```

```
Traceback (most recent call last):
  File "/Users/louyu/Code/Python/PyTorch2onnx/main.py", line 9, in <module>
    torch.onnx.export(model, dummy_input, "alexnet.onnx", verbose=True, input_names=input_names, output_names=output_names)
  File "/Users/louyu/anaconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/Users/louyu/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/Users/louyu/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)
  File "/Users/louyu/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 296, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/Users/louyu/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 135, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/Users/louyu/anaconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 179, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/Users/louyu/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 666, in _run_symbolic_function
    value = torch.stack([torch.tensor(v) for v in n["value"]]) if n["value"] else []
  File "/Users/louyu/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 784, in _node_getitem
    return getattr(self, sel)(k)
RuntimeError: required keyword attribute 'value' has the wrong type
```
Any ideas about the issue?

I am on:

macOS                     10.15.4
Anaconda Python   3.7
pytorch                    1.4.0
onnx                         1.6.0
torchvision               0.5.0

**Comment by linkerzhang** [comment]
@spandantiwari

**Comment by Louyu666** [comment]
> adding @spandantiwari (who owns pytorch to onnx exporter).
> 
> btw, it may be better to move this kind of issue to pytorch community.

Ah, thanks for your suggestion.
