### ISSUE TITLE
Failed to install onnx via pip

### ISSUE THREAD

**Issue by MaratZakirov** [onnx/onnx#2734]
```
(cexp) marat@saturn:~$ pip install onnx
Collecting onnx
  Using cached onnx-1.6.0.tar.gz (3.1 MB)
Requirement already satisfied: protobuf in ./anaconda3/envs/cexp/lib/python3.8/site-packages (from onnx) (3.11.4)
Requirement already satisfied: numpy in ./anaconda3/envs/cexp/lib/python3.8/site-packages (from onnx) (1.18.1)
Requirement already satisfied: six in ./anaconda3/envs/cexp/lib/python3.8/site-packages (from onnx) (1.14.0)
Requirement already satisfied: typing-extensions>=3.6.2.1 in ./anaconda3/envs/cexp/lib/python3.8/site-packages (from onnx) (3.7.4.2)
Requirement already satisfied: setuptools in ./anaconda3/envs/cexp/lib/python3.8/site-packages (from protobuf->onnx) (46.1.3.post20200330)
Building wheels for collected packages: onnx
  Building wheel for onnx (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/marat/anaconda3/envs/cexp/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qe0d4hto/onnx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qe0d4hto/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-y6zom3of
       cwd: /tmp/pip-install-qe0d4hto/onnx/
  Complete output (173 lines):
  fatal: Not a git repository (or any of the parent directories): .git
  running bdist_wheel
  running build
  running build_py
  running create_version
  running cmake_build
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  -- The C compiler identification is GNU 5.4.0
  -- The CXX compiler identification is GNU 5.4.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Looking for pthread_create
  -- Looking for pthread_create - not found
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE
  -- Found Protobuf: /home/marat/anaconda3/envs/cexp/lib/libprotobuf.so
  Generated: /tmp/pip-install-qe0d4hto/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
  Generated: /tmp/pip-install-qe0d4hto/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
  CMake Warning at CMakeLists.txt:394 (find_package):
    By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "pybind11",
    but CMake did not find one.
  
    Could not find a package configuration file provided by "pybind11"
    (requested version 2.2) with any of the following names:
  
      pybind11Config.cmake
      pybind11-config.cmake
  
    Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
    "pybind11_DIR" to a directory containing one of the above files.  If
    "pybind11" provides a separate development package or SDK, be sure it has
    been installed.
  
  
  --
  -- ******** Summary ********
  --   CMake version         : 3.5.1
  --   CMake command         : /usr/bin/cmake
  --   System                : Linux
  --   C++ compiler          : /usr/bin/c++
  --   C++ compiler version  : 5.4.0
  --   CXX flags             :  -Wnon-virtual-dtor
  --   Build type            : Release
  --   Compile definitions   :
  --   CMAKE_PREFIX_PATH     :
  --   CMAKE_INSTALL_PREFIX  : /usr/local
  --   CMAKE_MODULE_PATH     :
  --
  --   ONNX version          : 1.6.0
  --   ONNX NAMESPACE        : onnx
  --   ONNX_BUILD_TESTS      : OFF
  --   ONNX_BUILD_BENCHMARKS : OFF
  --   ONNX_USE_LITE_PROTO   : OFF
  --   ONNXIFI_DUMMY_BACKEND : OFF
  --   ONNXIFI_ENABLE_EXT    : OFF
  --
  --   Protobuf compiler     : /home/marat/anaconda3/envs/cexp/bin/protoc
  --   Protobuf includes     : /home/marat/anaconda3/envs/cexp/include
  --   Protobuf libraries    : optimized;/home/marat/anaconda3/envs/cexp/lib/libprotobuf.so;debug;/home/marat/anaconda3/envs/cexp/lib/libprotobuf.so;-lpthread
  --   BUILD_ONNX_PYTHON     : ON
  --     Python version      :
  --     Python executable   : /home/marat/anaconda3/envs/cexp/bin/python
  --     Python includes     : /home/marat/anaconda3/envs/cexp/include/python3.8
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-qe0d4hto/onnx/.setuptools-cmake-build
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  Scanning dependencies of target gen_onnx_proto
  Scanning dependencies of target onnxifi_dummy
  Scanning dependencies of target onnxifi_loader
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  [  1%] Running gen_proto.py on onnx/onnx.in.proto
  [  3%] Building C object CMakeFiles/onnxifi_dummy.dir/onnx/onnxifi_dummy.c.o
  [  4%] Building C object CMakeFiles/onnxifi_loader.dir/onnx/onnxifi_loader.c.o
  /tmp/pip-install-qe0d4hto/onnx/onnx/onnxifi_dummy.c: In function ‘onnxGetExtensionFunctionAddress’:
  /tmp/pip-install-qe0d4hto/onnx/onnx/onnxifi_dummy.c:173:21: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
             *function = &onnxGetExtensionFunctionAddress;
                       ^
  /tmp/pip-install-qe0d4hto/onnx/onnx/onnxifi_dummy.c:176:21: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
             *function = &onnxSetIOAndRunGraph;
                       ^
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  Processing /tmp/pip-install-qe0d4hto/onnx/onnx/onnx.in.proto
  Writing /tmp/pip-install-qe0d4hto/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
  Writing /tmp/pip-install-qe0d4hto/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto3
  generating /tmp/pip-install-qe0d4hto/onnx/.setuptools-cmake-build/onnx/onnx_pb.py
  [  6%] Linking C static library libonnxifi_loader.a
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  [  8%] Running C++ protocol buffer compiler on /tmp/pip-install-qe0d4hto/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  [  8%] Built target onnxifi_loader
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  [  9%] Linking C shared library libonnxifi_dummy.so
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  Scanning dependencies of target onnxifi_wrapper
  --python_out: onnx/onnx-ml.proto: Unknown generator option: dllexport_decl
  CMakeFiles/gen_onnx_proto.dir/build.make:61: recipe for target 'onnx/onnx-ml.pb.cc' failed
  make[2]: *** [onnx/onnx-ml.pb.cc] Error 1
  CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/gen_onnx_proto.dir/all' failed
  make[1]: *** [CMakeFiles/gen_onnx_proto.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  [ 11%] Building C object CMakeFiles/onnxifi_wrapper.dir/onnx/onnxifi_wrapper.c.o
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  [ 11%] Built target onnxifi_dummy
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  [ 13%] Linking C shared module libonnxifi.so
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
  [ 13%] Built target onnxifi_wrapper
  Makefile:127: recipe for target 'all' failed
  make: *** [all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-qe0d4hto/onnx/setup.py", line 315, in <module>
      setuptools.setup(
    File "/home/marat/anaconda3/envs/cexp/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/home/marat/anaconda3/envs/cexp/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/marat/anaconda3/envs/cexp/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/marat/anaconda3/envs/cexp/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/marat/anaconda3/envs/cexp/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/home/marat/anaconda3/envs/cexp/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/marat/anaconda3/envs/cexp/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/marat/anaconda3/envs/cexp/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/marat/anaconda3/envs/cexp/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/marat/anaconda3/envs/cexp/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-qe0d4hto/onnx/setup.py", line 209, in run
      self.run_command('cmake_build')
    File "/home/marat/anaconda3/envs/cexp/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/marat/anaconda3/envs/cexp/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-qe0d4hto/onnx/setup.py", line 203, in run
      subprocess.check_call(build_args)
    File "/home/marat/anaconda3/envs/cexp/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '.', '--', '-j', '8']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for onnx
  Running setup.py clean for onnx
Failed to build onnx
Installing collected packages: onnx
    Running setup.py install for onnx ... error
    ERROR: Command errored out with exit status 1:
     command: /home/marat/anaconda3/envs/cexp/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qe0d4hto/onnx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qe0d4hto/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-rqxbispg/install-record.txt --single-version-externally-managed --compile --install-headers /home/marat/anaconda3/envs/cexp/include/python3.8/onnx
         cwd: /tmp/pip-install-qe0d4hto/onnx/
    Complete output (117 lines):
    fatal: Not a git repository (or any of the parent directories): .git
    running install
    running build
    running build_py
    running create_version
    running cmake_build
    /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
    Generated: /tmp/pip-install-qe0d4hto/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
    Generated: /tmp/pip-install-qe0d4hto/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
    CMake Warning at CMakeLists.txt:394 (find_package):
      By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "pybind11",
      but CMake did not find one.
    
      Could not find a package configuration file provided by "pybind11"
      (requested version 2.2) with any of the following names:
    
        pybind11Config.cmake
        pybind11-config.cmake
    
      Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
      "pybind11_DIR" to a directory containing one of the above files.  If
      "pybind11" provides a separate development package or SDK, be sure it has
      been installed.
    
    
    --
    -- ******** Summary ********
    --   CMake version         : 3.5.1
    --   CMake command         : /usr/bin/cmake
    --   System                : Linux
    --   C++ compiler          : /usr/bin/c++
    --   C++ compiler version  : 5.4.0
    --   CXX flags             :  -Wnon-virtual-dtor
    --   Build type            : Release
    --   Compile definitions   :
    --   CMAKE_PREFIX_PATH     :
    --   CMAKE_INSTALL_PREFIX  : /usr/local
    --   CMAKE_MODULE_PATH     :
    --
    --   ONNX version          : 1.6.0
    --   ONNX NAMESPACE        : onnx
    --   ONNX_BUILD_TESTS      : OFF
    --   ONNX_BUILD_BENCHMARKS : OFF
    --   ONNX_USE_LITE_PROTO   : OFF
    --   ONNXIFI_DUMMY_BACKEND : OFF
    --   ONNXIFI_ENABLE_EXT    : OFF
    --
    --   Protobuf compiler     : /home/marat/anaconda3/envs/cexp/bin/protoc
    --   Protobuf includes     : /home/marat/anaconda3/envs/cexp/include
    --   Protobuf libraries    : optimized;/home/marat/anaconda3/envs/cexp/lib/libprotobuf.so;debug;/home/marat/anaconda3/envs/cexp/lib/libprotobuf.so;-lpthread
    --   BUILD_ONNX_PYTHON     : ON
    --     Python version      :
    --     Python executable   : /home/marat/anaconda3/envs/cexp/bin/python
    --     Python includes     : /home/marat/anaconda3/envs/cexp/include/python3.8
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-install-qe0d4hto/onnx/.setuptools-cmake-build
    /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
    /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
    /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
    /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
    /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
    /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
    /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
    /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
    /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
    [  4%] Running C++ protocol buffer compiler on /tmp/pip-install-qe0d4hto/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
    [  4%] Built target onnxifi_loader
    [  8%] Built target onnxifi_dummy
    /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
    /usr/bin/cmake: /home/marat/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
    [ 11%] Built target onnxifi_wrapper
    --python_out: onnx/onnx-ml.proto: Unknown generator option: dllexport_decl
    CMakeFiles/gen_onnx_proto.dir/build.make:61: recipe for target 'onnx/onnx-ml.pb.cc' failed
    make[2]: *** [onnx/onnx-ml.pb.cc] Error 1
    CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/gen_onnx_proto.dir/all' failed
    make[1]: *** [CMakeFiles/gen_onnx_proto.dir/all] Error 2
    Makefile:127: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qe0d4hto/onnx/setup.py", line 315, in <module>
        setuptools.setup(
      File "/home/marat/anaconda3/envs/cexp/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/home/marat/anaconda3/envs/cexp/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/marat/anaconda3/envs/cexp/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/marat/anaconda3/envs/cexp/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/marat/anaconda3/envs/cexp/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/marat/anaconda3/envs/cexp/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/marat/anaconda3/envs/cexp/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/marat/anaconda3/envs/cexp/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/marat/anaconda3/envs/cexp/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/marat/anaconda3/envs/cexp/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/marat/anaconda3/envs/cexp/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-qe0d4hto/onnx/setup.py", line 209, in run
        self.run_command('cmake_build')
      File "/home/marat/anaconda3/envs/cexp/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/marat/anaconda3/envs/cexp/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-qe0d4hto/onnx/setup.py", line 203, in run
        subprocess.check_call(build_args)
      File "/home/marat/anaconda3/envs/cexp/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '.', '--', '-j', '8']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/marat/anaconda3/envs/cexp/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qe0d4hto/onnx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qe0d4hto/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-rqxbispg/install-record.txt --single-version-externally-managed --compile --install-headers /home/marat/anaconda3/envs/cexp/include/python3.8/onnx Check the logs for full command output.
(cexp) marat@saturn:~$ 
```

**Comment by MaratZakirov** [comment]
If I try:
`conda install -c conda-forge onnx`
I get
`ImportError: libprotobuf.so.21: cannot open shared object file: No such file or directory`
I have only
```
(cexp) marat@saturn:~/anaconda3$ find . -name "libprotobuf.so*"
./pkgs/libprotobuf-3.11.4-h8b12597_0/lib/libprotobuf.so.22.0.4
./pkgs/libprotobuf-3.11.4-h8b12597_0/lib/libprotobuf.so.22
./pkgs/libprotobuf-3.11.4-h8b12597_0/lib/libprotobuf.so
```
Which I get from
```
(cexp) marat@saturn:~$ python
Python 3.8.2 (default, Mar 26 2020, 15:53:00) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'2.2.0-rc3'
```

**Comment by vinitra** [comment]
Looks like you're using python 3.8, which is currently unsupported. Can you try with python 3.7?

**Comment by zkj1995** [comment]
THX vinitra

**Comment by MaratZakirov** [comment]
> Looks like you're using python 3.8, which is currently unsupported. Can you try with python 3.7?

It works.

**Comment by agungor2** [comment]
I think the issue was because of pip. If you run the following command, it should fix: 
pip install --upgrade pip

**Comment by vishnumadhuintel** [comment]
@agungor2 Thanks Mecit. This works. The error thrown was cryptic, but a simple pip upgrade fixed it :)

**Comment by univerone** [comment]
> I think the issue was because of pip. If you run the following command, it should fix:
> pip install --upgrade pip

It doesn't work for me, I'm installing version 1.6.0 with python3.8

**Comment by Darrshan-Sankar** [comment]
@univerone It doesn't work because, the cp version wheels doesn't exist for python 3.8 for onnx==1.6.0.
Please try to downgrade your python to a lower version. For me onnx==1.8.1 installed with python 3.7
