### ISSUE TITLE
Problem with model test

### ISSUE THREAD

**Issue by tjingrant** [onnx/onnx#278]
Hi, has anyone seen this error from backend model tests?

```
======================================================================
ERROR: test_bvlc_alexnet_cpu (__main__.OnnxBackendModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/work/onnx/onnx/onnx/backend/test/runner/__init__.py", line 175, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/home/travis/work/onnx/onnx/onnx/backend/test/runner/__init__.py", line 191, in run
    model = onnx.load(model_pb_path)
  File "/home/travis/work/onnx/onnx/onnx/__init__.py", line 36, in load
    decoded, len(s)))
DecodeError: Protobuf decoding consumed too few bytes: None out of 243863373
```

The model is apparently being downloaded as we can see the output:
```
Start downloading model bvlc_alexnet from https://s3.amazonaws.com/download.onnx/models/bvlc_alexnet.tar.gz
Done
EsStart downloading model densenet121 from https://s3.amazonaws.com/download.onnx/models/densenet121.tar.gz
Done
EsStart downloading model inception_v1 from https://s3.amazonaws.com/download.onnx/models/inception_v1.tar.gz
Done
EsStart downloading model inception_v2 from https://s3.amazonaws.com/download.onnx/models/inception_v2.tar.gz
Done
EsStart downloading model resnet50 from https://s3.amazonaws.com/download.onnx/models/resnet50.tar.gz
Done
EsStart downloading model shufflenet from https://s3.amazonaws.com/download.onnx/models/shufflenet.tar.gz
Done
EsStart downloading model squeezenet from https://s3.amazonaws.com/download.onnx/models/squeezenet.tar.gz
Done
EsStart downloading model vgg16 from https://s3.amazonaws.com/download.onnx/models/vgg16.tar.gz
Done
```

Can anyone help us determine the possible cause?

**Comment by bddppq** [comment]
This is related to a check we added yesterday. PR created

**Comment by bddppq** [comment]
Should be fixed now

**Comment by tjingrant** [comment]
great, looks good now, thanks!
