### ISSUE TITLE
pip3 install onnx on aarch64 produces "Building wheels for onnx (PEP 517) ... error"

### ISSUE THREAD

**Issue by GalMoore** [onnx/onnx#2791]
I'm on an aarch64 server with EulerOS. I can install most packages with pip3 or YUM / RPM. However pip3 install onnx always leads to error. And I can't find the package elsewhere for aarch64. Any thoughts?
Thanks,
Gal

**Comment by snnn** [comment]
ONNX doesn't have a prebuilt package for ARM.  Please build it from source by yourself. See #2755 for instructions.

**Comment by gsrujana89** [comment]
Hi I get the same. I have followed steps on readme and #2755 

ubuntu@ip-172-31-21-80:~/sgattupa/mlperf_inference/vision/classification_and_detection$ pip install onnx
Defaulting to user installation because normal site-packages is not writeable
Collecting onnx
  Using cached onnx-1.8.1.tar.gz (5.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied: protobuf in /home/ubuntu/.local/lib/python3.6/site-packages (from onnx) (3.15.7)
Requirement already satisfied: typing-extensions>=3.6.2.1 in /home/ubuntu/.local/lib/python3.6/site-packages (from onnx) (3.7.4.3)
Requirement already satisfied: numpy>=1.16.6 in /usr/local/lib/python3.6/dist-packages (from onnx) (1.19.5)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from onnx) (1.11.0)
Building wheels for collected packages: onnx
  Building wheel for onnx (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /home/ubuntu/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpfewu1fs7
       cwd: /tmp/pip-install-_ilc3squ/onnx_7d1e07110e4249a584f916ca2e3719b4
  Complete output (60 lines):
  fatal: not a git repository (or any of the parent directories): .git
  running bdist_wheel
  running build
  running build_py
  running create_version
  running cmake_build
  Traceback (most recent call last):
    File "/home/ubuntu/.local/bin/cmake", line 5, in <module>
      from cmake import cmake
  ModuleNotFoundError: No module named 'cmake'
  /tmp/pip-build-env-driynwt3/overlay/lib/python3.6/site-packages/setuptools/dist.py:645: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
    % (opt, underscore_opt))
  Traceback (most recent call last):
    File "/home/ubuntu/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/ubuntu/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/ubuntu/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 205, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-driynwt3/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 222, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-driynwt3/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-driynwt3/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 259, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-driynwt3/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 341, in <module>
      'backend-test-tools = onnx.backend.test.cmd_tools:main',
    File "/tmp/pip-build-env-driynwt3/overlay/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-driynwt3/overlay/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "setup.py", line 217, in run
      self.run_command('cmake_build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "setup.py", line 203, in run
      subprocess.check_call(cmake_args)
    File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/home/ubuntu/.local/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.6m', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-36m-aarch64-linux-gnu.so',
'-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-_ilc3squ/onnx_7d1e07110e4249a584f916ca2e3719b4']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for onnx
Failed to build onnx
ERROR: Could not build wheels for onnx which use PEP 517 and cannot be installed directly

**Comment by snnn** [comment]
Where was /home/ubuntu/.local/bin/cmake from? You probably need to delete it and install cmake from https://cmake.org/download .
