### ISSUE TITLE
Converting a Pytorch Model to Tensorflow using ONNX

### ISSUE THREAD

**Issue by Nitya05** [onnx/onnx#3032]
# Ask a Question

### Question

I am trying to convert a very simple LSTM model from Pytorch to ONNX. Even after using a batch size of 1 and specifying h0, c0 as inputs, I am getting the following warning:
**UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with LSTM can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  "or define the initial states (h0/c0) as inputs of the model. ")**

And when this onnx model is used to generate a Tensorflow model, the following error is encountered:
**tensorflow.python.ops.op_selector.UnliftableError: Unable to lift tensor <tf.Tensor 'concat_2:0' shape=(6, 12) dtype=float32> because it depends transitively on placeholder <tf.Operation 'Squeeze_1/60' type=Placeholder> via at least one path, e.g.: concat_2 (ConcatV2) <- transpose_1 (Transpose) <- concat_1 (ConcatV2) <- split_1 (Split) <- Squeeze_1 (Squeeze) <- Squeeze_1/60 (Placeholder)**

Please suggest what is a suitable way of converting a Pytorch model to ONNX so that it can be further used to get a Tensorflow model.

### Notes

Attaching my Pytorch code for reference.

import torch
import torch.nn as nn
import torch.nn.functional as F 
import torch.optim as optim

import torch.onnx
import torchvision

torch.manual_seed(1)

lstm = nn.LSTM(3, 3, num_layers=1)
lstm.eval()

with torch.no_grad():
	inputs = [torch.randn(1,3) for _ in range(5)]	#make a sequence of length 5
	inputs = torch.cat(inputs).view(len(inputs), 1, -1)
	h0 = torch.randn(1, 1, 3)
	c0 = torch.randn(1, 1, 3)
	out, (hn, cn) = lstm(inputs, (h0, c0))

	input_names = ["input", "h0", "c0"]
	output_names = ["output", "hn", "cn"]

	torch.onnx.export(lstm, (inputs, (h0, c0)), "SimpleLSTM_2.onnx", input_names=input_names, output_names=output_names)

**Comment by jcwchen** [comment]
Hi @Nitya05,
This seems like a converter issue to me.
https://discuss.pytorch.org/t/userwarning-exporting-a-model-to-onnx-with-a-batch-size-other-than-1/64951
To resolve this warning, I suggest you to open an issue about this under pytorch repo to get the best help. Thanks.

**Comment by Nitya05** [comment]
Thanks @jcwchen.

**Comment by Nitya05** [comment]
Hi @jcwchen, I had an interaction with Pytorch team and they said that the user warning is being generated incorrectly, but the model conversion is happening properly. 
When I try to convert this onnx model to tensorflow, I get the following error:

Traceback (most recent call last):
File "testLSTM.py", line 14, in
tf_rep.export_graph('./SimpleLSTM.pb')
File "/workspace/ctg_nitya/onnx-tensorflow/onnx_tf/backend_rep.py", line 93, in export_graph
tf.saved_model.save(self.tf_module, path, signatures=self.tf_module.call.get_concrete_function(**self.signatures))
File "/workspace/ctg_nitya/python3_venv_tf_2.3_gpu/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 1167, in get_concrete_function
concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
File "/workspace/ctg_nitya/python3_venv_tf_2.3_gpu/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 1074, in _get_concrete_function_garbage_collected
self._initialize_uninitialized_variables(initializers)
File "/workspace/ctg_nitya/python3_venv_tf_2.3_gpu/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 965, in _initialize_uninitialized_variables
return initialize_variables.get_concrete_function()()
File "/workspace/ctg_nitya/python3_venv_tf_2.3_gpu/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2939, in get_concrete_function
*args, **kwargs)
File "/workspace/ctg_nitya/python3_venv_tf_2.3_gpu/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2906, in _get_concrete_function_garbage_collected
graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
File "/workspace/ctg_nitya/python3_venv_tf_2.3_gpu/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
graph_function = self._create_graph_function(args, kwargs)
File "/workspace/ctg_nitya/python3_venv_tf_2.3_gpu/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
capture_by_value=self._capture_by_value),
File "/workspace/ctg_nitya/python3_venv_tf_2.3_gpu/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
func_outputs = python_func(*func_args, **func_kwargs)
File "/workspace/ctg_nitya/python3_venv_tf_2.3_gpu/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 957, in initialize_variables
inits, ops.get_default_graph(), op_map=op_map)
File "/workspace/ctg_nitya/python3_venv_tf_2.3_gpu/lib/python3.6/site-packages/tensorflow/python/eager/lift_to_graph.py", line 260, in lift_to_graph
add_sources=add_sources))
File "/workspace/ctg_nitya/python3_venv_tf_2.3_gpu/lib/python3.6/site-packages/tensorflow/python/ops/op_selector.py", line 413, in map_subgraph
% (repr(init_tensor), repr(op), _path_from(op, init_tensor, sources)))
**tensorflow.python.ops.op_selector.UnliftableError: Unable to lift tensor <tf.Tensor 'concat_2:0' shape=(6, 12) dtype=float32> because it depends transitively on placeholder <tf.Operation 'Squeeze_1/60' type=Placeholder> via at least one path, e.g.: concat_2 (ConcatV2) <- transpose_1 (Transpose) <- concat_1 (ConcatV2) <- split_1 (Split) <- Squeeze_1 (Squeeze) <- Squeeze_1/60 (Placeholder)**

The code being used for ONNX to Tensorflow conversion is as follows:

import onnx
from onnx_tf.backend import prepare
onnx_model = onnx.load("./SimpleLSTM.onnx")
tf_rep = prepare(onnx_model)
tf_rep.export_graph('./SimpleLSTM.pb')

I am getting an error in this line:  **tf_rep.export_graph('./SimpleLSTM.pb')**. Could there be any problem on the onnx end?

**Comment by jcwchen** [comment]
Hi @Nitya05,
Thank you for contacting the pytorch/onnx team. The flow of your usage is pytorch->onnx->tensorflow.
If the warning is acceptable and the produced onnx is correct during pytorch->onnx, onnx itself should be good. (Also it can be correctly inferred by onnxruntime) In that case, I would say the problem is more likely in the onnx-tensorflow since this error occurs there. Hope you can find the right solution there. Thanks.

**Comment by Nitya05** [comment]
I have communicated with the Tensorflow team as well, but have not found any solution yet.

**Comment by jcwchen** [comment]
> I have communicated with the Tensorflow team as well, but have not found any solution yet.

Other than that, onnx-tensorflow team would be also helpful. You can try to contact them as well. Thank you.

**Comment by Nitya05** [comment]
Sure @jcwchen. Thanks a lot for your time.
