### ISSUE TITLE
Optimization on valid ONNX models fail with obscure message

### ISSUE THREAD

**Issue by siorpaes** [onnx/onnx#3088]
# Bug Report
Some valid ONNX models fail during optimization phase. The checker is not reporting any problem on the model though.

### System information
- OS Platform: Linux Ubuntu 18.04 
- ONNX version 1.6.0   
- Python version 3.7.6
- CMake version: 3.14.0
- Protobuf version: 3.9.1

### Reproduction instructions
```
import onnx
import argparse
from onnx import optimizer
import onnx.utils
import os

# Parse arguments
parser = argparse.ArgumentParser(description='')
parser.add_argument("--input", required=True, help="Input ONNX model")
args = parser.parse_args()

# Load ONNX model
print("Processing model:", args.input)
model = onnx.load(args.input)
onnx.checker.check_model(model)

# Remove dangling nodes and save new model
optimized_model = optimizer.optimize(model, ['eliminate_deadend'])
outputFile = os.path.splitext(args.input)[0] + "-opt.onnx"
onnx.save(optimized_model, outputFile)
```
Example ONNX model triggering the the issue is attached.
[posenet_mobilenet_float_075_1_default_1.onnx.gz](https://github.com/onnx/onnx/files/5483101/posenet_mobilenet_float_075_1_default_1.onnx.gz)

### Expected behavior
An optimized model is created

### Actual output
```
python optimize_model.py   --input posenet_mobilenet_float_075_1_default_1.onnx 
[posenet_mobilenet_float_075_1_default_1.onnx.gz](https://github.com/onnx/onnx/files/5483085/posenet_mobilenet_float_075_1_default_1.onnx.gz)

Processing model: posenet_mobilenet_float_075_1_default_1.onnx
Traceback (most recent call last):
  File "optimize_model.py", line 26, in <module>
    optimized_model = optimizer.optimize(model, ['eliminate_deadend'])
  File "/home/daz/anaconda3/envs/atonn/lib/python3.7/site-packages/onnx/optimizer.py", line 55, in optimize
    optimized_model_str = C.optimize(model_str, passes)
IndexError: _Map_base::at
```

**Comment by jackwish** [comment]
Thank you @siorpaes! And, for my local try regarding [the original issue](https://github.com/jackwish/tflite2onnx/issues/19), I have the error message as below (using ONNX 1.8).

```
WARNING: ONNX Optimizer has been moved to https://github.com/onnx/optimizer.
All further enhancements and fixes to optimizers will be done in this new repo.
The optimizer code in onnx/onnx repo will be removed in 1.9 release.

Traceback (most recent call last):
  File "repro.py", line 15, in <module>
    opt = onnx.optimizer.optimize(model, ['eliminate_deadend'])
  File "/Users/wzh/workspace/onnx/onnx.git/onnx/optimizer.py", line 55, in optimize
    optimized_model_str = C.optimize(model_str, passes)
IndexError: Input MobilenetV1/Conv2d_0/weights is undefined!
```

For the error message I got here, it seems to me that, [the ProtoBuf Graph reader `graphProtoToGraph`](https://github.com/onnx/onnx/blob/master/onnx/common/ir_pb_converter.cc#L186) expects the weights (initializers) to be _input_ of the graph? Here, the error indicates that `MobilenetV1/Conv2d_0/weights` should be included in `value_by_name_of`, which [documented to included initializer](https://github.com/onnx/onnx/blob/master/onnx/common/ir_pb_converter.cc#L204) but seems not in code?

**Comment by jackwish** [comment]
Off the topic, per the _Optimizer move_ warning, should we discuss here or move to the optimizer repo?

**Comment by askhade** [comment]
@jackwish @siorpaes moving this issue to the optimizer repo and it is the correct place for it.
