### ISSUE TITLE
No conversion function registered for op type _contrib_MultiBoxPrior yet

### ISSUE THREAD

**Issue by Kenneth-X** [onnx/onnx#3142]
### Describe the bug

$python mxnet2onnx.py
INFO:root:Converting json and weight file to sym and params
[11:27:45] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v0.12.0. Attempting to upgrade...
[11:27:45] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
Traceback (most recent call last):
  File "mxnet2onnx.py", line 12, in <module>
    converted_model_path = onnx_mxnet.export_model(sym, params, [input_shape], np.float32, onnx_file)
  File "/home/yuxi.xt/software/anaconda3/lib/python3.6/site-packages/mxnet/contrib/onnx/mx2onnx/export_model.py", line 83, in export_model
    verbose=verbose)
  File "/home/yuxi.xt/software/anaconda3/lib/python3.6/site-packages/mxnet/contrib/onnx/mx2onnx/export_onnx.py", line 253, in create_onnx_graph_proto
    idx=idx
  File "/home/yuxi.xt/software/anaconda3/lib/python3.6/site-packages/mxnet/contrib/onnx/mx2onnx/export_onnx.py", line 90, in convert_layer
    raise AttributeError("No conversion function registered for op type %s yet." % op)
AttributeError: No conversion function registered for op type _contrib_MultiBoxPrior yet.

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): 
- ONNX version :    1.7
-MXNET version:   1.5
- Python version:   3.6
- GCC/Compiler version (if compiling from source):
- CMake version:
- Protobuf version:
- Visual Studio version (if applicable):

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import mxnet as mx
import numpy as np
from mxnet.contrib import onnx as onnx_mxnet
import logging
logging.basicConfig(level=logging.INFO)
sym = './ssd_1213-symbol.json'
params = './ssd_1213-0000.params'
input_shape = (1, 3, 256, 512)
onnx_file = './slagtrunck.onnx'
 
converted_model_path = onnx_mxnet.export_model(sym, params, [input_shape], np.float32, onnx_file)
...
```
- Attach the ONNX model to the issue (where applicable)

### Notes

Any additional information

**Comment by askhade** [comment]
@Kenneth-X This seems to be a problem in the converter side and not in ONNX. Looks like the converter does not have an appropriate conversion for _contrib_MultiBoxPrior  optype. Please open this issue in the converter repo.

Closing this issue here.
