### ISSUE TITLE
RuntimeError: Exporting the operator uniform to ONNX opset version 9 is not supported.

### ISSUE THREAD

**Issue by iuhiyuh** [onnx/onnx#3154]
---

RuntimeError: Exporting the operator uniform to ONNX opset version 9 is not supported.
Traceback (most recent call last):
  File "/home/huyihui/.pyenv/versions/anaconda3-2018.12/envs/tensorrt/lib/python3.6/site-packages/torch/onnx/__init__.py", line 230, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/huyihui/.pyenv/versions/anaconda3-2018.12/envs/tensorrt/lib/python3.6/site-packages/torch/onnx/utils.py", line 91, in export
    use_external_data_format=use_external_data_format)
  File "/home/huyihui/.pyenv/versions/anaconda3-2018.12/envs/tensorrt/lib/python3.6/site-packages/torch/onnx/utils.py", line 639, in _export
    dynamic_axes=dynamic_axes)
  File "/home/huyihui/.pyenv/versions/anaconda3-2018.12/envs/tensorrt/lib/python3.6/site-packages/torch/onnx/utils.py", line 421, in _model_to_graph
    dynamic_axes=dynamic_axes, input_names=input_names)
  File "/home/huyihui/.pyenv/versions/anaconda3-2018.12/envs/tensorrt/lib/python3.6/site-packages/torch/onnx/utils.py", line 203, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/huyihui/.pyenv/versions/anaconda3-2018.12/envs/tensorrt/lib/python3.6/site-packages/torch/onnx/__init__.py", line 263, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/huyihui/.pyenv/versions/anaconda3-2018.12/envs/tensorrt/lib/python3.6/site-packages/torch/onnx/utils.py", line 930, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "/home/huyihui/.pyenv/versions/anaconda3-2018.12/envs/tensorrt/lib/python3.6/site-packages/torch/onnx/utils.py", line 888, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/home/huyihui/.pyenv/versions/anaconda3-2018.12/envs/tensorrt/lib/python3.6/site-packages/torch/onnx/symbolic_registry.py", line 111, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator uniform to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator.

**Comment by askhade** [comment]
@iuhiyuh : This is a converter issue. Please open a bug in the converter repo. BTW ONNX has now moved to opset 13 are you using the latest version of the converter?
Closing this issue as it is not relevant in this repo.
