### ISSUE TITLE
onnx build from source issue on mac

### ISSUE THREAD

**Issue by Roshrini** [onnx/onnx#323]
I want to build onnx from source on macos sierra 10.12 and facing the following issue:
Can anyone take a look at this please?

:~ roshanin$ python
Python 2.7.12 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:43:17) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import onnx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/roshanin/anaconda2/lib/python2.7/site-packages/onnx-0.2.1-py2.7-macosx-10.6-x86_64.egg/onnx/__init__.py", line 10, in <module>
    import onnx.helper  # noqa
  File "/Users/roshanin/anaconda2/lib/python2.7/site-packages/onnx-0.2.1-py2.7-macosx-10.6-x86_64.egg/onnx/helper.py", line 15, in <module>
    import onnx.defs as defs
  File "/Users/roshanin/anaconda2/lib/python2.7/site-packages/onnx-0.2.1-py2.7-macosx-10.6-x86_64.egg/onnx/defs/__init__.py", line 6, in <module>
    import onnx.onnx_cpp2py_export.defs as C
ImportError: dlopen(/Users/roshanin/anaconda2/lib/python2.7/site-packages/onnx-0.2.1-py2.7-macosx-10.6-x86_64.egg/onnx/onnx_cpp2py_export.so, 2): Symbol not found: __ZN6google8protobuf14MessageFactory29InternalRegisterGeneratedFileEPKcPFvRKSsE
  Referenced from: /Users/roshanin/anaconda2/lib/python2.7/site-packages/onnx-0.2.1-py2.7-macosx-10.6-x86_64.egg/onnx/onnx_cpp2py_export.so
  Expected in: flat namespace
 in /Users/roshanin/anaconda2/lib/python2.7/site-packages/onnx-0.2.1-py2.7-macosx-10.6-x86_64.egg/onnx/onnx_cpp2py_export.so

Tested that "conda install -c ezyang onnx" works fine.
 
roshanin$ protoc --version
libprotoc 3.4.0

python installed through conda and has 2.7.12 version

**Comment by dzhulgakov** [comment]
Probably the version of libprotobuf is different during building and in your loading path. Do you have only one version of protobuf installed? And is it installed through conda or not?

cc @bddppq

**Comment by bddppq** [comment]
What the commands you used to build from source?
Could you do `otool -L /Users/roshanin/anaconda2/lib/python2.7/site-packages/onnx-0.2.1-py2.7-macosx-10.6-x86_64.egg/onnx/onnx_cpp2py_export.so` and paste the output here?

**Comment by LucasMahieu** [comment]
Personally, i install onnx with : git clone then pip install ./onnx
Be carful to have the same version of protobuf-c (compiler) and protobuf installer.
I did it with brew install protobuf protobuf-c.
