### ISSUE TITLE
RuntimeError: Exporting the operator numpy_T to ONNX opset version 9, 10, 11 & 12 is not supported

### ISSUE THREAD

**Issue by DJ543** [onnx/onnx#3242]
# Bug Report
RuntimeError: Exporting the operator numpy_T to ONNX opset version 9, 10, 11 & 12 is not supported. Please open a bug to request ONNX export support for the missing operator.

### Describe the bug

Traceback (most recent call last):
File "model2onnx.py", line 69, in
main()
File "model2onnx.py", line 63, in main
onnx_export(model, args.output_path, input)
File "/home/ramos/miniconda3/envs/torch/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
return func(*args, **kwargs)
File "model2onnx.py", line 51, in onnx_export
torch_onnx.export(model, dummy_input, output_dir,
File "/home/ramos/miniconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/init.py", line 225, in export
return utils.export(model, args, f, export_params, verbose, training,
File "/home/ramos/miniconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/utils.py", line 85, in export
_export(model, args, f, export_params, verbose, training, input_names, output_names,
File "/home/ramos/miniconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/utils.py", line 632, in _export
_model_to_graph(model, args, verbose, input_names,
File "/home/ramos/miniconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/utils.py", line 417, in _model_to_graph
graph = _optimize_graph(graph, operator_export_type,
File "/home/ramos/miniconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/utils.py", line 203, in _optimize_graph
graph = torch._C._jit_pass_onnx(graph, operator_export_type)
File "/home/ramos/miniconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/init.py", line 263, in _run_symbolic_function
return utils._run_symbolic_function(*args, **kwargs)
File "/home/ramos/miniconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/utils.py", line 930, in _run_symbolic_function
symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
File "/home/ramos/miniconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/utils.py", line 888, in _find_symbolic_in_registry
return sym_registry.get_registered_op(op_name, domain, opset_version)
File "/home/ramos/miniconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/symbolic_registry.py", line 111, in get_registered_op
raise RuntimeError(msg)
RuntimeError: Exporting the operator numpy_T to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.

## Expected behavior
torch_onnx.export(model, dummy_input, output_dir,
input_names=input_names, output_names=output_names,opset_version=12)

### System information
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.18.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 9.1.85
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti

Nvidia driver version: 450.102.04
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.0
[pip3] torch2trt==0.1.0
[pip3] torchgeometry==0.1.2
[pip3] torchvision==0.8.1
[conda] cudatoolkit 10.0.130 0
[conda] numpy 1.19.4 pypi_0 pypi
[conda] torch 1.7.0 pypi_0 pypi
[conda] torch2trt 0.1.0 pypi_0 pypi
[conda] torchgeometry 0.1.2 pypi_0 pypi
[conda] torchvision 0.8.1 pypi_0 pypi

**Comment by DJ543** [comment]
I located the bug in:
head=dict(
        type='AMSoftmaxClsHead',
        num_classes=7,
        in_channels=512,
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
        topk=(1,),
        margin=0.15
    )

**Comment by jcwchen** [comment]
Hi @DJ543,
This should be a converter issue. I saw you also opened an issue under pytorch and that is the right place to track it. Thank you.

**Comment by jcwchen** [comment]
Close now. Please reopen it if you still have any ONNX issue. Thanks!
