### ISSUE TITLE
Scalar initializer not working

### ISSUE THREAD

**Issue by tjingrant** [onnx/onnx#325]
Hi, it seems like initializer cannot initialize a scalar tensor.
Here's the model that's causing trouble:
```
    X = np.array([[1, 2], [3, 4]]).astype(np.float32)
    Y = np.array([[1, 2], [3, 4]]).astype(np.float32)
    weight = np.array([[1, 0], [0, 1]])
    graph_def = helper.make_graph(
        [helper.make_node("Add", ["X", "Y"], ["Z0"])],
        name="test_initializer",
        inputs=[
            helper.make_tensor_value_info("X", TensorProto.FLOAT, ()),
            helper.make_tensor_value_info("Y", TensorProto.FLOAT, ()),
        ],
        outputs=[
            helper.make_tensor_value_info("Z", TensorProto.FLOAT, ())
        ],
        initializer=[helper.make_tensor("X",
                                 TensorProto.FLOAT,
                                 (),
                                 [1]),
                     helper.make_tensor("Y",
                                 TensorProto.FLOAT,
                                 (),
                                 [1])])

    tf_rep = prepare(helper.make_model(graph_def))
```
The error message reads:
```
Traceback (most recent call last):
  File "../backend/test_model.py", line 89, in test_const
    tf_rep = prepare(helper.make_model(graph_def))
  File "/localhd/tjin/onnxtf/onnx_tf/backend.py", line 385, in prepare
    super(TensorflowBackend, cls).prepare(model, device, **kwargs)
  File "/localhd/tjin/onnx/onnx/backend/base.py", line 53, in prepare
    onnx.checker.check_model(model)
  File "/localhd/tjin/onnx/onnx/checker.py", line 32, in checker
    proto.SerializeToString(), ir_version)
ValidationError: Field 'shape' of type is required but missing.
```

**Comment by Shannshan47** [comment]
Help. Dont know anything about fixing a cell. Please Help Me!!!!!!

**Comment by ezyang** [comment]
Hmm, it sounds like we're interpreting a shape that is an empty list as a missing field, but that's not right for scalar tensors. Sounds like a bug!

**Comment by tjingrant** [comment]
Indeed, @bddppq can you take a look at this and see if the checker needs any update?

**Comment by bddppq** [comment]
I just took a closer look, the checker is fine (it's not enforcing non-zero length dims). It's the helper function make_tensor_value_info doesn't initialize the "shape" field properly.

**Comment by tjingrant** [comment]
Thanks a lot for fixing it!
