### ISSUE TITLE
Not able to run inference with If operator

### ISSUE THREAD

**Issue by coocalcol** [onnx/onnx#3255]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug
https://github.com/onnx/onnx/blob/master/onnx/test/checker_test.py#L254
We created a model based on the above test case (test_nested_graph). Onnx model was successfully created but when running inference based on the generated model we got the following error:
The code we're running:
`model_path = "models/test1.onnx"`
`input_data = [np.array([True]), np.array([1.0, 2.0]).astype(np.float32)]`
`onnx_sess = onnxruntime.InferenceSession(model_path)`
`pred = onnx_sess.run(None, input_data)`
`print(pred)`

Traceback (most recent call last):
  File "create_test_model.py", line 299, in <module>
    onnx_sess = onnxruntime.InferenceSession(model_out_path)
  File "lib/python3.7/site-packages/onnxruntime/capi/session.py", line 195, in __init__
    self._create_inference_session(providers, provider_options)
  File "lib/python3.7/site-packages/onnxruntime/capi/session.py", line 200, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from models/test1.onnx failed:Node () Op (If) [TypeInferenceError] Graph attribute inferencing failed: Size mismatch validating subgraph inputs. Got 0 inputs but subgraph has 1 inputs and requires 1 inputs. Either provide all subgraph inputs, or just the required inputs.

### System information
- OS Platform and Distribution: Mac OS 10.14.6
- ONNX version: 1.7.0  
- Python version: 3.7.8
- GCC/Compiler version (if compiling from source):
- CMake version:
- Protobuf version:
- Visual Studio version (if applicable):

### Reproduction instructions
- Describe the code to reproduce the behavior.
See description.
- Attach the ONNX model to the issue (where applicable)

### Expected behavior
Expect onnxsession to be created and inference session to return float result 
### Notes

Any additional information

**Comment by jcwchen** [comment]
Hi @coocalcol,
I think the reason is this test uses a deprecated operator: `Scale`. You can check all the deprecated and experimental operators here: https://github.com/onnx/onnx/blob/master/docs/ManagingExperimentalOps.md. Currently if ONNX checker/shape_inference encounters any deprecated operator in a graph, it will stop checker/shape_inference and throw a warning. 

I am not sure how ONNXRuntime handles these deprecated operators, but I would say ORT will probably throw an error because it cannot infer the output shape of a deprecated operator (missing operator schema from ONNX).

Please note that some old tests might use intermediate models which could be invalid models. They are for testing purpose (check a single node). Thank you.

**Comment by coocalcol** [comment]
> Hi @coocalcol,
> I think the reason is this test uses a deprecated operator: `Scale`. You can check all the deprecated and experimental operators here: https://github.com/onnx/onnx/blob/master/docs/ManagingExperimentalOps.md. Currently if ONNX checker/shape_inference encounters any deprecated operator in a graph, it will stop checker/shape_inference and throw a warning.
> 
> I am not sure how ONNXRuntime handles these deprecated operators, but I would say ORT will probably throw an error because it cannot infer the output shape of a deprecated operator (missing operator schema from ONNX).
> 
> Please note that some old tests might use intermediate models which could be invalid models. They are for testing purpose (check a single node). Thank you.

Hi at the time we also tried Identity operator and it still gives error.

**Comment by jcwchen** [comment]
Does it (Identity operator) also come from ONNX's test?

**Comment by coocalcol** [comment]
No, I simply replaced the `scale` node with an `identity` node.
```
n1 = helper.make_node("Identity", ["X"], ["Y"])
n2 = helper.make_node("Identity", ["Y"], ["Z"])
```

**Comment by coocalcol** [comment]
Here is the entire test code we're running to reproduce the error:
```
def create_model_new(model_path):
    """
     This function creates a test feed model that consists of a single node that takes
     Tensors of all inputs
     """
    n1 = helper.make_node(
        "Identity", ["X"], ["Y"])
    n2 = helper.make_node(
        "Identity", ["Y"], ["Z"])

    graph = helper.make_graph(
        [n1, n2],
        "nested",
        inputs=[
            helper.make_tensor_value_info("X", TensorProto.FLOAT, [1, 2])
        ],
        outputs=[
            helper.make_tensor_value_info("Z", TensorProto.FLOAT, [1, 2])
        ]
    )

    i1 = helper.make_node(
        "If", ["cond"], ["Z"], then_branch=graph, else_branch=graph)

    graph = helper.make_graph(
        [i1],
        "test",
        inputs=[
            helper.make_tensor_value_info("cond", TensorProto.BOOL, [1]),
            helper.make_tensor_value_info("X", TensorProto.FLOAT, [1, 2])
        ],
        outputs=[helper.make_tensor_value_info("Z", TensorProto.FLOAT, [1, 2])],
    )

    model_def = helper.make_model(graph, producer_name='is_transform_test')
    onnx.save(model_def, model_path)


if __name__ == "__main__":
    model_path = "/models/test1.onnx"
    input_data = [np.array([True]), np.array([1.0, 2.0]).astype(np.float32)]
    create_model_new(model_path)
    onnx_sess = onnxruntime.InferenceSession(model_path)
    pred = onnx_sess.run(None, input_data)
    print(pred)
```

**Comment by jcwchen** [comment]
Thanks for the code and I can repro this error.

If you are pursuing a valid model for `If` operator, I would suggest you to check the example here: https://github.com/onnx/onnx/blob/master/onnx/backend/test/case/node/if.py

As I mentioned, those tests (intermediate models) are for testing purpose so it's possible that they cannot be run by Runtime. Still, honestly I think this old test code for `If` can be improved. Sorry for the confusion.

**Comment by michal-choinski** [comment]
@jcwchen I can see that this issue is closed but I have a follow-up question regarding subgraph inputs of then/else branches of the if operator. I am struggling for some time to create a working model that would execute either one or the other subgraph. The tricky part here is that they require different tensors to be fed into their inputs, therefore the suggested solution cannot work in my case. Is it even possible to do such a thing in ONNX? After many attempts, I always end up with the same error as the one reported by @coocalcol. It would also be great to have it better explained in the documentation of the operator.

**Comment by jcwchen** [comment]
Thanks for the details. IIUC, actually `onnx.compose.merge_graphs` is mainly used for merging two models. You could check the examples [here](https://github.com/onnx/onnx/blob/main/docs/PythonAPIOverview.md#onnx-compose). Thus intentionally it will add all inputs from original models into the new model, which is not the case for If node within a subgraph. Directly using make_node and make_graph (like this [example)](https://github.com/onnx/onnx/blob/26c7077e0a98eb4aaf190ad7131fca86e28c2e1f/onnx/test/shape_inference_test.py#L2100) should be a better approach.

> I implemented that logic in Tensorflow but I had issues with its conversion to ONNX. Then I decided to implement it purely in ONNX, by first loading both models trained with Tensorflow, and then applying the mentioned logic.

In most cases it's more convenient to write the model from upstream like TensorFlow or PyTorch. The converter should do the best job and you won't be worried about too many ONNX details. Therefore I would suggest you raise an issue in tf2onnx to get help from the converter team if you bump into any error during conversion.

> Even if there is clearly something wrong with this model, I could live with this as long as it worked. Unfortunately, I wanted to further convert this model from ONNX to TensorRT, and I received errors like:
[6] Invalid Node - next/model/c2_block_0_se_reduce/BiasAdd__712
Attribute not found: allowzero

So the model is runnable in ORT? Can it pass onnx.checker with full_check? If both yes, there might be some issues in the converter (ONNX to TensorRT). You could raise this issue in their repo to get assistance. According to the error message, it might be related to opset_version issue. Please note that only Reshape-14 (the model's opset_version should be >=14) supports allowzero attribute.

**Comment by michal-choinski** [comment]
@jcwchen thanks a lot, thanks to your comment I figured out that the last error was due to a mismatch in the onset versions between my model and TensorRT.

However one thing to point out is that in order to make my model work, I had to manually remove inputs from one subgraph (originally loaded from a file): `del then_body.input[:]`. It wasn't very intuitive and soon I will propose a PR to clarify that in the documentation.

**Comment by gyenesvi** [comment]
I also ran into this. Though leaving the inputs empty solves the problem of validation, it generates another one; namely, the inputs of the subgraph will not be listed! Is this by design? Sounds pretty counterintuitive. What's the reasoning behind this? @jcwchen could you explain? Or is it that it could be set somehow, just nobody knows how to do it properly and everybody leaves it empty?

I observed that exporting and if statement from PyTorch to ONNX also generates such a graph without inputs on subgraphs. This way some nodes in the graph will seem disconnected (for example when viewed in Netron). Tools that process ONNX could have trouble with this. For example ONNX simplifier seems to throw out part of such seemingly disconnected graphs. I believe this needs fixing by properly allowing the inputs of subgraphs to be enumerated (ideally the if operator should also list them as inputs to ease processing by tools).

**Comment by gramalingam** [comment]
I am not sure if I followed all of the discussion. But the sub-graphs used as the then and else branches have no inputs by design.

The subgraphs used as attributes of (control-flow) ops (like If, Loop, etc.) are allowed to refer to variables defined in the "outer scope". Hence, there is no need to pass in input-parameters to the then or else branch.

This is no different from an if-then-else statement in most programming languages. The variables used in the then or else branch may be defined in the outer scope.

**Comment by gyenesvi** [comment]
@gramalingam thanks for the reply. Though it may sound logical from a programming language perspective, I believe not so much from a computational graph perspective, which ONNX seems to adopt. That means that algorithms that rely on graph connectivity will break down on such control flow operators, and need to handle them as special cases. The number of such control flow operators may grow in the future, furthermore they need to be handled recursively; i.e. an if-branch body may contain a loop operator whose body actually uses a tensor from the outer scope where the branch is. This makes the whole graph quite difficult to analyse.

And indeed, tools (mentioned above) do break down on loop operators as well, for example in the special case when there are no loop carried dependencies, and the trip count is constant (for example looping through the batch dimension), a graph can become disconnected at a loop operator, as the loop operator seems to have no non-constant inputs.

Any chance of revising the representation of such control flow operators in a future version?
