### ISSUE TITLE
Create onnx model with reshape node

### ISSUE THREAD

**Issue by hoaquocphan** [onnx/onnx#3425]
Hi All,

Currently, I create a simple ONNX model with reshape node with below code:

```
shape = [2,4]
shape2 = [2,4]

input_data = np.random.randn(*shape).astype(np.int64)

original_shape = [2, 3, 4]
input_data2 = np.random.random_sample(original_shape).astype(np.int64)

const_node = onnx.helper.make_node('Constant', inputs=[], outputs=['const_shape'],
                               value=onnx.helper.make_tensor(
                                   name='const_tensor',
                                   data_type=onnx.TensorProto.INT64,
                                   dims=input_data.shape,
                                   vals=input_data.flatten()))

node1 = onnx.helper.make_node('Identity', inputs=['add1'], outputs=['identity1'], name='identity_node1')
node2 = onnx.helper.make_node('Abs', inputs=['identity1'], outputs=['add2'], name='abs_node2')
node3 = onnx.helper.make_node('Identity', inputs=['add2'], outputs=['identity2'], name='identity_node2')
node4 = onnx.helper.make_node('Abs', inputs=['identity2'], outputs=['add3'], name='abs_node3')
node5 = onnx.helper.make_node('Identity', inputs=['add3'], outputs=['identity3'], name='identity_node3')
node6 = onnx.helper.make_node('Abs', inputs=['identity3'], outputs=['add4'], name='abs_node4')
node7 = onnx.helper.make_node('Identity', inputs=['add4'], outputs=['identity4'], name='identity_node4')
node8 = onnx.helper.make_node('Abs', inputs=['identity4'], outputs=['add5'], name='abs_node5')
node9 = onnx.helper.make_node('Add', inputs=['add5', 'identity3'], outputs=['add6'], name='add_node1')
node10 = onnx.helper.make_node('Identity', inputs=['add6'], outputs=['identity5'], name='identity_node5')
node11 = onnx.helper.make_node('Abs', inputs=['identity5'], outputs=['add7'], name='abs_node6')
node12 = onnx.helper.make_node('Reshape', inputs=['add7', 'const_shape'], outputs=['reshape'])

graph = onnx.helper.make_graph([const_node, node1, node2, node3, node4, node5, node6, node7, node8, node9, node10, node11, node12], 'test_graph',
                    [onnx.helper.make_tensor_value_info('add1', onnx.TensorProto.FLOAT, shape)],
                    [onnx.helper.make_tensor_value_info('reshape', onnx.TensorProto.FLOAT, shape2)])

model = onnx.helper.make_model(graph, producer_name='ngraph ONNX Importer')

onnx.save(model, 'model.onnx')

model_path = 'model.onnx'
session = onnxruntime.InferenceSession(model_path, None)
input_name1 = session.get_inputs()[0].name

a = np.random.rand(*shape).astype("float32")

print(a)
raw_result = session.run(None, {input_name1: a})

output_data = np.array(raw_result[0])
print(output_data)
```

the error log as below:

```
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from model.onnx failed:Node () Op (Reshape) [ShapeInferenceError] Invalid position of 0
```
I have refer the sample code https://www.programcreek.com/python/example/122583/onnx.helper.make_node to create onnx model with reshape node, but I still get error.

So could anyone show me the way to create onnx model with reshape node?

**Comment by jcwchen** [comment]
Hi @hoaquocphan,
This is not a valid reshape operator because it cannot be correctly shape inferred. This error happens here: https://github.com/onnx/onnx/blob/ea8e57a71e01d1e70b188465c028eb3c6c6cc118/onnx/defs/tensor/defs.cc#L217 Which shape did you want to reshape? Your original shape is [2, 4], but your target shape is [[0, 0, 0,, 0], [1, -1, 0, -1]] (randomly generated), which is not a valid target shape for your input...

Regarding to how to create a valid reshape node, you can check examples here:
https://github.com/onnx/onnx/blob/master/onnx/backend/test/case/node/reshape.py

**Comment by hoaquocphan** [comment]
Hi @jcwchen 

I already tried your solutions as below snippet code:

```
original_shape = [2, 3, 4]
data = np.random.random_sample(original_shape).astype(np.float32)
shape=np.array([4, 2, 3], dtype=np.int64)
node = onnx.helper.make_node('Reshape', inputs=['data', 'shape'], outputs=['reshaped'])
graph = onnx.helper.make_graph([node], 'test_graph',
                    [onnx.helper.make_tensor_value_info('data', onnx.TensorProto.FLOAT, original_shape)],
                    [onnx.helper.make_tensor_value_info('reshaped', onnx.TensorProto.FLOAT, shape)])
model = onnx.helper.make_model(graph, producer_name='ngraph ONNX Importer')
onnx.save(model, 'model.onnx')
model_path = 'model.onnx'
session = onnxruntime.InferenceSession(model_path, None)
input_name1 = session.get_inputs()[0].name
```

and got the error log as below:
```
    [onnx.helper.make_tensor_value_info('reshaped', onnx.TensorProto.FLOAT, shape)])
  File "/home/hoaphan/.local/lib/python3.6/site-packages/onnx/helper.py", line 351, in make_tensor_value_info
    'Needs to of integer_types or text_type.'.format(d))
ValueError: Invalid item in shape: 4.0. Needs to of integer_types or text_type.
```

so, could you copy the above code and give me a help?
thank you very much!

**Comment by jcwchen** [comment]
Change your `shape` into `shape = [4, 2, 3]`. `onnx.helper.make_tensor_value_info` cannot take `numpy.array`. Thanks.

**Comment by hoaquocphan** [comment]
Hi @jcwchen 

I have already used "shape = [4, 2, 3]"
but it have the error as below:

```
Traceback (most recent call last):
  File "create_model.py", line 16, in <module>
    session = onnxruntime.InferenceSession(model_path, None)
  File "/home/hoaphan/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 280, in __init__
    self._create_inference_session(providers, provider_options)
  File "/home/hoaphan/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 307, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from model.onnx failed:This is an invalid model. Node () input arg (shape) does not have type information set by parent node.
```

that is reason I replace "shape = [4, 2, 3]" by  "shape=np.array([4, 2, 3], dtype=np.int64)"
So could you try the snippet of my code and see the error?

**Comment by jcwchen** [comment]
Don't forget to include shape as your input:
```
graph = onnx.helper.make_graph([node], 'test_graph',
                    [onnx.helper.make_tensor_value_info('data', onnx.TensorProto.FLOAT, original_shape), onnx.helper.make_tensor_value_info('shape', onnx.TensorProto.INT64, shape)],
                    [onnx.helper.make_tensor_value_info('reshaped', onnx.TensorProto.FLOAT, shape)])
```

**Comment by hoaquocphan** [comment]
Hi @jcwchen 

Thank you for your support.
I can create the simple model with reshape node and it can run successfully.
I also have 2 questions need support from you:

1/ Please see my below snippet code

```
original_shape = [2, 3, 4]
shape_of_shape=[3,]
new_shape=[1, 1, 24]
node = onnx.helper.make_node('Reshape', inputs=['data', 'shape'], outputs=['reshaped'])
graph = onnx.helper.make_graph([node], 'test_graph',
                    [onnx.helper.make_tensor_value_info('data', onnx.TensorProto.FLOAT, original_shape), 
                    onnx.helper.make_tensor_value_info('shape', onnx.TensorProto.INT64, shape_of_shape)],
                    [onnx.helper.make_tensor_value_info('reshaped', onnx.TensorProto.FLOAT, new_shape)])
model = onnx.helper.make_model(graph, producer_name='ngraph ONNX Importer')
onnx.save(model, 'model.onnx')
model_path = 'model.onnx'
session = onnxruntime.InferenceSession(model_path, None)
input_name1 = session.get_inputs()[0].name
input_name2 = session.get_inputs()[1].name
data = np.random.random_sample(original_shape).astype(np.float32)
data_shape = np.array([4, 2, 3], dtype=np.int64)
raw_result = session.run(None, {input_name1: data, input_name2: data_shape})
output_data = np.array(raw_result[0])
print("data:")
print(data)
print("output data:")
print(output_data)
```

You can see that I can create the model with output shape [1, 1, 24] is: **new_shape=[1, 1, 24]**
the model will define output of **reshaped** node is [1, 1, 24]

But when I feed the model with output shape  [4, 2, 3]: **data_shape = np.array([4, 2, 3], dtype=np.int64)**
The model create output with shape  [4, 2, 3]

this mean, the output shape define in  **[onnx.helper.make_tensor_value_info('reshaped', onnx.TensorProto.FLOAT, new_shape)])** doesn't impact to the output shape of model.
So, why we need to define the **new_shape=[1, 1, 24]** when create the model?

2/ Please get below models from my git repo: https://github.com/hoaquocphan/shared_files.git

> my_model.onnx
> mobilenetv2-1.0.onnx

You can see that the reshape node in **my_model.onnx** (created by above code snippet) have 2 inputs
but the reshape node in **mobilenetv2-1.0.onnx** model have only one input (the reshape_attr_tensor421  input is not output of any other node)

So How to create the model have reshape node as **mobilenetv2-1.0.onnx**?

**Comment by jcwchen** [comment]
Hi @hoaquocphan,
1/ Basically the shape of data_shape (shape for Reshape op) needs to be same as the shape of output tensor. Thus, in your case data_shape needs to be [1, 1, 24] as well.

2/ Actually I don't see these 2 models in your repo, but I think you can recreate the reshape node with update inputs (data and shape) and add this node into the original graph (or assign it to your original node).

**Comment by hoaquocphan** [comment]
Hi @jcwchen 

2/ i'm so sorry, I forgot got push the latest commit to git repo.
I just push latest commit.
could you check and give me comment?

**Comment by hoaquocphan** [comment]
Hi @jcwchen 

I can create the reshape node with fix shape input in the model.
