### ISSUE TITLE
Pip install onnx failed 

### ISSUE THREAD

**Issue by WeichenXu123** [onnx/onnx#3570]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug
When install onnx by:
```
sudo apt-get install protobuf-compiler libprotoc-dev
pip install git+https://github.com/onnx/onnx.git
```
get error:
```
  /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(arena.o): relocation R_X86_64_TPOFF32 against hidden symbol `_ZN6google8protobuf8internal9ArenaImpl13thread_cache_E' can not be used when making a shared object
  /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(common.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
```

Error log link (in mlflow CI): https://github.com/mlflow/mlflow/pull/4545/checks?check_run_id=3026228796#step:9:303

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Ubuntu 20.04.2 LTS
- ONNX version (*e.g. 1.7*):  github master version
- Python version: CPython (3.6.13)
- GCC/Compiler version (if compiling from source): The C compiler identification is GNU 9.3.0, The CXX compiler identification is GNU 9.3.0
- CMake version: 3.20.5
- Protobuf version: 3.17.3, libprotobuf.a;-lpthread (version "3.6.1")
- Visual Studio version (if applicable):

### Reproduction instructions
- Describe the code to reproduce the behavior.
Bash code 
```
sudo apt-get install protobuf-compiler libprotoc-dev
pip install git+https://github.com/onnx/onnx.git
```
- Attach the ONNX model to the issue (where applicable)

### Notes

Any additional information

**Comment by WeichenXu123** [comment]
<details>
<summary>Error log details</summary>
```bash
sudo apt-get install protobuf-compiler libprotoc-dev
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libprotobuf-dev libprotobuf-lite17 libprotoc17
The following NEW packages will be installed:
  libprotobuf-dev libprotobuf-lite17 libprotoc-dev libprotoc17
  protobuf-compiler
0 upgraded, 5 newly installed, 0 to remove and 13 not upgraded.
Need to get 2754 kB of archives.
After this operation, 19.9 MB of additional disk space will be used.
Get:1 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 libprotobuf-lite17 amd64 3.6.1.3-2ubuntu5 [132 kB]
Get:2 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 libprotoc17 amd64 3.6.1.3-2ubuntu5 [646 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 libprotobuf-dev amd64 3.6.1.3-2ubuntu5 [1155 kB]
Get:4 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 libprotoc-dev amd64 3.6.1.3-2ubuntu5 [793 kB]
Get:5 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 protobuf-compiler amd64 3.6.1.3-2ubuntu5 [27.6 kB]
Fetched 2754 kB in 0s (57.2 MB/s)
Selecting previously unselected package libprotobuf-lite17:amd64.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 232863 files and directories currently installed.)
Preparing to unpack .../libprotobuf-lite17_3.6.1.3-2ubuntu5_amd64.deb ...
Unpacking libprotobuf-lite17:amd64 (3.6.1.3-2ubuntu5) ...
Selecting previously unselected package libprotoc17:amd64.
Preparing to unpack .../libprotoc17_3.6.1.3-2ubuntu5_amd64.deb ...
Unpacking libprotoc17:amd64 (3.6.1.3-2ubuntu5) ...
Selecting previously unselected package libprotobuf-dev:amd64.
Preparing to unpack .../libprotobuf-dev_3.6.1.3-2ubuntu5_amd64.deb ...
Unpacking libprotobuf-dev:amd64 (3.6.1.3-2ubuntu5) ...
Selecting previously unselected package libprotoc-dev:amd64.
Preparing to unpack .../libprotoc-dev_3.6.1.3-2ubuntu5_amd64.deb ...
Unpacking libprotoc-dev:amd64 (3.6.1.3-2ubuntu5) ...
Selecting previously unselected package protobuf-compiler.
Preparing to unpack .../protobuf-compiler_3.6.1.3-2ubuntu5_amd64.deb ...
Unpacking protobuf-compiler (3.6.1.3-2ubuntu5) ...
Setting up libprotoc17:amd64 (3.6.1.3-2ubuntu5) ...
Setting up protobuf-compiler (3.6.1.3-2ubuntu5) ...
Setting up libprotobuf-lite17:amd64 (3.6.1.3-2ubuntu5) ...
Setting up libprotobuf-dev:amd64 (3.6.1.3-2ubuntu5) ...
Setting up libprotoc-dev:amd64 (3.6.1.3-2ubuntu5) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
+ export CMAKE_ARGS=-DCMAKE_POSITION_INDEPENDENT_CODE=ON
+ CMAKE_ARGS=-DCMAKE_POSITION_INDEPENDENT_CODE=ON
+ pip install git+https://github.com/onnx/onnx.git
Collecting git+https://github.com/onnx/onnx.git
  Cloning https://github.com/onnx/onnx.git to /tmp/pip-req-build-wk2vsoa4
  Running command git clone -q https://github.com/onnx/onnx.git /tmp/pip-req-build-wk2vsoa4
  Running command git submodule update --init --recursive -q
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Requirement already satisfied: six in /opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages (from onnx==1.9.0) (1.16.0)
Requirement already satisfied: numpy>=1.16.6 in /opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages (from onnx==1.9.0) (1.19.5)
Requirement already satisfied: protobuf in /opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages (from onnx==1.9.0) (3.17.3)
Requirement already satisfied: typing-extensions>=3.6.2.1 in /opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages (from onnx==1.9.0) (3.10.0.0)
Building wheels for collected packages: onnx
  Building wheel for onnx (PEP 517): started
  Building wheel for onnx (PEP 517): still running...
  Building wheel for onnx (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /opt/hostedtoolcache/Python/3.6.13/x64/bin/python /opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp7k6vzqwj
       cwd: /tmp/pip-req-build-wk2vsoa4
  Complete output (235 lines):
  running bdist_wheel
  running build
  running build_py
  running create_version
  running cmake_build
  Extra cmake args: ['-DCMAKE_POSITION_INDEPENDENT_CODE=ON']
  Using cmake args: ['/usr/local/bin/cmake', '-DPYTHON_INCLUDE_DIR=/opt/hostedtoolcache/Python/3.6.13/x64/include/python3.6m', '-DPYTHON_EXECUTABLE=/opt/hostedtoolcache/Python/3.6.13/x64/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-36m-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '-DCMAKE_POSITION_INDEPENDENT_CODE=ON', '/tmp/pip-req-build-wk2vsoa4']
Failed to build onnx
  -- The C compiler identification is GNU 9.3.0
  -- The CXX compiler identification is GNU 9.3.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: /opt/hostedtoolcache/Python/3.6.13/x64/bin/python (found version "3.6.13")
  -- Found PythonLibs: /opt/hostedtoolcache/Python/3.6.13/x64/lib/libpython3.6m.so (found version "3.6.13")
  -- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.a;-lpthread (found version "3.6.1")
  Generated: /tmp/pip-req-build-wk2vsoa4/.setuptools-cmake-build/onnx/onnx-ml.proto
  Generated: /tmp/pip-req-build-wk2vsoa4/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
  Generated: /tmp/pip-req-build-wk2vsoa4/.setuptools-cmake-build/onnx/onnx-data.proto
  CMake Warning at CMakeLists.txt:450 (find_package):
    By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "pybind11",
    but CMake did not find one.
  
    Could not find a package configuration file provided by "pybind11"
    (requested version 2.2) with any of the following names:
  
      pybind11Config.cmake
      pybind11-config.cmake
  
    Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
    "pybind11_DIR" to a directory containing one of the above files.  If
    "pybind11" provides a separate development package or SDK, be sure it has
    been installed.
  
  
  --
  -- ******** Summary ********
  --   CMake version             : 3.20.5
  --   CMake command             : /usr/local/bin/cmake
  --   System                    : Linux
  --   C++ compiler              : /usr/bin/c++
  --   C++ compiler version      : 9.3.0
  --   CXX flags                 :  -Wnon-virtual-dtor
  --   Build type                : Release
  --   Compile definitions       :
  --   CMAKE_PREFIX_PATH         :
  --   CMAKE_INSTALL_PREFIX      : /usr/local
  --   CMAKE_MODULE_PATH         :
  --
  --   ONNX version              : 1.9.0
  --   ONNX NAMESPACE            : onnx
  --   ONNX_USE_LITE_PROTO       : OFF
  --   USE_PROTOBUF_SHARED_LIBS  : OFF
  --   Protobuf_USE_STATIC_LIBS  : ON
  --   ONNX_DISABLE_EXCEPTIONS   : OFF
  --   ONNX_WERROR               : OFF
  --   ONNX_BUILD_TESTS          : OFF
  --   ONNX_BUILD_BENCHMARKS     : OFF
  --   ONNXIFI_DUMMY_BACKEND     : OFF
  --   ONNXIFI_ENABLE_EXT        : OFF
  --
  --   Protobuf compiler         : /usr/bin/protoc
  --   Protobuf includes         : /usr/include
  --   Protobuf libraries        : /usr/lib/x86_64-linux-gnu/libprotobuf.a;-lpthread
  --   BUILD_ONNX_PYTHON         : ON
  --     Python version        :
  --     Python executable     : /opt/hostedtoolcache/Python/3.6.13/x64/bin/python
  --     Python includes       : /opt/hostedtoolcache/Python/3.6.13/x64/include/python3.6m
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-req-build-wk2vsoa4/.setuptools-cmake-build
  [  1%] Building C object CMakeFiles/onnxifi_loader.dir/onnx/onnxifi_loader.c.o
  [  2%] Building C object CMakeFiles/onnxifi_dummy.dir/onnx/onnxifi_dummy.c.o
  /tmp/pip-req-build-wk2vsoa4/onnx/onnxifi_dummy.c: In function ‘onnxGetExtensionFunctionAddress’:
  /tmp/pip-req-build-wk2vsoa4/onnx/onnxifi_dummy.c:177:21: warning: assignment to ‘onnxExtensionFunctionPointer’ {aka ‘int (*)(void)’} from incompatible pointer type ‘onnxStatus (*)(void *, const char *, onnxStatus (**)(void))’ {aka ‘int (*)(void *, const char *, int (**)(void))’} [-Wincompatible-pointer-types]
    177 |           *function = &onnxGetExtensionFunctionAddress;
        |                     ^
  /tmp/pip-req-build-wk2vsoa4/onnx/onnxifi_dummy.c:180:21: warning: assignment to ‘onnxExtensionFunctionPointer’ {aka ‘int (*)(void)’} from incompatible pointer type ‘onnxStatus (*)(void *, uint32_t,  const onnxTensorDescriptorV1 *, uint32_t,  const onnxTensorDescriptorV1 *, onnxMemoryFenceV1 *)’ {aka ‘int (*)(void *, unsigned int,  const struct onnxTensorDescriptorV1 *, unsigned int,  const struct onnxTensorDescriptorV1 *, struct onnxMemoryFenceV1 *)’} [-Wincompatible-pointer-types]
    180 |           *function = &onnxSetIOAndRunGraph;
        |                     ^
  [  4%] Linking C static library libonnxifi_loader.a
  [  5%] Linking C shared library libonnxifi_dummy.so
  [  5%] Built target onnxifi_dummy
  [  5%] Built target onnxifi_loader
  [  7%] Running gen_proto.py on onnx/onnx.in.proto
  [  8%] Building C object CMakeFiles/onnxifi_wrapper.dir/onnx/onnxifi_wrapper.c.o
  Processing /tmp/pip-req-build-wk2vsoa4/onnx/onnx.in.proto
  Writing /tmp/pip-req-build-wk2vsoa4/.setuptools-cmake-build/onnx/onnx-ml.proto
  Writing /tmp/pip-req-build-wk2vsoa4/.setuptools-cmake-build/onnx/onnx-ml.proto3
  generating /tmp/pip-req-build-wk2vsoa4/.setuptools-cmake-build/onnx/onnx_pb.py
  [ 10%] Running C++ protocol buffer compiler on /tmp/pip-req-build-wk2vsoa4/.setuptools-cmake-build/onnx/onnx-ml.proto
  Writing mypy to onnx/onnx_ml_pb2.pyi
  [ 10%] Built target gen_onnx_proto
  [ 11%] Running gen_proto.py on onnx/onnx-operators.in.proto
  Processing /tmp/pip-req-build-wk2vsoa4/onnx/onnx-operators.in.proto
  Writing /tmp/pip-req-build-wk2vsoa4/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
  Writing /tmp/pip-req-build-wk2vsoa4/.setuptools-cmake-build/onnx/onnx-operators-ml.proto3
  generating /tmp/pip-req-build-wk2vsoa4/.setuptools-cmake-build/onnx/onnx_operators_pb.py
  [ 13%] Running gen_proto.py on onnx/onnx-data.in.proto
  [ 14%] Linking C shared module libonnxifi.so
  [ 14%] Built target onnxifi_wrapper
  [ 16%] Running C++ protocol buffer compiler on /tmp/pip-req-build-wk2vsoa4/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
  Processing /tmp/pip-req-build-wk2vsoa4/onnx/onnx-data.in.proto
  Writing /tmp/pip-req-build-wk2vsoa4/.setuptools-cmake-build/onnx/onnx-data.proto
  Writing /tmp/pip-req-build-wk2vsoa4/.setuptools-cmake-build/onnx/onnx-data.proto3
  generating /tmp/pip-req-build-wk2vsoa4/.setuptools-cmake-build/onnx/onnx_data_pb.py
  [ 17%] Running C++ protocol buffer compiler on /tmp/pip-req-build-wk2vsoa4/.setuptools-cmake-build/onnx/onnx-data.proto
  Writing mypy to onnx/onnx_operators_ml_pb2.pyi
  Writing mypy to onnx/onnx_data_pb2.pyi
  [ 19%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-ml.pb.cc.o
  [ 20%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-operators-ml.pb.cc.o
  [ 22%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-data.pb.cc.o
  [ 23%] Linking CXX static library libonnx_proto.a
  [ 26%] Built target onnx_proto
  [ 28%] Building CXX object CMakeFiles/onnx.dir/onnx/checker.cc.o
  [ 29%] Building CXX object CMakeFiles/onnx.dir/onnx/common/assertions.cc.o
  [ 31%] Building CXX object CMakeFiles/onnx.dir/onnx/common/interned_strings.cc.o
  [ 32%] Building CXX object CMakeFiles/onnx.dir/onnx/common/ir_pb_converter.cc.o
  [ 34%] Building CXX object CMakeFiles/onnx.dir/onnx/common/model_helpers.cc.o
  [ 35%] Building CXX object CMakeFiles/onnx.dir/onnx/common/path.cc.o
  [ 37%] Building CXX object CMakeFiles/onnx.dir/onnx/common/status.cc.o
  [ 38%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/attr_proto_util.cc.o
  [ 40%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/controlflow/defs.cc.o
  [ 41%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/controlflow/old.cc.o
  [ 43%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/data_type_utils.cc.o
  [ 44%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/function.cc.o
  [ 46%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/generator/defs.cc.o
  [ 47%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/generator/old.cc.o
  [ 49%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/logical/defs.cc.o
  [ 50%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/logical/old.cc.o
  [ 52%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/math/defs.cc.o
  [ 53%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/math/old.cc.o
  [ 55%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/nn/defs.cc.o
  [ 56%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/nn/old.cc.o
  [ 58%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/object_detection/defs.cc.o
  [ 59%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/object_detection/old.cc.o
  [ 61%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/optional/defs.cc.o
  [ 62%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/parser.cc.o
  /tmp/pip-req-build-wk2vsoa4/onnx/defs/parser.cc: In member function ‘onnx::Common::Status onnx::OnnxParser::Parse(onnx::ModelProto&)’:
  /tmp/pip-req-build-wk2vsoa4/onnx/defs/parser.cc:337:11: warning: this statement may fall through [-Wimplicit-fallthrough=]
    337 |           }
        |           ^
  /tmp/pip-req-build-wk2vsoa4/onnx/defs/parser.cc:339:9: note: here
    339 |         case KeyWordMap::KeyWord::PRODUCER_NAME:
        |         ^~~~
  [ 64%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/printer.cc.o
  [ 65%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/quantization/defs.cc.o
  [ 67%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/quantization/old.cc.o
  [ 68%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/reduction/defs.cc.o
  [ 70%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/reduction/old.cc.o
  [ 71%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/rnn/defs.cc.o
  [ 73%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/rnn/old.cc.o
  [ 74%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/schema.cc.o
  [ 76%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/sequence/defs.cc.o
  [ 77%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/shape_inference.cc.o
  [ 79%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor/defs.cc.o
  [ 80%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor/old.cc.o
  [ 82%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor/utils.cc.o
  [ 83%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor_proto_util.cc.o
  [ 85%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor_util.cc.o
  [ 86%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/traditionalml/defs.cc.o
  [ 88%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/traditionalml/old.cc.o
  [ 89%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/training/defs.cc.o
  [ 91%] Building CXX object CMakeFiles/onnx.dir/onnx/onnxifi_utils.cc.o
  [ 92%] Building CXX object CMakeFiles/onnx.dir/onnx/shape_inference/implementation.cc.o
  [ 94%] Building CXX object CMakeFiles/onnx.dir/onnx/version_converter/convert.cc.o
  [ 95%] Building CXX object CMakeFiles/onnx.dir/onnx/version_converter/helper.cc.o
  [ 97%] Linking CXX static library libonnx.a
  [ 97%] Built target onnx
  [ 98%] Building CXX object CMakeFiles/onnx_cpp2py_export.dir/onnx/cpp2py_export.cc.o
  [100%] Linking CXX shared module onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so
  /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(arena.o): relocation R_X86_64_TPOFF32 against hidden symbol `_ZN6google8protobuf8internal9ArenaImpl13thread_cache_E' can not be used when making a shared object
  /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(common.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
  /usr/bin/ld: final link failed: bad value
  collect2: error: ld returned 1 exit status
  make[2]: *** [CMakeFiles/onnx_cpp2py_export.dir/build.make:101: onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so] Error 1
  make[1]: *** [CMakeFiles/Makefile2:279: CMakeFiles/onnx_cpp2py_export.dir/all] Error 2
  make: *** [Makefile:136: all] Error 2
  /tmp/pip-build-env-a_4u63el/overlay/lib/python3.6/site-packages/setuptools/dist.py:700: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
    % (opt, underscore_opt))
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
      main()
    File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 205, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-a_4u63el/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 222, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-a_4u63el/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-a_4u63el/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 259, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-a_4u63el/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 359, in <module>
      'backend-test-tools = onnx.backend.test.cmd_tools:main',
    File "/tmp/pip-build-env-a_4u63el/overlay/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-a_4u63el/overlay/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "setup.py", line 233, in run
      self.run_command('cmake_build')
    File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "setup.py", line 227, in run
      subprocess.check_call(build_args)
    File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '.', '--', '-j', '2']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for onnx
ERROR: Could not build wheels for onnx which use PEP 517 and cannot be installed directly
```
</details>

**Comment by jcwchen** [comment]
Hi @WeichenXu123,
The protobuf version from apt-get is quite old... Could you please statically install protobuf like [this](https://github.com/onnx/onnx/blob/31f0fd6103e231664d1cfd3b25264f672f5de960/.github/workflows/manylinux/entrypoint.sh#L18) and try to build ONNX again?

**Comment by snnn** [comment]
/usr/lib/x86_64-linux-gnu/libprotobuf.a you got from apt-get can't be used for building onnx python package. The error says it  can not be used when making a shared object, please recompile with -fPIC.  So, @jcwchen  and I suggest you build protobuf from source.

**Comment by harupy** [comment]
@jcwchen @snnn We were able to build a wheel for Linux by using the following command:

```
```

**Comment by lutzroeder** [comment]
@snnn are there plans to improve this experience?

For example,
* ONNX build scripts download the right Protocol Buffers binaries from GitHub releases to a local folder
* ONNX build scripts handle building the right Protocol Buffers on each platform

**Comment by snnn** [comment]
Google doesn't provide prebuilt binaries on GitHub releases for libprotobuf. They only provided one for protoc.  On Windows it's possible to get it from nuget.org. On Linux people can use apt-get/yum. But most ML python users are using conda. conda has a  C/C++ protobuf package but it was built in a different way and it is not something we want.

**Comment by snnn** [comment]
We definitely can have an extra script to help handle building the right Protocol Buffers binaries for each platform.  The script doesn't have to be part of build.py. I feel it could ease a lot of things.

**Comment by snnn** [comment]
@WeichenXu123 back to your original question, 

Instead of running
```
sudo apt-get install protobuf-compiler libprotoc-dev
```

You should run

```
 apt-get install libprotobuf-dev
```

**Comment by snnn** [comment]
Add a PR to address this: #3602

**Comment by lutzroeder** [comment]
> Google doesn't provide prebuilt binaries on GitHub releases for libprotobuf.

Do you have any insights why that is or if it is something that can be added?

**Comment by snnn** [comment]
Not much. People need a prebuilt protoc.exe for cross-compiling, I think that's the major reason of why it is provided. But if you need a static library to link with onnx, you'd better to compile it by your self with exactly the same compiler and build options which will be used for building onnx. There are infinity combinations of compiler vendor/compiler versions/build options. Google guys treat such things seriously. They don't want to provide something that is not a good fit. So they'd rather not doing it. But for EXEs, this is not a concern.

**Comment by Inquisitive-ME** [comment]
It fails to build for me on Ubuntu 22.04. But I ran `export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON"` and it built

**Comment by code-wangshuyi** [comment]
> @WeichenXu123 back to your original question,
> 
> Instead of running
> 
> ```
> sudo apt-get install protobuf-compiler libprotoc-dev
> ```
> 
> You should run
> 
> ```
>  apt-get install libprotobuf-dev protobuf-compiler
> ```
> 
> Then, most important
> 
> ```
> export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON"
> ```

Amazing !

**Comment by hustc12** [comment]
> @WeichenXu123 back to your original question,
> 
> Instead of running
> 
> ```
> sudo apt-get install protobuf-compiler libprotoc-dev
> ```
> 
> You should run
> 
> ```
>  apt-get install libprotobuf-dev protobuf-compiler
> ```
> 
> Then, most important
> 
> ```
> export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON"
> ```

Thanks! It works!
