### ISSUE TITLE
Bug in Fp16 converstion of GPT2-XL 

### ISSUE THREAD

**Issue by dimaischenko** [onnx/onnx#3588]
# Bug Report

### Is the issue related to model conversion?

Yes

### Describe the bug
Get error while try to conert GPT2-XL to FP16 onnx

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/disk/projects/gpt/venv/lib/python3.6/site-packages/onnxruntime/transformers/convert_to_onnx.py", line 330, in <module>
    main()
  File "/mnt/disk/projects/gpt/venv/lib/python3.6/site-packages/onnxruntime/transformers/convert_to_onnx.py", line 236, in main
    args.use_external_data_format)
  File "/mnt/disk/projects/gpt/venv/lib/python3.6/site-packages/onnxruntime/transformers/gpt2_helper.py", line 357, in optimize_onnx
    m.convert_model_float32_to_float16(cast_input_output=False)
  File "/mnt/disk/projects/gpt/venv/lib/python3.6/site-packages/onnxruntime/transformers/onnx_model.py", line 503, in convert_model_float32_to_float16
    self.model = oc.float16.convert_float_to_float16(self.model, keep_io_types=cast_input_output)
  File "/mnt/disk/projects/gpt/venv/lib/python3.6/site-packages/onnxconverter_common/float16.py", line 130, in convert_float_to_float16
    model = func_infer_shape(model)
  File "/mnt/disk/projects/gpt/venv/lib/python3.6/site-packages/onnx/shape_inference.py", line 36, in infer_shapes
    model_str = model.SerializeToString()
ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 6602673518
```

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Linux Ubuntu 18.04
- ONNX version (*e.g. 1.7*):  1.9
- onnx==1.9.0 onnxconverter-common==1.8.1 onnxruntime==1.8.0 onnxruntime-gpu==1.8.0
- Python version: 3.5
- GCC/Compiler version (if compiling from source): install by pip
- CMake version: N/A
- Protobuf version: 3.14.0
- Visual Studio version (if applicable): N/A

### Reproduction instructions
- Describe the code to reproduce the behavior.

```
python -m onnxruntime.transformers.convert_to_onnx -m gpt2-xl --model_class GPT2LMHeadModel --output gpt2_xl_fp16 -p fp16 -o --use_gpu --use_external_data_format
```

### Expected behavior
I expect that conversion will be ok.

### Notes

I read previous issues and think that this bug was fixed in `1.7` and `1.8` onnxruntime versions. #3046

**Comment by jcwchen** [comment]
Hi @dimaischenko,
In ONNX, `shape_inference.infer_shapes` only supports <2GB python protobuf object and it's a protobuf limitation. To work around that, ONNX provides `shape_inference.infer_shapes_path` to load the model by the path to prevent loading the whole protobuf object.

Therefore, I think the code in onnxconverter-common [here](https://github.com/microsoft/onnxconverter-common/blob/b2215a038af3337ab6290ff30f18eaeb0e47c6c2/onnxconverter_common/float16.py#L119) can be improved by using `shape_inference.infer_shapes_path` instead of `shape_inference.infer_shapes` to prevent this issue.

**Comment by dimaischenko** [comment]
@jcwchen thanks! I'll try and write to this thread.
