### ISSUE TITLE
RuntimeError: Exporting the operator square to ONNX opset version 9 is not supported

### ISSUE THREAD

**Issue by emanuelgollob** [onnx/onnx#3589]
I am currently trying to export a stylegan2-ada-pytorch to ONNX opset version 9. 
Whenever I run:

torch.onnx.export(G_ema, args=(z, c), f="TextureGAN.onnx", export_params=True, opset_version=9, do_constant_folding=True, input_names=["z", "c"], output_names = ['Y'])

I get the error: RuntimeError: Exporting the operator square to ONNX opset version 9 is not supported
My setup: 64-bit Python 3.7 and PyTorch 1.7.1

My questions:
Is there a workaround for the square operator? 
And does anybody know if it is possible to convert stylegan2-ada-pytorch to ONNX with the currently supported operators in the first place?

Traceback:
Traceback (most recent call last):
  File "train.py", line 541, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "train.py", line 534, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "train.py", line 386, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "C:\Users\emanu\Downloads\stylegan2-ada-pytorch-main\stylegan2-ada-pytorch-main\training\training_loop.py", line 241, in training_loop
    torch.onnx.export(G_ema, args=(z, c), f="TextureGAN.onnx", export_params=True, opset_version=9, do_constant_folding=True, input_names=["z", "c"], output_names = ['Y'])
  File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\torch\onnx\__init__.py", line 230, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\torch\onnx\utils.py", line 91, in export
    use_external_data_format=use_external_data_format)
  File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\torch\onnx\utils.py", line 639, in _export
    dynamic_axes=dynamic_axes)
  File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\torch\onnx\utils.py", line 421, in _model_to_graph
    dynamic_axes=dynamic_axes, input_names=input_names)
  File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\torch\onnx\utils.py", line 203, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\torch\onnx\__init__.py", line 263, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\torch\onnx\utils.py", line 930, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\torch\onnx\utils.py", line 888, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\torch\onnx\symbolic_registry.py", line 111, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator square to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator.

**Comment by jcwchen** [comment]
Hi @emanuelgollob,
sqaure is not a supported pytorch op for conversion to ONNX. You can check the supported list here: https://pytorch.org/docs/stable/onnx.html#supported-operators. Please open an issue under PyTorch to request this op support from the converter team (torch.onnx.export). Thanks

**Comment by Wheest** [comment]
Hi there, I managed to make a fork of that which allows you to export [`stylegan2-ada-pytorch`](https://github.com/NVlabs/stylegan2-ada-pytorch) models to ONNX.  I'm unsure if it will work for opset 9, but I came across this issue while figuring out my own problem.

You can see [the fork and instructions here](https://github.com/Wheest/stylegan2-ada-pytorch).
