### ISSUE TITLE
Error when saving model with external data

### ISSUE THREAD

**Issue by yjydfnhc** [onnx/onnx#3596]
# Bug Report

### Describe the bug
For an in-memory onnx model loaded with load_external_data=False, when trying to save it with onnx.save(model, path), it will raise error because set_external_data() and save_external_data() will always check the existence of "raw_data" field.

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): win10
- ONNX version (*e.g. 1.7*):  1.9.0
- Python version: 3.8.0

### Reproduction instructions
- Example code:
```
import numpy as np
import onnx
from onnx import helper
from onnx import AttributeProto, TensorProto, GraphProto
import json
from google.protobuf.json_format import MessageToJson

#======== 1. create an onnx model

dtype = np.float32
x = np.random.randn(3, 5).astype(dtype)

data_w = np.random.randn(2, 5).astype(dtype)
w = helper.make_tensor(name = 'w', data_type = TensorProto.FLOAT, dims = data_w.shape, vals = data_w.flatten().astype(dtype).tobytes(), raw=True)

Z = helper.make_tensor_value_info('Z', TensorProto.FLOAT, [2, 3])

# Create node (NodeProto)
X = helper.make_node(
    'Constant',
    inputs=[],
    outputs=['X'],
    value=onnx.helper.make_tensor(
        name='const_tensor_x',
        data_type=onnx.TensorProto.FLOAT,
        dims=x.shape,
        vals=x.flatten().astype(float),
    ),
)
node_gemm = helper.make_node(
    'Gemm',                  # name
    ['w', 'X'], # inputs
    ['Z'],                  # outputs
    name = 'gemm1'
)
# Create the graph (GraphProto)
graph_def = helper.make_graph(
    [X, node_gemm],        # nodes
    'test-model',      # name
    [],  # inputs
    [Z],  # outputs
    initializer = [w],
)
model_def = helper.make_model(graph_def, producer_name='onnx-example')

# #======== 2. save an onnx model
model_path = '../outs/model.onnx'
# save model with separate data files
onnx.save_model(model_def, model_path
                , save_as_external_data=True
                , all_tensors_to_one_file=False
                , size_threshold=0)

#========= 3. for observe: convert model to json to find rawData
# (1) for model with data in one file
model_full = onnx.load(model_path)
onnx_json = json.loads(MessageToJson(model_full))
output_json = '../outs/model_full.json'
with open(output_json, 'w') as file:
    json.dump(onnx_json, file, indent=4)

# (2) for model with separate data
model_sep = onnx.load(model_path, load_external_data=False)
onnx_json = json.loads(MessageToJson(model_sep))
output_json = '../outs/model_sep.json'
with open(output_json, 'w') as file:
    json.dump(onnx_json, file, indent=4)

#======== 4. load and try save
# (1) load with data, then save: will success
model_full = onnx.load(model_path)
onnx.save(model_full, '../outs/model2_full.onnx')

# (2) load without data, then save: will fail
model_sep = onnx.load(model_path, load_external_data=False)
onnx.save(model_sep, '../outs/model2_sep.onnx', save_as_external_data=True)  # ValueError: raw_data field doesn't exist.
```
- Error1: 
Will raised the following error when checking tensor.HasField("raw_data") in external_data_helper.save_external_data():
```
Traceback (most recent call last):
  File "D:/myfiles/workspace/pythonTest/myTest/saved/issue2_save_model.py", line 76, in <module>
    onnx.save(model_sep, '../outs/model2_sep.onnx', save_as_external_data=True)  # ValueError: raw_data field doesn't exist.
  File "C:\Users\qingxialiu\AppData\Local\Programs\Python\Python38\lib\site-packages\onnx\__init__.py", line 201, in save_model
    proto = write_external_data_tensors(proto, basepath)
  File "C:\Users\qingxialiu\AppData\Local\Programs\Python\Python38\lib\site-packages\onnx\external_data_helper.py", line 262, in write_external_data_tensors
    save_external_data(tensor, filepath)
  File "C:\Users\qingxialiu\AppData\Local\Programs\Python\Python38\lib\site-packages\onnx\external_data_helper.py", line 166, in save_external_data
    raise ValueError("raw_data field doesn't exist.")
ValueError: raw_data field doesn't exist.
```
- Error 2: 
If comment out the code raised the above error, it will raised the following error when checking tensor.HasField("raw_data") in external_data_helper.set_external_data():
```
Traceback (most recent call last):
  File "D:/myfiles/workspace/pythonTest/myTest/saved/issue2_save_model.py", line 76, in <module>
    onnx.save(model_sep, '../outs/model2_sep.onnx', save_as_external_data=True)  # ValueError: raw_data field doesn't exist.
  File "C:\Users\qingxialiu\AppData\Local\Programs\Python\Python38\lib\site-packages\onnx\__init__.py", line 201, in save_model
    proto = write_external_data_tensors(proto, basepath)
  File "C:\Users\qingxialiu\AppData\Local\Programs\Python\Python38\lib\site-packages\onnx\external_data_helper.py", line 262, in write_external_data_tensors
    save_external_data(tensor, filepath)
  File "C:\Users\qingxialiu\AppData\Local\Programs\Python\Python38\lib\site-packages\onnx\external_data_helper.py", line 184, in save_external_data
    set_external_data(tensor, info.location, offset, data_file.tell() - offset)
  File "C:\Users\qingxialiu\AppData\Local\Programs\Python\Python38\lib\site-packages\onnx\external_data_helper.py", line 86, in set_external_data
    raise ValueError("Tensor " + tensor.name + "does not have raw_data field. Cannot set external data for this tensor.")
ValueError: Tensor wdoes not have raw_data field. Cannot set external data for this tensor.
```

### Expected behavior
For a model (e.g. model with large tensors) with external data that haven't been loaded into memory (therefore no  'raw_data' field), when trying to save this model with save_as_external_data=True, it is expected the external data of its tensors are not loaded into memory (e.g. 'raw_data' field) but directly copy the data files to the new model path.  And in this scenario, set_external_data() and save_external_data(), are expected to not check the existence of 'raw_data' field.

**Comment by jcwchen** [comment]
Please check the comment here: https://github.com/onnx/onnx/issues/3598#issuecomment-885949761. Thank you!

**Comment by jcwchen** [comment]
This issue should be covered by this PR: https://github.com/onnx/onnx/pull/3630. onnx.save won't throw an error for missing raw_data anymore. Close it now. Feel free to reopen it if you still have questions. Thank you!
