### ISSUE TITLE
ArrayRef length issue when export pytorch model to onnx

### ISSUE THREAD

**Issue by ZJG0** [onnx/onnx#3643]
Traceback (most recent call last):
  File "private_test.py", line 268, in <module>
    main()
  File "private_test.py", line 264, in main
    test(args, model)
  File "private_test.py", line 188, in test
    private_model = construct_private_model(input_size, model, args)
  File "private_test.py", line 178, in construct_private_model
    private_model = crypten.nn.from_pytorch(model_upd, dummy_input).encrypt(src=0)
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/crypten-0.1.0-py3.8.egg/crypten/nn/onnx_converter.py", line 45, in from_pytorch
    f = _from_pytorch_to_bytes(pytorch_model, dummy_input)
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/crypten-0.1.0-py3.8.egg/crypten/nn/onnx_converter.py", line 106, in _from_pytorch_to_bytes
    _export_pytorch_model(f, pytorch_model, dummy_input)
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/crypten-0.1.0-py3.8.egg/crypten/nn/onnx_converter.py", line 131, in _export_pytorch_model
    torch.onnx.export(pytorch_model, dummy_input, f, **kwargs)
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/torch/onnx/__init__.py", line 271, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/torch/onnx/utils.py", line 694, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/torch/onnx/utils.py", line 488, in _model_to_graph
    torch._C._jit_pass_onnx_assign_output_shape(graph, output_tensors, out_desc, _onnx_shape_inference)
RuntimeError: ArrayRef: invalid index Index = 1; Length = 1

**Comment by jcwchen** [comment]
Hi @ZJG0,
This error seems happened when using the converter (torch.onnx.export). I would suggest you rather raise this issue under PyTorch to get the best help from the converter team. Thanks!
