### ISSUE TITLE
Error exporting Pytorch model to ONNX

### ISSUE THREAD

**Issue by AditiDeepak15** [onnx/onnx#3705]
### Question
I am trying to convert a model from Pytorch to ONNX format and I am facing the following error during conversion. I have copied the error stack to this post. It would be great to have some suggestions regarding this - 

### Further information
Traceback (most recent call last):
  File "/code/demo-gen-onnx.py", line 78, in <module>
    make_animation(generator, cpu=opt.cpu)
  File "/code/demo-gen-onnx.py", line 67, in make_animation
    torch.onnx.export(generator.module, args,'first-order-model-generator.onnx',opset_version=11,export_params=True)
  File "/anaconda/lib/python3.9/site-packages/torch/onnx/__init__.py", line 275, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/anaconda/lib/python3.9/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/anaconda/lib/python3.9/site-packages/torch/onnx/utils.py", line 689, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/anaconda/lib/python3.9/site-packages/torch/onnx/utils.py", line 463, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/anaconda/lib/python3.9/site-packages/torch/onnx/utils.py", line 200, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/anaconda/lib/python3.9/site-packages/torch/onnx/__init__.py", line 313, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/anaconda/lib/python3.9/site-packages/torch/onnx/utils.py", line 990, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "/anaconda/lib/python3.9/site-packages/torch/onnx/utils.py", line 944, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/anaconda/lib/python3.9/site-packages/torch/onnx/symbolic_registry.py", line 116, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator inverse to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

Code information - 
demo-gen-onnx.py - Conversion script from Pytorch model to ONNX 
The generator model code, utilizes the torch.inverse() function for which the operator inverse in ONNX is not supported. 
The line goes as follows - 
normed_driving = torch.inverse(kp_driving['jacobian'])

Dependencies -
torch==1.9.0
torchvision==0.6.0
tqdm==4.24.0  
imageio==2.3.0
PyYAML==5.1
scikit-image==0.14.0
scikit-learn==0.19.2
pandas==0.23.4
python-dateutil==2.7.3
pytz==2018.5
scipy==1.1.0
matplotlib==2.2.2
numpy==1.15.0

**Comment by jcwchen** [comment]
Hi @AditiDeepak15,
As the error said, the conversion (Pytorch op to ONNX op) is not supported by the converter (torch.onnx.export). Please raise this issue on PyTorch repo to get help from the converter team. Thanks.
