### ISSUE TITLE
Please add support for python 3.10

### ISSUE THREAD

**Issue by snnn** [onnx/onnx#3723]
# Feature Request

### System information
ONNX version (you are using):
1.10.1

### What is the problem that this feature solves?
Please detail the discrepancy with our current functionality.
When I ran it with python 3.10 and this code:

```python
    reduce_min_node = onnx.helper.make_node('ReduceMin', [tensor], [tensor + '_ReduceMin'], reduce_min_name, keepdims=keepdims)
```

 I got the following error:
```
  File "/home/chasun/.local/lib/python3.10/site-packages/onnx/helper.py", line 115, in make_node
    node.attribute.extend(
  File "/home/chasun/.local/lib/python3.10/site-packages/google/protobuf/internal/containers.py", line 413, in extend
    for message in elem_seq:
  File "/home/chasun/.local/lib/python3.10/site-packages/onnx/helper.py", line 116, in <genexpr>
    make_attribute(key, value)
  File "/home/chasun/.local/lib/python3.10/site-packages/onnx/helper.py", line 364, in make_attribute
    is_iterable = isinstance(value, collections.Iterable)

AttributeError: module 'collections' has no attribute 'Iterable'
```

### Describe the alternatives you have considered

Do not use python 3.10

### Describe the feature
Why is this feature necessary? What does it accomplish?
To support new python versions

### Will this influence the current api?
If yes, how? 

No

### Feature Area
Which area in ONNX does this impact?  (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 

### Are you willing to contribute it (Y/N):
No. There has been a PR. #3106 

### Notes
Any additional information

**Comment by jcwchen** [comment]
Hi @snnn,
Thank you for catching this. I also have an existing PR covers it: https://github.com/onnx/onnx/pull/3674

**Comment by piti-diablotin** [comment]
Hi
 I also have trouble with python 3.10 and onnx 1.10.2 : 
```python
import onnx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/XXX/.local/lib/python3.10/site-packages/onnx/__init__.py", line 11, in <module>
    from onnx.external_data_helper import load_external_data_for_model, write_external_data_tensors, convert_model_to_external_data
  File "/home/XXX/.local/lib/python3.10/site-packages/onnx/external_data_helper.py", line 14, in <module>
    from .onnx_pb import TensorProto, ModelProto
  File "/home/XXX/.local/lib/python3.10/site-packages/onnx/onnx_pb.py", line 8, in <module>
    from .onnx_ml_pb2 import *  # noqa
  File "/home/XXX/.local/lib/python3.10/site-packages/onnx/onnx_ml_pb2.py", line 20, in <module>
    _VERSION = DESCRIPTOR.enum_types_by_name['Version']
AttributeError: 'NoneType' object has no attribute 'enum_types_by_name'
```
I'm not very familiar with onnx so I'm sorry if this is irrelevant.

**Comment by jcwchen** [comment]
Hi @piti-diablotin,
So did you build ONNX with Python 3.10 successfully on your own? I will try to repro it. What's your environment and protobuf version? Thanks!

**Comment by piti-diablotin** [comment]
Hi @jcwchen
I use Manjaro and I think I just got an update from 3.9 to 3.10. I then installed onnx with `pip install onnx`. 
Nothing special ...
What could it be ?
Thx

**Comment by jcwchen** [comment]
@piti-diablotin Thanks for the info. What's your protobuf version? You can check the version by:
```
protoc --version
```

**Comment by piti-diablotin** [comment]
@jcwchen 
Hi my protobuf version is `libprotoc 3.19.1` using your command line.
Cheers

**Comment by jcwchen** [comment]
With installed protobuf==3.16.0 and the latest numpy (1.22.0), I can build ONNX with Python 3.10 on Linux.

> my protobuf version is libprotoc 3.19.1 using your command line.

I can repro the same error (`AttributeError: 'NoneType' object has no attribute 'enum_types_by_name'`) if I build ONNX with protobuf==3.19.1 (protobuf source code) and test ONNX with protobuf==3.12.2 (Python protobuf).

@piti-diablotin what's your Python protobuf version? (You can check the version by `pip show protobuf`) If it is not 3.19.1, could you please try to install Python protobuf 3.19.1 by `pip install protobuf==3.19.1` and see whether it can resolve the error?

**Comment by piti-diablotin** [comment]
@jcwchen Thx now it works so there was a conflict of version I guess !
Problem solved :)
