### ISSUE TITLE
Cannot recreate a valid model from a validated reference model using onnx.helper

### ISSUE THREAD

**Issue by olivier-dl** [onnx/onnx#3866]
# Bug Report

### Describe the bug
I am unable to use onnx.helper to create a valid model (relative to the onnx.checker.check_model function) when using as reference an already validated model. 

I want to play with a valid pytorch exported model. However, simply recreating this model using its own nodes from its own graph with the help of the helper raises an error. I included in the code the pytorch model definition. It is a barebone resnet18 on cifar100.

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Ubuntu 16.04.7 LTS (GNU/Linux 4.15.0-041500-generic x86_64)
- ONNX version (*e.g. 1.7*): 1.10.2
- Python version: 3.7.7
- GCC/Compiler version (if compiling from source): [GCC 7.3.0] :: Anaconda, Inc. on linux
- CMake version: 3.5.1
- Protobuf version: 3.12.4

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
# pytorch model definition #

import torch
import torch.nn as nn
import torch.nn.functional as F


class BasicBlock(nn.Module):
    expansion = 1

    def __init__(self, in_planes, planes, stride=1):
        super(BasicBlock, self).__init__()
        self.conv1 = nn.Conv2d(
            in_planes, planes, kernel_size=3, stride=stride, padding=1, bias=False
        )
        self.bn1 = nn.BatchNorm2d(planes)
        self.conv2 = nn.Conv2d(
            planes, planes, kernel_size=3, stride=1, padding=1, bias=False
        )
        self.bn2 = nn.BatchNorm2d(planes)

        self.shortcut = nn.Sequential()
        if stride != 1 or in_planes != self.expansion * planes:
            self.shortcut = nn.Sequential(
                nn.Conv2d(
                    in_planes,
                    self.expansion * planes,
                    kernel_size=1,
                    stride=stride,
                    bias=False,
                ),
                nn.BatchNorm2d(self.expansion * planes),
            )

    def forward(self, x):
        out = F.relu(self.bn1(self.conv1(x)))
        out = self.bn2(self.conv2(out))
        out += self.shortcut(x)
        out = F.relu(out)
        return out


class ResNet(nn.Module):
    def __init__(self, block, num_blocks, num_classes=100):
        super(ResNet, self).__init__()
        self.in_planes = 64

        self.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)
        self.bn1 = nn.BatchNorm2d(64)
        self.layer1 = self._make_layer(block, 64, num_blocks[0], stride=1)
        self.layer2 = self._make_layer(block, 128, num_blocks[1], stride=2)
        self.layer3 = self._make_layer(block, 256, num_blocks[2], stride=2)
        self.layer4 = self._make_layer(block, 512, num_blocks[3], stride=2)
        self.linear = nn.Linear(512 * block.expansion, num_classes)

    def _make_layer(self, block, planes, num_blocks, stride):
        strides = [stride] + [1] * (num_blocks - 1)
        layers = []
        for stride in strides:
            layers.append(block(self.in_planes, planes, stride))
            self.in_planes = planes * block.expansion
        return nn.Sequential(*layers)

    def forward(self, x):
        out = F.relu(self.bn1(self.conv1(x)))
        out = self.layer1(out)
        out = self.layer2(out)
        out = self.layer3(out)
        out = self.layer4(out)
        out = F.avg_pool2d(out, 4)
        out = out.view(out.size(0), -1)
        out = self.linear(out)
        return out

resnet18 = ResNet(BasicBlock, [2, 2, 2, 2]).cpu().eval()
torch.onnx.export(resnet18, torch.randn(1, 3, 32, 32), 'ref.onnx')

# onnx part #

import onnx
from onnx import helper

ref = onnx.load('ref.onnx')
onnx.checker.check_model(ref) # this does not crash

graph = ref.graph

new_nodes = []
for n graph.node:
    attr=n.attribute
    new_node = helper.make_node(
        op_type=n.op_type,
        inputs=n.input,
        outputs=n.output,
        name=n.name,
        doc_string=n.doc_string,
        domain=n.domain,
    )
    new_node.attribute.MergeFrom(attr)

    new_nodes.append(new_node)


new_graph = helper.make_graph(
    nodes=new_nodes,
    name=graph.name,
    inputs=graph.input,
    outputs=graph.output,
    initializer=graph.initializer,
    sparse_initializer=graph.sparse_initializer,
    value_info=graph.value_info,
)

model_def = helper.make_model(new_graph, producer_name='onnx-helpers')

onnx.checker.check_model(model_def) # crashes
print('The model is checked!')
```
Error:
```
Traceback (most recent call last):
  File "onnxbug.py", line 117, in <module>
    onnx.checker.check_model(model_def)
  File "/home/olivier/.conda/envs/ga/lib/python3.7/site-packages/onnx/checker.py", line 106, in check_model
    C.check_model(protobuf_string)
onnx.onnx_cpp2py_export.checker.ValidationError: Node (Pad_45) has input size 1 not in range [min=2, max=3].

==> Context: Bad node spec for node. Name: Pad_45 OpType: Pad
```

### Expected behavior

I expect the helpers to be able to create a valid model from the exact same information of a valid model

### Notes

Sorry if this is not a bug and I am doing something wrong.

**Comment by olivier-dl** [comment]
finally found it, I was missing the opset_imports in

 `model_def = helper.make_model(new_graph, opset_imports=ref.opset_import, producer_name='onnx-helpers')`

Looks like the maker and pytorch when not exporting the same opset version.
