### ISSUE TITLE
 onnx model from 10 to 8 on jetson xavier

### ISSUE THREAD

**Issue by dsnsabari** [onnx/onnx#3886]
When  i tried to downgrade the sdd mobilenet v3 onnx model from 10 to 8.  It was not working , i am getting the below error.
This onnx  model was created from TF frozen graph.

Jetpack version --> 4.6

```
   converted_model = version_converter.convert_version(onnx_model, 8)
  File "/home/rachel/.local/lib/python3.6/site-packages/onnx/version_converter.py", line 174, in convert_version
    converted_model_str = C.convert_version(model_str, target_version)
IndexError: Input Preprocessor/mul/x:0 is undefined!
```

**Comment by jcwchen** [comment]
Hi @dsnsabari,
If possible, could you please provide the ONNX model for me to repro this error? Thank you.

**Comment by dsnsabari** [comment]
@jcwchen  I tried the build the ONNX from source. It was not working. I am getting the below error.


```
ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-exue87ie/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://pypi.ngc.nvidia.com --trusted-host pypi.ngc.nvidia.com -- setuptools wheel protobuf
       cwd: None
  Complete output (31 lines):
  Traceback (most recent call last):
    File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.6/dist-packages/pip/__main__.py", line 29, in <module>
      from pip._internal.cli.main import main as _main
    File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/main.py", line 9, in <module>
      from pip._internal.cli.autocompletion import autocomplete
    File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
      from pip._internal.cli.main_parser import create_main_parser
    File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
      from pip._internal.cli import cmdoptions
    File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
      from pip._internal.cli.parser import ConfigOptionParser
    File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/parser.py", line 12, in <module>
      from pip._internal.configuration import Configuration, ConfigurationError
    File "/usr/local/lib/python3.6/dist-packages/pip/_internal/configuration.py", line 26, in <module>
      from pip._internal.utils.logging import getLogger
    File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/logging.py", line 13, in <module>
      from pip._internal.utils.misc import ensure_dir
    File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/misc.py", line 36, in <module>
      from pip._vendor.tenacity import retry, stop_after_delay, wait_fixed
    File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/tenacity/__init__.py", line 26, in <module>
      from concurrent import futures
    File "/usr/local/lib/python3.6/dist-packages/concurrent/futures/__init__.py", line 8, in <module>
      from concurrent.futures._base import (FIRST_COMPLETED,
    File "/usr/local/lib/python3.6/dist-packages/concurrent/futures/_base.py", line 357
      raise type(self._exception), self._exception, self._traceback
                                 ^
  SyntaxError: invalid syntax
  ----------------------------------------
WARNING: Discarding file:///home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0. Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-exue87ie/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://pypi.ngc.nvidia.com --trusted-host pypi.ngc.nvidia.com -- setuptools wheel protobuf Check the logs for full command output.
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-exue87ie/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://pypi.ngc.nvidia.com --trusted-host pypi.ngc.nvidia.com -- setuptools wheel protobuf Check the logs for full command output.

```

**Comment by jcwchen** [comment]
FYI: I replied it in the right issue instead. Thanks!

**Comment by dsnsabari** [comment]
@jcwchen , could you share the ONNX support email id. I will share the ONNX model for reproducing the error.

**Comment by jcwchen** [comment]
> @jcwchen , could you share the ONNX support email id. I will share the ONNX model for reproducing the error.

How about joining ONNX slack group: https://slack.lfai.foundation/ and directly messaging me with the model there? Thanks

**Comment by dsnsabari** [comment]
@jcwchen okay. I will join the slack group.

**Comment by jcwchen** [comment]
Thank you for providing the model. I think it is due to a known IR gap issue for the version converter. Please check my comment here: https://github.com/onnx/onnx/issues/2873#issuecomment-917004554. Using the script add_input_from_initializer should help to resolve the issue. There will be a PR https://github.com/onnx/onnx/pull/3676 for fixing it as well.
