### ISSUE TITLE
NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from onnx/bert-base-cased/model.onnx failed:Load model onnx/bert-base-cased/model.onnx

### ISSUE THREAD

**Issue by danielbellhv** [onnx/onnx#3931]
Based on [SO post](https://stackoverflow.com/q/70652768/17840900).

Kernel: `conda_pytorch_p36`. I performed Restart & Run All, and refreshed file view in working directory.

I'm following along with this [code tutorial][1], the first Python code module.

**Update:** I need to have a `transformers.onnx` file. **Where can I download this?**

---

```
pip install transformers
pip install onnxruntime
pip install onnx
```

**Code:**
```
import onnxruntime as ort

from transformers import BertTokenizerFast

tokenizer = BertTokenizerFast.from_pretrained("bert-base-cased")

ort_session = ort.InferenceSession("onnx/bert-base-cased/model.onnx")

inputs = tokenizer("Using BERT in ONNX!", return_tensors="np")
outputs = ort_session.run(["last_hidden_state", "pooler_output"], dict(inputs))
```

**Traceback:**
```
---------------------------------------------------------------------------
NoSuchFile                                Traceback (most recent call last)
<ipython-input-5-6c2daa1cf144> in <module>
      5 tokenizer = BertTokenizerFast.from_pretrained("bert-base-cased")
      6 
----> 7 ort_session = ort.InferenceSession("onnx/bert-base-cased/model.onnx")
      8 
      9 inputs = tokenizer("Using BERT in ONNX!", return_tensors="np")

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py in __init__(self, path_or_bytes, sess_options, providers, provider_options)
    278 
    279         try:
--> 280             self._create_inference_session(providers, provider_options)
    281         except RuntimeError:
    282             if self._enable_fallback:

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py in _create_inference_session(self, providers, provider_options)
    305         session_options = self._sess_options if self._sess_options else C.get_default_session_options()
    306         if self._model_path:
--> 307             sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    308         else:
    309             sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)

NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from onnx/bert-base-cased/model.onnx failed:Load model onnx/bert-base-cased/model.onnx failed. File doesn't exist
```

Please let me know if there's anything else I can add to post.

  [1]: https://huggingface.co/docs/transformers/master/serialization

**Comment by jcwchen** [comment]
Hi @danielbellhv,
It seems like a question for the transformers. According to the tutorial, have you used this command to get the ONNX model first?
```
python -m transformers.onnx --model=bert-base-cased onnx/bert-base-cased/
```

**Comment by danielbellhv** [comment]
> ```
> python -m transformers.onnx --model=bert-base-cased onnx/bert-base-cased/
> ```

Hey @jcwchen, I ran the command in Console `conda_pytorch_p36` and Terminal.

Console:
```
python -m transformers.onnx --model=bert-base-cased onnx/bert-base-cased/
  File "<ipython-input-1-0652039cb84d>", line 1
    python -m transformers.onnx --model=bert-base-cased onnx/bert-base-cased/
                         ^
SyntaxError: invalid syntax
```

Terminal:
```
sh-4.2$ python -m transformers.onnx --model=bert-base-cased onnx/bert-base-cased/
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/bin/python: Error while finding module specification for 'transformers.onnx' (ModuleNotFoundError: No module named 'transformers')
```

**Comment by danielbellhv** [comment]
Update on Console:
```
pip install transformers
> Requirement satisfied ...
```
```
sh-4.2$ python -m transformers.onnx --model=bert-base-cased onnx/bert-base-cased/
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
The ONNX export features are only supported for PyTorch, you will not be able to export models without it.
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/transformers/onnx/__main__.py", line 22, in <module>
    from .features import FeaturesManager
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/transformers/onnx/features.py", line 69, in <module>
    class FeaturesManager:
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/transformers/onnx/features.py", line 253, in FeaturesManager
    def get_model_from_feature(feature: str, model: str) -> PreTrainedModel:
NameError: name 'PreTrainedModel' is not defined
```

**Comment by jcwchen** [comment]
Sorry I am not a transformer expert so I am not sure where the problem is. I would suggest you raise this question under transformers repo. It seems that transformers was not installed successfully because it cannot find PreTrainedModel from transformers somehow. Perhaps you can try to remove your existing one and reinstall it.

**Comment by askhade** [comment]
@tianleiwu : Do you have any suggestions for this one?

**Comment by tianleiwu** [comment]
@danielbellhv, as mentioned in the error message, you will need install PyTorch or Tensorflow to work with transformers.

For example, you can install PyTorch here: https://pytorch.org/get-started/locally/

**Comment by danielbellhv** [comment]
I no longer using this Notebook, so don't worry if you cannot replicate error... but for future reference:

I've installed PyTorch and Tensorflow and performed Restart & Run All.

Kernels: `conda_pytorch_latest_p36`, `conda_pytorch_p36` and `conda_tensorflow_p36`.

Still end up with `NoSuchFile` error.

```
pip install pytorch
>>>
pip install pytorch
Collecting pytorch
  Using cached pytorch-1.0.2.tar.gz (689 bytes)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pytorch
  Building wheel for pytorch (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ec2-user/anaconda3/envs/pytorch_latest_p36/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d17yfqx9/pytorch_13e255b4cd79486780b3e1c02b2b1bbb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d17yfqx9/pytorch_13e255b4cd79486780b3e1c02b2b1bbb/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-3dlry5ci
       cwd: /tmp/pip-install-d17yfqx9/pytorch_13e255b4cd79486780b3e1c02b2b1bbb/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-d17yfqx9/pytorch_13e255b4cd79486780b3e1c02b2b1bbb/setup.py", line 15, in <module>
      raise Exception(message)
  Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
  ----------------------------------------
  ERROR: Failed building wheel for pytorch
  Running setup.py clean for pytorch
Failed to build pytorch
Installing collected packages: pytorch
    Running setup.py install for pytorch ... error
    ERROR: Command errored out with exit status 1:
     command: /home/ec2-user/anaconda3/envs/pytorch_latest_p36/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d17yfqx9/pytorch_13e255b4cd79486780b3e1c02b2b1bbb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d17yfqx9/pytorch_13e255b4cd79486780b3e1c02b2b1bbb/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-i12sz0vl/install-record.txt --single-version-externally-managed --compile --install-headers /home/ec2-user/anaconda3/envs/pytorch_latest_p36/include/python3.6m/pytorch
         cwd: /tmp/pip-install-d17yfqx9/pytorch_13e255b4cd79486780b3e1c02b2b1bbb/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-d17yfqx9/pytorch_13e255b4cd79486780b3e1c02b2b1bbb/setup.py", line 11, in <module>
        raise Exception(message)
    Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ec2-user/anaconda3/envs/pytorch_latest_p36/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d17yfqx9/pytorch_13e255b4cd79486780b3e1c02b2b1bbb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d17yfqx9/pytorch_13e255b4cd79486780b3e1c02b2b1bbb/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-i12sz0vl/install-record.txt --single-version-externally-managed --compile --install-headers /home/ec2-user/anaconda3/envs/pytorch_latest_p36/include/python3.6m/pytorch Check the logs for full command output.
Note: you may need to restart the kernel to use updated packages.
```

```
pip install tensorflow
>>>
Collecting tensorflow
  Downloading tensorflow-2.6.2-cp36-cp36m-manylinux2010_x86_64.whl (458.3 MB)
     |█████████████████████▉          | 312.9 MB 142.0 MB/s eta 0:00:02
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

     |████████████████████████████████| 458.3 MB 32 kB/s               
ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device

Note: you may need to restart the kernel to use updated packages.
```

**Comment by askhade** [comment]
@danielbellhv : According to the logs both pytorch and tensorflow were not installed. Both installations ran into errors.

**Comment by danielbellhv** [comment]
Ah yes, package name should be `torch`. I'll try again

**Comment by danielbellhv** [comment]
Both installations are now coming up with `[Errno 28] No space left on device`. This seems to be it's own issue, regarding the storage on AWS SageMaker instance.
