### ISSUE TITLE
extract_model fails when the model contains a model local function

### ISSUE THREAD

**Issue by jantonguirao** [onnx/onnx#3938]
# Bug Report

### Is the issue related to model conversion?
No. No converter was used.

### Describe the bug
`extract_model` fails on models containing a model local function call in the graph.

There is a warning about the local function being an unsupported op (only during the extract_model call), then there is a key error when looking for one of the edges in the graph (see details in the reproduction steps).

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Linux Ubuntu 20.04.3 LTS
- ONNX version (*e.g. 1.7*): 1.10.2
- Python version: 3.8
- GCC/Compiler version (if compiling from source): 9.3.0 
- CMake version: 3.22.1
- Protobuf version: 3.16
- Visual Studio version (if applicable): N/A

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import onnx
import onnx.checker as checker
import onnx.parser as parser
from onnx import save
import onnxruntime

m = parser.parse_model('''
<
  ir_version: 8,
  opset_import: [ "" : 14, "local" : 1],
  producer_name: "test",
  producer_version: "1.0",
  model_version: 1,
  doc_string: "Test"
>
agraph (uint8[H, W, C] x) => (uint8[H, W, C] y)
{
    x1 = local.func(x)
    y = Identity(x1)
}

<
  opset_import: [ "" : 14 ],
  domain: "local",
  doc_string: "test"
>
func (a) => (b)
{
    b = Identity(a)
}
''')

checker.check_model(m)
save(m, 'extract_model_bug.onnx')
extracted = onnx.utils.Extractor(m).extract_model(['x1'], ['y'])
```
produces an error:
```
Warning: Unsupported operator func. No schema registered for this operator.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_3936245/4281959894.py in <module>
     33 checker.check_model(m)
     34 save(m, 'extract_model_bug.onnx')
---> 35 extracted = onnx.utils.Extractor(m).extract_model(['x1'], ['y'])
     36 session = onnxruntime.InferenceSession('extract_model_bug.onnx', None)

~/git/onnx/onnx/utils.py in extract_model(self, input_names, output_names)
    121             output_names,  # type: List[Text]
    122     ):  # type: (...) -> ModelProto
--> 123         inputs = self._collect_new_inputs(input_names)
    124         outputs = self._collect_new_outputs(output_names)
    125         nodes = self._collect_reachable_nodes(input_names, output_names)

~/git/onnx/onnx/utils.py in _collect_new_inputs(self, names)
     46 
     47     def _collect_new_inputs(self, names):  # type: (List[Text]) -> List[ValueInfoProto]
---> 48         return self._collect_new_io_core(self.graph.input, names)  # type: ignore
     49 
     50     def _collect_new_outputs(self, names):  # type: (List[Text]) -> List[ValueInfoProto]

~/git/onnx/onnx/utils.py in _collect_new_io_core(self, original_io, io_names_to_extract)
     39         for name in new_io_names_to_add:
     40             # activation become input or output
---> 41             new_io_tensors.append(self.vimap[name])
     42 
     43         # adjust sequence

KeyError: 'x1'
```
- Attach the ONNX model to the issue (where applicable)
[extract_model_bug.zip](https://github.com/onnx/onnx/files/7856146/extract_model_bug.zip)

### Expected behavior
The extract_model call succeeds and a model containing the subgraph is extracted.

### Notes

Any additional information

**Comment by askhade** [comment]
@jantonguirao : Thanks for reporting.

**Comment by liqunfu** [comment]
@jantonguirao thanks for the clear repo steps! I tested it with the latest main branch. It passed. The graph.value_info does contain 'x1'. 
See my test case at:
https://github.com/onnx/onnx/pull/3954

**Comment by jantonguirao** [comment]
@liqunfu I can confirm that it works with the latest main branch. Thank you!

**Comment by jantonguirao** [comment]
One more thing. If I actually try to extract the part of the graph that uses the local function I get this error:
```
extracted = onnx.utils.Extractor(m).extract_model(['x1'], ['x'])
```
```
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    extracted = onnx.utils.Extractor(m).extract_model(['x1'], ['x'])
  File "/home/janton/git/onnx/onnx/utils.py", line 124, in extract_model
    outputs = self._collect_new_outputs(output_names)
  File "/home/janton/git/onnx/onnx/utils.py", line 51, in _collect_new_outputs
    return self._collect_new_io_core(self.graph.output, names)  # type: ignore
  File "/home/janton/git/onnx/onnx/utils.py", line 41, in _collect_new_io_core
    new_io_tensors.append(self.vimap[name])
KeyError: 'x'
```

**Comment by jantonguirao** [comment]
One more thing. If I extract the part of the model that uses the local function. The local function definition is not present in the resulting model
```
import onnx
import onnx.checker as checker
import onnx.parser as parser
from onnx import save
import onnxruntime

m = parser.parse_model('''                                                                                                                                                                                 
<                                                                                                                                                                                                          
  ir_version: 8,                                                                                                                                                                                           
  opset_import: [ "" : 14, "local" : 1],                                                                                                                                                                   
  producer_name: "test",                                                                                                                                                                                   
  producer_version: "1.0",                                                                                                                                                                                 
  model_version: 1,                                                                                                                                                                                        
  doc_string: "Test"                                                                                                                                                                                       
>                                                                                                                                                                                                          
agraph (uint8[H, W, C] x) => (uint8[H, W, C] y)                                                                                                                                                            
{                                                                                                                                                                                                          
    x1 = local.func(x)                                                                                                                                                                                     
    y = Identity(x1)                                                                                                                                                                                       
}                                                                                                                                                                                                          
                                                                                                                                                                                                           
<                                                                                                                                                                                                          
  opset_import: [ "" : 14 ],                                                                                                                                                                               
  domain: "local",                                                                                                                                                                                         
  doc_string: "test"                                                                                                                                                                                       
>                                                                                                                                                                                                          
func (a) => (b)                                                                                                                                                                                            
{                                                                                                                                                                                                          
    b = Identity(a)                                                                                                                                                                                        
}                                                                                                                                                                                                          
''')

checker.check_model(m)
print("Original model functions:\n", m.functions)
assert len(m.functions) == 1

extracted = onnx.utils.Extractor(m).extract_model(['x'], ['x1'])
print("Extracted model functions:\n", extracted.functions)
assert len(extracted.functions) == 1
```

This produces:
```
Original model functions:
 [name: "func"
input: "a"
output: "b"
node {
  input: "a"
  output: "b"
  op_type: "Identity"
  domain: ""
}
doc_string: "test"
opset_import {
  domain: ""
  version: 14
}
domain: "local"
]
Extracted model functions:
 []
Traceback (most recent call last):
  File "test.py", line 40, in <module>
    assert len(extracted.functions) == 1
AssertionError
```

**Comment by liqunfu** [comment]
it is a bug in onnx. I updated my PR to address it.

**Comment by liqunfu** [comment]
[https://github.com/onnx/onnx/pull/3954](url)
