### ISSUE TITLE
Filed to install on python3.7

### ISSUE THREAD

**Issue by daeeros** [onnx/onnx#4054]
I always getting this error when try to install:
```
   --
    -- ******** Summary ********
    --   CMake version             : 3.22.2
    --   CMake command             : /usr/local/lib/python3.7/dist-packages/cmake/data/bin/cmake
    --   System                    : Linux
    --   C++ compiler              : /usr/bin/c++
    --   C++ compiler version      : 7.5.0
    --   CXX flags                 :  -Wnon-virtual-dtor
    --   Build type                : Release
    --   Compile definitions       : __STDC_FORMAT_MACROS
    --   CMAKE_PREFIX_PATH         :
    --   CMAKE_INSTALL_PREFIX      : /usr/local
    --   CMAKE_MODULE_PATH         :
    --
    --   ONNX version              : 1.11.0
    --   ONNX NAMESPACE            : onnx
    --   ONNX_USE_LITE_PROTO       : OFF
    --   USE_PROTOBUF_SHARED_LIBS  : OFF
    --   Protobuf_USE_STATIC_LIBS  : ON
    --   ONNX_DISABLE_EXCEPTIONS   : OFF
    --   ONNX_WERROR               : OFF
    --   ONNX_BUILD_TESTS          : OFF
    --   ONNX_BUILD_BENCHMARKS     : OFF
    --   ONNXIFI_DUMMY_BACKEND     : OFF
    --   ONNXIFI_ENABLE_EXT        : OFF
    --
    --   Protobuf compiler         : /usr/bin/protoc
    --   Protobuf includes         : /usr/include
    --   Protobuf libraries        : /usr/lib/x86_64-linux-gnu/libprotobuf.a;-lpthread
    --   BUILD_ONNX_PYTHON         : ON
    --     Python version        :
    --     Python executable     : /usr/bin/python3.7
    --     Python includes       : /usr/include/python3.7m
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-build-u8nyzf7f/onnx/.setuptools-cmake-build
    [  2%] Built target gen_onnx_proto
    [  5%] Built target gen_onnx_data_proto
    [  8%] Built target gen_onnx_operators_proto
    Consolidate compiler generated dependencies of target onnx_proto
    [ 22%] Built target onnx_proto
    Consolidate compiler generated dependencies of target onnx
    [ 88%] Built target onnx
    Consolidate compiler generated dependencies of target onnx_cpp2py_export
    [ 90%] Linking CXX shared module onnx_cpp2py_export.cpython-37m-x86_64-linux-gnu.so
    /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(arena.o): relocation R_X86_64_TPOFF32 against hidden symbol `_ZN6google8protobuf5Arena13thread_cache_E' can not be used when making a shared object
    /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(descriptor.o): relocation R_X86_64_PC32 against symbol `_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EED1Ev' can not be used when making a shared object; recompile with -fPIC
    /usr/bin/ld: final link failed: Bad value
    collect2: error: ld returned 1 exit status
    CMakeFiles/onnx_cpp2py_export.dir/build.make:100: recipe for target 'onnx_cpp2py_export.cpython-37m-x86_64-linux-gnu.so' failed
    make[2]: *** [onnx_cpp2py_export.cpython-37m-x86_64-linux-gnu.so] Error 1
    CMakeFiles/Makefile2:228: recipe for target 'CMakeFiles/onnx_cpp2py_export.dir/all' failed
    make[1]: *** [CMakeFiles/onnx_cpp2py_export.dir/all] Error 2
    Makefile:135: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-u8nyzf7f/onnx/setup.py", line 358, in <module>
        'backend-test-tools = onnx.backend.test.cmd_tools:main',
      File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 155, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.7/dist-packages/setuptools/_distutils/core.py", line 148, in setup
        return run_commands(dist)
      File "/usr/local/lib/python3.7/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
        dist.run_commands()
      File "/usr/local/lib/python3.7/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.7/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/dist-packages/setuptools/command/install.py", line 68, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.7/dist-packages/setuptools/_distutils/command/install.py", line 670, in run
        self.run_command('build')
      File "/usr/local/lib/python3.7/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.7/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/dist-packages/setuptools/_distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.7/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.7/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-u8nyzf7f/onnx/setup.py", line 232, in run
        self.run_command('cmake_build')
      File "/usr/local/lib/python3.7/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.7/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-u8nyzf7f/onnx/setup.py", line 226, in run
        subprocess.check_call(build_args)
      File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '.', '--', '-j', '1']' returned non-zero exit status 2
```

How can i fix it?

System:
Ubuntu 18.04
Python3.7

**Comment by jcwchen** [comment]
Hi @daeeros,
Similar to https://github.com/onnx/onnx/issues/3570? Build protobuf from source with -fPIC should help (recommended version is 3.16.0). You can check the installation steps [here](https://github.com/onnx/onnx#linux).
