### ISSUE TITLE
"Failed building wheel for onnx" on a virtualenv, what am I doing wrong?

### ISSUE THREAD

**Issue by cyriltw** [onnx/onnx#4071]
### Question
I'm trying to install onnx package on a cluster (I do not have sudu access) in a virtualenv. 

Python version is Python 3.6.9
I installed numpy and proton-buf
`pip install numpy protobuf==3.16.0`

Yet, when I try to do an install for ONNX, it crashes. Anyone have any ideas on what to do? There were some similar issues, but all of them seem to need sudo. 

I tried installing with `pip install onnx`

Thank you

### Notes
```
Collecting onnx
  Using cached https://files.pythonhosted.org/packages/fd/b7/fccddff4d1873074605ff08acc812202b4a849cf4925b1f6ed5eeba575c4/onnx-1.11.0.tar.gz
Requirement already satisfied: numpy>=1.16.6 in /Experiments/offensive/lib/python3.6/site-packages (from onnx)
Requirement already satisfied: protobuf>=3.12.2 in /Experiments/offensive/lib/python3.6/site-packages (from onnx)
Requirement already satisfied: typing-extensions>=3.6.2.1 in /Experiments/offensive/lib/python3.6/site-packages (from onnx)
Requirement already satisfied: six>=1.9 in /Experiments/offensive/lib/python3.6/site-packages (from protobuf>=3.12.2->onnx)
Building wheels for collected packages: onnx
  Running setup.py bdist_wheel for onnx ... error
  Complete output from command /Experiments/offensive/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-c8yrulk5/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmprbq179mkpip-wheel- --python-tag cp36:
  fatal: not a git repository (or any of the parent directories): .git
  /Experiments/offensive/lib/python3.6/site-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
    SetuptoolsDeprecationWarning,
  running bdist_wheel
  running build
  running build_py
  running create_version
  running cmake_build
  Using cmake args: ['/usr/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.6m', '-DPYTHON_EXECUTABLE=/Experiments/offensive/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-36m-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-build-c8yrulk5/onnx']
  -- The C compiler identification is GNU 7.5.0
  -- The CXX compiler identification is GNU 7.5.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: /Experiments/offensive/bin/python3 (found version "3.6.9")
  -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.9")
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Looking for pthread_create
  -- Looking for pthread_create - not found
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE
  -- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.a;-lpthread (found version "3.0.0")
  Generated: /tmp/pip-build-c8yrulk5/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
  Generated: /tmp/pip-build-c8yrulk5/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
  Generated: /tmp/pip-build-c8yrulk5/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
  CMake Warning at CMakeLists.txt:451 (find_package):
    By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "pybind11",
    but CMake did not find one.
  
    Could not find a package configuration file provided by "pybind11"
    (requested version 2.2) with any of the following names:
  
      pybind11Config.cmake
      pybind11-config.cmake
  
    Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
    "pybind11_DIR" to a directory containing one of the above files.  If
    "pybind11" provides a separate development package or SDK, be sure it has
    been installed.
  
  
  --
  -- ******** Summary ********
  --   CMake version             : 3.10.2
  --   CMake command             : /usr/bin/cmake
  --   System                    : Linux
  --   C++ compiler              : /usr/bin/c++
  --   C++ compiler version      : 7.5.0
  --   CXX flags                 :  -Wnon-virtual-dtor
  --   Build type                : Release
  --   Compile definitions       : __STDC_FORMAT_MACROS
  --   CMAKE_PREFIX_PATH         :
  --   CMAKE_INSTALL_PREFIX      : /usr/local
  --   CMAKE_MODULE_PATH         :
  --
  --   ONNX version              : 1.11.0
  --   ONNX NAMESPACE            : onnx
  --   ONNX_USE_LITE_PROTO       : OFF
  --   USE_PROTOBUF_SHARED_LIBS  : OFF
  --   Protobuf_USE_STATIC_LIBS  : ON
  --   ONNX_DISABLE_EXCEPTIONS   : OFF
  --   ONNX_WERROR               : OFF
  --   ONNX_BUILD_TESTS          : OFF
  --   ONNX_BUILD_BENCHMARKS     : OFF
  --   ONNXIFI_DUMMY_BACKEND     : OFF
  --   ONNXIFI_ENABLE_EXT        : OFF
  --
  --   Protobuf compiler         : /usr/bin/protoc
  --   Protobuf includes         : /usr/include
  --   Protobuf libraries        : /usr/lib/x86_64-linux-gnu/libprotobuf.a;-lpthread
  --   BUILD_ONNX_PYTHON         : ON
  --     Python version        :
  --     Python executable     : /Experiments/offensive/bin/python3
  --     Python includes       : /usr/include/python3.6m
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-build-c8yrulk5/onnx/.setuptools-cmake-build
  Scanning dependencies of target gen_onnx_proto
  Scanning dependencies of target onnxifi_loader
  Scanning dependencies of target onnxifi_dummy
  [  1%] Running gen_proto.py on onnx/onnx.in.proto
  [  2%] Building C object CMakeFiles/onnxifi_loader.dir/onnx/onnxifi_loader.c.o
  [  4%] Building C object CMakeFiles/onnxifi_dummy.dir/onnx/onnxifi_dummy.c.o
  [  5%] Linking C static library libonnxifi_loader.a
  [  7%] Linking C shared library libonnxifi_dummy.so
  [  7%] Built target onnxifi_loader
  Scanning dependencies of target onnxifi_wrapper
  [  8%] Building C object CMakeFiles/onnxifi_wrapper.dir/onnx/onnxifi_wrapper.c.o
  [  8%] Built target onnxifi_dummy
  Processing /tmp/pip-build-c8yrulk5/onnx/onnx/onnx.in.proto
  Writing /tmp/pip-build-c8yrulk5/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
  Writing /tmp/pip-build-c8yrulk5/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto3
  generating /tmp/pip-build-c8yrulk5/onnx/.setuptools-cmake-build/onnx/onnx_pb.py
  [  9%] Running C++ protocol buffer compiler on /tmp/pip-build-c8yrulk5/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
  [ 11%] Linking C shared module libonnxifi.so
  [ 11%] Built target onnxifi_wrapper
  Writing mypy to onnx/onnx_ml_pb2.pyi
  [ 11%] Built target gen_onnx_proto
  Scanning dependencies of target gen_onnx_data_proto
  Scanning dependencies of target gen_onnx_operators_proto
  [ 12%] Running gen_proto.py on onnx/onnx-operators.in.proto
  [ 14%] Running gen_proto.py on onnx/onnx-data.in.proto
  Processing /tmp/pip-build-c8yrulk5/onnx/onnx/onnx-operators.in.proto
  Writing /tmp/pip-build-c8yrulk5/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
  Writing /tmp/pip-build-c8yrulk5/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto3
  generating /tmp/pip-build-c8yrulk5/onnx/.setuptools-cmake-build/onnx/onnx_operators_pb.py
  Processing /tmp/pip-build-c8yrulk5/onnx/onnx/onnx-data.in.proto
  Writing /tmp/pip-build-c8yrulk5/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
  Writing /tmp/pip-build-c8yrulk5/onnx/.setuptools-cmake-build/onnx/onnx-data.proto3
  generating /tmp/pip-build-c8yrulk5/onnx/.setuptools-cmake-build/onnx/onnx_data_pb.py
  [ 15%] Running C++ protocol buffer compiler on /tmp/pip-build-c8yrulk5/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
  [ 16%] Running C++ protocol buffer compiler on /tmp/pip-build-c8yrulk5/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
  Writing mypy to onnx/onnx_data_pb2.pyi
  Writing mypy to onnx/onnx_operators_ml_pb2.pyi
  [ 16%] Built target gen_onnx_operators_proto
  [ 16%] Built target gen_onnx_data_proto
  Scanning dependencies of target onnx_proto
  [ 18%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-ml.pb.cc.o
  [ 19%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-operators-ml.pb.cc.o
  [ 21%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-data.pb.cc.o
  [ 22%] Linking CXX static library libonnx_proto.a
  [ 30%] Built target onnx_proto
  Scanning dependencies of target onnx
  [ 32%] Building CXX object CMakeFiles/onnx.dir/onnx/checker.cc.o
  [ 33%] Building CXX object CMakeFiles/onnx.dir/onnx/common/interned_strings.cc.o
  [ 35%] Building CXX object CMakeFiles/onnx.dir/onnx/common/model_helpers.cc.o
  [ 36%] Building CXX object CMakeFiles/onnx.dir/onnx/common/assertions.cc.o
  [ 38%] Building CXX object CMakeFiles/onnx.dir/onnx/common/ir_pb_converter.cc.o
  [ 39%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/nn/defs.cc.o
  [ 40%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/controlflow/old.cc.o
  [ 43%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/logical/defs.cc.o
  [ 43%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/generator/defs.cc.o
  [ 45%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/data_type_utils.cc.o
  [ 46%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/function.cc.o
  [ 47%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/attr_proto_util.cc.o
  [ 49%] Building CXX object CMakeFiles/onnx.dir/onnx/common/path.cc.o
  [ 50%] Building CXX object CMakeFiles/onnx.dir/onnx/common/status.cc.o
  [ 52%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/controlflow/defs.cc.o
  [ 54%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/object_detection/defs.cc.o
  [ 54%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/logical/old.cc.o
  [ 56%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/generator/old.cc.o
  [ 57%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/math/defs.cc.o
  [ 59%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/math/old.cc.o
  [ 60%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/parser.cc.o
  [ 63%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/nn/old.cc.o
  [ 63%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/quantization/defs.cc.o
  [ 64%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/optional/defs.cc.o
  [ 66%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/reduction/old.cc.o
  [ 67%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/quantization/old.cc.o
  [ 70%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/object_detection/old.cc.o
  [ 70%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/printer.cc.o
  [ 71%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/rnn/defs.cc.o
  [ 73%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/schema.cc.o
  [ 74%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/shape_inference.cc.o
  [ 76%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/sequence/defs.cc.o
  [ 78%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/rnn/old.cc.o
  [ 78%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor/defs.cc.o
  [ 80%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor/old.cc.o
  [ 81%] Building CXX object CMakeFiles/onnx.dir/onnx/version_converter/convert.cc.o
  [ 83%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/reduction/defs.cc.o
  [ 85%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor_proto_util.cc.o
  [ 85%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor_util.cc.o
  [ 87%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor/utils.cc.o
  [ 88%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/traditionalml/old.cc.o
  [ 90%] Building CXX object CMakeFiles/onnx.dir/onnx/shape_inference/implementation.cc.o
  [ 91%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/training/defs.cc.o
  [ 92%] Building CXX object CMakeFiles/onnx.dir/onnx/onnxifi_utils.cc.o
  [ 94%] Building CXX object CMakeFiles/onnx.dir/onnx/version_converter/helper.cc.o
  [ 95%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/traditionalml/defs.cc.o
  [ 97%] Linking CXX static library libonnx.a
  [ 97%] Built target onnx
  Scanning dependencies of target onnx_cpp2py_export
  [ 98%] Building CXX object CMakeFiles/onnx_cpp2py_export.dir/onnx/cpp2py_export.cc.o
  [100%] Linking CXX shared module onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so
  /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(arena.o): relocation R_X86_64_TPOFF32 against hidden symbol `_ZN6google8protobuf5Arena13thread_cache_E' can not be used when making a shared object
  /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(descriptor.o): relocation R_X86_64_PC32 against symbol `_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EED1Ev' can not be used when making a shared object; recompile with -fPIC
  /usr/bin/ld: final link failed: Bad value
  collect2: error: ld returned 1 exit status
  CMakeFiles/onnx_cpp2py_export.dir/build.make:98: recipe for target 'onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so' failed
  gmake[2]: *** [onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so] Error 1
  CMakeFiles/Makefile2:351: recipe for target 'CMakeFiles/onnx_cpp2py_export.dir/all' failed
  gmake[1]: *** [CMakeFiles/onnx_cpp2py_export.dir/all] Error 2
  Makefile:129: recipe for target 'all' failed
  gmake: *** [all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-c8yrulk5/onnx/setup.py", line 358, in <module>
      'backend-test-tools = onnx.backend.test.cmd_tools:main',
    File "/Experiments/offensive/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Experiments/offensive/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-c8yrulk5/onnx/setup.py", line 232, in run
      self.run_command('cmake_build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-c8yrulk5/onnx/setup.py", line 226, in run
      subprocess.check_call(build_args)
    File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '.', '--', '-j', '48']' returned non-zero exit status 2.
  
  ----------------------------------------
  Failed building wheel for onnx
  Running setup.py clean for onnx
Failed to build onnx
Installing collected packages: onnx
  Running setup.py install for onnx ... error
    Complete output from command /Experiments/offensive/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-c8yrulk5/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-dea4sm_t-record/install-record.txt --single-version-externally-managed --compile --install-headers /Experiments/offensive/include/site/python3.6/onnx:
    fatal: not a git repository (or any of the parent directories): .git
    /Experiments/offensive/lib/python3.6/site-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
      SetuptoolsDeprecationWarning,
    running install
    /Experiments/offensive/lib/python3.6/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    running build
    running build_py
    running create_version
    running cmake_build
    Using cmake args: ['/usr/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.6m', '-DPYTHON_EXECUTABLE=/Experiments/offensive/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-36m-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-build-c8yrulk5/onnx']
    Generated: /tmp/pip-build-c8yrulk5/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
    Generated: /tmp/pip-build-c8yrulk5/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
    Generated: /tmp/pip-build-c8yrulk5/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
    CMake Warning at CMakeLists.txt:451 (find_package):
      By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "pybind11",
      but CMake did not find one.
    
      Could not find a package configuration file provided by "pybind11"
      (requested version 2.2) with any of the following names:
    
        pybind11Config.cmake
        pybind11-config.cmake
    
      Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
      "pybind11_DIR" to a directory containing one of the above files.  If
      "pybind11" provides a separate development package or SDK, be sure it has
      been installed.
    
    
    --
    -- ******** Summary ********
    --   CMake version             : 3.10.2
    --   CMake command             : /usr/bin/cmake
    --   System                    : Linux
    --   C++ compiler              : /usr/bin/c++
    --   C++ compiler version      : 7.5.0
    --   CXX flags                 :  -Wnon-virtual-dtor
    --   Build type                : Release
    --   Compile definitions       : __STDC_FORMAT_MACROS
    --   CMAKE_PREFIX_PATH         :
    --   CMAKE_INSTALL_PREFIX      : /usr/local
    --   CMAKE_MODULE_PATH         :
    --
    --   ONNX version              : 1.11.0
    --   ONNX NAMESPACE            : onnx
    --   ONNX_USE_LITE_PROTO       : OFF
    --   USE_PROTOBUF_SHARED_LIBS  : OFF
    --   Protobuf_USE_STATIC_LIBS  : ON
    --   ONNX_DISABLE_EXCEPTIONS   : OFF
    --   ONNX_WERROR               : OFF
    --   ONNX_BUILD_TESTS          : OFF
    --   ONNX_BUILD_BENCHMARKS     : OFF
    --   ONNXIFI_DUMMY_BACKEND     : OFF
    --   ONNXIFI_ENABLE_EXT        : OFF
    --
    --   Protobuf compiler         : /usr/bin/protoc
    --   Protobuf includes         : /usr/include
    --   Protobuf libraries        : /usr/lib/x86_64-linux-gnu/libprotobuf.a;-lpthread
    --   BUILD_ONNX_PYTHON         : ON
    --     Python version        :
    --     Python executable     : /Experiments/offensive/bin/python3
    --     Python includes       : /usr/include/python3.6m
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-build-c8yrulk5/onnx/.setuptools-cmake-build
    [  2%] Built target onnxifi_dummy
    [  5%] Built target gen_onnx_proto
    [  8%] Built target onnxifi_loader
    [ 11%] Built target onnxifi_wrapper
    [ 14%] Built target gen_onnx_data_proto
    [ 16%] Built target gen_onnx_operators_proto
    [ 30%] Built target onnx_proto
    [ 97%] Built target onnx
    [ 98%] Linking CXX shared module onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so
    /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(arena.o): relocation R_X86_64_TPOFF32 against hidden symbol `_ZN6google8protobuf5Arena13thread_cache_E' can not be used when making a shared object
    /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(descriptor.o): relocation R_X86_64_PC32 against symbol `_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EED1Ev' can not be used when making a shared object; recompile with -fPIC
    /usr/bin/ld: final link failed: Bad value
    collect2: error: ld returned 1 exit status
    CMakeFiles/onnx_cpp2py_export.dir/build.make:98: recipe for target 'onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so' failed
    gmake[2]: *** [onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so] Error 1
    CMakeFiles/Makefile2:351: recipe for target 'CMakeFiles/onnx_cpp2py_export.dir/all' failed
    gmake[1]: *** [CMakeFiles/onnx_cpp2py_export.dir/all] Error 2
    Makefile:129: recipe for target 'all' failed
    gmake: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-c8yrulk5/onnx/setup.py", line 358, in <module>
        'backend-test-tools = onnx.backend.test.cmd_tools:main',
      File "/Experiments/offensive/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Experiments/offensive/lib/python3.6/site-packages/setuptools/command/install.py", line 68, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-c8yrulk5/onnx/setup.py", line 232, in run
        self.run_command('cmake_build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-c8yrulk5/onnx/setup.py", line 226, in run
        subprocess.check_call(build_args)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '.', '--', '-j', '48']' returned non-zero exit status 2.
    
    ----------------------------------------
Command "/Experiments/offensive/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-c8yrulk5/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-dea4sm_t-record/install-record.txt --single-version-externally-managed --compile --install-headers /Experiments/offensive/include/site/python3.6/onnx" failed with error code 1 in /tmp/pip-build-c8yrulk5/onnx/
```

**Comment by jcwchen** [comment]
Hi @cyriltw,
Similar to https://github.com/onnx/onnx/issues/3570? Build protobuf from source with -fPIC should help (recommended version is 3.16.0). Could you please try the installation steps [here](https://github.com/onnx/onnx#linux)?

**Comment by jcwchen** [comment]
If for some reasons you cannot build protobuf from source, you can try conda environment with installed protobuf from conda. Then building ONNX from source with `export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON"` should work.

**Comment by cyriltw** [comment]
> Hi @cyriltw,
> Similar to #3570? Build protobuf from source with -fPIC should help (recommended version is 3.16.0). Could you please try the installation steps [here](https://github.com/onnx/onnx#linux)?

Hi @jcwchen thanks! So this helped. I went back and installed `pybind11', updated pip and then used the 'export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON"'. I didn't have to install protobuf since it was installed on a system level, just needed to use the export command to link it.
