### ISSUE TITLE
Installation via pip throws error

### ISSUE THREAD

**Issue by krenem** [onnx/onnx#4146]
# Bug Report

### Describe the bug
The installation of onnx via pip throws twice an ``` subprocess-exited-with-error``` and afterwards the ```legacy-install-failure```.

### System information
- OS Platform and Distribution: Windows 10 
- Python version: 3.10.2
- CMake version: 3.22.3
- Protobuf version: 3.20.0

### Reproduction instructions
- I tried to install onnx via pip as specified in the README.md. Beforehand, I installed the prerequisities needed.
```
pip install numpy protobuf typing-extensions
pip install onnx
```
Installing the required packages was successfull. But trying to install onnx resulted in the following error:
```
Collecting onnx
  Using cached onnx-1.11.0.tar.gz (9.9 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.16.6 in c:\users\krena\desktop\github\perass\core\.env\lib\site-packages (from onnx) (1.22.3)
Requirement already satisfied: protobuf>=3.12.2 in c:\users\krena\desktop\github\perass\core\.env\lib\site-packages (from onnx) (3.20.0)
Requirement already satisfied: typing-extensions>=3.6.2.1 in c:\users\krena\desktop\github\perass\core\.env\lib\site-packages (from onnx) (4.1.1)
Building wheels for collected packages: onnx
  Building wheel for onnx (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [80 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      running create_version
      running cmake_build
      Using cmake args: ['C:\\Users\\krena\\Desktop\\github\\perass\\core\\.env\\Scripts\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Users\\krena\\AppData\\Local\\Programs\\Python\\Python310\\include', '-DPYTHON_EXECUTABLE=C:\\Users\\krena\\Desktop\\github\\perass\\core\\.env\\Scripts\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp310-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.10', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\krena\\AppData\\Local\\Temp\\pip-install-yhobb2wb\\onnx_bd234aa4c3d04838a8f5659efdb64b2d']
      -- Building for: Visual Studio 16 2019
      -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
      -- The C compiler identification is MSVC 19.29.30142.1
      -- The CXX compiler identification is MSVC 19.29.30142.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found PythonInterp: C:/Users/krena/Desktop/github/perass/core/.env/Scripts/python.exe (found suitable version "3.10.2", minimum required is "3.10")
      -- Found PythonLibs: C:/Users/krena/AppData/Local/Programs/Python/Python310/libs/python310.lib (found suitable version "3.10.2", minimum required is "3.10")
      Generated: C:/Users/krena/AppData/Local/Temp/pip-install-yhobb2wb/onnx_bd234aa4c3d04838a8f5659efdb64b2d/.setuptools-cmake-build/onnx/onnx-ml.proto
      CMake Error at CMakeLists.txt:295 (message):
        Protobuf compiler not found
      Call Stack (most recent call first):
        CMakeLists.txt:326 (relative_protobuf_generate_cpp)


      -- Configuring incomplete, errors occurred!
      See also "C:/Users/krena/AppData/Local/Temp/pip-install-yhobb2wb/onnx_bd234aa4c3d04838a8f5659efdb64b2d/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\krena\AppData\Local\Temp\pip-install-yhobb2wb\onnx_bd234aa4c3d04838a8f5659efdb64b2d\setup.py", line 336, in <module>
          setuptools.setup(
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
          dist.run_commands()
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\dist.py", line 1214, in run_command
          super().run_command(command)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\dist.py", line 1214, in run_command
          super().run_command(command)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\command\build.py", line 136, in run
          self.run_command(cmd_name)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\dist.py", line 1214, in run_command
          super().run_command(command)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\krena\AppData\Local\Temp\pip-install-yhobb2wb\onnx_bd234aa4c3d04838a8f5659efdb64b2d\setup.py", line 232, in run
          self.run_command('cmake_build')
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\dist.py", line 1214, in run_command
          super().run_command(command)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\krena\AppData\Local\Temp\pip-install-yhobb2wb\onnx_bd234aa4c3d04838a8f5659efdb64b2d\setup.py", line 218, in run
          subprocess.check_call(cmake_args)
        File "C:\Users\krena\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Users\\krena\\Desktop\\github\\perass\\core\\.env\\Scripts\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Users\\krena\\AppData\\Local\\Programs\\Python\\Python310\\include', '-DPYTHON_EXECUTABLE=C:\\Users\\krena\\Desktop\\github\\perass\\core\\.env\\Scripts\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp310-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.10', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\krena\\AppData\\Local\\Temp\\pip-install-yhobb2wb\\onnx_bd234aa4c3d04838a8f5659efdb64b2d']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for onnx
  Running setup.py clean for onnx
Failed to build onnx
Installing collected packages: onnx
  Running setup.py install for onnx ... error
  error: subprocess-exited-with-error

  × Running setup.py install for onnx did not run successfully.
  │ exit code: 1
  ╰─> [69 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running install
      C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      running create_version
      running cmake_build
      Using cmake args: ['C:\\Users\\krena\\Desktop\\github\\perass\\core\\.env\\Scripts\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Users\\krena\\AppData\\Local\\Programs\\Python\\Python310\\include', '-DPYTHON_EXECUTABLE=C:\\Users\\krena\\Desktop\\github\\perass\\core\\.env\\Scripts\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp310-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.10', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\krena\\AppData\\Local\\Temp\\pip-install-yhobb2wb\\onnx_bd234aa4c3d04838a8f5659efdb64b2d']
      -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
      Generated: C:/Users/krena/AppData/Local/Temp/pip-install-yhobb2wb/onnx_bd234aa4c3d04838a8f5659efdb64b2d/.setuptools-cmake-build/onnx/onnx-ml.proto
      CMake Error at CMakeLists.txt:295 (message):
        Protobuf compiler not found
      Call Stack (most recent call first):
        CMakeLists.txt:326 (relative_protobuf_generate_cpp)


      -- Configuring incomplete, errors occurred!
      See also "C:/Users/krena/AppData/Local/Temp/pip-install-yhobb2wb/onnx_bd234aa4c3d04838a8f5659efdb64b2d/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\krena\AppData\Local\Temp\pip-install-yhobb2wb\onnx_bd234aa4c3d04838a8f5659efdb64b2d\setup.py", line 336, in <module>
          setuptools.setup(
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
          dist.run_commands()
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\dist.py", line 1214, in run_command
          super().run_command(command)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\command\install.py", line 68, in run
          return orig.install.run(self)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\command\install.py", line 670, in run
          self.run_command('build')
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\dist.py", line 1214, in run_command
          super().run_command(command)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\command\build.py", line 136, in run
          self.run_command(cmd_name)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\dist.py", line 1214, in run_command
          super().run_command(command)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\krena\AppData\Local\Temp\pip-install-yhobb2wb\onnx_bd234aa4c3d04838a8f5659efdb64b2d\setup.py", line 232, in run
          self.run_command('cmake_build')
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\dist.py", line 1214, in run_command
          super().run_command(command)
        File "C:\Users\krena\Desktop\github\perass\core\.env\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\krena\AppData\Local\Temp\pip-install-yhobb2wb\onnx_bd234aa4c3d04838a8f5659efdb64b2d\setup.py", line 218, in run
          subprocess.check_call(cmake_args)
        File "C:\Users\krena\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Users\\krena\\Desktop\\github\\perass\\core\\.env\\Scripts\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Users\\krena\\AppData\\Local\\Programs\\Python\\Python310\\include', '-DPYTHON_EXECUTABLE=C:\\Users\\krena\\Desktop\\github\\perass\\core\\.env\\Scripts\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp310-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.10', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\krena\\AppData\\Local\\Temp\\pip-install-yhobb2wb\\onnx_bd234aa4c3d04838a8f5659efdb64b2d']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> onnx

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

### Expected behavior
Complete installation without occuring error.

### Notes

Originally the error occured in my attempt to install the insightface package via ``` pip install -U insightface ```.

**Comment by jcwchen** [comment]
Hi @krenem,
Python 3.10 wheel has not  been supported yet (https://github.com/onnx/onnx/pull/3734), but next release ONNX will publish Python 3.10 wheel. That's why you built ONNX from source and bumped into missing Protobuf error. To use ONNX in Python 3.10 now, you need to build ONNX from source. Building ONNX from source needs Protobuf installed and you can follow the instruction [here](https://github.com/onnx/onnx/commit/94e2f64551ded652df53a7e9111031e8aabddaee). Another workaround would be using [onnx-weekly package](https://test.pypi.org/project/onnx-weekly/) from TestPyPI. There are Python 3.10 wheel already, but those wheel were built weekly from the main branch.
