### ISSUE TITLE
Install ONNX on ARM32

### ISSUE THREAD

**Issue by thestarivore** [onnx/onnx#4211]
Hi,
I'm trying to install ONNX on a Raspberry PI 4B with a ARM32 OS (Raspbian Buster: [image](https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-legacy) ), but I had no luck so far. I know that "pip install onnx" works on ARM64, but because of other packages that only work on ARM32 I'm stuck on this OS.

### Question
Has anyone managed to install ONNX on Raspbian Buster or any other ARM32 OS? Is there any **tested** procedure that I can follow?

### Further information
Since i couldn't find any wheels I just compiled onnx directly on the raspberry pi. I followed the instruction on:
- [https://github.com/onnx/onnx](https://github.com/onnx/onnx)
- [https://pypi.org/project/onnx/](https://pypi.org/project/onnx/)

And also the solution of [maitek](https://github.com/maitek) on the following issue: [389](https://github.com/onnx/onnx/issues/389).
But all my attempts failed in some way or another.

### Notes
All my attempts fail either on "pip install -e ." or on "sudo python setup.py install".

Thank you in advance!

**Comment by jcwchen** [comment]
Hi @thestarivore,
May I understand what error did you bump into?

**Comment by thestarivore** [comment]
> Hi @thestarivore, May I understand what error did you bump into?

Hi @jcwchen, right now the error I get is:

    pi@raspberrypi:~/onnx $ pip uninstall onnx
    Skipping onnx as it is not installed.
    pi@raspberrypi:~/onnx $ python3 -m pip uninstall onnx
    Can't uninstall 'onnx'. No files were found to uninstall.
    pi@raspberrypi:~/onnx $ python3 -m pip install -e .
    Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
    Obtaining file:///home/pi/onnx
    Requirement already satisfied: numpy>=1.16.6 in /home/pi/.local/lib/python3.7/site-packages (from onnx==1.11.0) (1.21.6)
    Requirement already satisfied: protobuf>=3.12.2 in /usr/local/lib/python3.7/dist-packages/protobuf-4.21.0rc1-py3.7.egg (from onnx==1.11.0) (4.21.0rc1)
    Requirement already satisfied: typing-extensions>=3.6.2.1 in /home/pi/.local/lib/python3.7/site-packages (from onnx==1.11.0) (4.2.0)
    Installing collected packages: onnx
      Found existing installation: onnx 1.11.0
        Can't uninstall 'onnx'. No files were found to uninstall.
      Running setup.py develop for onnx
        Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/home/pi/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=:
        running develop
        running build_py
        running create_version
        running cmake_build
        Using cmake args: ['/usr/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.7m', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-37m-arm-linux-gnueabihf.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/home/pi/onnx']
        Generated: /home/pi/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
        Generated: /home/pi/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
        Generated: /home/pi/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
        -- Could NOT find pybind11 (missing: pybind11_DIR)
        -- pybind11 v2.9.1
        --
        -- ******** Summary ********
        --   CMake version             : 3.16.3
        --   CMake command             : /usr/bin/cmake
        --   System                    : Linux
        --   C++ compiler              : /usr/bin/c++
        --   C++ compiler version      : 8.3.0
        --   CXX flags                 :  -Wnon-virtual-dtor
        --   Build type                : Release
        --   Compile definitions       : __STDC_FORMAT_MACROS
        --   CMAKE_PREFIX_PATH         :
        --   CMAKE_INSTALL_PREFIX      : /usr/local
        --   CMAKE_MODULE_PATH         :
        --
        --   ONNX version              : 1.11.0
        --   ONNX NAMESPACE            : onnx
        --   ONNX_USE_LITE_PROTO       : ON
        --   USE_PROTOBUF_SHARED_LIBS  : ON
        --   Protobuf_USE_STATIC_LIBS  : OFF
        --   ONNX_DISABLE_EXCEPTIONS   : OFF
        --   ONNX_WERROR               : OFF
        --   ONNX_BUILD_TESTS          : OFF
        --   ONNX_BUILD_BENCHMARKS     : OFF
        --   ONNXIFI_DUMMY_BACKEND     : OFF
        --   ONNXIFI_ENABLE_EXT        : OFF
        --
        --   Protobuf compiler         : /usr/local/bin/protoc
        --   Protobuf includes         : /usr/local/include
        --   Protobuf libraries        : /usr/local/lib/libprotobuf.so
        --   BUILD_ONNX_PYTHON         : ON
        --     Python version        :
        --     Python executable     : /usr/bin/python3
        --     Python includes       : /usr/include/python3.7m
        -- Configuring done
        -- Generating done
        -- Build files have been written to: /home/pi/onnx/.setuptools-cmake-build
        [  9%] Built target onnxifi_dummy
        [  9%] Running C++ protocol buffer compiler on /home/pi/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
        [  9%] Built target onnxifi_loader
        onnx/onnx-ml.proto:474:3: Expected "required", "optional", or "repeated".
        onnx/onnx-ml.proto:474:12: Expected field name.
        onnx/onnx-ml.proto:475:3: Expected "required", "optional", or "repeated".
        onnx/onnx-ml.proto:475:12: Expected field name.
        onnx/onnx-ml.proto:786:3: Expected "required", "optional", or "repeated".
        onnx/onnx-ml.proto:786:12: Expected field name.
        onnx/onnx-ml.proto:787:3: Expected "required", "optional", or "repeated".
        onnx/onnx-ml.proto:787:12: Expected field name.
        onnx/onnx-ml.proto:791:3: Expected "required", "optional", or "repeated".
        onnx/onnx-ml.proto:791:12: Expected field name.
        onnx/onnx-ml.proto:792:3: Expected "required", "optional", or "repeated".
        onnx/onnx-ml.proto:792:12: Expected field name.
        make[2]: *** [CMakeFiles/gen_onnx_proto.dir/build.make:62: onnx/onnx-ml.pb.cc] Error 1
        make[1]: *** [CMakeFiles/Makefile2:190: CMakeFiles/gen_onnx_proto.dir/all] Error 2
        make[1]: *** Waiting for unfinished jobs....
        [  9%] Built target onnxifi_wrapper
        make: *** [Makefile:130: all] Error 2
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/home/pi/onnx/setup.py", line 354, in <module>
            "backend-test-tools = onnx.backend.test.cmd_tools:main",
          File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
            return distutils.core.setup(**attrs)
          File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
            dist.run_commands()
          File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
            self.run_command(cmd)
          File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
            cmd_obj.run()
          File "/home/pi/onnx/setup.py", line 239, in run
            self.run_command("build_py")
          File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
            self.distribution.run_command(command)
          File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
            cmd_obj.run()
          File "/home/pi/onnx/setup.py", line 223, in run
            self.run_command("cmake_build")
          File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
            self.distribution.run_command(command)
          File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
            cmd_obj.run()
          File "/home/pi/onnx/setup.py", line 217, in run
            subprocess.check_call(build_args)
          File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '.', '--', '-j', '4']' returned non-zero exit status 2.
        
        ----------------------------------------
      Can't roll back onnx; was not uninstalled
    Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/home/pi/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=" failed with error code 1 in /home/pi/onnx/

**Comment by jcwchen** [comment]
Thanks for providing the error log. It seems like a Protobuf version conflict issue. I saw your C++ Protobuf is an old one:
```
 -- Found Protobuf: /usr/local/lib/libprotobuf.so;-lpthread (found version "2.6.1")
```
Could you please try higher C++ Protobuf version? (For instance, 3.16.0+). You can follow the instruction [here](https://github.com/onnx/onnx#linux) to build Protobuf 3.16.0 from source.

**Comment by mshr-h** [comment]
Hi, I've compiled ONNX for ARMv7l CPU a few years ago.
- https://mshr-h.com/posts/how-to-build-onnx-for-your-armv7l-devices/

I'm not sure whether the procedure is still valid or not.

**Comment by zoldaten** [comment]
https://github.com/zoldaten/onnx_wheel_armv7l

**Comment by RZDoesDeploys** [comment]
I want to build onnx-runtime for Raspberry PI OS for Desktop:

will it work?

OS: Debain GNU / Linux
Kernel: Linux 5.10.0-15-amd64
Architecture: x86-64
