### ISSUE TITLE
onnx work does not work well in my conda envirinment

### ISSUE THREAD

**Issue by chayliu1991** [onnx/onnx#4216]
I install onnx on my conda envs(python=3.7) by 
```
conda install -c conda-forge numpy protobuf==3.16.0 libprotobuf=3.16.0
conda install -c conda-forge onnx
```

I list all the results after `conda list` command:
```
 packages in environment at /root/anaconda3/envs/py37:
#
# Name                    Version                   Build  Channel
backcall                  0.2.0              pyhd3eb1b0_0
ca-certificates           2022.5.18.1          ha878542_0    conda-forge
certifi                   2022.5.18.1      py37h89c1867_0    conda-forge
debugpy                   1.5.1            py37h295c915_0
decorator                 5.1.1              pyhd3eb1b0_0
entrypoints               0.4              py37h06a4308_0
ipykernel                 6.9.1            py37h06a4308_0
ipython                   7.31.1           py37h06a4308_0
jedi                      0.18.1           py37h06a4308_1
jupyter_client            7.2.2            py37h06a4308_0
jupyter_core              4.10.0           py37h06a4308_0
ld_impl_linux-64          2.38                 h1181459_1
libblas                   3.9.0           14_linux64_openblas    conda-forge
libcblas                  3.9.0           14_linux64_openblas    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0               h1234567_0
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
liblapack                 3.9.0           14_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.20          pthreads_h78a6416_0    conda-forge
libprotobuf               3.16.0               h780b84a_0    conda-forge
libsodium                 1.0.18               h7b6447c_0
libstdcxx-ng              11.2.0               h1234567_0
libzlib                   1.2.11            h166bdaf_1014    conda-forge
matplotlib-inline         0.1.2              pyhd3eb1b0_2
ncurses                   6.3                  h7f8727e_2
nest-asyncio              1.5.5            py37h06a4308_0
numpy                     1.21.6           py37h976b520_0    conda-forge
onnx                      1.10.1           py37h23e98fe_0    conda-forge
openssl                   3.0.3                h166bdaf_0    conda-forge
parso                     0.8.3              pyhd3eb1b0_0
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pip                       21.2.2           py37h06a4308_0
prompt-toolkit            3.0.20             pyhd3eb1b0_0
protobuf                  3.16.0           py37hcd2ae1e_0    conda-forge
ptyprocess                0.7.0              pyhd3eb1b0_2
pygments                  2.11.2             pyhd3eb1b0_0
python                    3.7.12          hf930737_100_cpython    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0
python_abi                3.7                     2_cp37m    conda-forge
pyzmq                     22.3.0           py37h295c915_2
readline                  8.1.2                h7f8727e_1
setuptools                61.2.0           py37h06a4308_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.38.5               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tornado                   6.1              py37h27cfd23_0
traitlets                 5.1.1              pyhd3eb1b0_0
typing-extensions         4.2.0                hd8ed1ab_1    conda-forge
typing_extensions         4.2.0              pyha770c72_1    conda-forge
wcwidth                   0.2.5              pyhd3eb1b0_0
wheel                     0.37.1             pyhd3eb1b0_0
xz                        5.2.5                h7f8727e_1
zeromq                    4.3.4                h2531618_0
zlib                      1.2.11            h166bdaf_1014    conda-forge
```

Then I download onnx model by:
wget https://github.com/onnx/models/tree/main/vision/object_detection_segmentation/tiny-yolov2/model/tinyyolov2-7.onnx

then I write the following code and it raise a exception:
```
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnx
>>> mod=onnx.load('tinyyolov2-7.onnx')
/root/anaconda3/envs/py37/lib/python3.7/site-packages/onnx/__init__.py:99: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  decoded = cast(Optional[int], proto.ParseFromString(s))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/onnx/__init__.py", line 121, in load_model
    model = load_model_from_string(s, format=format)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/onnx/__init__.py", line 158, in load_model_from_string
    return _deserialize(s, ModelProto())
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/onnx/__init__.py", line 103, in _deserialize
    decoded, len(s)))
google.protobuf.message.DecodeError: Protobuf decoding consumed too few bytes: 13 out of 132300
```

**Comment by chayliu1991** [comment]
sloved
