### ISSUE TITLE
ONNX 1.0.0 PyPi install fails when git is not installed on host

### ISSUE THREAD

**Issue by lupesko** [onnx/onnx#432]
To reproduce:
- Setup an OS without git, e.g. clean ubuntu:latest docker image
- pip install onnx

Expected result: onnx installed successfully

Actual result: 
`
Downloading onnx-1.0.0.tar.gz (763kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-35XWgl/onnx/setup.py", line 40, in <module>
        cwd=TOP_DIR).decode('ascii').strip()
      File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
        process = Popen(stdout=PIPE, *popenargs, **kwargs)
      File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
`

I filed #430 to fix.
This may be a critical issue that we'll want a patch release out for.

Opinions?

**Comment by bddppq** [comment]
Yep, we will need do a patch release.

**Comment by StupidTAO** [comment]
I had the same problem.

**Comment by lupesko** [comment]
Fixed by #430
