### ISSUE TITLE
Build onnx arm32 with protobuf permission error

### ISSUE THREAD

**Issue by jji2019** [onnx/onnx#4327]
# Bug Report
fail to build onnx into python wheel with error snippet:
```
[ 98%] Linking CXX shared module onnx_cpp2py_export.cpython-37m-arm-linux-gnueabihf.so
/usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0x7cc): R_ARM_TLS_LE32 relocation not permitted in shared object
```

### Is the issue related to model conversion?
No. 

### Describe the bug
build failure

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*):  Linux Ubuntu 22.04 (jammy)
- ONNX version (*e.g. 1.7*):  1.10
- Python version: 3.7
- GCC/Compiler version (if compiling from source): 11.2.0 (apt-get)
- CMake version: 3.22.1 (apt-get)
- Protobuf version: 3.12.4 (apt-get)
- Visual Studio version (if applicable): n/a

Some information:
```
Using cmake args: ['/usr/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/local/include/python3.7m', '-DPYTHON_EXECUTABLE=/usr/local/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-37m-arm-linux-gnueabihf.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/code/onnx']
Generated: /code/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
Generated: /code/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
Generated: /code/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
-- Found pybind11: /usr/local/lib/python3.7/site-packages/pybind11/include (found version "2.9.2")
-- 
-- ******** Summary ********
--   CMake version             : 3.22.1
--   CMake command             : /usr/bin/cmake
--   System                    : Linux
--   C++ compiler              : /usr/bin/c++
--   C++ compiler version      : 11.2.0
--   CXX flags                 :  -Wnon-virtual-dtor
--   Build type                : Release
--   Compile definitions       : 
--   CMAKE_PREFIX_PATH         : 
--   CMAKE_INSTALL_PREFIX      : /usr/local
--   CMAKE_MODULE_PATH         : 
-- 
--   ONNX version              : 1.10.0
--   ONNX NAMESPACE            : onnx
--   ONNX_USE_LITE_PROTO       : OFF
--   USE_PROTOBUF_SHARED_LIBS  : OFF
--   Protobuf_USE_STATIC_LIBS  : ON
--   ONNX_DISABLE_EXCEPTIONS   : OFF
--   ONNX_WERROR               : OFF
--   ONNX_BUILD_TESTS          : OFF
--   ONNX_BUILD_BENCHMARKS     : OFF
--   ONNXIFI_DUMMY_BACKEND     : OFF
--   ONNXIFI_ENABLE_EXT        : OFF
-- 
--   Protobuf compiler         : /usr/bin/protoc
--   Protobuf includes         : /usr/include
--   Protobuf libraries        : /usr/lib/arm-linux-gnueabihf/libprotobuf.a
--   BUILD_ONNX_PYTHON         : ON
--     Python version        : 
--     Python executable     : /usr/local/bin/python3
--     Python includes       : /usr/local/include/python3.7m
-- Configuring done
-- Generating done
```

The installed protobuf lib:
```
root@4a00714193b1:/code/onnx# ls -la /usr/lib/arm-linux-gnueabihf/libproto*
-rw-r--r-- 1 root root 1234380 Mar 17 19:36 /usr/lib/arm-linux-gnueabihf/libprotobuf-lite.a
lrwxrwxrwx 1 root root      26 Mar 17 19:36 /usr/lib/arm-linux-gnueabihf/libprotobuf-lite.so -> libprotobuf-lite.so.23.0.4
lrwxrwxrwx 1 root root      26 Mar 17 19:36 /usr/lib/arm-linux-gnueabihf/libprotobuf-lite.so.23 -> libprotobuf-lite.so.23.0.4
-rw-r--r-- 1 root root  485592 Mar 17 19:36 /usr/lib/arm-linux-gnueabihf/libprotobuf-lite.so.23.0.4
-rwxrwxrwx 1 root root 5179258 Mar 17 19:36 /usr/lib/arm-linux-gnueabihf/libprotobuf.a
lrwxrwxrwx 1 root root      21 Mar 17 19:36 /usr/lib/arm-linux-gnueabihf/libprotobuf.so -> libprotobuf.so.23.0.4
lrwxrwxrwx 1 root root      21 Mar 17 19:36 /usr/lib/arm-linux-gnueabihf/libprotobuf.so.23 -> libprotobuf.so.23.0.4
-rw-r--r-- 1 root root 2049608 Mar 17 19:36 /usr/lib/arm-linux-gnueabihf/libprotobuf.so.23.0.4
lrwxrwxrwx 1 root root      19 Mar 17 19:36 /usr/lib/arm-linux-gnueabihf/libprotoc.so.23 -> libprotoc.so.23.0.4
-rw-r--r-- 1 root root 1929184 Mar 17 19:36 /usr/lib/arm-linux-gnueabihf/libprotoc.so.23.0.4
```

apt list:
```
root@4a00714193b1:/code/onnx# apt list --installed

cmake/jammy,now 3.22.1-1ubuntu1 armhf [installed]
...
libprotobuf-dev/jammy,now 3.12.4-1ubuntu7 armhf [installed]
libprotobuf-lite23/jammy,now 3.12.4-1ubuntu7 armhf [installed,automatic]
libprotobuf23/jammy,now 3.12.4-1ubuntu7 armhf [installed,automatic]
libprotoc23/jammy,now 3.12.4-1ubuntu7 armhf [installed,automatic]
```

### Reproduction instructions
The command to build:
```sh
git clone --single-branch --branch v1.10.0 https://github.com/onnx/onnx
cd onnx
python3 setup.py bdist_wheel
```

**Comment by jcwchen** [comment]
Hi @jji2019,
How did you build Protobuf? If you build Protobuf from source, please use `export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=OFF"` (this is the default config btw). If you install Protobuf from Conda or apt-get, please use `export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON"` instead. Let me know if you still bump into other errors. Thanks!

**Comment by jji2019** [comment]
I use ```apt install protobuf-compiler libprotobuf-dev```, but still see the error with arguments set as on.

Argument:
```sh
root@4a00714193b1:/code/onnx# echo $CMAKE_ARGS
-DONNX_USE_PROTOBUF_SHARED_LIBS=ON -DUSE_PROTOBUF_SHARED_LIBS=ON
```

Build log:
```sh
root@4a00714193b1:/code/onnx# python3 setup.py bdist_wheel
/usr/local/lib/python3.7/site-packages/setuptools/dist.py:775: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
  % (opt, underscore_opt)
/usr/local/lib/python3.7/site-packages/setuptools/config/setupcfg.py:463: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
  warnings.warn(msg, warning_class)
/usr/local/lib/python3.7/site-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  SetuptoolsDeprecationWarning,
running bdist_wheel
running build
running build_py
running create_version
running cmake_build
Extra cmake args: ['-DONNX_USE_PROTOBUF_SHARED_LIBS=ON', '-DUSE_PROTOBUF_SHARED_LIBS=ON']
Using cmake args: ['/usr/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/local/include/python3.7m', '-DPYTHON_EXECUTABLE=/usr/local/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-37m-arm-linux-gnueabihf.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '-DONNX_USE_PROTOBUF_SHARED_LIBS=ON', '-DUSE_PROTOBUF_SHARED_LIBS=ON', '/code/onnx']
Generated: /code/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
Generated: /code/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
Generated: /code/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
-- Found pybind11: /usr/local/lib/python3.7/site-packages/pybind11/include (found version "2.9.2")
-- 
-- ******** Summary ********
--   CMake version             : 3.22.1
--   CMake command             : /usr/bin/cmake
--   System                    : Linux
--   C++ compiler              : /usr/bin/c++
--   C++ compiler version      : 11.2.0
--   CXX flags                 :  -Wnon-virtual-dtor
--   Build type                : Release
--   Compile definitions       : 
--   CMAKE_PREFIX_PATH         : 
--   CMAKE_INSTALL_PREFIX      : /usr/local
--   CMAKE_MODULE_PATH         : 
-- 
--   ONNX version              : 1.10.0
--   ONNX NAMESPACE            : onnx
--   ONNX_USE_LITE_PROTO       : OFF
--   USE_PROTOBUF_SHARED_LIBS  : ON
--   Protobuf_USE_STATIC_LIBS  : OFF
--   ONNX_DISABLE_EXCEPTIONS   : OFF
--   ONNX_WERROR               : OFF
--   ONNX_BUILD_TESTS          : OFF
--   ONNX_BUILD_BENCHMARKS     : OFF
--   ONNXIFI_DUMMY_BACKEND     : OFF
--   ONNXIFI_ENABLE_EXT        : OFF
-- 
--   Protobuf compiler         : /usr/bin/protoc
--   Protobuf includes         : /usr/include
--   Protobuf libraries        : /usr/lib/arm-linux-gnueabihf/libprotobuf.a
--   BUILD_ONNX_PYTHON         : ON
--     Python version        : 
--     Python executable     : /usr/local/bin/python3
--     Python includes       : /usr/local/include/python3.7m
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    USE_PROTOBUF_SHARED_LIBS


-- Build files have been written to: /code/onnx/.setuptools-cmake-build
Consolidate compiler generated dependencies of target onnxifi_loader
Consolidate compiler generated dependencies of target onnxifi_dummy
[  2%] Built target gen_onnx_proto
[  5%] Built target onnxifi_loader
[  8%] Built target onnxifi_dummy
Consolidate compiler generated dependencies of target onnx_proto
Consolidate compiler generated dependencies of target onnxifi_wrapper
[ 11%] Built target onnxifi_wrapper
[ 26%] Built target onnx_proto
Consolidate compiler generated dependencies of target onnx
[ 97%] Built target onnx
Consolidate compiler generated dependencies of target onnx_cpp2py_export
[ 98%] Linking CXX shared module onnx_cpp2py_export.cpython-37m-arm-linux-gnueabihf.so
/usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0x7cc): R_ARM_TLS_LE32 relocation not permitted in shared object
/usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o): in function `google::protobuf::internal::ArenaImpl::Init()':
(.text+0x7cc): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0x86c): R_ARM_TLS_LE32 relocation not permitted in shared object
/usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o): in function `google::protobuf::internal::ArenaImpl::GetSerialArenaFallback(void*)':
(.text+0x86c): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0x8ac): R_ARM_TLS_LE32 relocation not permitted in shared object
/usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o): in function `google::protobuf::internal::ArenaImpl::GetSerialArena()':
(.text+0x8ac): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0x9cc): R_ARM_TLS_LE32 relocation not permitted in shared object
/usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o): in function `google::protobuf::internal::ArenaImpl::AllocateAlignedFallback(unsigned int)':
(.text+0x9cc): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0xa64): R_ARM_TLS_LE32 relocation not permitted in shared object
/usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o): in function `google::protobuf::internal::ArenaImpl::AddCleanupFallback(void*, void (*)(void*))':
(.text+0xa64): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0xac0): R_ARM_TLS_LE32 relocation not permitted in shared object
/usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o): in function `google::protobuf::internal::ArenaImpl::AddCleanup(void*, void (*)(void*))':
(.text+0xac0): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0xbf0): R_ARM_TLS_LE32 relocation not permitted in shared object
/usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o): in function `google::protobuf::internal::ArenaImpl::AllocateAlignedAndAddCleanupFallback(unsigned int, void (*)(void*))':
(.text+0xbf0): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0xd4c): R_ARM_TLS_LE32 relocation not permitted in shared object
/usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o): in function `google::protobuf::internal::ArenaImpl::AllocateAlignedAndAddCleanup(unsigned int, void (*)(void*))':
(.text+0xd4c): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0xeb0): R_ARM_TLS_LE32 relocation not permitted in shared object
/usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o): in function `google::protobuf::Arena::AllocateAlignedNoHook(unsigned int)':
(.text+0xeb0): dangerous relocation: unsupported relocation
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/onnx_cpp2py_export.dir/build.make:101: onnx_cpp2py_export.cpython-37m-arm-linux-gnueabihf.so] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:227: CMakeFiles/onnx_cpp2py_export.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 361, in <module>
    'backend-test-tools = onnx.backend.test.cmd_tools:main',
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 177, in setup
    return run_commands(dist)
  File "/usr/local/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
    dist.run_commands()
  File "/usr/local/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/usr/local/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/build.py", line 24, in run
    super().run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/usr/local/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "setup.py", line 233, in run
    self.run_command('cmake_build')
  File "/usr/local/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "setup.py", line 227, in run
    subprocess.check_call(build_args)
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '.', '--', '-j', '8']' returned non-zero exit status 2.
```

**Comment by zoldaten** [comment]
hi!
following steps above i removed protobuf installed with apt-get install.
Then i built it (protobuf) from source.
After that i tried to install onnx but got error:
```
pi@raspberrypi:~/onnx $ pip install -e .
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Obtaining file:///home/pi/onnx
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/pi/onnx/setup.py", line 92
        raise RuntimeError(f"Can only cd to absolute path, got: {path}")
                                                                      ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/pi/onnx/
```
how to fix it ?

**Comment by zoldaten** [comment]
ok. solved. that was a setuptools issue.
the last command should be:
```python3 -m pip install```
not:
```pip install -e .```

moreover i installed pybind11:
```pip install "pybind11[global]"```

and finally i got import error:
```
pi@raspberrypi:~/onnx $ python -c "import onnx"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pi/onnx/onnx/__init__.py", line 6, in <module>
    from .onnx_cpp2py_export import ONNX_ML
ImportError: cannot import name 'ONNX_ML' from 'onnx.onnx_cpp2py_export' (unknown location)
```
which should be fixed by add to ~/.bashrc (sudo nano ~/.bashrc):
```export LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1```

and reread ~/.bashrc:
```source ~/.bashrc```
