### ISSUE TITLE
RuntimeError: 0INTERNAL ASSERT FAILED at "C:\\actions-runner\\_work\\pytorch\\pytorch\\builder\\windows\\pytorch\\torch\\csrc\\jit\\ir\\alias_analysis.cpp":607

### ISSUE THREAD

**Issue by liushifu12138** [onnx/onnx#4348]
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\EMOCA\test_emoca_on_images.py", line 143, in <module>
    main()
  File "C:\Users\Admin\Desktop\EMOCA\test_emoca_on_images.py", line 111, in main
    torch.onnx.export(emoca, batch, "model.onnx", export_params=True,
  File "C:\Users\Admin\anaconda3\envs\pytorch3d\lib\site-packages\torch\onnx\__init__.py", line 305, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "C:\Users\Admin\anaconda3\envs\pytorch3d\lib\site-packages\torch\onnx\utils.py", line 118, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "C:\Users\Admin\anaconda3\envs\pytorch3d\lib\site-packages\torch\onnx\utils.py", line 719, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "C:\Users\Admin\anaconda3\envs\pytorch3d\lib\site-packages\torch\onnx\utils.py", line 499, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "C:\Users\Admin\anaconda3\envs\pytorch3d\lib\site-packages\torch\onnx\utils.py", line 440, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "C:\Users\Admin\anaconda3\envs\pytorch3d\lib\site-packages\torch\onnx\utils.py", line 391, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "C:\Users\Admin\anaconda3\envs\pytorch3d\lib\site-packages\torch\jit\_trace.py", line 1166, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\envs\pytorch3d\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Admin\anaconda3\envs\pytorch3d\lib\site-packages\torch\jit\_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
RuntimeError: 0INTERNAL ASSERT FAILED at "C:\\actions-runner\\_work\\pytorch\\pytorch\\builder\\windows\\pytorch\\torch\\csrc\\jit\\ir\\alias_analysis.cpp":607, please report a bug to PyTorch. We don't have an op for aten::eq but it isn't a special case.  Argument types: Tensor, bool, 

Candidates:
	aten::eq.Tensor(Tensor self, Tensor other) -> (Tensor)
	aten::eq.Scalar(Tensor self, Scalar other) -> (Tensor)
	aten::eq.Scalar_out(Tensor self, Scalar other, *, Tensor(a!) out) -> (Tensor(a!))
	aten::eq.Tensor_out(Tensor self, Tensor other, *, Tensor(a!) out) -> (Tensor(a!))
	aten::eq.int_list(int[] a, int[] b) -> (bool)
	aten::eq.device(Device a, Device b) -> (bool)
	aten::eq.bool(bool a, bool b) -> (bool)
	aten::eq.enum(AnyEnumType a, AnyEnumType b) -> (bool)
	aten::eq.int(int a, int b) -> (bool)
	aten::eq.complex(complex a, complex b) -> (bool)
	aten::eq.float(float a, float b) -> (bool)
	aten::eq.int_float(int a, float b) -> (bool)
	aten::eq.float_int(float a, int b) -> (bool)
	aten::eq.float_complex(float a, complex b) -> (bool)
	aten::eq.complex_float(complex a, float b) -> (bool)
	aten::eq(Scalar a, Scalar b) -> (bool)
	aten::eq.str(str a, str b) -> (bool)
	aten::eq.float_list(float[] a, float[] b) -> (bool)
	aten::eq.Tensor_list(Tensor[] a, Tensor[] b) -> (bool)
	aten::eq.bool_list(bool[] a, bool[] b) -> (bool)
	aten::eq.str_list(str[] a, str[] b) -> (bool)

**Comment by jcwchen** [comment]
Hi @liushifu12138,
I think it should be a question for the converter (`torch.onnx.export`) since this error happened during the conversion. Please raise this issue in the converter repo instead (under PyTorch) to get better assistance from the converter experts. I will close this one. Feel free to reopen it if you still have other ONNX questions.
