### ISSUE TITLE
ERROR: Command errored out with exit status 1

### ISSUE THREAD

**Issue by ojipadeson** [onnx/onnx#4449]
# Bug Report

### Describe the bug
Error when install onnx from source.
```
CMakeFiles/onnx.dir/build.make:854: recipe for target 'CMakeFiles/onnx.dir/onnx/defs/shape_inference.cc.o' failed
make[2]: *** [CMakeFiles/onnx.dir/onnx/defs/shape_inference.cc.o] Error 1
CMakeFiles/onnx.dir/build.make:734: recipe for target 'CMakeFiles/onnx.dir/onnx/defs/reduction/old.cc.o' failed
make[2]: *** [CMakeFiles/onnx.dir/onnx/defs/reduction/old.cc.o] Error 1
# ......
CMakeFiles/onnx.dir/build.make:902: recipe for target 'CMakeFiles/onnx.dir/onnx/defs/tensor/old.cc.o' failed
make[2]: *** [CMakeFiles/onnx.dir/onnx/defs/tensor/old.cc.o] Error 1
CMakeFiles/onnx.dir/build.make:1118: recipe for target 'CMakeFiles/onnx.dir/onnx/version_converter/convert.cc.o' failed
make[2]: *** [CMakeFiles/onnx.dir/onnx/version_converter/convert.cc.o] Error 1
CMakeFiles/Makefile2:313: recipe for target 'CMakeFiles/onnx.dir/all' failed
make[1]: *** [CMakeFiles/onnx.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
EasyInstallDeprecationWarning,
/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
setuptools.SetuptoolsDeprecationWarning,
```

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): 
- ONNX version (*e.g. 1.7*):  
- Python version: 3.6.9
- GCC/Compiler version (if compiling from source): 7.5.0
- CMake version: 3.10.2
- Protobuf version: libprotoc 3.0.0

### Reproduction instructions

```
git clone https://github.com/onnx/onnx.git
cd onnx
git submodule update --init --recursive
# Optional: prefer lite proto
export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON"
export CMAKE_ARGS=-DONNX_USE_LITE_PROTO=ON
pip install -e .
```

### Expected behavior
Build success.

### Notes
In a docker

**Comment by jcwchen** [comment]
Hi @ojipadeson,
If possible, could you please share more error messages? Also, please remove `export CMAKE_ARGS=-DONNX_USE_LITE_PROTO=ON` and simply use `export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON"` if you are using protobuf 3.0.0 from apt-get, because ONNX's `ONNX_USE_LITE_PROTO` does not support protoc 3.0.0.

**Comment by ojipadeson** [comment]
@jcwchen I simply use ```export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON"```, and output and error logs are as follows:

**Output**
```
        ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/data_1/oji/Transfer/onnx/setup.py'"'"'; __file__='"'"'/data_1/oji/Transfer/onnx/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /data_1/oji/Transfer/onnx/
    Complete output (99 lines):
    running develop
    running build_py
    running create_version
    running cmake_build
    Extra cmake args: ['-DONNX_USE_PROTOBUF_SHARED_LIBS=ON']
    Using cmake args: ['/usr/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.6m', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-36m-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '-DONNX_USE_PROTOBUF_SHARED_LIBS=ON', '/data_1/oji/Transfer/onnx']
    Generated: /data_1/oji/Transfer/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
    Generated: /data_1/oji/Transfer/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
    Generated: /data_1/oji/Transfer/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
    -- Could NOT find pybind11 (missing: pybind11_DIR)
    -- pybind11 v2.9.1
    --
    -- ******** Summary ********
    --   CMake version             : 3.10.2
    --   CMake command             : /usr/bin/cmake
    --   System                    : Linux
    --   C++ compiler              : /usr/bin/c++
    --   C++ compiler version      : 7.5.0
    --   CXX flags                 :  -Wnon-virtual-dtor
    --   Build type                : Release
    --   Compile definitions       : __STDC_FORMAT_MACROS
    --   CMAKE_PREFIX_PATH         :
    --   CMAKE_INSTALL_PREFIX      : /usr/local
    --   CMAKE_MODULE_PATH         :
    --
    --   ONNX version              : 1.12.0
    --   ONNX NAMESPACE            : onnx
    --   ONNX_USE_LITE_PROTO       : OFF
    --   USE_PROTOBUF_SHARED_LIBS  : ON
    --   Protobuf_USE_STATIC_LIBS  : OFF
    --   ONNX_DISABLE_EXCEPTIONS   : OFF
    --   ONNX_WERROR               : OFF
    --   ONNX_BUILD_TESTS          : OFF
    --   ONNX_BUILD_BENCHMARKS     : OFF
    --   ONNXIFI_DUMMY_BACKEND     : OFF
    --   ONNXIFI_ENABLE_EXT        : OFF
    --
    --   Protobuf compiler         : /usr/bin/protoc
    --   Protobuf includes         : /usr/include
    --   Protobuf libraries        : /usr/lib/x86_64-linux-gnu/libprotobuf.a;-lpthread
    --   BUILD_ONNX_PYTHON         : ON
    --     Python version        :
    --     Python executable     : /usr/bin/python3
    --     Python includes       : /usr/include/python3.6m
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /data_1/oji/Transfer/onnx/.setuptools-cmake-build
    [  8%] Built target gen_onnx_proto
    [  8%] Built target onnxifi_loader
    [  8%] Built target onnxifi_dummy
    [ 14%] Built target gen_onnx_data_proto
    [ 14%] Built target gen_onnx_operators_proto
    [ 18%] Built target onnxifi_wrapper
    [ 30%] Built target onnx_proto
    [ 97%] Built target onnx
    [ 98%] Linking CXX shared module onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so
```

**Error Log**
```
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(arena.o): relocation R_X86_64_TPOFF32 against hidden symbol `_ZN6google8protobuf5Arena13thread_cache_E' can not be used when making a shared object
    /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(descriptor.o): relocation R_X86_64_PC32 against symbol `_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EED1Ev' can not be used when making a shared object; recompile with -fPIC
    /usr/bin/ld: final link failed: Bad value
    collect2: error: ld returned 1 exit status
    CMakeFiles/onnx_cpp2py_export.dir/build.make:98: recipe for target 'onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so' failed
    make[2]: *** [onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so] Error 1
    CMakeFiles/Makefile2:351: recipe for target 'CMakeFiles/onnx_cpp2py_export.dir/all' failed
    make[1]: *** [CMakeFiles/onnx_cpp2py_export.dir/all] Error 2
    Makefile:129: recipe for target 'all' failed
    make: *** [all] Error 2
    /usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      EasyInstallDeprecationWarning,
    /usr/local/lib/python3.6/dist-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data_1/oji/Transfer/onnx/setup.py", line 366, in <module>
        "backend-test-tools = onnx.backend.test.cmd_tools:main",
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/data_1/oji/Transfer/onnx/setup.py", line 248, in run
        self.run_command("build_py")
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/data_1/oji/Transfer/onnx/setup.py", line 233, in run
        self.run_command("cmake_build")
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File /data_1/oji/Transfer/onnx/setup.py", line 227, in run
        subprocess.check_call(build_args)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '.', '--', '-j', '64']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/data_1/oji/Transfer/onnx/setup.py'"'"'; __file__='"'"'/data_1/oji/Transfer/onnx/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

**Comment by jcwchen** [comment]
Thanks for providing more details! Similar to this issue #3570.

3 options to solve this:
1. https://github.com/onnx/onnx/issues/3570#issuecomment-885757750 Remove previous protoc and run
```
apt-get install libprotobuf-dev protobuf-compiler
export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON"
```
Please note that the order of `libprotobuf-dev protobuf-compiler` matters here.

2. If you can use conda, simply install higher protoc version (libprotobuf) there and use `export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON"` to build ONNX.
3. If you are happy to build Protobuf from source, please follow the steps [here](https://github.com/onnx/onnx#linux) (click Installing Protobuf from source). And you will need `export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=OFF"` to build ONNX.

**Comment by ojipadeson** [comment]
@jcwchen Thanks for your help! The 3rd option build ONNX successfully.

The first option still seems to install the incorrect version of protobuf and causes the onnx installation to report an error, here is the output of ```apt-get install libprotobuf-dev protobuf-compiler```:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  libprotobuf-dev protobuf-compiler
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 983 kB of archives.
After this operation, 8226 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 libprotobuf-dev amd64 3.0.0-9.1ubuntu1 [959 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/universe amd64 protobuf-compiler amd64 3.0.0-9.1ubuntu1 [24.5 kB]
Fetched 983 kB in 3s (369 kB/s)             
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libprotobuf-dev:amd64.
(Reading database ... 22400 files and directories currently installed.)
Preparing to unpack .../libprotobuf-dev_3.0.0-9.1ubuntu1_amd64.deb ...
Unpacking libprotobuf-dev:amd64 (3.0.0-9.1ubuntu1) ...
Selecting previously unselected package protobuf-compiler.
Preparing to unpack .../protobuf-compiler_3.0.0-9.1ubuntu1_amd64.deb ...
Unpacking protobuf-compiler (3.0.0-9.1ubuntu1) ...
Setting up protobuf-compiler (3.0.0-9.1ubuntu1) ...
Setting up libprotobuf-dev:amd64 (3.0.0-9.1ubuntu1) ...
```

**Comment by ojipadeson** [comment]
@jcwchen A new problem has emerged
```
Traceback (most recent call last):
  File "../tools/script/fastTestOnnx.py", line 5, in <module>
    import onnx
  File "/data_nas/fangrui/TransferMNN/onnx/onnx/__init__.py", line 6, in <module>
    from .onnx_cpp2py_export import ONNX_ML
ImportError: /data_nas/fangrui/TransferMNN/onnx/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf7Message9SpaceUsedEv
```
The issue is similar to [#745](https://github.com/onnx/onnx/issues/745), but I cannot execute my file in onnx_tensorrt directory. Is there any other solution?

**Comment by jcwchen** [comment]
If you simply import onnx without import onnx_tensorrt, is there any issue? It seems there is a Protobuf conflict issue. Did you get onnx_tensorrt from PyPI or build it from source? Besides, Have you removed all installed Protobuf before installing Protobuf from source?

**Comment by ojipadeson** [comment]
I've changed my environment to onnx docker for now, and will look into this when I get a chance. Thanks for your help!
