### ISSUE TITLE
Failed to check converted float16 model

### ISSUE THREAD

**Issue by seungtaek94** [onnx/onnx#4480]
# Ask a Question

### Question

Hi. I try to convert fp32 superpoint model to fp16 using [onnxconverter-common](https://github.com/microsoft/onnxconverter-common).

But failed to convert with following message.
```
Traceback (most recent call last):
  File "/home/seungtaek/superpoint/convertonnxfloat2float16.py", line 31, in <module>
    onnx.checker.check_model(onnx_model16)
  File "/home/seungtaek/anaconda3/envs/pytorch_build/lib/python3.9/site-packages/onnx/checker.py", line 106, in check_model
    C.check_model(protobuf_string)
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'TopK_111_input_cast_0' of node: 
name: TopK_111 OpType: TopK
 is not output of any previous nodes.
```

Details of issues are below:
https://github.com/microsoft/onnxconverter-common/issues/240#issue-1358192493

How can I solve this problem?

### Further information
- Relevant Area: converters

- Is this issue related to a specific model?  
**Model name**:  superpoint
**Model opset**:  16

**Comment by seungtaek94** [comment]
@jcwchen 

Thanks for reply :)

> Hi @seungtaek94, ONNX IR requires the nodes be to topological-sorted. See the doc [here](https://github.com/onnx/onnx/blob/main/docs/IR.md#graphs). So I would say it should be a question for the tool in onnxconverter-common. The converted ONNX model should be topological-sorted after conversion.
