### ISSUE TITLE
ONNX OpenCV DNN

### ISSUE THREAD

**Issue by gonulsinem** [onnx/onnx#4647]
Hi,

**System Information**
Python 3.8.0
OpenCV version: '4.6.0'
OS : Windows10

**Detailed description**
I trained the Yolov5 model on my own custom dataset.
I converted ".pt" file to ONNX file. The ONNX model I created works fine.
I converted ONNX file to Quantize ONNX file. It cannot read the file "yolov5n_quant.onnx" that I created.
The error is as follows.

onnx for ONNX OpenCV DNN inference...
[ERROR:0@2.773] global D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onn_importer.cpp (1021) cv::dnn::dnn4_v20220524::ONNXImporter::handleNode DNN/ONNX: Euring processing node with 1 inputs and 3 outputs: [DynamicQuantizeLinear]:(onnx_nages_QuantizeLinear) from domain='ai.onnx'
Traceback (most recent call last):
File "g:/yolov5-master/detect.py", line 252, in
main(opt)
File "g:/yolov5-master/detect.py", line 247, in main
run(**vars(opt))
File "C:\Users\anaconda3\envs\yolov5\lib\site-packages\torch\autograd\gradpy", line 28, in decorate_context
init
net = cv2.dnn.readNetFromONNX(w)
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\o> Node [[DynamicQuantizeLinear@ai.onnx](mailto:DynamicQuantizeLinear@ai.onnx)]:(onnx_node!images_QuantizeLinear) parse errscale not found in const blobs in function 'cv::dnn::dnnscale not found in const b4_v20220524::ONNXImporter::getBlob'

**Comment by XantaKross** [comment]
Hey!

Have you found a workaround yet?
