### ISSUE TITLE
onnx.parser.ParseError: b"[ParseError at position (line: 4 column: 25)]\nError context:

### ISSUE THREAD

**Issue by chayliu1991** [onnx/onnx#4682]
onnx version:1.12.0

```
import onnx.parser
from onnx.checker import check_model

input = '''
    <
        ir_version: 8,
        opset_import: [ '' : 15]
    >
    agraph (float[I,J] X, float[I] A, float[I] B) => (float[I] Y) {
        XA = MatMul(X, A)
        Y = Add(XA, B)
    }
    '''
onnx_model = onnx.parser.parse_model(input)
check_model(onnx_model)

print(onnx_model)
```

error:
```
Traceback (most recent call last):
  File "/data/share/onnx/ONNX with Python/test.py", line 14, in <module>
    onnx_model = onnx.parser.parse_model(input)
  File "/home/lcy/miniconda3/lib/python3.9/site-packages/onnx/parser.py", line 22, in parse_model
    raise ParseError(msg)
onnx.parser.ParseError: b"[ParseError at position (line: 4 column: 25)]\nError context:         opset_import: [ '' : 15]\nString value expected, but not found."
```

**Comment by gramalingam** [comment]
Can you try using double-quotes instead of single-quotes? That is, `[ "" : 15]`
