### ISSUE TITLE
`printable_attribute` crashes when value of "Constant" is type uint8.

### ISSUE THREAD

**Issue by BowenBao** [onnx/onnx#4825]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug
`printable_attribute` crashes when value of "Constant" is type uint8.

### Reproduction instructions
```python
import onnxscript
from onnxscript import opset17 as op


@onnxscript.script()
def repro(x: onnxscript.FLOAT):
    y_scale = op.Constant(value_float=1.0)
    y_zero_point = op.Constant(
        value=numpy_helper.from_array(np.array(1, dtype=np.uint8))
    )
    return op.QuantizeLinear(x, y_scale, y_zero_point), y_scale, y_zero_point

print(repro.function_ir)
```

Error log
```
Traceback (most recent call last):
  File "repro_jan_ort2.py", line 17, in <module>
    print(repro.function_ir)
  File "/home/bowbao/onnx-script/onnxscript/irbuilder.py", line 214, in __str__
    stmts = _format(self.stmts, "\n{\n   ", "\n   ", "\n}\n")
  File "/home/bowbao/onnx-script/onnxscript/irbuilder.py", line 30, in _format
    return prefix + sep.join([formatter(x) for x in seq]) + suffix
  File "/home/bowbao/onnx-script/onnxscript/irbuilder.py", line 30, in <listcomp>
    return prefix + sep.join([formatter(x) for x in seq]) + suffix
  File "/home/bowbao/onnx-script/onnxscript/irbuilder.py", line 155, in __str__
    attrs = _format(self.attrs, "<", ", ", ">")
  File "/home/bowbao/onnx-script/onnxscript/irbuilder.py", line 30, in _format
    return prefix + sep.join([formatter(x) for x in seq]) + suffix
  File "/home/bowbao/onnx-script/onnxscript/irbuilder.py", line 30, in <listcomp>
    return prefix + sep.join([formatter(x) for x in seq]) + suffix
  File "/home/bowbao/onnx-script/onnxscript/irbuilder.py", line 121, in __str__
    return helper.printable_attribute(self.attr_proto)
  File "/home/bowbao/anaconda3/envs/torch38/lib/python3.8/site-packages/onnx/helper.py", line 817, in printable_attribute
    field = STORAGE_TENSOR_TYPE_TO_FIELD[attr.t.data_type]
KeyError: 2
```
### Expected behavior
Readable graph printed.

**Comment by jcwchen** [comment]
Hi @BowenBao,
I guess you are using an old version of ONNX? The latest ONNX won't bump into that error. Here is the result from my end (using ONNX 1.13.0):
```
repro (x : <class 'onnxscript.onnx_types.FLOAT'>) => (return_val0 : None, y_scale : None, y_zero_point : None)
{
   y_scale = Constant <value_float = 1>()
   y_zero_point = Constant <value = <Scalar Tensor []>>()
   return_val0 = QuantizeLinear (x, y_scale, y_zero_point)
}
```

Still, currently printable_attribute is not able to print a tensor value from raw_data so the tensor show empty here: `<Scalar Tensor []>`.

**Comment by BowenBao** [comment]
Thanks @jcwchen, you are right! I swapped to ONNX 1.12 for testing some other stuff. ONNX 1.13 produces the result you posted. Closing.
