### ISSUE TITLE
[Reference runtime] ReduceSum an integer is required (got type RefAttrName)

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#4850]
While running the gpt2 model:

```
ReduceSum(self_5, dim_13) -> result
F

================================ FAILURES =================================
_______________ TestFxToOnnxWithOnnxRuntime.test_gpt2_tiny ________________
Traceback (most recent call last):
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/onnx/reference/ops/op_reduce_sum.py", line 43, in _run
    res = np.sum(x, axis=axes, keepdims=keepdims, dtype=x.dtype)
  File "<__array_function__ internals>", line 180, in sum
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 2298, in sum
    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
TypeError: an integer is required (got type RefAttrName)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/onnx/reference/op_run.py", line 421, in run
    res = self._run(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/onnx/reference/op_run.py", line 574, in _run
    results = self.impl_.run(None, feeds, attributes=attributes)
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/onnx/reference/reference_evaluator.py", line 457, in run
    outputs = node.run(*inputs, **linked_attributes)
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/onnx/reference/ops/op_reduce_sum.py", line 20, in run
    res = self._run(x, axes=axes, keepdims=keepdims)
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/onnx/reference/ops/op_reduce_sum.py", line 46, in _run
    raise TypeError(
TypeError: Unable to reduce shape (1, 2, 3, 3) with axes=(-1,) and keepdims=RefAttrName('keepdim').

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/justinchu/dev/pytorch/test/onnx/test_fx_to_onnx_with_onnxruntime.py", line 126, in test_gpt2_tiny
    ort_outputs = self._run_ort(onnx_model, (input_ids, attention_mask))
  File "/home/justinchu/dev/pytorch/test/onnx/test_fx_to_onnx_with_onnxruntime.py", line 30, in _run_ort
    return session.run(
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/onnx/reference/reference_evaluator.py", line 457, in run
    outputs = node.run(*inputs, **linked_attributes)
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/onnx/reference/op_run.py", line 423, in run
    raise TypeError(
TypeError: Issues with types [<class 'numpy.ndarray'>, <class 'numpy.ndarray'>] and attributes ['dtype', 'keepdim'] and linked attributes=[] (operator 'OpFunction').
```

**Comment by justinchuby** [comment]
For some reason ReduceSum doesn't get `keepdims` for now I just patched below

Also the original `keepdims or self.keepdims` is unsafe because `False or True` is `True`

```python
class ReduceSum_1(OpRunReduceNumpy):
    def _run(self, x, axes=None, keepdims=True):  # type: ignore # pylint: disable=W0221
        axes = tuple(axes) if axes is not None else None
        return (np.sum(x, axis=axes, keepdims=keepdims, dtype=x.dtype),)


class ReduceSum_13(OpRunReduceNumpy):
    def run(self, x, axes=None, keepdims=True, **_):  # type: ignore
        keepdims = keepdims if keepdims is not None else self.keepdims  # type: ignore
        res = self._run(x, axes=axes, keepdims=keepdims)
        if res[0].dtype != x.dtype:
            raise RuntimeTypeError(
                f"Output type mismatch: input {x.dtype} != output {res[0].dtype} "
                f"(operator {self.__class__.__name__!r})."
            )
        return res

    def _run(self, x, axes=None, keepdims=True):  # type: ignore
        if (
            axes is None or len(axes.shape) == 0 or axes.shape[0] == 0
        ) and self.noop_with_empty_axes:  # type: ignore
            return (x,)
        if (
            axes is not None and len(axes.shape) > 0 and axes.shape[0] > 0
        ) and not isinstance(axes, int):
            if isinstance(axes, np.ndarray) and len(axes.shape) == 0:
                axes = int(axes)
            else:
                axes = tuple(axes.ravel().tolist()) if len(axes) > 0 else None
        if isinstance(axes, np.ndarray) and (len(axes.shape) == 0 or 0 in axes.shape):
            axes = None
        try:
            res = np.sum(x, axis=axes, keepdims=keepdims, dtype=x.dtype)
            return (res,)  # type: ignore
        except TypeError as e:
            raise TypeError(
                f"Unable to reduce shape {x.shape!r} with axes={axes!r} and keepdims={keepdims}."
            ) from e
```
