### ISSUE TITLE
Export to ONNX of SwinUNETR in the graph, it seems to be not supported.

### ISSUE THREAD

**Issue by JohnMasoner** [onnx/onnx#4898]
# Bug Report

### Is the issue related to model conversion?
Yes

### Describe the bug
Exporting to ONNX a very simple PyTorch model with a tensor.as_strided() operation, no warning or error is raised during the export, but the exported ONNX model is wrong.

Exporting to ONNX a MONAI [SwinUNETR](https://docs.monai.io/en/stable/networks.html#swinunetr), get some error. 

### System information

PyTorch version: 1.13.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0 11.3.0)
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

### Reproduction instructions
```python
import torch
from monai.networks.nets import SwinUNETR
model1 = SwinUNETR(img_size=(96,96), in_channels=3, out_channels=2, use_checkpoint=False, spatial_dims=2)
x = torch.randn(2, 3, 96, 96, requires_grad=True)
torch.onnx.export(model1,
                x,
                "model.onnx",
                )
```

```shell
>pip list | grep monai
monai                              1.1.0


>pip list | grep monai
onnx                               1.13.0
onnxruntime                        1.13.1
```

```shell
Traceback (most recent call last):
  File "torch2.py", line 18, in <module>
    opset_version =16,
  File "/home/xxx/.local/lib/python3.7/site-packages/torch/onnx/utils.py", line 519, in export
    export_modules_as_functions=export_modules_as_functions,
  File "/home/xxx/.local/lib/python3.7/site-packages/torch/onnx/utils.py", line 1539, in _export
    dynamic_axes=dynamic_axes,
  File "/home/xxx/.local/lib/python3.7/site-packages/torch/onnx/utils.py", line 1123, in _model_to_graph
    module=module,
  File "/home/xxx/.local/lib/python3.7/site-packages/torch/onnx/utils.py", line 663, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/home/xxx/.local/lib/python3.7/site-packages/torch/onnx/utils.py", line 1899, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File "/home/xxx/.local/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 380, in wrapper
    return fn(g, *args, **kwargs)
  File "/home/xxx/.local/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 288, in wrapper
    for arg, arg_desc, arg_name in zip(args, arg_descriptors, arg_names)
  File "/home/xxx/.local/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 288, in <listcomp>
    for arg, arg_desc, arg_name in zip(args, arg_descriptors, arg_names)
  File "/home/xxx/.local/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 109, in _parse_arg
    value,
torch.onnx.errors.SymbolicValueError: Failed to export a node '%2378 : Long(device=cpu) = onnx::Gather[axis=0](%2375, %2377), scope: monai.networks.nets.swin_unetr.SwinUNETR::/monai.networks.nets.swin_unetr.SwinTransformer::swinViT # /home/xxx/.local/lib/python3.7/site-packages/monai/networks/nets/swin_unetr.py:994:0
' (in list node %2408 : int[] = prim::ListConstruct(%2378), scope: monai.networks.nets.swin_unetr.SwinUNETR::/monai.networks.nets.swin_unetr.SwinTransformer::swinViT
) because it is not constant. Please try to make things (e.g. kernel sizes) static if possible.  [Caused by the value '2408 defined in (%2408 : int[] = prim::ListConstruct(%2378), scope: monai.networks.nets.swin_unetr.SwinUNETR::/monai.networks.nets.swin_unetr.SwinTransformer::swinViT
)' (type 'List[int]') in the TorchScript graph. The containing node has kind 'prim::ListConstruct'.] 

    Inputs:
        #0: 2378 defined in (%2378 : Long(device=cpu) = onnx::Gather[axis=0](%2375, %2377), scope: monai.networks.nets.swin_unetr.SwinUNETR::/monai.networks.nets.swin_unetr.SwinTransformer::swinViT # /home/xxx/.local/lib/python3.7/site-packages/monai/networks/nets/swin_unetr.py:994:0
    )  (type 'Tensor')
    Outputs:
        #0: 2408 defined in (%2408 : int[] = prim::ListConstruct(%2378), scope: monai.networks.nets.swin_unetr.SwinUNETR::/monai.networks.nets.swin_unetr.SwinTransformer::swinViT
    )  (type 'List[int]')
```

**Comment by JohnMasoner** [comment]
I find a similar problem in pytorch repo [#34780](https://github.com/pytorch/pytorch/issues/34780). 

i change the code
```python
x_shape = x.size()
```
to
```python
x_shape = [int(i) for i in x.size()]
```

make sure the `x_shape `is the list of int instead of `torch.Size()`.

l have solved the problem, but i don't know why.

I would greatly appreciate how someone could explain to me why this is.

Mason
