### ISSUE TITLE
convert_version

### ISSUE THREAD

**Issue by hmy-meng** [onnx/onnx#5140]
# Bug Report
error : 
Traceback (most recent call last):
  File "D:\yizhu_project\onnx_official\convert_opset.py", line 43, in <module>
    onnx_model = version_converter.convert_version(onnx_model, 15)
  File "C:\Users\hmy\anaconda3\lib\site-packages\onnx\version_converter.py", line 170, in convert_version
    converted_model_str = C.convert_version(model_str, target_version)
RuntimeError: D:\a\onnx\onnx\onnx\onnx/version_converter/adapters/transformers.h:30: operator (): Assertion `node->i(attr) == value` failed: Attribute spatial must have value 1

### System information
torch==1.13.1
onnx==1.13.1

### Reproduction instructions
<!--
- Describe the code to reproduce the behavior.
```
import onnx
onnx_model = onnx.load(r"vgg16-bn-7.onnx")
onnx_model = version_converter.convert_version(onnx_model, 15)

**Comment by hmy-meng** [comment]
from onnx import version_converter

onnx_model = onnx.load(r"models/vgg16-bn-7.onnx")
onnx_model = version_converter.convert_version(onnx_model, 15)
