### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by zhangguangzhi** [onnx/onnx#517]
I have installed onnx 
but when I execute 'python -c "import onnx"', I get the following error

bainuo@bainuo-SYS-7048GR-TR:~/protobuf-3.5.1$ python -c "import onnx"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/onnx/__init__.py", line 10, in <module>
    import onnx.helper  # noqa
  File "/usr/local/lib/python2.7/dist-packages/onnx/helper.py", line 15, in <module>
    import onnx.defs as defs
  File "/usr/local/lib/python2.7/dist-packages/onnx/defs/__init__.py", line 6, in <module>
    import onnx.onnx_cpp2py_export.defs as C
ImportError: /usr/local/lib/python2.7/dist-packages/onnx/onnx_cpp2py_export.so: undefined symbol: _ZNK6google8protobuf7Message13SpaceUsedLongEv

What is the reason?

**Comment by zhangguangzhi** [comment]
@bddppq

**Comment by zhangguangzhi** [comment]
I remove libprotobuf-dev without this error
