### ISSUE TITLE
onnx is throwing "ImportError: libprotobuf.so.21: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by armando-fandango** [onnx/onnx#5259]
this issue resurfaces with the following:
```
libprotobuf               3.21.12              h3eb15da_0    conda-forge
protobuf                  4.21.12          py38h8dc9893_0    conda-forge
onnx                      1.6.0            py38he1b5a44_0    conda-forge
```

The error:

```
python
Python 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:55) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/py/lib/python3.8/site-packages/onnx/__init__.py", line 8, in <module>
    from .onnx_cpp2py_export import ONNX_ML
ImportError: libprotobuf.so.21: cannot open shared object file: No such file or directory
```

_Originally posted by @armando-fandango in https://github.com/onnx/onnx/issues/2434#issuecomment-1563344665_

**Comment by jcwchen** [comment]
Hi @armando-fandango,
ONNX 1.6.0 is an old version which is not compatible with Protobuf v21. Starting ONNX 1.14.0 it is compatible with Protobuf v21. If you really want to use ONNX 1.6.0 for some reasons, you need to install older Protobuf version like 3.5.
