### ISSUE TITLE
Numpy helper's `from_dict` raises TypeError

### ISSUE THREAD

**Issue by andletenkov** [onnx/onnx#5522]
# Bug Report

### Describe the bug
`onnx.numpy_helper.from_dict` raises TypeError
### System information
- OS Platform and Distribution: macOS Monterey 12.5.1
- ONNX version: 1.14.0
- Python version: 3.11.4
- Protobuf version: 3.20.2

### Reproduction instructions
```
import onnx
map_proto = onnx.numpy_helper.from_dict({0: 0.1, 1: 0.9})
```
Raises following error:
```
Traceback (most recent call last):
  File "/Users/andrey.letenkov/proj/src/foo/bar.py", line 41, in <module>
    dummy = numpy_helper.from_dict({1: 0.1, 2: 0.9})
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey.letenkov/proj/.venv/lib/python3.11/site-packages/onnx/numpy_helper.py", line 449, in from_dict
    if not all(
           ^^^^
  File "/Users/andrey.letenkov/proj/.venv/lib/python3.11/site-packages/onnx/numpy_helper.py", line 450, in <genexpr>
    isinstance(
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
```

### Expected behavior
The function is able to create `MapProto` instance successfully.

**Comment by ClifHouck** [comment]
I believe the bug here has been addressed, however it should be noted that the motivating example is still invalid.

This dictionary will *not* be valid input for `from_dict`:
```python
{
  0: 0.1,
  1: 0.9,
}
```

This *will* work:
```python
{
  0: numpy.ndarray(0.1),
  1: numpy.ndarray(0.9),
}
```

Essentially, all values must be valid numpy types.

**Comment by andletenkov** [comment]
Hi @ClifHouck, the point regarding numpy types completely makes sense. Thank you!
