### ISSUE TITLE
Can't install it/build it source.

### ISSUE THREAD

**Issue by guranu** [onnx/onnx#5629]
Hello i can't seem to build/compile onnx i was wondering on how to fix it: 
```
~/onnx $ python setup.py install                        running install                                         /data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.             !!
        ********************************************************************************                                Please avoid running ``setup.py`` directly.             Instead, use pypa/build, pypa/installer or other        standards-based tools.
        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.                              ********************************************************************************
!!                                                        self.initialize_options()                             /data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.        !!
        ********************************************************************************                                Please avoid running ``setup.py`` and ``easy_install``.                                                         Instead, use pypa/build, pypa/installer or other        standards-based tools.
        See https://github.com/pypa/setuptools/issues/917 for details.                                                  ********************************************************************************
!!                                                        self.initialize_options()                             running bdist_egg                                       running egg_info                                        writing onnx.egg-info/PKG-INFO                          writing dependency_links to onnx.egg-info/dependency_links.txt                                                  writing entry points to onnx.egg-info/entry_points.txt  writing requirements to onnx.egg-info/requires.txt      writing top-level names to onnx.egg-info/top_level.txt  reading manifest file 'onnx.egg-info/SOURCES.txt'       reading manifest template 'MANIFEST.in'                 warning: no files found matching '*.c' under directory 'onnx'                                                   warning: no files found matching '*' under directory 'third_party'                                              adding license file 'LICENSE'                           writing manifest file 'onnx.egg-info/SOURCES.txt'       installing library code to build/bdist.linux-aarch64/eggrunning install_lib                                     running build_py                                        running build_ext                                       running cmake_build                                     Using cmake args: ['/data/data/com.termux/files/usr/bin/cmake', '-DPYTHON_INCLUDE_DIR=/data/data/com.termux/files/usr/include/python3.11', '-DPYTHON_EXECUTABLE=/data/data/com.termux/files/usr/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-311.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/data/data/com.termux/files/home/onnx']                                  CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):                                           Compatibility with CMake < 3.5 will be removed from a future version of                                         CMake.
  Update the VERSION argument <min> value or use a ...<max> suffix to tell                                        CMake that the project does not need compatibility with older versions.

CMake Warning (dev) at CMakeLists.txt:112 (find_package):                                                         Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules                                      are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use                                        the cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.
CMake Warning (dev) at CMakeLists.txt:114 (find_package):                                                         Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules                                      are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use                                        the cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.
Loading Dependencies URLs ...                           CMake Warning (dev) at /data/data/com.termux/files/usr/share/cmake-3.27/Modules/FetchContent.cmake:1316 (message):                                                        The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is                                       not set.  The policy's OLD behavior will be used.  When using a URL                                             download, the timestamps of extracted files should preferably be that of                                        the time of extraction, otherwise code that depends on the extracted                                            contents might not be rebuilt if the URL changes.  The OLD behavior                                             preserves the timestamps from the archive instead, but this is usually not                                      what you want.  Update your project to the NEW behavior or specify the                                          DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this                                            robustness issue.                                     Call Stack (most recent call first):                      CMakeLists.txt:238 (FetchContent_Declare)             This warning is for project developers.  Use -Wno-dev to suppress it.
-- Download and build Abseil from https://github.com/abseil/abseil-cpp/archive/refs/tags/20230125.3.tar.gz      -- Abseil source dir:/data/data/com.termux/files/home/onnx/.setuptools-cmake-build/_deps/abseil-src             CMake Warning (dev) at /data/data/com.termux/files/usr/share/cmake-3.27/Modules/FetchContent.cmake:1316 (message):                                                        The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is                                       not set.  The policy's OLD behavior will be used.  When using a URL                                             download, the timestamps of extracted files should preferably be that of                                        the time of extraction, otherwise code that depends on the extracted                                            contents might not be rebuilt if the URL changes.  The OLD behavior                                             preserves the timestamps from the archive instead, but this is usually not                                      what you want.  Update your project to the NEW behavior or specify the                                          DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this                                            robustness issue.                                     Call Stack (most recent call first):                      CMakeLists.txt:256 (FetchContent_Declare)             This warning is for project developers.  Use -Wno-dev to suppress it.
-- Download and build Protobuf from https://github.com/protocolbuffers/protobuf/releases/download/v22.3/protobuf-22.3.tar.gz                                            --                                                      -- 22.3.0                                               -- ONNX_PROTOC_EXECUTABLE: $<TARGET_FILE:protobuf::protoc>                                                      -- Protobuf_VERSION: 4.22.3                             Generated: /data/data/com.termux/files/home/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto                     Generated: /data/data/com.termux/files/home/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto           Generated: /data/data/com.termux/files/home/onnx/.setuptools-cmake-build/onnx/onnx-data.proto                   -- Could NOT find pybind11 (missing: pybind11_DIR)      CMake Error at CMakeLists.txt:561 (message):              cannot find pybind

-- Configuring incomplete, errors occurred!             Traceback (most recent call last):                        File "/data/data/com.termux/files/home/onnx/setup.py", line 327, in <module>                                      setuptools.setup(                                     File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup    return distutils.core.setup(**attrs)                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup                                                     return run_commands(dist)                                      ^^^^^^^^^^^^^^^^^^                             File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands                                              dist.run_commands()                                   File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands                                              self.run_command(cmd)                                 File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command                                                         super().run_command(command)                          File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command                                               cmd_obj.run()                                         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/command/install.py", line 84, in run                                                        self.do_egg_install()                                 File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/command/install.py", line 132, in do_egg_install                                            self.run_command('bdist_egg')                         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command                                                self.distribution.run_command(command)                File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command                                                         super().run_command(command)                          File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command                                               cmd_obj.run()                                         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/command/bdist_egg.py", line 167, in run                                                     cmd = self.call_command('install_lib', warn_dir=0)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command                                            self.run_command(cmdname)                             File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command                                                self.distribution.run_command(command)                File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command                                                         super().run_command(command)                          File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command                                               cmd_obj.run()                                         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/command/install_lib.py", line 11, in run                                                    self.build()                                          File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build                                      self.run_command('build_ext')                         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command                                                self.distribution.run_command(command)                File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command                                                         super().run_command(command)                          File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command                                               cmd_obj.run()                                         File "/data/data/com.termux/files/home/onnx/setup.py", line 264, in run                                           self.run_command("cmake_build")                       File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command                                                self.distribution.run_command(command)                File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command                                                         super().run_command(command)                          File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command                                               cmd_obj.run()                                         File "/data/data/com.termux/files/home/onnx/setup.py", line 235, in run                                           subprocess.check_call(cmake_args)                     File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 413, in check_call                      raise CalledProcessError(retcode, cmd)              subprocess.CalledProcessError: Command '['/data/data/com.termux/files/usr/bin/cmake', '-DPYTHON_INCLUDE_DIR=/data/data/com.termux/files/usr/include/python3.11', '-DPYTHON_EXECUTABLE=/data/data/com.termux/files/usr/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-311.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/data/data/com.termux/files/home/onnx']' returned non-zero exit status 1.
```

**Comment by justinchuby** [comment]
I can seem to find the error message? Could you point it out?

Also please use `pip install .` to install the package. We will include a note in the 1.15 release

**Comment by guranu** [comment]
> I can’t seem to find the error message? Could you point it out?
> 
> Also please use `pip install .` to install the package. We will include a note in the 1.15 release

it's already fixed.
