### ISSUE TITLE
I can't build a wheel.

### ISSUE THREAD

**Issue by Koris95** [onnx/onnx#5679]
I'm trying to install sd-webui-roop which requires webui-roop which requires onnx. It automatically attempts to install onnx but it fails. I used to get a 20 line error, which I fixed by `pip install cmake` but when attempting to install onnx, I still get an error, this time it's 71 lines long and it still has `ModuleNotFoundError: No module named 'cmake'`. I tried to manually check the `echo %PATH%` and found that the directory for cmake.exe is present, but the module is still not found, so I'm confused.

 **System information**
- Windows 10 Pro Version: 21H1 (OS Build 19043.1165)
- Python version: 3.12.0
- CMake version: 3.27.7
- Protobuf version: 4.24.4
- Visual Studio version: Visual Studio Community 2022 with Desktop Development with C++, Python, and Visual Studio Extension Development.

**Reproduction instructions**
Not sure if this is relevant but I use cmd and not python and I run these codes:
`pip install onnx`
or
`pip install insightface==0.7.3`

**Expected behavior**
The terminal prints that it fails to construct a wheel.

```
C:\Users\Work pc>pip install onnx
Collecting onnx
  Using cached onnx-1.14.1.tar.gz (11.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy (from onnx)
  Using cached numpy-1.26.1-cp312-cp312-win_amd64.whl.metadata (61 kB)
Requirement already satisfied: protobuf>=3.20.2 in c:\users\work pc\appdata\local\programs\python\python312\lib\site-packages (from onnx) (4.24.4)
Collecting typing-extensions>=3.6.2.1 (from onnx)
  Using cached typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Using cached numpy-1.26.1-cp312-cp312-win_amd64.whl (15.5 MB)
Building wheels for collected packages: onnx
  Building wheel for onnx (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for onnx (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [71 lines of output]
      running bdist_wheel
      running build
      running build_py
      running create_version
      running cmake_build
      Using cmake args: ['C:\\Users\\Work pc\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Users\\Work pc\\AppData\\Local\\Programs\\Python\\Python312\\include', '-DPYTHON_EXECUTABLE=C:\\Users\\Work pc\\AppData\\Local\\Programs\\Python\\Python312\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp312-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.12', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\Work pc\\AppData\\Local\\Temp\\pip-install-lgazppp5\\onnx_2292cbaf4ae7455a925b71603c299ccc']
      Traceback (most recent call last):
        File "<frozen runpy>", line 198, in _run_module_as_main
        File "<frozen runpy>", line 88, in _run_code
        File "C:\Users\Work pc\AppData\Local\Programs\Python\Python312\Scripts\cmake.exe\__main__.py", line 4, in <module>
      ModuleNotFoundError: No module named 'cmake'
      Traceback (most recent call last):
        File "C:\Users\Work pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Work pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Work pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Work pc\AppData\Local\Temp\pip-build-env-fpbbnmk3\overlay\Lib\site-packages\setuptools\build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Work pc\AppData\Local\Temp\pip-build-env-fpbbnmk3\overlay\Lib\site-packages\setuptools\build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\Work pc\AppData\Local\Temp\pip-build-env-fpbbnmk3\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\Work pc\AppData\Local\Temp\pip-build-env-fpbbnmk3\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 342, in <module>
        File "C:\Users\Work pc\AppData\Local\Temp\pip-build-env-fpbbnmk3\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Work pc\AppData\Local\Temp\pip-build-env-fpbbnmk3\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\Work pc\AppData\Local\Temp\pip-build-env-fpbbnmk3\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Work pc\AppData\Local\Temp\pip-build-env-fpbbnmk3\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\Work pc\AppData\Local\Temp\pip-build-env-fpbbnmk3\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\Work pc\AppData\Local\Temp\pip-build-env-fpbbnmk3\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Work pc\AppData\Local\Temp\pip-build-env-fpbbnmk3\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "C:\Users\Work pc\AppData\Local\Temp\pip-build-env-fpbbnmk3\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Work pc\AppData\Local\Temp\pip-build-env-fpbbnmk3\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\Work pc\AppData\Local\Temp\pip-build-env-fpbbnmk3\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Work pc\AppData\Local\Temp\pip-build-env-fpbbnmk3\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\Work pc\AppData\Local\Temp\pip-build-env-fpbbnmk3\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Work pc\AppData\Local\Temp\pip-build-env-fpbbnmk3\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\Work pc\AppData\Local\Temp\pip-build-env-fpbbnmk3\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 236, in run
        File "C:\Users\Work pc\AppData\Local\Temp\pip-build-env-fpbbnmk3\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Work pc\AppData\Local\Temp\pip-build-env-fpbbnmk3\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\Work pc\AppData\Local\Temp\pip-build-env-fpbbnmk3\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 222, in run
        File "C:\Users\Work pc\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Users\\Work pc\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Users\\Work pc\\AppData\\Local\\Programs\\Python\\Python312\\include', '-DPYTHON_EXECUTABLE=C:\\Users\\Work pc\\AppData\\Local\\Programs\\Python\\Python312\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp312-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.12', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\Work pc\\AppData\\Local\\Temp\\pip-install-lgazppp5\\onnx_2292cbaf4ae7455a925b71603c299ccc']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for onnx
Failed to build onnx
ERROR: Could not build wheels for onnx, which is required to install pyproject.toml-based projects
```

**Comment by justinchuby** [comment]
You may have more luck running with Python 3.11 since 3.12 is not officially supported yet.

**Comment by Koris95** [comment]
> You may have more luck running with Python 3.11 since 3.12 is not officially supported yet.

That worked perfectly, thank you very much!

**Comment by justinchuby** [comment]
#5680
