### ISSUE TITLE
Failed Building wheel for onnx 1.6.0 for python3.10

### ISSUE THREAD

**Issue by RuchitaTekade** [onnx/onnx#5867]
I am installing caffe2onnx in Python 3.10. and for that, I need onnx==1.6.0. While installing onnx 1.6.0, I am getting following error

```
Collecting onnx==1.6.0
  Using cached onnx-1.6.0.tar.gz (3.1 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from onnx==1.6.0) (1.26.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.10/dist-packages (from onnx==1.6.0) (3.20.3)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from onnx==1.6.0) (1.16.0)
Requirement already satisfied: typing-extensions>=3.6.2.1 in /usr/local/lib/python3.10/dist-packages (from onnx==1.6.0) (4.9.0)
Building wheels for collected packages: onnx
  Building wheel for onnx (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [148 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      /usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
        warnings.warn(
      /usr/lib/python3/dist-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      /usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      running create_version
      running cmake_build
      Extra cmake args: ['-DONNX_NAMESPACE=onnx']
      CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      -- The C compiler identification is GNU 11.4.0
      -- The CXX compiler identification is GNU 11.4.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so (found version "3.20.2")
      Generated: /tmp/pip-install-gwqh6n9o/onnx_1f26b84ba524493091f7e9cd84ede919/.setuptools-cmake-build/onnx/onnx-ml.proto
      Generated: /tmp/pip-install-gwqh6n9o/onnx_1f26b84ba524493091f7e9cd84ede919/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
      CMake Warning at CMakeLists.txt:394 (find_package):
        By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "pybind11",
        but CMake did not find one.
      
        Could not find a package configuration file provided by "pybind11"
        (requested version 2.2) with any of the following names:
      
          pybind11Config.cmake
          pybind11-config.cmake
      
        Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
        "pybind11_DIR" to a directory containing one of the above files.  If
        "pybind11" provides a separate development package or SDK, be sure it has
        been installed.
      
      
      --
      -- ******** Summary ********
      --   CMake version         : 3.28.1
      --   CMake command         : /usr/local/lib/python3.10/dist-packages/cmake/data/bin/cmake
      --   System                : Linux
      --   C++ compiler          : /usr/bin/c++
      --   C++ compiler version  : 11.4.0
      --   CXX flags             :  -Wnon-virtual-dtor
      --   Build type            : Release
      --   Compile definitions   :
      --   CMAKE_PREFIX_PATH     :
      --   CMAKE_INSTALL_PREFIX  : /usr/local
      --   CMAKE_MODULE_PATH     :
      --
      --   ONNX version          : 1.6.0
      --   ONNX NAMESPACE        : onnx
      --   ONNX_BUILD_TESTS      : OFF
      --   ONNX_BUILD_BENCHMARKS : OFF
      --   ONNX_USE_LITE_PROTO   : OFF
      --   ONNXIFI_DUMMY_BACKEND : OFF
      --   ONNXIFI_ENABLE_EXT    : OFF
      --
      --   Protobuf compiler     : /usr/bin/protoc
      --   Protobuf includes     : /usr/include
      --   Protobuf libraries    : /usr/lib/x86_64-linux-gnu/libprotobuf.so
      --   BUILD_ONNX_PYTHON     : ON
      --     Python version      :
      --     Python executable   : /usr/bin/python3
      --     Python includes     : /usr/include/python3.10
      -- Configuring done (0.3s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-gwqh6n9o/onnx_1f26b84ba524493091f7e9cd84ede919/.setuptools-cmake-build
      [  3%] Building C object CMakeFiles/onnxifi_dummy.dir/onnx/onnxifi_dummy.c.o
      [  3%] Running gen_proto.py on onnx/onnx.in.proto
      [  4%] Building C object CMakeFiles/onnxifi_loader.dir/onnx/onnxifi_loader.c.o
      /tmp/pip-install-gwqh6n9o/onnx_1f26b84ba524493091f7e9cd84ede919/onnx/onnxifi_dummy.c: In function ‘onnxGetExtensionFunctionAddress’:
      /tmp/pip-install-gwqh6n9o/onnx_1f26b84ba524493091f7e9cd84ede919/onnx/onnxifi_dummy.c:173:21: warning: assignment to ‘onnxExtensionFunctionPointer’ {aka ‘int (*)(void)’} from incompatible pointer type ‘onnxStatus (*)(void *, const char *, onnxStatus (**)(void))’ {aka ‘int (*)(void *, const char *, int (**)(void))’} [-Wincompatible-pointer-types]
        173 |           *function = &onnxGetExtensionFunctionAddress;
            |                     ^
      /tmp/pip-install-gwqh6n9o/onnx_1f26b84ba524493091f7e9cd84ede919/onnx/onnxifi_dummy.c:176:21: warning: assignment to ‘onnxExtensionFunctionPointer’ {aka ‘int (*)(void)’} from incompatible pointer type ‘onnxStatus (*)(void *, uint32_t,  const onnxTensorDescriptorV1 *, uint32_t,  const onnxTensorDescriptorV1 *, onnxMemoryFenceV1 *)’ {aka ‘int (*)(void *, unsigned int,  const onnxTensorDescriptorV1 *, unsigned int,  const onnxTensorDescriptorV1 *, onnxMemoryFenceV1 *)’} [-Wincompatible-pointer-types]
        176 |           *function = &onnxSetIOAndRunGraph;
            |                     ^
      Processing /tmp/pip-install-gwqh6n9o/onnx_1f26b84ba524493091f7e9cd84ede919/onnx/onnx.in.proto
      Writing /tmp/pip-install-gwqh6n9o/onnx_1f26b84ba524493091f7e9cd84ede919/.setuptools-cmake-build/onnx/onnx-ml.proto
      Writing /tmp/pip-install-gwqh6n9o/onnx_1f26b84ba524493091f7e9cd84ede919/.setuptools-cmake-build/onnx/onnx-ml.proto3
      generating /tmp/pip-install-gwqh6n9o/onnx_1f26b84ba524493091f7e9cd84ede919/.setuptools-cmake-build/onnx/onnx_pb.py
      [  6%] Linking C static library libonnxifi_loader.a
      [  8%] Running C++ protocol buffer compiler on /tmp/pip-install-gwqh6n9o/onnx_1f26b84ba524493091f7e9cd84ede919/.setuptools-cmake-build/onnx/onnx-ml.proto
      [  8%] Built target onnxifi_loader
      [  9%] Linking C shared library libonnxifi_dummy.so
      [ 11%] Building C object CMakeFiles/onnxifi_wrapper.dir/onnx/onnxifi_wrapper.c.o
      --python_out: onnx/onnx-ml.proto: Unknown generator option: dllexport_decl
      gmake[2]: *** [CMakeFiles/gen_onnx_proto.dir/build.make:74: onnx/onnx-ml.pb.cc] Error 1
      gmake[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/gen_onnx_proto.dir/all] Error 2
      gmake[1]: *** Waiting for unfinished jobs....
      [ 11%] Built target onnxifi_dummy
      [ 13%] Linking C shared module libonnxifi.so
      [ 13%] Built target onnxifi_wrapper
      gmake: *** [Makefile:136: all] Error 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-gwqh6n9o/onnx_1f26b84ba524493091f7e9cd84ede919/setup.py", line 315, in <module>
          setuptools.setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.10/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-gwqh6n9o/onnx_1f26b84ba524493091f7e9cd84ede919/setup.py", line 209, in run
          self.run_command('cmake_build')
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-gwqh6n9o/onnx_1f26b84ba524493091f7e9cd84ede919/setup.py", line 203, in run
          subprocess.check_call(build_args)
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '.', '--', '-j', '8']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for onnx
  Running setup.py clean for onnx
Failed to build onnx
ERROR: Could not build wheels for onnx, which is required to install pyproject.toml-based projects
```

**Comment by xadupre** [comment]
Can you share the command line you used to build onnx?

**Comment by MarkMendelsohn** [comment]
I have the same issue:

(base) MacMiniM1:tvm mpm$ python -m pip install -r requirements.txt 
Requirement already satisfied: numpy in /opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (1.26.4)
Collecting decorator (from -r requirements.txt (line 2))
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting attrs (from -r requirements.txt (line 3))
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting typing-extensions (from -r requirements.txt (line 4))
  Using cached typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
Collecting psutil (from -r requirements.txt (line 5))
  Using cached psutil-5.9.8-cp38-abi3-macosx_11_0_arm64.whl.metadata (21 kB)
Collecting scipy (from -r requirements.txt (line 6))
  Using cached scipy-1.12.0-cp310-cp310-macosx_12_0_arm64.whl.metadata (112 kB)
Collecting onnx==1.12.0 (from -r requirements.txt (line 7))
  Using cached onnx-1.12.0.tar.gz (10.1 MB)
  Preparing metadata (setup.py) ... done
Collecting onnxruntime==1.14.1 (from -r requirements.txt (line 9))
  Using cached onnxruntime-1.14.1-cp310-cp310-macosx_11_0_arm64.whl.metadata (3.9 kB)
Collecting onnxoptimizer==0.2.7 (from -r requirements.txt (line 11))
  Using cached onnxoptimizer-0.2.7-cp310-cp310-macosx_14_0_arm64.whl
Collecting onnx-simplifier==0.4.17 (from -r requirements.txt (line 12))
  Using cached onnx_simplifier-0.4.17-cp310-cp310-macosx_10_15_universal2.whl.metadata (4.3 kB)
Collecting protobuf<=3.20.1,>=3.12.2 (from onnx==1.12.0->-r requirements.txt (line 7))
  Using cached protobuf-3.20.1-cp310-cp310-macosx_10_9_universal2.whl (962 kB)
Collecting coloredlogs (from onnxruntime==1.14.1->-r requirements.txt (line 9))
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Collecting flatbuffers (from onnxruntime==1.14.1->-r requirements.txt (line 9))
  Using cached flatbuffers-23.5.26-py2.py3-none-any.whl.metadata (850 bytes)
Requirement already satisfied: packaging in /opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages (from onnxruntime==1.14.1->-r requirements.txt (line 9)) (23.2)
Collecting sympy (from onnxruntime==1.14.1->-r requirements.txt (line 9))
  Using cached sympy-1.12-py3-none-any.whl.metadata (12 kB)
Collecting rich (from onnx-simplifier==0.4.17->-r requirements.txt (line 12))
  Using cached rich-13.7.0-py3-none-any.whl.metadata (18 kB)
Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime==1.14.1->-r requirements.txt (line 9))
  Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Collecting markdown-it-py>=2.2.0 (from rich->onnx-simplifier==0.4.17->-r requirements.txt (line 12))
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich->onnx-simplifier==0.4.17->-r requirements.txt (line 12))
  Using cached pygments-2.17.2-py3-none-any.whl.metadata (2.6 kB)
Collecting mpmath>=0.19 (from sympy->onnxruntime==1.14.1->-r requirements.txt (line 9))
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->onnx-simplifier==0.4.17->-r requirements.txt (line 12))
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached onnxruntime-1.14.1-cp310-cp310-macosx_11_0_arm64.whl (5.8 MB)
Using cached onnx_simplifier-0.4.17-cp310-cp310-macosx_10_15_universal2.whl (3.2 MB)
Using cached attrs-23.2.0-py3-none-any.whl (60 kB)
Using cached typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Using cached psutil-5.9.8-cp38-abi3-macosx_11_0_arm64.whl (249 kB)
Using cached scipy-1.12.0-cp310-cp310-macosx_12_0_arm64.whl (31.4 MB)
Using cached flatbuffers-23.5.26-py2.py3-none-any.whl (26 kB)
Using cached rich-13.7.0-py3-none-any.whl (240 kB)
Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Using cached pygments-2.17.2-py3-none-any.whl (1.2 MB)
Building wheels for collected packages: onnx
  Building wheel for onnx (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [87 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      /opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      running build_py
      running create_version
      running cmake_build
      Using cmake args: ['/opt/homebrew/bin/cmake', '-DPYTHON_INCLUDE_DIR=/opt/homebrew/Caskroom/miniforge/base/include/python3.10', '-DPYTHON_EXECUTABLE=/opt/homebrew/Caskroom/miniforge/base/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-310-darwin.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/private/var/folders/2k/hr96tj9127x4_3ypczs4q6s80000gr/T/pip-install-8qebifzt/onnx_024efb6f15ef41819a1bc471cb019575']
      -- The C compiler identification is AppleClang 15.0.0.15000100
      -- The CXX compiler identification is AppleClang 15.0.0.15000100
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found PythonInterp: /opt/homebrew/Caskroom/miniforge/base/bin/python (found version "3.10.13")
      -- Found PythonLibs: /opt/homebrew/Caskroom/miniforge/base/lib/libpython3.10.dylib (found version "3.10.13")
      Generated: /private/var/folders/2k/hr96tj9127x4_3ypczs4q6s80000gr/T/pip-install-8qebifzt/onnx_024efb6f15ef41819a1bc471cb019575/.setuptools-cmake-build/onnx/onnx-ml.proto
      CMake Error at CMakeLists.txt:299 (message):
        Protobuf compiler not found
      Call Stack (most recent call first):
        CMakeLists.txt:330 (relative_protobuf_generate_cpp)
      
      
      -- Configuring incomplete, errors occurred!
      See also "/private/var/folders/2k/hr96tj9127x4_3ypczs4q6s80000gr/T/pip-install-8qebifzt/onnx_024efb6f15ef41819a1bc471cb019575/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
      See also "/private/var/folders/2k/hr96tj9127x4_3ypczs4q6s80000gr/T/pip-install-8qebifzt/onnx_024efb6f15ef41819a1bc471cb019575/.setuptools-cmake-build/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/2k/hr96tj9127x4_3ypczs4q6s80000gr/T/pip-install-8qebifzt/onnx_024efb6f15ef41819a1bc471cb019575/setup.py", line 332, in <module>
          setuptools.setup(
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/2k/hr96tj9127x4_3ypczs4q6s80000gr/T/pip-install-8qebifzt/onnx_024efb6f15ef41819a1bc471cb019575/setup.py", line 223, in run
          self.run_command("cmake_build")
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/2k/hr96tj9127x4_3ypczs4q6s80000gr/T/pip-install-8qebifzt/onnx_024efb6f15ef41819a1bc471cb019575/setup.py", line 209, in run
          subprocess.check_call(cmake_args)
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/opt/homebrew/bin/cmake', '-DPYTHON_INCLUDE_DIR=/opt/homebrew/Caskroom/miniforge/base/include/python3.10', '-DPYTHON_EXECUTABLE=/opt/homebrew/Caskroom/miniforge/base/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-310-darwin.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/private/var/folders/2k/hr96tj9127x4_3ypczs4q6s80000gr/T/pip-install-8qebifzt/onnx_024efb6f15ef41819a1bc471cb019575']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for onnx
  Running setup.py clean for onnx
Failed to build onnx
ERROR: Could not build wheels for onnx, which is required to install pyproject.toml-based projects

(base) MacMiniM1:tvm mpm$ python --version
Python 3.10.13

(base) MacMiniM1:tvm mpm$ cat requirements.txt 
numpy
decorator
attrs
typing-extensions
psutil
scipy
onnx==1.12.0
# onnxruntime==1.14.0
onnxruntime==1.14.1
# onnxoptimizer==0.2.6
onnxoptimizer==0.2.7
onnx-simplifier==0.4.17

**Comment by justinchuby** [comment]
@MarkMendelsohn please make sure the Protobuf compiler is install correctly in your environment.

**Comment by MarkMendelsohn** [comment]
[output.log](https://github.com/onnx/onnx/files/14514311/output.log)
Same issue after installing the Protobuf  compiler with brew

**Comment by pareshgp** [comment]
I am also facing same issue.

**Comment by devwasabi** [comment]
@justinchuby  if onnx version 1.6.0 is no longer supported, then which version must we use? I am having the same installation issue. Please help

**Comment by justinchuby** [comment]
The latest version is 1.15.
