### ISSUE TITLE
I can't install onnx

### ISSUE THREAD

**Issue by ironcg20** [onnx/onnx#5905]
During install onnx for python, I have issues under this command.
conda pip install onnx

(swap) E:\Workspace\repo-others\swapface\DeepFaceLive-master>pip install onnx-weekly==1.16.0.dev20231106
Collecting onnx-weekly==1.16.0.dev20231106
  Downloading onnx-weekly-1.16.0.dev20231106.tar.gz (12.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 11.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\Users\111\MiniConda3\envs\swap\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\111\MiniConda3\envs\swap\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\111\MiniConda3\envs\swap\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\111\AppData\Local\Temp\pip-build-env-9ru1p677\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\111\AppData\Local\Temp\pip-build-env-9ru1p677\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\111\AppData\Local\Temp\pip-build-env-9ru1p677\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 61, in <module>
      AssertionError: Could not find cmake in PATH
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by xadupre** [comment]
It seems it tries to installing from the sources and it needs to compile them. It was not able to detect a suitable compiled version for your environment. Can you try to select the file you need in that list https://pypi.org/project/onnx-weekly/1.16.0.dev20231106/#files and do ``pip install <url>``?

**Comment by justinchuby** [comment]
Please consider installing a newer development version. ONNX supports Python 3.8-3.12 as of today.

**Comment by justinchuby** [comment]
Please feel free to re-open of the issue persists.

**Comment by itmeicn** [comment]
today  use python3.11.7 of win11x64 .i installed it  same error. how to solved?

**Comment by itmeicn** [comment]
Collecting onnx<=1.9.0 (from paddle2onnx>=0.5.1->paddlehub)
  Using cached https://mirrors.163.com/pypi/packages/73/e9/5b953497c0e36df589fc60cc6c6b35a65eb67d9ad1e45a9163663e43426e/onnx-1.9.0.tar.gz (9.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "D:\python\pyside6Test\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\python\pyside6Test\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\python\pyside6Test\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\zspym\AppData\Local\Temp\pip-build-env-qszjaty2\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel  
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\zspym\AppData\Local\Temp\pip-build-env-qszjaty2\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\zspym\AppData\Local\Temp\pip-build-env-qszjaty2\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\zspym\AppData\Local\Temp\pip-build-env-qszjaty2\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 86, in <module>
      AssertionError: Could not find "cmake" executable!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
