### ISSUE TITLE
Source build failed with cmake error

### ISSUE THREAD

**Issue by onlyucanconquertime** [onnx/onnx#6000]
# Ask a Question

### Question

Failed in `pip install -r requirements.txt` or `pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/ --trusted-host pypi.tuna.tsinghua.edu.cn` or `pip install -r requirements.txt --use-pep517`

Building wheel for onnx (pyproject.toml) ... error
ERROR: Failed building wheel for onnx
Failed to build onnx
ERROR: Could not build wheels for onnx, which is required to install pyproject.toml-based projects

### Further information
The detail: 
```
  Building wheels for collected packages: onnx
  Building wheel for onnx (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for onnx (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      running bdist_wheel
      running build
      running build_py
      running create_version
      running cmake_build
      Using cmake args: ['/Users/xuyiping/Documents/project/imClumsyPanda/venv/bin/cmake', '-DPYTHON_INCLUDE_DIR=/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers', '-DPYTHON_EXECUTABLE=/Users/xuyiping/Documents/project/imClumsyPanda/venv/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-39-darwin.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-install-frk8euri/onnx_b84481a8c2df4d13a92b5fb2bfa632b9']
      Traceback (most recent call last):
        File "/Users/xuyiping/Documents/project/imClumsyPanda/venv/bin/cmake", line 5, in <module>
          from cmake import cmake
      ModuleNotFoundError: No module named 'cmake'
      Traceback (most recent call last):
        File "/Users/xuyiping/Documents/project/imClumsyPanda/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/xuyiping/Documents/project/imClumsyPanda/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/xuyiping/Documents/project/imClumsyPanda/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-build-env-bxt5n1j0/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 410, in build_wheel
          return self._build_with_temp_dir(
        File "/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-build-env-bxt5n1j0/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-build-env-bxt5n1j0/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-build-env-bxt5n1j0/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 332, in <module>
        File "/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-build-env-bxt5n1j0/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-build-env-bxt5n1j0/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-build-env-bxt5n1j0/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-build-env-bxt5n1j0/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-build-env-bxt5n1j0/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-build-env-bxt5n1j0/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-build-env-bxt5n1j0/normal/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-build-env-bxt5n1j0/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-build-env-bxt5n1j0/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-build-env-bxt5n1j0/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-build-env-bxt5n1j0/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-build-env-bxt5n1j0/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-build-env-bxt5n1j0/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-build-env-bxt5n1j0/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 223, in run
        File "/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-build-env-bxt5n1j0/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-build-env-bxt5n1j0/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-build-env-bxt5n1j0/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 209, in run
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/xuyiping/Documents/project/imClumsyPanda/venv/bin/cmake', '-DPYTHON_INCLUDE_DIR=/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers', '-DPYTHON_EXECUTABLE=/Users/xuyiping/Documents/project/imClumsyPanda/venv/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-39-darwin.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/private/var/folders/__/4llnl5r10yj45rg3zj4xhfm80000gn/T/pip-install-frk8euri/onnx_b84481a8c2df4d13a92b5fb2bfa632b9']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for onnx
Failed to build onnx
ERROR: Could not build wheels for onnx, which is required to install pyproject.toml-based projects
```

I checked the info about "cmake", and tried to changed the version, but it didn't work at all.
cmake version 3.26.0 / cmake version 3.28.3

**Comment by justinchuby** [comment]
Looks like this is an error calling cmake itself?

**Comment by BrunodaSilvaBelo** [comment]
@onlyucanconquertime I have this error when try to install using python 3.12.x, if you use python 3.11.x, pip installs successfully

**Comment by bilibili12433014** [comment]
i have the same problem with python 3.12.2

**Comment by ODAncona** [comment]
Was able to reproduce.

**Commands**
```bash
conda create --name py312 python=3.12
pip install cmake
pip install onnx
```
**Traceback**
```
Traceback (most recent call last):
  File "C:\Users\bob.morane\AppData\Local\anaconda3\envs\py312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
    main()
  File "C:\Users\bob.morane\AppData\Local\anaconda3\envs\py312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bob.morane\AppData\Local\anaconda3\envs\py312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bob.morane\AppData\Local\Temp\pip-build-env-6wqij0or\overlay\Lib\site-packages\setuptools\build_meta.py", line 410, in build_wheel
    return self._build_with_temp_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bob.morane\AppData\Local\Temp\pip-build-env-6wqij0or\overlay\Lib\site-packages\setuptools\build_meta.py", line 395, in _build_with_temp_dir
    self.run_setup()
  File "C:\Users\bob.morane\AppData\Local\Temp\pip-build-env-6wqij0or\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 327, in <module>
  File "C:\Users\bob.morane\AppData\Local\Temp\pip-build-env-6wqij0or\overlay\Lib\site-packages\setuptools\__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bob.morane\AppData\Local\Temp\pip-build-env-6wqij0or\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\bob.morane\AppData\Local\Temp\pip-build-env-6wqij0or\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\bob.morane\AppData\Local\Temp\pip-build-env-6wqij0or\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\bob.morane\AppData\Local\Temp\pip-build-env-6wqij0or\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "C:\Users\bob.morane\AppData\Local\Temp\pip-build-env-6wqij0or\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\bob.morane\AppData\Local\Temp\pip-build-env-6wqij0or\normal\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
    self.run_command("build")
  File "C:\Users\bob.morane\AppData\Local\Temp\pip-build-env-6wqij0or\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\bob.morane\AppData\Local\Temp\pip-build-env-6wqij0or\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "C:\Users\bob.morane\AppData\Local\Temp\pip-build-env-6wqij0or\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\bob.morane\AppData\Local\Temp\pip-build-env-6wqij0or\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
    self.run_command(cmd_name)
  File "C:\Users\bob.morane\AppData\Local\Temp\pip-build-env-6wqij0or\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\bob.morane\AppData\Local\Temp\pip-build-env-6wqij0or\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "C:\Users\bob.morane\AppData\Local\Temp\pip-build-env-6wqij0or\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "<string>", line 264, in run
  File "C:\Users\bob.morane\AppData\Local\Temp\pip-build-env-6wqij0or\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\bob.morane\AppData\Local\Temp\pip-build-env-6wqij0or\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "C:\Users\bob.morane\AppData\Local\Temp\pip-build-env-6wqij0or\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "<string>", line 243, in run
  File "C:\Users\bob.morane\AppData\Local\anaconda3\envs\py312\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\bob.morane\\AppData\\Local\\anaconda3\\envs\\py312\\

Scripts\\cmake.EXE', '--build', '.', '--config', 'Release', '--', '/maxcpucount:8']' returned non-zero exit status 1.
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for onnx
Failed to build onnx
ERROR: Could not build wheels for onnx, which is required to install pyproject.toml-based projects
```

[For reference](https://www.youtube.com/watch?v=M7X6oYg6iro)

**Comment by justinchuby** [comment]
@ODAncona could you share the full error message? The python stack does not show the cmake errors which should be on its above.
