### ISSUE TITLE
Building failed with Vitis AI.

### ISSUE THREAD

**Issue by blurSong** [onnx/onnx#6012]
I tried to build ort on my laptop with VS 2022 according to this guide: [Vitis AI ](https://onnxruntime.ai/docs/build/eps.html#amd-vitis-ai)
But failed and got

```
2024-03-11 17:45:37,213 build [INFO] - C:\Dev\miniconda3\python.exe onnxruntime_test_python.py
2024-03-11 17:45:37.6327802 [F:onnxruntime:Default, onnxruntime_pybind_state.cc:988 onnxruntime::python::CreateExecutionProviderInstance] cannot find provider options for VitisAIExecutionProvider
Traceback (most recent call last):
  File "C:\SRC\onnxruntime\\tools\ci_build\build.py", line 2918, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\SRC\onnxruntime\\tools\ci_build\build.py", line 2817, in main
    run_onnxruntime_tests(args, source_dir, ctest_path, build_dir, configs)
  File "C:\SRC\onnxruntime\\tools\ci_build\build.py", line 2044, in run_onnxruntime_tests
    run_subprocess(
  File "C:\SRC\onnxruntime\\tools\ci_build\build.py", line 852, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\SRC\onnxruntime\tools\python\util\run.py", line 49, in run
    completed_process = subprocess.run(
                        ^^^^^^^^^^^^^^^
  File "C:\Dev\miniconda3\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Dev\\miniconda3\\python.exe', 'onnxruntime_test_python.py']' returned non-zero exit status 3221225477.
```

**Comment by justinchuby** [comment]
Please create this issue in the microsoft/onnxruntime repository to get better help. Thanks!
