### ISSUE TITLE
AttributeError while installing ONNX

### ISSUE THREAD

**Issue by charmway** [onnx/onnx#6013]
# Bug Report

### Is the issue related to model conversion?

No

### Describe the bug

when I install ONNX from source in Ubuntu22.04, I follow the instructions in [install ONNX in Linux](https://github.com/onnx/onnx?tab=readme-ov-file#linux). However it failed.
### System information

- OS: Ubuntu22.04
- ONNX: latest
- python: 3.10.12
- GCC: 11.4.0
- Cmake: 3.22.1
- Protobuf: 3.21.12

### Reproduction instructions

just follow the [install ONNX in Linux](https://github.com/onnx/onnx?tab=readme-ov-file#linux)

### Error logs
```
➜  onnx git:(main) ✗ sudo pip install .
Processing /home/cwwu/Downloads/onnx
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for UNKNOWN (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [105 lines of output]
      running bdist_wheel
      running build
      running build_ext
      running cmake_build
      -- ONNX_PROTOC_EXECUTABLE: /usr/bin/protoc
      -- Protobuf_VERSION: 3.21.12
      Generated: /home/cwwu/Downloads/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
      Generated: /home/cwwu/Downloads/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
      Generated: /home/cwwu/Downloads/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
      -- Could NOT find pybind11 (missing: pybind11_DIR)
      -- pybind11 v2.10.4
      --
      -- ******** Summary ********
      --   CMake version                     : 3.22.1
      --   CMake command                     : /usr/bin/cmake
      --   System                            : Linux
      --   C++ compiler                      : /usr/bin/c++
      --   C++ compiler version              : 11.4.0
      --   CXX flags                         :  -Wnon-virtual-dtor
      --   Build type                        : Release
      --   Compile definitions               : __STDC_FORMAT_MACROS
      --   CMAKE_PREFIX_PATH                 :
      --   CMAKE_INSTALL_PREFIX              : /usr/local
      --   CMAKE_MODULE_PATH                 :
      --
      --   ONNX version                      : 1.17.0
      --   ONNX NAMESPACE                    : onnx
      --   ONNX_USE_LITE_PROTO               : OFF
      --   USE_PROTOBUF_SHARED_LIBS          : OFF
      --   Protobuf_USE_STATIC_LIBS          : ON
      --   ONNX_DISABLE_EXCEPTIONS           : OFF
      --   ONNX_DISABLE_STATIC_REGISTRATION  : OFF
      --   ONNX_WERROR                       : OFF
      --   ONNX_BUILD_TESTS                  : OFF
      --   ONNX_BUILD_BENCHMARKS             : OFF
      --   ONNX_BUILD_SHARED_LIBS            :
      --   BUILD_SHARED_LIBS                 :
      --
      --   Protobuf compiler                 : /usr/bin/protoc
      --   Protobuf includes                 : /usr/include
      --   Protobuf libraries                : /usr/lib/x86_64-linux-gnu/libprotobuf.a
      --   BUILD_ONNX_PYTHON                 : ON
      --     Python version                :
      --     Python executable             : /usr/bin/python3
      --     Python includes               : /usr/include/python3.10
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /home/cwwu/Downloads/onnx/.setuptools-cmake-build
      [  2%] Built target gen_onnx_proto
      [  8%] Built target gen_onnx_operators_proto
      [  8%] Built target gen_onnx_data_proto
      Consolidate compiler generated dependencies of target onnx_proto
      [ 22%] Built target onnx_proto
      Consolidate compiler generated dependencies of target onnx
      [ 97%] Built target onnx
      Consolidate compiler generated dependencies of target onnx_cpp2py_export
      [100%] Built target onnx_cpp2py_export
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 230, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 309, in <module>
          setuptools.setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "setup.py", line 247, in run
          return super().run()
        File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
          self.build_extensions()
        File "setup.py", line 276, in build_extensions
          if self.editable_mode:
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 103, in __getattr__
          raise AttributeError(attr)
      AttributeError: editable_mode
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for UNKNOWN
Failed to build UNKNOWN
ERROR: Could not build wheels for UNKNOWN, which is required to install pyproject.toml-based projects
```

**Comment by Tom-Teamo** [comment]
I already updated pip, which is `24.0`. And I do not know which setup-tool you mean. All the version informations of my setup-tool are in `System information` section.

**Comment by justinchuby** [comment]
https://pypi.org/project/setuptools/

`pip install --upgrade setuptools`

**Comment by Tom-Teamo** [comment]
Thanks, BUT it failed again. It shows the same error info.

**Comment by justinchuby** [comment]
Was it the same environment? I also assume the ONNX project is freshly cloned?

**Comment by Tom-Teamo** [comment]
Yes, the same environment. and I tried to clone a new one but failed again.

**Comment by Tom-Teamo** [comment]
Anybody help me?

**Comment by justinchuby** [comment]
I would try using a Python virtual environment to ensure the environment is configured correctly.

**Comment by devwasabi** [comment]
I am actually have the same error as you @Tom-Teamo . Did you manage to install ONXX? I also tried upgrading the setup tools, which did not work.

**Comment by justinchuby** [comment]
Please share your environment setup: OS version, Python version, setuptools version, onnx commit etc.

**Comment by devwasabi** [comment]
## System information
* OS: Windows 11
* onnx: 1.15.0
* python: 3.12.2
* GCC: 13.2.0
* cmake: 3.29.0-rc4
* Protobuf: 5.26.0
* setuptools: 69.2.0

## Error logs

`



      FileTracker : error FTK1011: could not create the new file tracking log file: C:\Users\bbdnet2520\AppData\Local\Temp\pip-install-5588i1j3\onnx_ea147439b23b4fd7890fec093d21e7a5\.setuptools-cmake-build\_deps\protobuf-build\third_party\abseil-cpp\absl\synchronization\graphcycles_internal.dir\Release\graphcyc.10BD53DF.tlog\Lib-link.write.1.tlog. The system cannot find the path specified. [C:\Users\bbdnet2520\AppData\Local\Temp\pip-install-5588i1j3\onnx_ea147439b23b4fd7890fec093d21e7a5\.setuptools-cmake-build\_deps\protobuf-build\third_party\abseil-cpp\absl\synchronization\graphcycles_internal.vcxproj]



        strings.vcxproj -> C:\Users\bbdnet2520\AppData\Local\Temp\pip-install-5588i1j3\onnx_ea147439b23b4fd7890fec093d21e7a5\.setuptools-cmake-build\_deps\protobuf-build\third_party\abseil-cpp\absl\strings\Release\absl_strings.lib
        Building Custom Rule C:/Users/bbdnet2520/AppData/Local/Temp/pip-install-5588i1j3/onnx_ea147439b23b4fd7890fec093d21e7a5/.setuptools-cmake-build/_deps/abseil-src/absl/crc/CMakeLists.txt
        Building Custom Rule C:/Users/bbdnet2520/AppData/Local/Temp/pip-install-5588i1j3/onnx_ea147439b23b4fd7890fec093d21e7a5/.setuptools-cmake-build/_deps/abseil-src/absl/strings/CMakeLists.txt
        Building Custom Rule C:/Users/bbdnet2520/AppData/Local/Temp/pip-install-5588i1j3/onnx_ea147439b23b4fd7890fec093d21e7a5/.setuptools-cmake-build/_deps/abseil-src/absl/debugging/CMakeLists.txt
        Building Custom Rule C:/Users/bbdnet2520/AppData/Local/Temp/pip-install-5588i1j3/onnx_ea147439b23b4fd7890fec093d21e7a5/.setuptools-cmake-build/_deps/abseil-src/absl/log/CMakeLists.txt
        Building Custom Rule C:/Users/bbdnet2520/AppData/Local/Temp/pip-install-5588i1j3/onnx_ea147439b23b4fd7890fec093d21e7a5/.setuptools-cmake-build/_deps/abseil-src/absl/hash/CMakeLists.txt
        Building Custom Rule C:/Users/bbdnet2520/AppData/Local/Temp/pip-install-5588i1j3/onnx_ea147439b23b4fd7890fec093d21e7a5/.setuptools-cmake-build/_deps/abseil-src/absl/time/CMakeLists.txt
        Building Custom Rule C:/Users/bbdnet2520/AppData/Local/Temp/pip-install-5588i1j3/onnx_ea147439b23b4fd7890fec093d21e7a5/.setuptools-cmake-build/_deps/protobuf-src/third_party/utf8_range/CMakeLists.txt  
        symbolize.cc
        proto.cc
        hash.cc
        arg.cc
        bind.cc
        extension.cc
        crc32c.cc
        crc_memcpy_fallback.cc
        float_conversion.cc
        crc_memcpy_x86_64.cc
        output.cc
        parser.cc
        crc_non_temporal_memcpy.cc
        civil_time.cc
        clock.cc
        duration.cc
        format.cc
        utf8_validity.cc
        time.cc
        log_internal_proto.vcxproj -> C:\Users\bbdnet2520\AppData\Local\Temp\pip-install-5588i1j3\onnx_ea147439b23b4fd7890fec093d21e7a5\.setuptools-cmake-build\_deps\protobuf-build\third_party\abseil-cpp\absl\log\Release\absl_log_internal_proto.lib
        hash.vcxproj -> C:\Users\bbdnet2520\AppData\Local\Temp\pip-install-5588i1j3\onnx_ea147439b23b4fd7890fec093d21e7a5\.setuptools-cmake-build\_deps\protobuf-build\third_party\abseil-cpp\absl\hash\Release\absl_hash.lib
        utf8_validity.vcxproj -> C:\Users\bbdnet2520\AppData\Local\Temp\pip-install-5588i1j3\onnx_ea147439b23b4fd7890fec093d21e7a5\.setuptools-cmake-build\_deps\protobuf-build\third_party\utf8_range\Release\utf8_validity.lib
        Building Custom Rule C:/Users/bbdnet2520/AppData/Local/Temp/pip-install-5588i1j3/onnx_ea147439b23b4fd7890fec093d21e7a5/.setuptools-cmake-build/_deps/abseil-src/absl/log/CMakeLists.txt
        crc32c.vcxproj -> C:\Users\bbdnet2520\AppData\Local\Temp\pip-install-5588i1j3\onnx_ea147439b23b4fd7890fec093d21e7a5\.setuptools-cmake-build\_deps\protobuf-build\third_party\abseil-cpp\absl\crc\Release\absl_crc32c.lib
        symbolize.vcxproj -> C:\Users\bbdnet2520\AppData\Local\Temp\pip-install-5588i1j3\onnx_ea147439b23b4fd7890fec093d21e7a5\.setuptools-cmake-build\_deps\protobuf-build\third_party\abseil-cpp\absl\debugging\Release\absl_symbolize.lib
        Building Custom Rule C:/Users/bbdnet2520/AppData/Local/Temp/pip-install-5588i1j3/onnx_ea147439b23b4fd7890fec093d21e7a5/.setuptools-cmake-build/_deps/abseil-src/absl/crc/CMakeLists.txt
        Building Custom Rule C:/Users/bbdnet2520/AppData/Local/Temp/pip-install-5588i1j3/onnx_ea147439b23b4fd7890fec093d21e7a5/.setuptools-cmake-build/_deps/abseil-src/absl/debugging/CMakeLists.txt
        globals.cc
        examine_stack.cc
        crc_cord_state.cc
        str_format_internal.vcxproj -> C:\Users\bbdnet2520\AppData\Local\Temp\pip-install-5588i1j3\onnx_ea147439b23b4fd7890fec093d21e7a5\.setuptools-cmake-build\_deps\protobuf-build\third_party\abseil-cpp\absl\strings\Release\absl_str_format_internal.lib
        Building Custom Rule C:/Users/bbdnet2520/AppData/Local/Temp/pip-install-5588i1j3/onnx_ea147439b23b4fd7890fec093d21e7a5/.setuptools-cmake-build/_deps/abseil-src/absl/flags/CMakeLists.txt
        time.vcxproj -> C:\Users\bbdnet2520\AppData\Local\Temp\pip-install-5588i1j3\onnx_ea147439b23b4fd7890fec093d21e7a5\.setuptools-cmake-build\_deps\protobuf-build\third_party\abseil-cpp\absl\time\Release\absl_time.lib
        Building Custom Rule C:/Users/bbdnet2520/AppData/Local/Temp/pip-install-5588i1j3/onnx_ea147439b23b4fd7890fec093d21e7a5/.setuptools-cmake-build/_deps/abseil-src/absl/log/CMakeLists.txt
        Building Custom Rule C:/Users/bbdnet2520/AppData/Local/Temp/pip-install-5588i1j3/onnx_ea147439b23b4fd7890fec093d21e7a5/.setuptools-cmake-build/_deps/abseil-src/absl/log/CMakeLists.txt
        marshalling.cc
        globals.cc
        log_entry.cc
        examine_stack.vcxproj -> C:\Users\bbdnet2520\AppData\Local\Temp\pip-install-5588i1j3\onnx_ea147439b23b4fd7890fec093d21e7a5\.setuptools-cmake-build\_deps\protobuf-build\third_party\abseil-cpp\absl\debugging\Release\absl_examine_stack.lib
        crc_cord_state.vcxproj -> C:\Users\bbdnet2520\AppData\Local\Temp\pip-install-5588i1j3\onnx_ea147439b23b4fd7890fec093d21e7a5\.setuptools-cmake-build\_deps\protobuf-build\third_party\abseil-cpp\absl\crc\Release\absl_crc_cord_state.lib
        log_globals.vcxproj -> C:\Users\bbdnet2520\AppData\Local\Temp\pip-install-5588i1j3\onnx_ea147439b23b4fd7890fec093d21e7a5\.setuptools-cmake-build\_deps\protobuf-build\third_party\abseil-cpp\absl\log\Release\absl_log_globals.lib
        Building Custom Rule C:/Users/bbdnet2520/AppData/Local/Temp/pip-install-5588i1j3/onnx_ea147439b23b4fd7890fec093d21e7a5/.setuptools-cmake-build/_deps/abseil-src/absl/strings/CMakeLists.txt
        cord_internal.cc
        cord_rep_btree.cc
        cord_rep_btree_navigator.cc
        cord_rep_btree_reader.cc
        cord_rep_crc.cc
        cord_rep_consume.cc
        cord_rep_ring.cc
        log_internal_globals.vcxproj -> C:\Users\bbdnet2520\AppData\Local\Temp\pip-install-5588i1j3\onnx_ea147439b23b4fd7890fec093d21e7a5\.setuptools-cmake-build\_deps\protobuf-build\third_party\abseil-cpp\absl\log\Release\absl_log_internal_globals.lib
        log_entry.vcxproj -> C:\Users\bbdnet2520\AppData\Local\Temp\pip-install-5588i1j3\onnx_ea147439b23b4fd7890fec093d21e7a5\.setuptools-cmake-build\_deps\protobuf-build\third_party\abseil-cpp\absl\log\Release\absl_log_entry.lib
        Building Custom Rule C:/Users/bbdnet2520/AppData/Local/Temp/pip-install-5588i1j3/onnx_ea147439b23b4fd7890fec093d21e7a5/.setuptools-cmake-build/_deps/abseil-src/absl/log/CMakeLists.txt
        Building Custom Rule C:/Users/bbdnet2520/AppData/Local/Temp/pip-install-5588i1j3/onnx_ea147439b23b4fd7890fec093d21e7a5/.setuptools-cmake-build/_deps/abseil-src/absl/log/CMakeLists.txt
        Building Custom Rule C:/Users/bbdnet2520/AppData/Local/Temp/pip-install-5588i1j3/onnx_ea147439b23b4fd7890fec093d21e7a5/.setuptools-cmake-build/_deps/abseil-src/absl/log/CMakeLists.txt
        flags_marshalling.vcxproj -> C:\Users\bbdnet2520\AppData\Local\Temp\pip-install-5588i1j3\onnx_ea147439b23b4fd7890fec093d21e7a5\.setuptools-cmake-build\_deps\protobuf-build\third_party\abseil-cpp\absl\flags\Release\absl_flags_marshalling.lib
        log_sink.cc
        log_format.cc
        initialize.cc
        cord_internal.vcxproj -> C:\Users\bbdnet2520\AppData\Local\Temp\pip-install-5588i1j3\onnx_ea147439b23b4fd7890fec093d21e7a5\.setuptools-cmake-build\_deps\protobuf-build\third_party\abseil-cpp\absl\strings\Release\absl_cord_internal.lib
        log_initialize.vcxproj -> C:\Users\bbdnet2520\AppData\Local\Temp\pip-install-5588i1j3\onnx_ea147439b23b4fd7890fec093d21e7a5\.setuptools-cmake-build\_deps\protobuf-build\third_party\abseil-cpp\absl\log\Release\absl_log_initialize.lib
        log_sink.vcxproj -> C:\Users\bbdnet2520\AppData\Local\Temp\pip-install-5588i1j3\onnx_ea147439b23b4fd7890fec093d21e7a5\.setuptools-cmake-build\_deps\protobuf-build\third_party\abseil-cpp\absl\log\Release\absl_log_sink.lib
        log_internal_format.vcxproj -> C:\Users\bbdnet2520\AppData\Local\Temp\pip-install-5588i1j3\onnx_ea147439b23b4fd7890fec093d21e7a5\.setuptools-cmake-build\_deps\protobuf-build\third_party\abseil-cpp\absl\log\Release\absl_log_internal_format.lib
      Traceback (most recent call last):
        File "C:\Users\bbdnet2520\OneDrive - BBD Software Development\Desktop\Projects\EfficientVIT\efficientvit\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\bbdnet2520\OneDrive - BBD Software Development\Desktop\Projects\EfficientVIT\efficientvit\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bbdnet2520\OneDrive - BBD Software Development\Desktop\Projects\EfficientVIT\efficientvit\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bbdnet2520\AppData\Local\Temp\pip-build-env-b2z3q90c\overlay\Lib\site-packages\setuptools\build_meta.py", line 410, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bbdnet2520\AppData\Local\Temp\pip-build-env-b2z3q90c\overlay\Lib\site-packages\setuptools\build_meta.py", line 395, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\bbdnet2520\AppData\Local\Temp\pip-build-env-b2z3q90c\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 327, in <module>
        File "C:\Users\bbdnet2520\AppData\Local\Temp\pip-build-env-b2z3q90c\overlay\Lib\site-packages\setuptools\__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bbdnet2520\AppData\Local\Temp\pip-build-env-b2z3q90c\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\bbdnet2520\AppData\Local\Temp\pip-build-env-b2z3q90c\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\bbdnet2520\AppData\Local\Temp\pip-build-env-b2z3q90c\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\bbdnet2520\AppData\Local\Temp\pip-build-env-b2z3q90c\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\bbdnet2520\AppData\Local\Temp\pip-build-env-b2z3q90c\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\bbdnet2520\AppData\Local\Temp\pip-build-env-b2z3q90c\normal\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\bbdnet2520\AppData\Local\Temp\pip-build-env-b2z3q90c\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\bbdnet2520\AppData\Local\Temp\pip-build-env-b2z3q90c\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\bbdnet2520\AppData\Local\Temp\pip-build-env-b2z3q90c\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\bbdnet2520\AppData\Local\Temp\pip-build-env-b2z3q90c\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\bbdnet2520\AppData\Local\Temp\pip-build-env-b2z3q90c\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\bbdnet2520\AppData\Local\Temp\pip-build-env-b2z3q90c\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\bbdnet2520\AppData\Local\Temp\pip-build-env-b2z3q90c\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 264, in run
        File "C:\Users\bbdnet2520\AppData\Local\Temp\pip-build-env-b2z3q90c\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\bbdnet2520\AppData\Local\Temp\pip-build-env-b2z3q90c\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\bbdnet2520\AppData\Local\Temp\pip-build-env-b2z3q90c\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 243, in run
        File "D:\Program Files\Python\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.EXE', '--build', '.', '--config', 'Release', '--', '/maxcpucount:20']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for onnx
ERROR: Could not build wheels for onnx, which is required to install pyproject.toml-based projects`

**Comment by aruncs31s** [comment]
Have anyone solved it yet?

**Comment by gorloffslava** [comment]
This can be solved by exporting `pybind11_DIR` environment variable and pointing that to the directory where pybind11 is installed. It should be the `pybind11` Python module directory if installed via pip. E.g., 
```
export pybind11_DIR="../__venv/lib/python3.12/site-packages/pybind11/"
```

(Better to use absolute paths in such cases just had this example nearby me).

The reason behind this
