### ISSUE TITLE
Error While Installing ONNX

### ISSUE THREAD

**Issue by jh97321** [onnx/onnx#6140]
# Bug Report

### Is the issue related to model conversion?
no

### System information
Ubuntu 14.04
onnx 1.9.0
python 2.7.6
protobuf 2.6.1
cmake 3.28.4
gcc 4.8.4

### Describe the bug
 ```
Building wheels for collected packages: onnx
  Building wheel for onnx (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip-20.3.4-py2.7.egg/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpfR3xK2
       cwd: /tmp/pip-install-dMWHiR/onnx
  Complete output (267 lines):
  fatal: Not a git repository (or any of the parent directories): .git
  running bdist_wheel
  running build
  running build_py
  running create_version
  running cmake_build
  Using cmake args: [u'/usr/local/bin/cmake', u'-DPYTHON_INCLUDE_DIR=/usr/include/python2.7', u'-DPYTHON_EXECUTABLE=/usr/bin/python', u'-DBUILD_ONNX_PYTHON=ON', u'-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', u'-DONNX_NAMESPACE=onnx', u'-DPY_EXT_SUFFIX=', u'-DCMAKE_BUILD_TYPE=Release', u'-DONNX_ML=1', '/tmp/pip-install-dMWHiR/onnx']
  CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
    Compatibility with CMake < 3.5 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  -- The C compiler identification is GNU 4.8.4
  -- The CXX compiler identification is GNU 4.8.4
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Warning (dev) at CMakeLists.txt:114 (find_package):
    Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
    are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
    the cmake_policy command to set the policy and suppress this warning.
  
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  -- Found PythonInterp: /usr/bin/python (found version "2.7.6")
  CMake Warning (dev) at CMakeLists.txt:115 (find_package):
    Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
    are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
    the cmake_policy command to set the policy and suppress this warning.
  
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.6")
  -- Found Protobuf: /usr/local/lib/libprotobuf.so (found version "2.6.1")
  Generated: /tmp/pip-install-dMWHiR/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
  Generated: /tmp/pip-install-dMWHiR/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
  Generated: /tmp/pip-install-dMWHiR/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
  CMake Warning (dev) at /usr/local/share/cmake/pybind11/FindPythonLibsNew.cmake:98 (find_package):
    Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
    are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
    the cmake_policy command to set the policy and suppress this warning.
  
  Call Stack (most recent call first):
    /usr/local/share/cmake/pybind11/pybind11Tools.cmake:50 (find_package)
    /usr/local/share/cmake/pybind11/pybind11Common.cmake:206 (include)
    /usr/local/share/cmake/pybind11/pybind11Config.cmake:250 (include)
    CMakeLists.txt:447 (find_package)
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  -- Found pybind11: /usr/local/include (found version "2.9.0")
  --
  -- ******** Summary ********
  --   CMake version             : 3.28.4
  --   CMake command             : /usr/local/lib/python2.7/dist-packages/cmake/data/bin/cmake
  --   System                    : Linux
  --   C++ compiler              : /usr/bin/c++
  --   C++ compiler version      : 4.8.4
  --   CXX flags                 :  -Wnon-virtual-dtor
  --   Build type                : Release
  --   Compile definitions       :
  --   CMAKE_PREFIX_PATH         :
  --   CMAKE_INSTALL_PREFIX      : /usr/local
  --   CMAKE_MODULE_PATH         :
  --
  --   ONNX version              : 1.9.0
  --   ONNX NAMESPACE            : onnx
  --   ONNX_USE_LITE_PROTO       : OFF
  --   USE_PROTOBUF_SHARED_LIBS  : OFF
  --   ONNX_DISABLE_EXCEPTIONS   : OFF
  --   ONNX_WERROR               : OFF
  --   ONNX_BUILD_TESTS          : OFF
  --   ONNX_BUILD_BENCHMARKS     : OFF
  --   ONNXIFI_DUMMY_BACKEND     : OFF
  --   ONNXIFI_ENABLE_EXT        : OFF
  --
  --   Protobuf compiler         : /usr/local/bin/protoc
  --   Protobuf includes         : /usr/local/include
  --   Protobuf libraries        : /usr/local/lib/libprotobuf.so
  --   BUILD_ONNX_PYTHON         : ON
  --     Python version        :
  --     Python executable     : /usr/bin/python
  --     Python includes       : /usr/include/python2.7
  -- Configuring done (1.1s)
  -- Generating done (0.0s)
  -- Build files have been written to: /tmp/pip-install-dMWHiR/onnx/.setuptools-cmake-build
  [  1%] Running gen_proto.py on onnx/onnx.in.proto
  [  3%] Building C object CMakeFiles/onnxifi_loader.dir/onnx/onnxifi_loader.c.o
  [  4%] Building C object CMakeFiles/onnxifi_dummy.dir/onnx/onnxifi_dummy.c.o
  Processing /tmp/pip-install-dMWHiR/onnx/onnx/onnx.in.proto
  Writing /tmp/pip-install-dMWHiR/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
  Writing /tmp/pip-install-dMWHiR/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto3
  generating /tmp/pip-install-dMWHiR/onnx/.setuptools-cmake-build/onnx/onnx_pb.py
  [  6%] Running C++ protocol buffer compiler on /tmp/pip-install-dMWHiR/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
  /tmp/pip-install-dMWHiR/onnx/onnx/onnxifi_dummy.c: In function ‘onnxGetExtensionFunctionAddress’:
  /tmp/pip-install-dMWHiR/onnx/onnx/onnxifi_dummy.c:177:21: warning: assignment from incompatible pointer type [enabled by default]
             *function = &onnxGetExtensionFunctionAddress;
                       ^
  /tmp/pip-install-dMWHiR/onnx/onnx/onnxifi_dummy.c:180:21: warning: assignment from incompatible pointer type [enabled by default]
             *function = &onnxSetIOAndRunGraph;
                       ^
  [  7%] Linking C static library libonnxifi_loader.a
  Writing mypy to onnx/onnx_ml_pb2.pyi
  [  9%] Linking C shared library libonnxifi_dummy.so
  [  9%] Built target onnxifi_loader
  [  9%] Built target gen_onnx_proto
  [ 10%] Running gen_proto.py on onnx/onnx-operators.in.proto
  [ 12%] Building C object CMakeFiles/onnxifi_wrapper.dir/onnx/onnxifi_wrapper.c.o
  [ 12%] Built target onnxifi_dummy
  [ 13%] Running gen_proto.py on onnx/onnx-data.in.proto
  Processing /tmp/pip-install-dMWHiR/onnx/onnx/onnx-operators.in.proto
  Writing /tmp/pip-install-dMWHiR/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
  Writing /tmp/pip-install-dMWHiR/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto3
  generating /tmp/pip-install-dMWHiR/onnx/.setuptools-cmake-build/onnx/onnx_operators_pb.py
  [ 15%] Running C++ protocol buffer compiler on /tmp/pip-install-dMWHiR/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
  Processing /tmp/pip-install-dMWHiR/onnx/onnx/onnx-data.in.proto
  Writing /tmp/pip-install-dMWHiR/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
  Writing /tmp/pip-install-dMWHiR/onnx/.setuptools-cmake-build/onnx/onnx-data.proto3
  generating /tmp/pip-install-dMWHiR/onnx/.setuptools-cmake-build/onnx/onnx_data_pb.py
  [ 16%] Running C++ protocol buffer compiler on /tmp/pip-install-dMWHiR/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
  Writing mypy to onnx/onnx_operators_ml_pb2.pyi
  Writing mypy to onnx/onnx_data_pb2.pyi
  [ 18%] Linking C shared module libonnxifi.so
  [ 20%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-ml.pb.cc.o
  [ 21%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-operators-ml.pb.cc.o
  [ 23%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-data.pb.cc.o
  [ 23%] Built target onnxifi_wrapper
  [ 24%] Linking CXX static library libonnx_proto.a
  [ 27%] Built target onnx_proto
  [ 30%] Building CXX object CMakeFiles/onnx.dir/onnx/checker.cc.o
  [ 30%] Building CXX object CMakeFiles/onnx.dir/onnx/common/assertions.cc.o
  [ 32%] Building CXX object CMakeFiles/onnx.dir/onnx/common/interned_strings.cc.o
  [ 33%] Building CXX object CMakeFiles/onnx.dir/onnx/common/ir_pb_converter.cc.o
  [ 35%] Building CXX object CMakeFiles/onnx.dir/onnx/common/model_helpers.cc.o
  [ 36%] Building CXX object CMakeFiles/onnx.dir/onnx/common/path.cc.o
  [ 38%] Building CXX object CMakeFiles/onnx.dir/onnx/common/status.cc.o
  [ 40%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/attr_proto_util.cc.o
  [ 41%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/controlflow/defs.cc.o
  [ 43%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/controlflow/old.cc.o
  [ 44%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/data_type_utils.cc.o
  [ 46%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/function.cc.o
  [ 47%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/generator/defs.cc.o
  [ 49%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/generator/old.cc.o
  [ 50%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/logical/defs.cc.o
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc:24:15: error: unterminated raw string
           doc = R"DOC(
                 ^
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc:23:5: error: stray ‘R’ in program
       POPULATE_OP_DOC_STR(
       ^
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc:23:5: error: stray ‘`’ in program
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc:23:5: error: stray ‘`’ in program
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc:23:5: error: stray ‘`’ in program
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc:23:5: error: stray ‘`’ in program
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc:23:5: error: stray ‘`’ in program
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc:23:5: error: stray ‘`’ in program
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc:29:5: warning: missing terminating " character [enabled by default]
   )DOC";
       ^
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc:23:5: error: missing terminating " character
       POPULATE_OP_DOC_STR(
       ^
  In file included from /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc:7:0:
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc: In lambda function:
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc:25:1: error: ‘Returns’ was not declared in this scope
   Returns the tensor resulted from performing the `{name}` logical operation
   ^
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/schema.h:1290:5: note: in definition of macro ‘POPULATE_OP_DOC_STR’
       DocPopulatorCode                          \
       ^
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc:25:9: error: expected ‘;’ before ‘the’
   Returns the tensor resulted from performing the `{name}` logical operation
           ^
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/schema.h:1290:5: note: in definition of macro ‘POPULATE_OP_DOC_STR’
       DocPopulatorCode                          \
       ^
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc:25:58: error: ‘logical’ was not declared in this scope
   Returns the tensor resulted from performing the `{name}` logical operation
                                                            ^
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/schema.h:1290:5: note: in definition of macro ‘POPULATE_OP_DOC_STR’
       DocPopulatorCode                          \
       ^
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc:25:66: error: expected ‘;’ before ‘operation’
   Returns the tensor resulted from performing the `{name}` logical operation
                                                                    ^
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/schema.h:1290:5: note: in definition of macro ‘POPULATE_OP_DOC_STR’
       DocPopulatorCode                          \
       ^
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc:29:2: error: expected ‘;’ before ‘DOC’
   )DOC";
    ^
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc:29:2: error: ‘DOC’ was not declared in this scope
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc:30:9: error: expected ‘;’ before ‘ReplaceAll’
           ReplaceAll(doc, "{name}", name);
           ^
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc:32:75: error: expected primary-expression before ‘)’ token
               doc, "{broadcast_doc}", GenerateBroadcastingDocMul().c_str()););
                                                                             ^
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc:32:75: error: expected ‘;’ before ‘)’ token
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc: At global scope:
  /tmp/pip-install-dMWHiR/onnx/onnx/defs/logical/defs.cc:20:32: warning: unused parameter ‘name’ [-Wunused-parameter]
   std::function<void(OpSchema&)> BinaryLogicDocGenerator(const char* name) {
                                  ^
  make[2]: *** [CMakeFiles/onnx.dir/onnx/defs/logical/defs.cc.o] 错误 1
  make[2]: *** 正在等待未完成的任务....
  make[1]: *** [CMakeFiles/onnx.dir/all] 错误 2
  make: *** [all] 错误 2
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pip-20.3.4-py2.7.egg/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python2.7/dist-packages/pip-20.3.4-py2.7.egg/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python2.7/dist-packages/pip-20.3.4-py2.7.egg/pip/_vendor/pep517/_in_process.py", line 205, in build_wheel
      metadata_directory)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 209, in build_wheel
      wheel_directory, config_settings)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 194, in _build_with_temp_dir
      self.run_setup()
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 243, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 359, in <module>
      'backend-test-tools = onnx.backend.test.cmd_tools:main',
    File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 162, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-kdmVEW/overlay/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "setup.py", line 233, in run
      self.run_command('cmake_build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "setup.py", line 227, in run
      subprocess.check_call(build_args)
    File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '[u'/usr/local/bin/cmake', u'--build', '.', u'--', u'-j', '4']' returned non-zero exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for onnx
Failed to build onnx
ERROR: Could not build wheels for onnx which use PEP 517 and cannot be installed directly

```

**Comment by seanshpark** [comment]
> /usr/local/lib/python2.7

Try with python3.8 or above.

**Comment by jh97321** [comment]
> > /usr/local/lib/python2.7
> 
> Try with python3.8 or above.

onnx1.9.0 is not match with pyhton2.7?

**Comment by seanshpark** [comment]
> onnx1.9.0 is not match with pyhton2.7?

not sure about that, but https://pypi.org/project/onnx/#history shows `Requires: Python >=3.8`
