### ISSUE TITLE
onnx.utils.extract_model failed to extract subgraph from whisper-tiny-decoder

### ISSUE THREAD

**Issue by axinging** [onnx/onnx#6229]
I tried to extract a subgraph from whisper-tiny-decoder.  In whisper-tiny-decoder, it has a control if node. Below code is tring to extract a subgraph from no_past branch:
```
import onnx
name = "whisper-tiny-decoder"
if name == "whisper-tiny-decoder":
    input_path = "whisper-tiny-decoder.onnx"
    output_path = "whisper-tiny-decoder-if.onnx"
    input_names = ["/model/decoder/ConstantOfShape_output_0"]
    output_names = ["/model/decoder/Concat_2_output_0"]

onnx.utils.extract_model(input_path, output_path, input_names, output_names)
```
However, I got below errors:
```
Traceback (most recent call last):
  File "C:\ort\ort-models\split.py", line 24, in <module>
    onnx.utils.extract_model(input_path, output_path, input_names, output_names)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\lib\site-packages\onnx\utils.py", line 210, in extract_model
    extracted = e.extract_model(input_names, output_names)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\lib\site-packages\onnx\utils.py", line 165, in extract_model
    inputs = self._collect_new_inputs(input_names)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\lib\site-packages\onnx\utils.py", line 44, in _collect_new_inputs
    return self._collect_new_io_core(self.graph.input, names)  # type: ignore
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\lib\site-packages\onnx\utils.py", line 37, in _collect_new_io_core
    new_io_tensors.append(self.vimap[name])
KeyError: '/model/decoder/ConstantOfShape_output_0'

```

**Comment by xadupre** [comment]
It is difficult without knowing the model. It is possible to run something like?

```python
model = onnx.load(".....")
for node in model.graph.node:
    print(f"{node.op_type}({', '.join(node.input)}) -> {', '.join(node.output)}")
```

**Comment by axinging** [comment]
I got same error on this model:
https://huggingface.co/dmmagdal/whisper-tiny-onnx/blob/main/decoder_model_merged.onnx
