### ISSUE TITLE
ai.onnxruntime.OrtException: Unexpected number of requestedOutputs & pinnedOutputs, expected [1,1) found 2

### ISSUE THREAD

**Issue by yeqinfu** [onnx/onnx#6245]
# Ask a Question

### Question
Exception caught when perform ObjectDetection
                                                                                                    ai.onnxruntime.OrtException: Unexpected number of requestedOutputs & pinnedOutputs, expected [1,1) found 2
                                                                                                    	at ai.onnxruntime.OrtSession.run(OrtSession.java:341)
                                                                                                    	at ai.onnxruntime.OrtSession.run(OrtSession.java:242)
                                                                                                    	at ai.onnxruntime.example.objectdetection.ObjectDetector.detect(ObjectDetector.kt:36)
                                                                                                    	at ai.onnxruntime.example.objectdetection.MainActivity.performObjectDetection(MainActivity.kt:117)

yolov8s custom model export to onnx  and run on onnx android demo application.
i found add_pre_post_processing_to_model.py set yolov8 output number=2

 if yolo_v8_or_later:
        post_processing_steps += [
            Transpose([1, 0]),  # transpose to (num_boxes, box+scores)
            # split  elements into the box and scores for the classes. no confidence value to apply to scores
            Split(num_outputs=2, axis=-1, splits=[4, num_classes]),
        ]
    else:
        post_processing_steps += [
            # Split bounding box from confidence and scores for each class
            # Apply confidence to the scores.
            SplitOutBoxAndScoreWithConf(num_classes=num_classes),
        ]
but android lib error need only 1 output

**Comment by justinchuby** [comment]
Please open the issue in the ONNX Runtime repository and attach your model to receive more help. Thanks!

**Comment by cnfive** [comment]
。。。。。。
