### ISSUE TITLE
Op (Softmax) [ShapeInferenceError] 'axis' must be in [0 , -1]. Its actual value is: -1 (Softmax-13)

### ISSUE THREAD

**Issue by Ai-ZL** [onnx/onnx#6259]
# Bug Report

### Describe the bug
I use quantize_static and convert_float_to_float16 functions in onnx to convert fp32 model to fp16 + int8 model. The fp16 model can inference through onnxruntime InferenceSession. But after coverting to fp16+int8 model, the model has error: 

onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from ./model_fp16_int8_v19.onnx failed:Node (/layers.0/self_attn/Softmax) Op (Softmax) [ShapeInferenceError] 'axis' must be in [0 , -1]. Its actual value is: -1

The Softmax Op node in fp16 model is same as Softmax node in fp16+int8 model. Why this model have this error? And I also don't understand, Softmax Op axis = -1 is in the range [0, -1]

Softmax Op: 
inputs: <tensor: float16>
outputs: <tensor: float16>
attributes: <axis=-1, type=int64>
module: Softmax-13

### System information
- ONNX version (1.16.0)
- ONNXruntime version (1.18.1)
- ONNconverter-common version (1.14.0)
- Python version: 3.8

**Comment by gramalingam** [comment]
My guess is that the input to Softmax op is a scalar (rank 0) here, triggering this error. This seems strange (especially since the fp16 model doesn't have this problem). There must be some problem earlier in the model/graph before this node ... do you have the two models available to reproduce the error?

Aside: [0, -1] is actually an empty set. The error message can be improved in this case, but is valid, I think. The axis -1 means the last axis, but for a scalar (rank 0 tensor), there are no axes. Several implementations add "rank" to negative axes, and expect the result to be >= 0.

**Comment by Ai-ZL** [comment]
Thank you very much! I also agree with your comment. Because my input is dynamic dimension, the input and output of Softmax node representation is like:
![softmax_representation](https://github.com/user-attachments/assets/7fa95555-2f7f-4cfe-bbec-8bc722c391c7)
I don't know whether this tensor format will be seen as rank 0. But before quantization, the model's tensor format is also like it and have no error.

Here is my attached model:
https://drive.google.com/file/d/1Ja-U5ovYqGekiJoacO4E6wJ6z_VHxPvu/view?usp=drive_link
model_fp16.onnx is before quantization and have no error
model_fp16_static_int8.onnx is after quantization and have error about rank 0 input

My test code is:
onnx_model = onnx.load("model_fp16.onnx")
inferred_model = shape_inference.infer_shapes(onnx_model, check_type=True, strict_mode=True)

Error is:
Traceback (most recent call last):
  File "C:/Users/user/conformer-ctc/load_nemo_model.py", line 174, in <module>
    inferred_model = shape_inference.infer_shapes(onnx_model, check_type=True, strict_mode=True)
  File "C:\Users\user\anaconda3\envs\bibert\lib\site-packages\onnx\shape_inference.py", line 46, in infer_shapes
    inferred_model_str = C.infer_shapes(
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] Inference error(s): (op_type:Softmax, node name: /layers.0/self_attn/Softmax): [ShapeInferenceError] 'axis' must be in [0 , -1]. Its actual value is: -1
(op_type:MatMul, node name: /layers.0/self_attn/MatMul_2): [ShapeInferenceError] Input tensors of wrong rank (0).
(op_type:Transpose, node name: /layers.0/self_attn/Transpose_6): [TypeInferenceError] Invalid attribute perm {0, 2, 1, 3}, input shape = {
(op_type:Softmax, node name: /layers.1/self_attn/Softmax): [ShapeInferenceError] 'axis' must be in [0 , -1]. Its actual value is: -1
(op_type:MatMul, node name: /layers.1/self_attn/MatMul_2): [ShapeInferenceError] Input tensors of wrong rank (0).
(op_type:Transpose, node name: /layers.1/self_attn/Transpose_6): [TypeInferenceError] Invalid attribute perm {0, 2, 1, 3}, input shape = {
(op_type:Softmax, node name: /layers.2/self_attn/Softmax): [ShapeInferenceError] 'axis' must be in [0 , -1]. Its actual value is: -1
(op_type:MatMul, node name: /layers.2/self_attn/MatMul_2): [ShapeInferenceError] Input tensors of wrong rank (0).
(op_type:Transpose, node name: /layers.2/self_attn/Transpose_6): [TypeInferenceError] Invalid attribute perm {0, 2, 1, 3}, input shape = {
(op_type:Softmax, node name: /layers.3/self_attn/Softmax): [ShapeInferenceError] 'axis' must be in [0 , -1]. Its actual value is: -1
(op_type:MatMul, node name: /layers.3/self_attn/MatMul_2): [ShapeInferenceError] Input tensors of wrong rank (0).
(op_type:Transpose, node name: /layers.3/self_attn/Transpose_6): [TypeInferenceError] Invalid attribute perm {0, 2, 1, 3}, input shape = {
(op_type:Softmax, node name: /layers.4/self_attn/Softmax): [ShapeInferenceError] 'axis' must be in [0 , -1]. Its actual value is: -1
(op_type:MatMul, node name: /layers.4/self_attn/MatMul_2): [ShapeInferenceError] Input tensors of wrong rank (0).
(op_type:Transpose, node name: /layers.4/self_attn/Transpose_6): [TypeInferenceError] Invalid attribute perm {0, 2, 1, 3}, input shape = {
(op_type:Softmax, node name: /layers.5/self_attn/Softmax): [ShapeInferenceError] 'axis' must be in [0 , -1]. Its actual value is: -1
(op_type:MatMul, node name: /layers.5/self_attn/MatMul_2): [ShapeInferenceError] Input tensors of wrong rank (0).
(op_type:Transpose, node name: /layers.5/self_attn/Transpose_6): [TypeInferenceError] Invalid attribute perm {0, 2, 1, 3}, input shape = {
(op_type:Softmax, node name: /layers.6/self_attn/Softmax): [ShapeInferenceError] 'axis' must be in [0 , -1]. Its actual value is: -1
(op_type:MatMul, node name: /layers.6/self_attn/MatMul_2): [ShapeInferenceError] Input tensors of wrong rank (0).
(op_type:Transpose, node name: /layers.6/self_attn/Transpose_6): [TypeInferenceError] Invalid attribute perm {0, 2, 1, 3}, input shape = {
(op_type:Softmax, node name: /layers.7/self_attn/Softmax): [ShapeInferenceError] 'axis' must be in [0 , -1]. Its actual value is: -1
(op_type:MatMul, node name: /layers.7/self_attn/MatMul_2): [ShapeInferenceError] Input tensors of wrong rank (0).
(op_type:Transpose, node name: /layers.7/self_attn/Transpose_6): [TypeInferenceError] Invalid attribute perm {0, 2, 1, 3}, input shape = {
(op_type:Softmax, node name: /layers.8/self_attn/Softmax): [ShapeInferenceError] 'axis' must be in [0 , -1]. Its actual value is: -1
(op_type:MatMul, node name: /layers.8/self_attn/MatMul_2): [ShapeInferenceError] Input tensors of wrong rank (0).
(op_type:Transpose, node name: /layers.8/self_attn/Transpose_6): [TypeInferenceError] Invalid attribute perm {0, 2, 1, 3}, input shape = {
(op_type:Softmax, node name: /layers.9/self_attn/Softmax): [ShapeInferenceError] 'axis' must be in [0 , -1]. Its actual value is: -1
(op_type:MatMul, node name: /layers.9/self_attn/MatMul_2): [ShapeInferenceError] Input tensors of wrong rank (0).
(op_type:Transpose, node name: /layers.9/self_attn/Transpose_6): [TypeInferenceError] Invalid attribute perm {0, 2, 1, 3}, input shape = {
(op_type:Softmax, node name: /layers.10/self_attn/Softmax): [ShapeInferenceError] 'axis' must be in [0 , -1]. Its actual value is: -1
(op_type:MatMul, node name: /layers.10/self_attn/MatMul_2): [ShapeInferenceError] Input tensors of wrong rank (0).
(op_type:Transpose, node name: /layers.10/self_attn/Transpose_6): [TypeInferenceError] Invalid attribute perm {0, 2, 1, 3}, input shape = {
(op_type:Softmax, node name: /layers.11/self_attn/Softmax): [ShapeInferenceError] 'axis' must be in [0 , -1]. Its actual value is: -1
(op_type:MatMul, node name: /layers.11/self_attn/MatMul_2): [ShapeInferenceError] Input tensors of wrong rank (0).
(op_type:Transpose, node name: /layers.11/self_attn/Transpose_6): [TypeInferenceError] Invalid attribute perm {0, 2, 1, 3}, input shape = {
(op_type:Softmax, node name: /layers.12/self_attn/Softmax): [ShapeInferenceError] 'axis' must be in [0 , -1]. Its actual value is: -1
(op_type:MatMul, node name: /layers.12/self_attn/MatMul_2): [ShapeInferenceError] Input tensors of wrong rank (0).
(op_type:Transpose, node name: /layers.12/self_attn/Transpose_6): [TypeInferenceError] Invalid attribute perm {0, 2, 1, 3}, input shape = {
(op_type:Softmax, node name: /layers.13/self_attn/Softmax): [ShapeInferenceError] 'axis' must be in [0 , -1]. Its actual value is: -1
(op_type:MatMul, node name: /layers.13/self_attn/MatMul_2): [ShapeInferenceError] Input tensors of wrong rank (0).
(op_type:Transpose, node name: /layers.13/self_attn/Transpose_6): [TypeInferenceError] Invalid attribute perm {0, 2, 1, 3}, input shape = {
(op_type:Softmax, node name: /layers.14/self_attn/Softmax): [ShapeInferenceError] 'axis' must be in [0 , -1]. Its actual value is: -1
(op_type:MatMul, node name: /layers.14/self_attn/MatMul_2): [ShapeInferenceError] Input tensors of wrong rank (0).
(op_type:Transpose, node name: /layers.14/self_attn/Transpose_6): [TypeInferenceError] Invalid attribute perm {0, 2, 1, 3}, input shape = {
(op_type:Softmax, node name: /layers.15/self_attn/Softmax): [ShapeInferenceError] 'axis' must be in [0 , -1]. Its actual value is: -1
(op_type:MatMul, node name: /layers.15/self_attn/MatMul_2): [ShapeInferenceError] Input tensors of wrong rank (0).
(op_type:Transpose, node name: /layers.15/self_attn/Transpose_6): [TypeInferenceError] Invalid attribute perm {0, 2, 1, 3}, input shape = {

**Comment by gramalingam** [comment]
I don't have access to the above link to the model. If you zip the model, I think github will allow you to directly include the zipped model file here, which everybody will be able to access

**Comment by Ai-ZL** [comment]
[model.zip](https://github.com/user-attachments/files/16579995/model.zip)
This is quantized model, the unquantized model is too large, I will try to upload it later.

**Comment by Ai-ZL** [comment]
I update the link permission: https://drive.google.com/file/d/1Ja-U5ovYqGekiJoacO4E6wJ6z_VHxPvu/view?usp=sharing

Can you access the file now?

**Comment by gramalingam** [comment]
> [model.zip](https://github.com/user-attachments/files/16579995/model.zip) This is quantized model, the unquantized model is too large, I will try to upload it later.

I tried `onnx.shape_inference.infer_shapes(model, True, True)` and don't get any errors ... I am using the current dev branch of onnx, but not sure that should make a difference here .... strange

**Comment by gramalingam** [comment]
In the quantized model, I do see that shape-inference is unable to infer shapes at some point. In particular, the first place where that happens is `/Expand_1_output_0 = Expand (/Unsqueeze_4_output_0, /ConstantOfShape_2_output_0)` ... however, I am puzzled by this statement, since the shape here seems to be all 1s, while the input's shape has non-1 in two dimensions. It's a bit suspicious.

**Comment by Ai-ZL** [comment]
Thanks. Yes, I didn't have any problems with the before-quantized model either. For the quantized model, I think it might all go to 1 when the inputs or outputs of the model nodes are dynamic shapes. I just think maybe I can try to use optimization before quantization, it can infer a shape for each inputs and outputs.
