### ISSUE TITLE
Error Loading ONNX Model: Invalid Node Input 'compute_STFT.window'

### ISSUE THREAD

**Issue by cocovoc** [onnx/onnx#6367]
I'm encountering an issue while trying to load an ONNX model using onnxruntime.InferenceSession. The error message indicates that there is a problem with a node input 'compute_STFT.window', which is not recognized as a graph input, initializer, or output of a previous node.

```
Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydevd_asyncio/pydevd_asyncio_utils.py", line 117, in _exec_async_code
    result = func()
  File "<input>", line 1, in <module>
  File "/opt/xxx/conda/envs/duqj_onnx_py39/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/opt/xxx/conda/envs/duqj_onnx_py39/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 480, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Load model from /opt/xxx/compute_features_0915.onnx failed:Invalid model. Node input 'compute_STFT.window' is not a graph input, initializer, or output of a previous node.
```
source code is :
```python

import onnx
import onnxruntime as ort

model_path = 'xxx'
onnx_model = onnx.load(model_path)

session = ort.InferenceSession(model_path)
```

onnx==1.16.2
onnx_runtime = 1.19.2

**Comment by xadupre** [comment]
How did you generete the onnx model? Maybe it was saved with external_weights and they are missing.
