### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by tonypottera24** [onnx/onnx#6423]
# Bug Report

### Describe the bug

The DFS function `_dfs_search_reachable_nodes` used in `utils.extract_model` is implemented by recursion, which prohibits it from extracting complicated models such as UNet.

https://github.com/onnx/onnx/blob/56cf02beb2331a75f2a119f8b6d64e9d460d3a98/onnx/utils.py#L47

### System information

- OS Platform and Distribution: Ubuntu 24.04
- ONNX version: onnx-weekly==1.18.0.dev20240930
- Python version: 3.12.3
- Protobuf version: 5.28.2

### Reproduction instructions

```
#!/usr/bin/env python3

import onnx

model_path = "models/unet/model.onnx"
new_model_path = "models/unet/model_new.onnx"

model = onnx.load(model_path)

onnx.utils.extract_model(
    input_path=model_path,
    output_path=new_model_path,
    input_names=[node.name for node in model.graph.input],
    output_names=[node.name for node in model.graph.output],
)

onnx.checker.check_model(new_model_path)
```

### Error message
```
Traceback (most recent call last):
  File "/onnx_test.py", line 17, in <module>
    onnx.utils.extract_model(
  File "/venv/lib/python3.12/site-packages/onnx/utils.py", line 231, in extract_model
    extracted = e.extract_model(input_names, output_names)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/onnx/utils.py", line 188, in extract_model
    nodes = self._collect_reachable_nodes(input_names, output_names)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/onnx/utils.py", line 95, in _collect_reachable_nodes
    self._dfs_search_reachable_nodes(
  File "/venv/lib/python3.12/site-packages/onnx/utils.py", line 81, in _dfs_search_reachable_nodes
    self._dfs_search_reachable_nodes(
  File "/venv/lib/python3.12/site-packages/onnx/utils.py", line 81, in _dfs_search_reachable_nodes
    self._dfs_search_reachable_nodes(
  File "/venv/lib/python3.12/site-packages/onnx/utils.py", line 81, in _dfs_search_reachable_nodes
    self._dfs_search_reachable_nodes(
  [Previous line repeated 993 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by tonypottera24** [comment]
I tried to create a pull request.
https://github.com/onnx/onnx/pull/6424
