### ISSUE TITLE
`pyarrow` causes `ImportError: DLL load failed while importing onnx_cpp2py_export` in `onnx`

### ISSUE THREAD

**Issue by Stanley5249** [onnx/onnx#6490]
# Bug Report

### Is the issue related to model conversion?
No.

### Describe the bug
Importing `pyarrow` before `onnx` causes an import error for `onnx`.

### System information
- OS Platform and Distribution: Windows 11
- ONNX version: 1.17.0
- Python version: 3.12.6

### Requirements
```plaintext
onnx==1.17.0
pyarrow==17.0.0
```

### Reproduction instructions
To reproduce the issue, run the following code:

```python
import pyarrow
import onnx
```

This results in the following error:

```plaintext
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import onnx
  File ".venv\Lib\site-packages\onnx\__init__.py", line 77, in <module>
    from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: 動態連結程式庫 (DLL) 初始化例行程序 失敗。
```

### Temporary Solution
Changing the import order temporarily resolves the problem:

```python
import onnx
import pyarrow
```

**Comment by cbourjau** [comment]
I believe this is solved, but please feel free to re-open if the issue still exists.
