### ISSUE TITLE
How to use version converter on a large (>2GB) model?

### ISSUE THREAD

**Issue by yuanyao-nv** [onnx/onnx#6529]
# Ask a Question

### Question
I have a model with external weights. The size of the external weights file is larger than 2GB.
If I run the converter with
```
original_model = onnx.load(model_path)
converted_model = version_converter.convert_version(original_model, 21)
```
then the converter runs into an error (even though the error itself is a bit misleading `RuntimeError: /github/workspace/onnx/common/ir_pb_converter.cc:716: assertNonNull: Assertion `g.get() != nullptr` failed: Warning: onnx version converter is unable to parse input model. (The IR version of the ONNX model may be too old.)`)

If I skip loading the external weights:
```
original_model = onnx.load(model_path, load_external_data=False)
converted_model = version_converter.convert_version(original_model, 21)
```
then the weights in the converted model do not have file location info anymore so the model becomes unusable.

Is there a way to work around this issue?

**Comment by justinchuby** [comment]
> then the weights in the converted model do not have file location info anymore so the model becomes unusable.

Hmm sounds like a bug

**Comment by yuanyao-nv** [comment]
@justinchuby Any thoughts what the root cause could be or which part of the code would be relevant? Could it just be a proto issue rather than an ONNX issue?

Some additional info: the same issue also manifests itself on the inliner, although in slightly different ways:
- If I load the model with external data, then the inliner completely wipes out everything in the GraphProto.
- If I load the model with `load_external_data=False`, then the inliner wipes out all the FunctionProtos.

**Comment by justinchuby** [comment]
> If I load the model with external data, then the inliner completely wipes out everything in the GraphProto.

Is the model >2gb? This is due to the c++/python interop

> If I load the model with load_external_data=False, then the inliner wipes out all the FunctionProtos.

That's expected right? That's what the inliner is supposed to do

**Comment by justinchuby** [comment]
I would recommend using the inliner in onnxscript. We are building a version converter based on ONNX IR too, which will not have the protobuf limitations.

**Comment by yuanyao-nv** [comment]
> Is the model >2gb? This is due to the c++/python interop
The external data file is >2gb. The model file is quite small.

> That's expected right? That's what the inliner is supposed to do
In case you misunderstood, the inliner in this case wipes out the FunctionProtos without actually inlining them. In other words, the local function subgraphs are completely lost.

**Comment by justinchuby** [comment]
> The external data file is >2gb. The model file is quite small.

If you load external data, they will be loaded as a part of the model proto. As the call to the inliner (c++) happens, it gets serialized and that will exceed 2gb and fail.

> wipes out the FunctionProtos without actually inlining them

I see. So no inlining happened. Could you share a file we can debug with?

**Comment by yuanyao-nv** [comment]
Here's an artificial example where the model is very simple but it contains a weight tensor that exceeds 2GB. Running the following script will export the model.

If you run `onnx.inliner.inline_local_functions()` on it you will see what I described above:
- If you load the model with `load_external_data=True` the output file has an empty graph.
- If you load it with `load_external_data=False` no inlining happens (Although for this artificial example the behavior is slightly different from the real model I described above where no inlining happens and the local function subgraph disappears)

```
import onnx_graphsurgeon as gs
import onnx
import numpy as np

dtype = np.float32
X = gs.Variable(name="X", dtype=dtype, shape=(1,1))

Y = gs.Constant(name="Y", values=np.zeros((20000,30000), dtype=dtype))
Add_out = gs.Variable(name="Add_out")
Z = gs.Variable(name="Z", dtype=np.int64)

node_identity = gs.Node(op="Add", inputs=[X, Y], outputs=[Add_out])
node_local = gs.Node(op="LocalFunction", inputs=[Add_out], outputs=[Z], attrs={"axis":1}, domain="trt")

graph = gs.Graph(nodes=[node_identity, node_local], inputs=[X, Y], outputs=[Z], opset=20)


# Register local function
def register_ops():
    @gs.Graph.register()
    def constant(self, *args, **kwargs):
        available_attrs = [
            "sparse_value",
            "value",
            "value_float",
            "value_floats",
            "value_int",
            "value_ints",
            "value_string",
            "value_strings",
        ]
        found_attrs = sum(
            1 for available_attr in available_attrs if available_attr in kwargs
        )
        assert (
            found_attrs == 1
        ), f"Exactly 1 attribute must be specified for op Constant. Got {found_attrs}"

        out = self.layer(op="Constant", outputs=["constant_out"], attrs=kwargs)[0]
        return out

    @gs.Graph.register()
    def shape(self, x):
        out = self.layer(
            op="Shape",
            inputs=[x],
            outputs=["shape_out"],
        )[0]
        return out

    @gs.Graph.register()
    def gather(self, x, indices, axis=0):
        out = self.layer(
            op="Gather",
            inputs=[x, indices],
            outputs=["gather_out"],
            attrs={"axis": axis},
        )[0]
        return out

def register_local_function(graph):
    local_input = gs.Variable("local_input", shape=[-1, -1])

    local_func = gs.Function(
        "LocalFunction",
        domain="trt",
        inputs=[local_input],
        opset=21,
        attrs={"axis": None},
    )

    axis_constant_out_1 = local_func.constant(
        value_int=gs.Node.AttributeRef("axis", int)
    )
    input_shape = local_func.shape(local_input)

    shape_at_axis = local_func.gather(input_shape, axis_constant_out_1, axis=0)
    local_func.outputs.append(shape_at_axis)

    graph.functions.append(local_func)

register_ops()
register_local_function(graph)

model = gs.export_onnx(graph)
onnx.save(model, "test_clean.onnx", save_as_external_data=True)
```

**Comment by geqian-9192** [comment]
I also have the problem, do you have any solution now？ @yuanyao-nv

**Comment by yuanyao-nv** [comment]
> I also have the problem, do you have any solution now？ @yuanyao-nv

I haven't made more progress. Not sure whether @justinchuby has found out anything.

**Comment by justinchuby** [comment]
I see this is a large constant node. You would need to convert the tensor to external data before calling infer shapes. Anytime you give infer_shapes a proto with more than 2gb of data it will fail. The idea is always finding ways to change the proto to be less than 2gb. In this case you can call the external data helper to convert to external tensor

**Comment by yuanyao-nv** [comment]
> I see this is a large constant node. You would need to convert the tensor to external data before calling infer shapes. Anytime you give infer_shapes a proto with more than 2gb of data it will fail. The idea is always finding ways to change the proto to be less than 2gb. In this case you can call the external data helper to convert to external tensor

The export script in my previous comment https://github.com/onnx/onnx/issues/6529#issuecomment-2458509883 already exports the model with external data. Whether you then load the model with `load_external_data` set to True or False, you will run into errors described in that comment. For this model there currently doesn't seem to be a way to get the inliner or version converter to work correctly.

**Comment by justinchuby** [comment]
You want to set convert_attribute to True as well when saving.

**Comment by postrational** [comment]
I investigated the problem @yuanyao-nv is having a bit further.

I was able to reproduce the problem using only native ONNX code:

```python
import onnx
import numpy as np
from onnx import TensorProto

# Random data
np.random.seed(42)
random_shape = (20000,30000)  # Approx 2.4 GB
random_data = np.random.rand(*random_shape).astype(np.float32)
print(f"Data size in GB: {random_data.nbytes / (1024**3):.2f} GB")

# Create two initializer nodes: one for the data tensor, second is just a scalar 1
initializer_tensor = onnx.helper.make_tensor(
    name="initializer_tensor",
    data_type=onnx.TensorProto.FLOAT,
    dims=list(random_shape),
    vals=random_data.flatten(),
)
initializer_scalar = onnx.helper.make_tensor(
    name="initializer_scalar",
    data_type=onnx.TensorProto.FLOAT,
    dims=[],
    vals=[1.0],
)

# Define a graph with simple addition
add_node = onnx.helper.make_node(
    "Add",
    inputs=["initializer_tensor", "initializer_scalar"],
    outputs=["sum_output"]
)

# WILL CRASH ON THIS LINE WITH google.protobuf.message.DecodeError: Error parsing message with type 'onnx.TensorProto'
graph_def = onnx.helper.make_graph(
    name="SimpleAddition",
    nodes=[add_node],
    inputs=[],
    outputs=[
        onnx.helper.make_tensor_value_info("sum_output", TensorProto.FLOAT, list(random_shape))
    ],
    initializer=[initializer_tensor, initializer_scalar]
)

# Save model to file
model_filename = "test_simple_add.onnx"
opset_imports=[onnx.helper.make_opsetid("", 21)]
model_def = onnx.helper.make_model(graph_def, opset_imports=opset_imports)
model_def.ir_version = 10
onnx.save(model_def, model_filename)
print(f"ONNX model saved as {model_filename}")

onnx.checker.check_model(model_filename)
print("ONNX model is valid")
```

It seems to me that the problem stems from the fact that it isn't his whole model which is >2GB, but a single initializer value.

The problem can be traced further into how ONNX uses protobuf objects to store initializer data:

```python
import numpy as np
from onnx import TensorProto, GraphProto

# Random data
np.random.seed(42)
random_shape = (20000,30000)  # Approx 2.4 GB
# random_shape = (2,3)  # Approx 2.4 GB
random_data = np.random.rand(*random_shape).astype(np.float32)
print(f"Data size in GB: {random_data.nbytes / (1024**3):.2f} GB")

tensor = TensorProto()
tensor.data_type = 1
tensor.name = "initializer_tensor"
tensor.float_data.extend(random_data.flat)
tensor.dims.extend(random_shape)

graph = GraphProto()
graph.initializer.extend([tensor])
```

This is essentially what ONNX is trying to do and the last line causes the protobuf `DecodeError`.

This is a limitation of Protobuf for which we currently do not have a workaround.

**Comment by postrational** [comment]
I can't reproduce you problem, @yuanyao-nv. It works for me ;-)

Running your test code, generated these 2 files for me:

    2.4G 21 Feb 13:39 ec158c76-f050-11ef-9bb8-829cb162e004
     708 21 Feb 13:39 test_clean.onnx


I can also load the model in ONNX and inspect the initializers.

```python
>>> model.graph.initializer[0].name
    'Y'

>>> model.graph.initializer[0].dims
    [10000, 30000]

# Basic types. https://github.com/onnx/onnx/blob/v1.17.0/onnx/onnx.proto#L502-L503
# FLOAT = 1;   // float
>>> model.graph.initializer[0].data_type
    1

>>> len(model.graph.initializer[0].raw_data)
    1200000000

>>> len(model.graph.initializer[0].raw_data[0:10])
    10

>>> model.graph.initializer[0].raw_data[0:10]
    b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'



>>> model.graph.initializer[1].name
    'M'

>>> model.graph.initializer[1].dims
    [10000, 30000]

>>> model.graph.initializer[1].data_type
    1

>>> len(model.graph.initializer[1].raw_data)
    1200000000

>>> model.graph.initializer[1].raw_data[0:10]
    b'\x00\x00\x80?\x00\x00\x80?\x00\x00'
```

I can also open it in Netron and export the initializer tensors to numpy array files.

    1.2G 21 Feb 13:42 M.npy
    1.2G 21 Feb 13:41 Y.npy

So, for this example everything seems to be working well.

But if I increase the size of either of the initializers to over 2GB (e.g. shape `(20000,30000)`), I do get the error:

```
  File ".../lib/python3.9/site-packages/onnx/helper.py", line 236, in make_graph
    graph.initializer.extend(initializer)
google.protobuf.message.DecodeError: Error parsing message with type 'onnx.TensorProto'
```

So, the issue you are reporting may be specific to an OS or ONNX version you are using. I have this on MacOS, Python 3.9.21.

  
    Package                   Version
    ------------------------- --------------
    numpy                     2.0.2
    onnx                      1.17.0
    onnx_graphsurgeon         0.5.5
    protobuf                  5.29.3

**Comment by yuanyao-nv** [comment]
@postrational When you say everything works well for this model do you mean the inliner also works for you? It's the inliner that's failing for me. Model creation and visualization works fine.

**Comment by zjgarvey** [comment]
We have quite a few onnx models bigger than 2gb running in one of our test suites: <https://github.com/nod-ai/SHARK-TestSuite/tree/main/alt_e2eshark>. Version updating is very useful for us, since we need the updated shape inference functions available at newer opset versions. Since updating the opset version for these models fails when loading the external data, I've occasionally hacked around this by:

1. loading model without external data
2. Performing version update (destroys external data references)
3. tracing through the old model and collecting all external data references (initializers and node attributes)
4. copying them over to the new model

You can see this implemented in <https://github.com/nod-ai/SHARK-TestSuite/blob/949ef993885e3941e20a496f0c0330d24b74489c/alt_e2eshark/onnx_tests/models/nlp.py#L84-L114>. 

In general, I was wondering why it is necessary to load external data for the version-updating tool. Are there certain ops which need knowledge of external data to update properly?

**Comment by justinchuby** [comment]
> I was wondering why it is necessary to load external data for the version-updating tool. Are there certain ops which need knowledge of external data to update properly?

Probably not necessary. I am supprised that the version update logic destroys external data references.

**Comment by zjgarvey** [comment]
> Probably not necessary. I am supprised that the version update logic destroys external data references.

If I get a chance to try and figure out what is happening, I'll post an update here.

**Comment by zjgarvey** [comment]
Okay, I'm guessing a bit here, but 

<https://github.com/onnx/onnx/blob/a952ab0e15884f4aa1d67ef935c3e691ae78c061/onnx/version_converter/convert.cc#L124>

calls

<https://github.com/onnx/onnx/blob/3d5acaf3e23ae8db7ac01b8cfedb17b8817121f4/onnx/common/ir_pb_converter.cc#L391>

calls

<https://github.com/onnx/onnx/blob/3d5acaf3e23ae8db7ac01b8cfedb17b8817121f4/onnx/common/ir_pb_converter.cc#L229>

which does:

<https://github.com/onnx/onnx/blob/3d5acaf3e23ae8db7ac01b8cfedb17b8817121f4/onnx/common/ir_pb_converter.cc#L288-L289>

And as far as I can grok from this, `tensorProtoToTensor` doesn't handle external data. 

My understanding after skimming some of the codebase is that `TensorProto` has external data support, but <https://github.com/onnx/onnx/blob/a952ab0e15884f4aa1d67ef935c3e691ae78c061/onnx/common/tensor.h#L24> does not. The version converter works on a `Graph` and not a `GraphProto`, so the conversions back and forth to protobuf destroy the external data references.

**Comment by yuanyao-nv** [comment]
Seems like a bug that can be fixed by adding the external_data field to `struct Tensor`.

@justinchuby when calling onnxscript.optimizer._inliner.inline() I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yuanyao/.local/lib/python3.12/site-packages/onnxscript/optimizer/_inliner.py", line 310, in inline
    inliner = _Inliner(model)
              ^^^^^^^^^^^^^^^
  File "/home/yuanyao/.local/lib/python3.12/site-packages/onnxscript/optimizer/_inliner.py", line 194, in __init__
    self._function_id_abbreviations = _abbreviate(self._functions.keys())
                                                  ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'google._upb._message.RepeatedCompositeContainer' object has no attribute 'keys'
```
a protobuf version issue?

**Comment by justinchuby** [comment]
Likely a version issue. What is the protobuf version you are using?

**Comment by yuanyao-nv** [comment]
> Likely a version issue. What is the protobuf version you are using?

I was using protobuf 3.21.12

**Comment by justinchuby** [comment]
I think you need a 4.x version

**Comment by yuanyao-nv** [comment]
I made a PR to fix this https://github.com/onnx/onnx/pull/6847

**Comment by justinchuby** [comment]
For future reference, here is how you can run version converter on a large model with onnxscript:

https://github.com/onnx/onnx/pull/6847#issuecomment-2840687942
