### ISSUE TITLE
invalid version error when converting llama3 model from opset 20 to 21

### ISSUE THREAD

**Issue by RyanMetcalfeInt8** [onnx/onnx#6551]
Here is cmd's / code to reproduce:

To generate llama3 opset 20 onnx model:
```
pip install optimum[exporters]
huggingface-cli login
optimum-cli export onnx --model meta-llama/Meta-Llama-3-8B-Instruct llama3_opt_chat_onnx --opset 20
```

I then want to convert this model from 20 to 21. Here are python cmds:

```
import onnx
model = onnx.load("model.onnx")

from onnx.version_converter import convert_version
converted_model = convert_version(model, target_version=21)
```

This produces the following error:
```
Traceback (most recent call last):
  File "/home/devcloud/llama3_opt_chat_onnx/../opset_convert.py", line 21, in <module>
    converted_model = convert_version(model, target_version=21)
  File "/home/devcloud/conv_env/lib64/python3.9/site-packages/onnx/version_converter.py", line 39, in convert_version
    converted_model_str = C.convert_version(model_str, target_version)
RuntimeError: /github/workspace/onnx/version_converter/convert.h:86: assertInVersionRange: Assertion `version >= version_range.first && version <= version_range.second` failed: Warning: invalid version (must be between 1 and 22)
```

Any ideas?

**Comment by justinchuby** [comment]
optimum most likely works best for upset 17 because it uses the old pytorch exporter. But this is still strange. Could you share your onnx model(without weights)?

**Comment by justinchuby** [comment]
Also, upset 20->21 mostly likely doesn't require any changes. You may change the opset import field directly instead:

```
from onnxscript import ir

model = ir.load('model.onnx')
model.opset_imports[''] = 21
it.save(model, 'model.onnx')
```

**Comment by RyanMetcalfeInt8** [comment]
> optimum most likely works best for upset 17 because it uses the old pytorch exporter. But this is still strange. Could you share your onnx model(without weights)?

Sorry, I can't seem to upload the weightless .onnx (blocked by my IT policy) -- but you can produce it using the optimum cmd's that I shared above.

**Comment by RyanMetcalfeInt8** [comment]
> Also, opset 20->21 mostly likely doesn't require any changes. You may change the opset import field directly instead:
> 
> ```
> from onnxscript import ir
> 
> model = ir.load('model.onnx')
> model.opset_imports[''] = 21
> it.save(model, 'model.onnx')
> ```

I'll try it, thanks. 

On a side note, I want to quantize to 4-bit, and I've heard that it needs to be opset 21 in order to do that. Kind of new to working directly with onnx models / opsets / etc... Do you know if there are some known instructions to produce 4-bit quantized llama3 onnx model? I didn't really find anything in my various searches. Thanks!

**Comment by justinchuby** [comment]
Looks like this may be relevant: https://github.com/onnx/neural-compressor#weight-only-quantization-llms

**Comment by cbourjau** [comment]
Please re-open or comment if this issues is still relevant.
