### ISSUE TITLE
ImportError when importing onnx in python script packed in snap on arm machine

### ISSUE THREAD

**Issue by BjGoCraft** [onnx/onnx#6583]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug 
There is an ImportError when trying to import onnx into a python program when the python file is packed into a snap package and run on an arm device. The error is: `ImportError: cannot import name 'ONNX_ML' from 'onnx.onnx_cpp2py_export' (unknown location)`. 
### Reproduction instructions
I'm trying to pack onnx into a snap package and run it on an arm device. This is my project folder I used for testing:
[onnx_test.zip](https://github.com/user-attachments/files/18129005/onnx_test.zip)

The folder contains the following:

- 2 scripts to build a snap for arm and amd architecture:
```
#!/usr/bin/env bash
set -e
sudo snapcraft clean
sudo snapcraft --build-for=arm64 --verbosity=verbose
```
and
```
#!/usr/bin/env bash
set -e
sudo snapcraft clean
sudo snapcraft --build-for=amd64 --verbosity=verbose
```
- main.py file that tries to import onnx:
```
#!/usr/bin/env python3
print("now importing...")
import onnx
print("Import done")
```
- setup.cfg file (tbh no idea what it does):
```
[metadata]
description-file = README.md

[flake8]
max-line-length = 150
```
- setup.py (some metadata and it links to main.py file):
```
from setuptools import setup

setup(
    name='test-app',
    version='2.4.0',
    description='Test onnx import',
    author='me',
    scripts=['main.py']
)
```
- snap folder with snapcraft.yaml:
```
name: test-app
title: ONNX test app
version: 1.0.0
summary: test app with onnx
description: |
  Test the onnx import
base: core22
confinement: strict
grade: stable

architectures:
  - build-on: [amd64, arm64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

apps:
  provider:
    command: bin/main.py
    daemon: simple
    restart-condition: always
    passthrough:
      restart-delay: 30s

parts:
  provider:
    plugin: python
    source: .
    python-packages:
      - onnx
```

1. I created the snaps by running the build-snap scripts for arm and amd: `./build-snap-arm64.sh` and `./build-snap-amd64.sh`
2. I installed the snaps on their respective system archticture:
`sudo snap install test-app_1.0.0_arm64.snap --dangerous` and `sudo snap install test-app_1.0.0_amd64.snap --dangerous`.
3. I run the app with:
`sudo snap run test-app.provider`

To see the logs and errors, I typed `sudo snap logs test-app.provider` on both systems. 

On the amd system, there were no errors:
```2024-12-13T17:27:34+01:00 systemd[1]: Started snap.test-app.provider.service - Service for snap application test-app.provider.
2024-12-13T17:27:36+01:00 test-app.provider[68868]: now importing...
2024-12-13T17:27:36+01:00 test-app.provider[68868]: Import done
2024-12-13T17:27:36+01:00 systemd[1]: snap.test-app.provider.service: Deactivated successfully.
2024-12-13T17:27:36+01:00 systemd[1]: snap.test-app.provider.service: Consumed 1.924s CPU time.
```

On the arm system on the other hand:
```2024-12-13T17:54:17+01:00 systemd[1]: Started Service for snap application test-app.provider.
2024-12-13T17:54:17+01:00 test-app.provider[17552]: now importing...
2024-12-13T17:54:17+01:00 test-app.provider[17552]: Traceback (most recent call last):
2024-12-13T17:54:17+01:00 test-app.provider[17552]:   File "/snap/test-app/x1/bin/main.py", line 3, in <module>
2024-12-13T17:54:17+01:00 test-app.provider[17552]:     import onnx
2024-12-13T17:54:17+01:00 test-app.provider[17552]:   File "/snap/test-app/x1/lib/python3.10/site-packages/onnx/__init__.py", line 77, in <module>
2024-12-13T17:54:17+01:00 test-app.provider[17552]:     from onnx.onnx_cpp2py_export import ONNX_ML
2024-12-13T17:54:17+01:00 test-app.provider[17552]: ImportError: cannot import name 'ONNX_ML' from 'onnx.onnx_cpp2py_export' (unknown location)
2024-12-13T17:54:17+01:00 systemd[1]: snap.test-app.provider.service: Main process exited, code=exited, status=1/FAILURE
2024-12-13T17:54:17+01:00 systemd[1]: snap.test-app.provider.service: Failed with result 'exit-code'.
```

I saw issues where others had the same error, but it was always in the development process where onnx was compiled from source. In my case on the other hand, I get onnx directly from pip so I can't change anything suggested in the other issues. The error message says the location is unknown, but the file path "/snap/test-app/x1/lib/python3.10/site-packages/onnx/__init__.py" exists and has "ONNX_ML" in it, so I don't know where the problem comes from. If this is an issue with snap, let me know and I'll try it there.

### System information
- OS Platform and Distribution: tried it both on Ubuntu Core 22.04 (arm) and Debian 12 (arm)
- ONNX version (*e.g. 1.13*): not specified in snapcraft.yaml, so should be the latest from pip
- Python version: Python 3.9.2

**Comment by rdeits-bd** [comment]
I'm running into this as well. In my case, `onnx` is being installed from PyPI using `rules_py` in bazel. As with the OP, the issue only occurs on Arm.

**Comment by andife** [comment]
we should be able to create a test for that? since we now have arm runner in GitHub.
