### ISSUE TITLE
"Assertion `state` failed" if using variable slice/index assignment when exporting model

### ISSUE THREAD

**Issue by lanpa** [onnx/onnx#916]
``` python 
import torch
from torch.autograd import Variable

class DummyModule(torch.nn.Module):
    def forward(self, x):
        V = Variable(torch.Tensor(2, 2))
        V[0, 0] = x
        return torch.sum(V * 3)

model = DummyModule()
x = Variable(torch.Tensor([1]))  # forward pass OK

print(model(x))
torch.onnx.export(model, (x,), 'dummy.pb')  # error
```
environment is pytorch 0.4, and the output of the above code is:
```
tensor(3.)
Traceback (most recent call last):
  File "issue85.py", line 14, in <module>
    torch.onnx.export(model, (x,), 'dummy.pb')
  File "/home/dexter/anaconda3/lib/python3.6/site-packages/torch/onnx/__init__.py", line 25, in export
    return utils.export(*args, **kwargs)
  File "/home/dexter/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 84, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names)
  File "/home/dexter/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 134, in _export
    trace, torch_out = torch.jit.get_trace_graph(model, args)
  File "/home/dexter/anaconda3/lib/python3.6/site-packages/torch/jit/__init__.py", line 255, in get_trace_graph
    return LegacyTracedModule(f, nderivs=nderivs)(*args, **kwargs)
  File "/home/dexter/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dexter/anaconda3/lib/python3.6/site-packages/torch/jit/__init__.py", line 291, in forward
    torch._C._tracer_exit(out_vars)
RuntimeError: /pytorch/torch/csrc/jit/tracer.h:120: getTracingState: Assertion `state` failed.
```
ref: https://github.com/lanpa/tensorboard-pytorch/issues/85
cc @filipeabperes

**Comment by sauercrowd** [comment]
I had the same issue, but installing onnx with 
```bash
conda install -c conda-forge onnx
```
solved it, probably you want to give it a try

**Comment by sauercrowd** [comment]
I had the same issue, and forgot to install onnx.

If you didn't install it, give it a try with
```bash
conda install -c conda-forge onnx
```
and rerun your script afterwards

**Comment by iNLyze** [comment]
I am experiencing the exact same issue. A similar problem was imported [PyTroch](https://discuss.pytorch.org/t/exporting-rnn-model-with-torch-onnx-export/11690)

**Comment by prasanthpul** [comment]
Please open an issue in PyTorch github if you are still having this issue with latest PyTorch
