### ISSUE TITLE
Error in importing onnx

### ISSUE THREAD

**Issue by ayush1999** [onnx/onnx#922]
Followed the docs to install onnx from the binary. However, this is what I get when I import it.

```
>>> import onnx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ayush99/anaconda3/lib/python3.6/site-packages/onnx/__init__.py", line 10, in <module>
    import onnx.helper  # noqa
  File "/home/ayush99/anaconda3/lib/python3.6/site-packages/onnx/helper.py", line 15, in <module>
    import onnx.defs as defs
  File "/home/ayush99/anaconda3/lib/python3.6/site-packages/onnx/defs/__init__.py", line 6, in <module>
    import onnx.onnx_cpp2py_export.defs as C
ImportError: /home/ayush99/anaconda3/lib/python3.6/site-packages/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameEv

```
Any idea what might be causing this error?

**Comment by houseroad** [comment]
protobuf library mismatching, you may install two versions of protobuf, for example one in the operating system, and one in the anaconda environment.

**Comment by askhade** [comment]
Can you try installing from pip instead of conda... Pip package statically links to protobuf and therefore removes issues occurring because of protobuf version mismatches... 

Closing this issue due to inactivity... please try with latest onnx package and reopen if you still bump into this.
