### ISSUE TITLE
ValueError: The graph does not have an ir_version set properly.

### ISSUE THREAD

**Issue by christoph-conrads** [onnx/onnx#95]
I am trying to load a model that I exported from PyTorch. This is the code that I use to load the ONNX model from disk:
```python
    graph = onnx.load(filename)
    onnx.checker.check_graph(graph)
```
This is the error message:
```
Traceback (most recent call last):
  File "run-onnx.py", line 51, in <module>
    sys.exit( main() )
  File "run-onnx.py", line 38, in main
    onnx.checker.check_graph(graph)
  File "/home/christoph/anaconda2/lib/python2.7/site-packages/onnx/checker.py", line 52, in check_graph
    raise ValueError('The graph does not have an ir_version set properly.')
ValueError: The graph does not have an ir_version set properly.
```
Please advise me how I can resolve or help resolve this error.

I am using conda 4.3.27 for Python 2 with onnx 0.1 (py27hd76de5e_1). The model file was created with self-compiled PyTorch 0.2.0+803afd5.

**Comment by bddppq** [comment]
@cconrads-scicomp Was the model exported with an older version of PyTorch? We had a backward incompatible change last week, so PyTorch now exports a `ModelProto` and `onnx.load` also returns a `ModelProto` (instead of a `GraphProto`). Could you try updating the onnx version and also using the new version PyTorch to export the model and invoke `checker.check_model` instead of `checker.check_graph`?

**Comment by cconrads-scicomp** [comment]
I exported with [PyTorch commit 803a](https://github.com/pytorch/pytorch/commit/803afd58a08bccfe93cdb7c5b600200108e1c5a6) from yesterday but I am using ONNX 0.1 from the conda *ezyang* channel. I will try to build a more recent ONNX.

**Comment by cconrads-scicomp** [comment]
I built as follows:
```sh
# Ubuntu 16.04 ships with a too old protobuf (2.6.1)
sudo apt-get remove libprotobuf-dev protobuf-compiler
conda remove onnx
export CMAKE_PREFIX_PATH=$(readlink -f "$(dirname $(which conda)/)/..")
export CFLAGS="-I$HOME/anaconda2/include -D_GLIBCXX_USE_CXX11_ABI=0"
git clone --recursive -- 'https://github.com/onnx/onnx'
cd onnx
python setup.py install
```
Without the environment variable `CFLAGS`, the protobuf headers are not found:
```
christoph:/tmp/tmp.qd0rlDiOmt/onnx$ time python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to onnx.egg-info/requires.txt
writing onnx.egg-info/PKG-INFO
writing top-level names to onnx.egg-info/top_level.txt
writing dependency_links to onnx.egg-info/dependency_links.txt
reading manifest file 'onnx.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'onnx.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running create_version
running build_proto
compiling /tmp/tmp.qd0rlDiOmt/onnx/onnx/onnx.proto
copying onnx/onnx_pb2.py -> build/lib.linux-x86_64-2.7/onnx
copying onnx/version.py -> build/lib.linux-x86_64-2.7/onnx
warning: build_py: byte-compiling is disabled, skipping.

running build_ext
building 'onnx.onnx_cpp2py_export' extension
gcc -pthread -B /home/christoph/anaconda2/compiler_compat -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -I/tmp/tmp.qd0rlDiOmt/onnx -I/tmp/tmp.qd0rlDiOmt/onnx/third_party/pybind11/include -I/home/christoph/anaconda2/include/python2.7 -I/home/christoph/anaconda2/include/python2.7 -c /tmp/tmp.qd0rlDiOmt/onnx/onnx/onnx.pb.cc -o build/temp.linux-x86_64-2.7/tmp/tmp.qd0rlDiOmt/onnx/onnx/onnx.pb.o -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /tmp/tmp.qd0rlDiOmt/onnx/onnx/onnx.pb.cc:5:0:
/tmp/tmp.qd0rlDiOmt/onnx/onnx/onnx.pb.h:9:42: fatal error: google/protobuf/stubs/common.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
```
Without the preprocessor define, we get an API mismatch because Ubuntu 16.04 ships with GCC 5.4 which uses a new C++ ABI whereas conda packages are built with an older GCC:
```
christoph:~/caffe2-demo$ LD_LIBRARY_PATH=~/anaconda2/lib python run-onnx.py MNIST.fc.proto
Traceback (most recent call last):
  File "run-onnx.py", line 7, in <module>
    import onnx
  File "/home/christoph/anaconda2/lib/python2.7/site-packages/onnx-0.2-py2.7-linux-x86_64.egg/onnx/__init__.py", line 7, in <module>
  File "/home/christoph/anaconda2/lib/python2.7/site-packages/onnx-0.2-py2.7-linux-x86_64.egg/onnx/checker.py", line 15, in <module>
  File "/home/christoph/anaconda2/lib/python2.7/site-packages/onnx-0.2-py2.7-linux-x86_64.egg/onnx/defs/__init__.py", line 6, in <module>
  File "/home/christoph/anaconda2/lib/python2.7/site-packages/onnx-0.2-py2.7-linux-x86_64.egg/onnx/onnx_cpp2py_export.py", line 7, in <module>
  File "/home/christoph/anaconda2/lib/python2.7/site-packages/onnx-0.2-py2.7-linux-x86_64.egg/onnx/onnx_cpp2py_export.py", line 6, in __bootstrap__
ImportError: /home/christoph/.cache/Python-Eggs/onnx-0.2-py2.7-linux-x86_64.egg-tmp/onnx/onnx_cpp2py_export.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev
christoph:~$ nm --dynamic ~/anaconda2/lib/libprotobuf.so.14 | fgrep GetTypeName
00000000001874c0 T _ZNK6google8protobuf7Message11GetTypeNameEv
0000000000195f10 W _ZNK6google8protobuf8internal12MapEntryImplINS0_6Struct18Struct_FieldsEntryENS0_7MessageESsNS0_5ValueELNS1_14WireFormatLite9FieldTypeE9ELS8_11ELi0EE11GetTypeNameEv
```
Finally, onnx is implement in C++ but `setup.py` only calls `gcc`. Thus, we have to use `CFLAGS` instead of `CXXFLAGS`.

It works now.

**Comment by ezyang** [comment]
Thanks @christoph-conrads.

I'm reopening this issue in case there are some things we can do to make this better for end users. For example, arguably `setup.py` should call `g++` not `gcc` (though it sounds like this is happening in distutils land which we may not have control over. I guess I tend to always set both CFLAGS and CXXFLAGS)

**Comment by bddppq** [comment]
I think using the compiler's default abi configuration is better?

**Comment by bddppq** [comment]
The issue is indeed in distutils. It uses same compiler command for compiling c and c++ files, and it only detects `CFLAGS` and `CPPFLAGS`, but not `CXXFLAGS` or `CCFLAGS`.
